# **Start Section:**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!pip install git+https://github.com/DaneshSelwal/treeffuser.git

Collecting git+https://github.com/DaneshSelwal/treeffuser.git
  Cloning https://github.com/DaneshSelwal/treeffuser.git to /tmp/pip-req-build-_mqryp7i
  Running command git clone --filter=blob:none --quiet https://github.com/DaneshSelwal/treeffuser.git /tmp/pip-req-build-_mqryp7i
  Resolved https://github.com/DaneshSelwal/treeffuser.git to commit 9717581990db9e7dedaa8c593ec724997e52bdb8
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: einops<0.9.0,>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from treeffuser==0.1.3) (0.8.2)
Collecting jaxtyping<0.3.0,>=0.2.19 (from treeffuser==0.1.3)
  Downloading jaxtyping-0.2.38-py3-none-any.whl.metadata (6.6 kB)
Collecting lightgbm==4.3.0 (from treeffuser==0.1.3)
  Downloading lightgbm-4.3.0-py3-none-manylinux_2_28_x86_64.whl.metadata (19 kB)
Collecting ml-collections<0.2.0,>=0.1.1 (from treeffuser==0.1.3)
  Downloading ml_collections-0.1.1.tar.gz (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 3.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting numpy<2.0,>=1.24 (from treeffuser==0.1.3)
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 5.6 MB/s eta 0:00:00
Requirement already satisfied: pandas<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from treeffuser==0.1.3) (2.2.2)
Collecting scikit-learn==1.5.0 (from treeffuser==0.1.3)
  Downloading scikit_learn-1.5.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Requirement already satisfied: scipy<2.0,>=1.13 in /usr/local/lib/python3.12/dist-packages (from treeffuser==0.1.3) (1.16.3)
Requirement already satisfied: tqdm<5.0.0,>=4.66.4 in /usr/local/lib/python3.12/dist-packages (from treeffuser==0.1.3) (4.67.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.0->treeffuser==0.1.3) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.0->treeffuser==0.1.3) (3.6.0)
Collecting wadler-lindig>=0.1.3 (from jaxtyping<0.3.0,>=0.2.19->treeffuser==0.1.3)
  Downloading wadler_lindig-0.1.7-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from ml-collections<0.2.0,>=0.1.1->treeffuser==0.1.3) (1.4.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from ml-collections<0.2.0,>=0.1.1->treeffuser==0.1.3) (6.0.3)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from ml-collections<0.2.0,>=0.1.1->treeffuser==0.1.3) (1.17.0)
Collecting contextlib2 (from ml-collections<0.2.0,>=0.1.1->treeffuser==0.1.3)
  Downloading contextlib2-21.6.0-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.0.0->treeffuser==0.1.3) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.0.0->treeffuser==0.1.3) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.0.0->treeffuser==0.1.3) (2025.3)
Downloading lightgbm-4.3.0-py3-none-manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 21.1 MB/s eta 0:00:00
Downloading scikit_learn-1.5.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 95.7 MB/s eta 0:00:00
Downloading jaxtyping-0.2.38-py3-none-any.whl (56 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.4/56.4 kB 4.4 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 84.7 MB/s eta 0:00:00
Downloading wadler_lindig-0.1.7-py3-none-any.whl (20 kB)
Downloading contextlib2-21.6.0-py2.py3-none-any.whl (13 kB)
Building wheels for collected packages: treeffuser, ml-collections
  Building wheel for treeffuser (pyproject.toml) ... done
  Created wheel for treeffuser: filename=treeffuser-0.1.3-py3-none-any.whl size=27753 sha256=e5c45049e71a049243495589832658896796e7f9fb131f77f0156dc2dbdc7232
  Stored in directory: /tmp/pip-ephem-wheel-cache-dba31er0/wheels/5f/d1/1a/e628d7eb76d35fc5915026a0d96591b38160a883cc5a7d2116
  Building wheel for ml-collections (setup.py) ... done
  Created wheel for ml-collections: filename=ml_collections-0.1.1-py3-none-any.whl size=94507 sha256=d75d4c7239f9bf78416dedb34bc2b42a8a1ce901d04c441de0366d9031bf8beb
  Stored in directory: /root/.cache/pip/wheels/3e/53/7b/1a6f4bfa9dac09618feedc8b1f28a55d4ab9d4bb8835dc0b7e
Successfully built treeffuser ml-collections
Installing collected packages: wadler-lindig, numpy, contextlib2, ml-collections, jaxtyping, scikit-learn, lightgbm, treeffuser
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1
  Attempting uninstall: lightgbm
    Found existing installation: lightgbm 4.6.0
    Uninstalling lightgbm-4.6.0:
      Successfully uninstalled lightgbm-4.6.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.37.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
umap-learn 0.5.11 requires scikit-learn>=1.6, but you have scikit-learn 1.5.0 which is incompatible.
shap 0.50.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
tobler 0.13.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
hdbscan 0.8.41 requires scikit-learn>=1.6, but you have scikit-learn 1.5.0 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
Successfully installed contextlib2-21.6.0 jaxtyping-0.2.38 lightgbm-4.3.0 ml-collections-0.1.1 numpy-1.26.4 scikit-learn-1.5.0 treeffuser-0.1.3 wadler-lindig-0.1.7

In [3]:
# Uninstall existing scikit-learn to avoid conflicts
!pip uninstall -y scikit-learn
# Install specific versions of libraries to avoid conflicts
!pip install scikit-learn==1.5.2
!pip install bayesian-optimization==3.2.0
!pip install optuna==4.6.0
!pip install gpboost==1.6.1
!pip install shap==0.50.0
!pip install ngboost==0.5.8
!pip install dask[dataframe]==2025.12.0
!pip install torch==2.9.0+cpu
!pip install seaborn==0.13.2
!pip install lightgbm==4.6.0
!pip install xgboost==3.1.2
!pip install lime==0.2.0.1
!pip install interpret==0.7.4
!pip install optunahub==0.4.0
!pip install cmaes==0.12.0
!pip install plotly==5.24.1
!pip install kaleido==1.2.0
!pip install openpyxl==3.1.5
!pip install properscoring==0.1
!pip install XlsxWriter==3.2.9
!pip install cython==3.0.12
!pip install pgbm==2.2.0
!pip install cp==2020.12.3
!pip install mapie==0.6.0
!pip install skorch==1.3.1
!pip install puncc==0.8.0
# Reinstall scikit-learn to the version required by ngboost
!pip uninstall -y scikit-learn
!pip install scikit-learn==1.6.1
# Reinstall numpy first
!pip install numpy==1.26.4  # Use the version compatible with catboost
# Reinstall catboost
!pip install catboost==1.2.8
!pip install pytorch-tabnet2==4.5.3

Found existing installation: scikit-learn 1.5.0
Uninstalling scikit-learn-1.5.0:
  Successfully uninstalled scikit-learn-1.5.0
Collecting scikit-learn==1.5.2
  Downloading scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (3.6.0)
Downloading scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 41.5 MB/s eta 0:00:00
Installing collected packages: scikit-learn
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
treeffuser 0.1.3 requires scikit-learn==1.5.0, but you have scikit-learn 1.5.2 which is incompatible.
umap-learn 0.5.11 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
shap 0.50.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
tobler 0.13.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
hdbscan 0.8.41 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
Successfully installed scikit-learn-1.5.2
Collecting bayesian-optimization==3.2.0
  Downloading bayesian_optimization-3.2.0-py3-none-any.whl.metadata (11 kB)
Collecting colorama>=0.4.6 (from bayesian-optimization==3.2.0)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from bayesian-optimization==3.2.0) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from bayesian-optimization==3.2.0) (26.0)
Requirement already satisfied: scikit-learn>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bayesian-optimization==3.2.0) (1.5.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bayesian-optimization==3.2.0) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.0->bayesian-optimization==3.2.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.0->bayesian-optimization==3.2.0) (3.6.0)
Downloading bayesian_optimization-3.2.0-py3-none-any.whl (37 kB)
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Installing collected packages: colorama, bayesian-optimization
Successfully installed bayesian-optimization-3.2.0 colorama-0.4.6
Collecting optuna==4.6.0
  Downloading optuna-4.6.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna==4.6.0) (1.18.4)
Collecting colorlog (from optuna==4.6.0)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna==4.6.0) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna==4.6.0) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna==4.6.0) (2.0.46)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna==4.6.0) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna==4.6.0) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna==4.6.0) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna==4.6.0) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna==4.6.0) (3.3.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna==4.6.0) (3.0.3)
Downloading optuna-4.6.0-py3-none-any.whl (404 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 404.7/404.7 kB 8.2 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.6.0
Collecting gpboost==1.6.1
  Downloading gpboost-1.6.1-py3-none-manylinux1_x86_64.whl.metadata (7.9 kB)
Requirement already satisfied: wheel in /usr/local/lib/python3.12/dist-packages (from gpboost==1.6.1) (0.46.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from gpboost==1.6.1) (1.26.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from gpboost==1.6.1) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from gpboost==1.6.1) (1.16.3)
Requirement already satisfied: scikit-learn!=0.22.0 in /usr/local/lib/python3.12/dist-packages (from gpboost==1.6.1) (1.5.2)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (from gpboost==1.6.1) (4.6.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn!=0.22.0->gpboost==1.6.1) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn!=0.22.0->gpboost==1.6.1) (3.6.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna->gpboost==1.6.1) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna->gpboost==1.6.1) (6.10.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna->gpboost==1.6.1) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->gpboost==1.6.1) (2.0.46)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna->gpboost==1.6.1) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna->gpboost==1.6.1) (6.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->gpboost==1.6.1) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->gpboost==1.6.1) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->gpboost==1.6.1) (2025.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->gpboost==1.6.1) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->gpboost==1.6.1) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->gpboost==1.6.1) (1.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna->gpboost==1.6.1) (3.3.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna->gpboost==1.6.1) (3.0.3)
Downloading gpboost-1.6.1-py3-none-manylinux1_x86_64.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 49.7 MB/s eta 0:00:00
Installing collected packages: gpboost
Successfully installed gpboost-1.6.1
Requirement already satisfied: shap==0.50.0 in /usr/local/lib/python3.12/dist-packages (0.50.0)
Collecting numpy>=2 (from shap==0.50.0)
  Downloading numpy-2.4.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (1.16.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (1.5.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (2.2.2)
Requirement already satisfied: tqdm>=4.27.0 in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (4.67.3)
Requirement already satisfied: packaging>20.9 in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (26.0)
Requirement already satisfied: slicer==0.0.8 in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (0.0.8)
Requirement already satisfied: numba>=0.54 in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (0.60.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (3.1.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (4.15.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.54->shap==0.50.0) (0.43.0)
  Downloading numpy-2.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.9/60.9 kB 2.5 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->shap==0.50.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->shap==0.50.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->shap==0.50.0) (2025.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->shap==0.50.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->shap==0.50.0) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->shap==0.50.0) (1.17.0)
Downloading numpy-2.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.2/19.2 MB 67.6 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
treeffuser 0.1.3 requires numpy<2.0,>=1.24, but you have numpy 2.0.2 which is incompatible.
treeffuser 0.1.3 requires scikit-learn==1.5.0, but you have scikit-learn 1.5.2 which is incompatible.
umap-learn 0.5.11 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
hdbscan 0.8.41 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
Successfully installed numpy-2.0.2

Collecting ngboost==0.5.8
  Downloading ngboost-0.5.8-py3-none-any.whl.metadata (4.2 kB)
Collecting lifelines>=0.25 (from ngboost==0.5.8)
  Downloading lifelines-0.30.1-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: numpy>=1.21.2 in /usr/local/lib/python3.12/dist-packages (from ngboost==0.5.8) (2.0.2)
Collecting scikit-learn<2.0,>=1.6 (from ngboost==0.5.8)
  Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: scipy>=1.7.2 in /usr/local/lib/python3.12/dist-packages (from ngboost==0.5.8) (1.16.3)
Requirement already satisfied: tqdm>=4.3 in /usr/local/lib/python3.12/dist-packages (from ngboost==0.5.8) (4.67.3)
Requirement already satisfied: pandas<3.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from lifelines>=0.25->ngboost==0.5.8) (2.2.2)
Requirement already satisfied: matplotlib>=3.0 in /usr/local/lib/python3.12/dist-packages (from lifelines>=0.25->ngboost==0.5.8) (3.10.0)
Requirement already satisfied: autograd>=1.5 in /usr/local/lib/python3.12/dist-packages (from lifelines>=0.25->ngboost==0.5.8) (1.8.0)
Collecting autograd-gamma>=0.3 (from lifelines>=0.25->ngboost==0.5.8)
  Downloading autograd-gamma-0.5.0.tar.gz (4.0 kB)
  Preparing metadata (setup.py) ... done
Collecting formulaic>=0.2.2 (from lifelines>=0.25->ngboost==0.5.8)
  Downloading formulaic-1.2.1-py3-none-any.whl.metadata (7.0 kB)
Requirement already satisfied: joblib>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0,>=1.6->ngboost==0.5.8) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0,>=1.6->ngboost==0.5.8) (3.6.0)
Collecting interface-meta>=1.2.0 (from formulaic>=0.2.2->lifelines>=0.25->ngboost==0.5.8)
  Downloading interface_meta-1.3.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines>=0.25->ngboost==0.5.8) (2.16.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines>=0.25->ngboost==0.5.8) (4.15.0)
Requirement already satisfied: wrapt>=1.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines>=0.25->ngboost==0.5.8) (2.1.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=2.1->lifelines>=0.25->ngboost==0.5.8) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=2.1->lifelines>=0.25->ngboost==0.5.8) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (1.17.0)
Downloading ngboost-0.5.8-py3-none-any.whl (36 kB)
Downloading lifelines-0.30.1-py3-none-any.whl (350 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 350.0/350.0 kB 10.5 MB/s eta 0:00:00
Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 89.5 MB/s eta 0:00:00
Downloading formulaic-1.2.1-py3-none-any.whl (117 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.3/117.3 kB 11.0 MB/s eta 0:00:00
Downloading interface_meta-1.3.0-py3-none-any.whl (14 kB)
Building wheels for collected packages: autograd-gamma
  Building wheel for autograd-gamma (setup.py) ... done
  Created wheel for autograd-gamma: filename=autograd_gamma-0.5.0-py3-none-any.whl size=4030 sha256=67f88ec1a2ea92884269525bf2f82baec59e666f5da3e2875b49d025c06292e2
  Stored in directory: /root/.cache/pip/wheels/50/37/21/0a719b9d89c635e89ff24bd93b862882ad675279552013b2fb
Successfully built autograd-gamma
Installing collected packages: interface-meta, scikit-learn, autograd-gamma, formulaic, lifelines, ngboost
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.5.2
    Uninstalling scikit-learn-1.5.2:
      Successfully uninstalled scikit-learn-1.5.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
treeffuser 0.1.3 requires numpy<2.0,>=1.24, but you have numpy 2.0.2 which is incompatible.
treeffuser 0.1.3 requires scikit-learn==1.5.0, but you have scikit-learn 1.8.0 which is incompatible.
Successfully installed autograd-gamma-0.5.0 formulaic-1.2.1 interface-meta-1.3.0 lifelines-0.30.1 ngboost-0.5.8 scikit-learn-1.8.0
Requirement already satisfied: dask==2025.12.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]==2025.12.0) (2025.12.0)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (8.3.1)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (3.1.2)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (2025.3.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (26.0)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (6.0.3)
Requirement already satisfied: toolz>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (0.12.1)
Requirement already satisfied: pandas>=2.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]==2025.12.0) (2.2.2)
Requirement already satisfied: pyarrow>=14.0.1 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]==2025.12.0) (18.1.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]==2025.12.0) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]==2025.12.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]==2025.12.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]==2025.12.0) (2025.3)
Requirement already satisfied: locket in /usr/local/lib/python3.12/dist-packages (from partd>=1.4.0->dask==2025.12.0->dask[dataframe]==2025.12.0) (1.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0->dask[dataframe]==2025.12.0) (1.17.0)
ERROR: Could not find a version that satisfies the requirement torch==2.9.0+cpu (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.5.0, 2.5.1, 2.6.0, 2.7.0, 2.7.1, 2.8.0, 2.9.0, 2.9.1, 2.10.0)
ERROR: No matching distribution found for torch==2.9.0+cpu
Requirement already satisfied: seaborn==0.13.2 in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from seaborn==0.13.2) (2.0.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from seaborn==0.13.2) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.12/dist-packages (from seaborn==0.13.2) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn==0.13.2) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn==0.13.2) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (1.17.0)
Collecting lightgbm==4.6.0
  Downloading lightgbm-4.6.0-py3-none-manylinux_2_28_x86_64.whl.metadata (17 kB)
Requirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from lightgbm==4.6.0) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from lightgbm==4.6.0) (1.16.3)
Downloading lightgbm-4.6.0-py3-none-manylinux_2_28_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 37.3 MB/s eta 0:00:00
Installing collected packages: lightgbm
  Attempting uninstall: lightgbm
    Found existing installation: lightgbm 4.3.0
    Uninstalling lightgbm-4.3.0:
      Successfully uninstalled lightgbm-4.3.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
treeffuser 0.1.3 requires lightgbm==4.3.0, but you have lightgbm 4.6.0 which is incompatible.
treeffuser 0.1.3 requires numpy<2.0,>=1.24, but you have numpy 2.0.2 which is incompatible.
treeffuser 0.1.3 requires scikit-learn==1.5.0, but you have scikit-learn 1.8.0 which is incompatible.
Successfully installed lightgbm-4.6.0
Collecting xgboost==3.1.2
  Downloading xgboost-3.1.2-py3-none-manylinux_2_28_x86_64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost==3.1.2) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost==3.1.2) (2.29.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost==3.1.2) (1.16.3)
Downloading xgboost-3.1.2-py3-none-manylinux_2_28_x86_64.whl (115.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.9/115.9 MB 7.7 MB/s eta 0:00:00
Installing collected packages: xgboost
  Attempting uninstall: xgboost
    Found existing installation: xgboost 3.2.0
    Uninstalling xgboost-3.2.0:
      Successfully uninstalled xgboost-3.2.0
Successfully installed xgboost-3.1.2
Collecting lime==0.2.0.1
  Downloading lime-0.2.0.1.tar.gz (275 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 275.7/275.7 kB 5.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from lime==0.2.0.1) (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from lime==0.2.0.1) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from lime==0.2.0.1) (1.16.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from lime==0.2.0.1) (4.67.3)
Requirement already satisfied: scikit-learn>=0.18 in /usr/local/lib/python3.12/dist-packages (from lime==0.2.0.1) (1.8.0)
Requirement already satisfied: scikit-image>=0.12 in /usr/local/lib/python3.12/dist-packages (from lime==0.2.0.1) (0.25.2)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime==0.2.0.1) (3.6.1)
Requirement already satisfied: pillow>=10.1 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime==0.2.0.1) (11.3.0)
Requirement already satisfied: imageio!=2.35.0,>=2.33 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime==0.2.0.1) (2.37.2)
Requirement already satisfied: tifffile>=2022.8.12 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime==0.2.0.1) (2026.2.16)
Requirement already satisfied: packaging>=21 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime==0.2.0.1) (26.0)
Requirement already satisfied: lazy-loader>=0.4 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime==0.2.0.1) (0.4)
Requirement already satisfied: joblib>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.18->lime==0.2.0.1) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.18->lime==0.2.0.1) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime==0.2.0.1) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime==0.2.0.1) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime==0.2.0.1) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime==0.2.0.1) (1.4.9)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime==0.2.0.1) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime==0.2.0.1) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->lime==0.2.0.1) (1.17.0)
Building wheels for collected packages: lime
  Building wheel for lime (setup.py) ... done
  Created wheel for lime: filename=lime-0.2.0.1-py3-none-any.whl size=283834 sha256=502680376ad6132de326e9537ab005a478851c04c122e1090662c96acd98710a
  Stored in directory: /root/.cache/pip/wheels/e7/5d/0e/4b4fff9a47468fed5633211fb3b76d1db43fe806a17fb7486a
Successfully built lime
Installing collected packages: lime
Successfully installed lime-0.2.0.1
Collecting interpret==0.7.4
  Downloading interpret-0.7.4-py3-none-any.whl.metadata (1.2 kB)
Collecting interpret-core==0.7.4 (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.4->interpret==0.7.4)
  Downloading interpret_core-0.7.4-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from interpret-core==0.7.4->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.4->interpret==0.7.4) (2.0.2)
Requirement already satisfied: pandas>=0.19.2 in /usr/local/lib/python3.12/dist-packages (from interpret-core==0.7.4->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.4->interpret==0.7.4) (2.2.2)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from interpret-core==0.7.4->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.4->interpret==0.7.4) (1.8.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.12/dist-packages (from interpret-core==0.7.4->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.4->interpret==0.7.4) (1.5.3)
Requirement already satisfied: psutil>=5.6.2 in /usr/local/lib/python3.12/dist-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.4->interpret==0.7.4) (5.9.5)
Requirement already satisfied: ipykernel>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.4->interpret==0.7.4) (6.17.1)
Requirement already satisfied: ipython>=5.5.0 in /usr/local/lib/python3.12/dist-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.4->interpret==0.7.4) (7.34.0)
Requirement already satisfied: plotly>=3.8.1 in /usr/local/lib/python3.12/dist-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.4->interpret==0.7.4) (5.24.1)
Collecting SALib>=1.3.3 (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.4->interpret==0.7.4)
  Downloading salib-1.5.2-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: shap>=0.28.5 in /usr/local/lib/python3.12/dist-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.4->interpret==0.7.4) (0.50.0)
Requirement already satisfied: dill>=0.2.5 in /usr/local/lib/python3.12/dist-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.4->interpret==0.7.4) (0.3.8)
Collecting aplr>=10.6.1 (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.4->interpret==0.7.4)
  Downloading aplr-10.21.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.0 kB)
Collecting dash<3.0.0,>=2.0.0 (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.4->interpret==0.7.4)
  Downloading dash-2.18.2-py3-none-any.whl.metadata (10 kB)
Collecting dash-cytoscape>=0.1.1 (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.4->interpret==0.7.4)
  Downloading dash_cytoscape-1.0.2.tar.gz (4.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 40.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting gevent>=1.3.6 (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.4->interpret==0.7.4)
  Downloading gevent-25.9.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (14 kB)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.4->interpret==0.7.4) (2.32.4)
Collecting Flask<3.1,>=1.0.4 (from dash<3.0.0,>=2.0.0->interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.7.4->interpret==0.7.4)
  Downloading flask-3.0.3-py3-none-any.whl.metadata (3.2 kB)

Collecting catboost==1.2.8
  Downloading catboost-1.2.8-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (1.26.4)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost==1.2.8) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost==1.2.8) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost==1.2.8) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost==1.2.8) (9.1.4)
Downloading catboost-1.2.8-cp312-cp312-manylinux2014_x86_64.whl (99.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 MB 6.6 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.8
Collecting pytorch-tabnet2==4.5.3
  Downloading pytorch_tabnet2-4.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting activations-plus>=0.1.1 (from pytorch-tabnet2==4.5.3)
  Downloading activations_plus-0.1.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pytorch-tabnet2==4.5.3) (1.26.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from pytorch-tabnet2==4.5.3) (1.6.1)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from pytorch-tabnet2==4.5.3) (2.10.0+cpu)
Collecting torcheval (from pytorch-tabnet2==4.5.3)
  Downloading torcheval-0.0.7-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->pytorch-tabnet2==4.5.3) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->pytorch-tabnet2==4.5.3) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->pytorch-tabnet2==4.5.3) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (3.24.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (2025.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->pytorch-tabnet2==4.5.3) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->pytorch-tabnet2==4.5.3) (3.0.3)
Downloading pytorch_tabnet2-4.5.3-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.9/70.9 kB 2.6 MB/s eta 0:00:00
Downloading activations_plus-0.1.1-py3-none-any.whl (15 kB)
Downloading torcheval-0.0.7-py3-none-any.whl (179 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.2/179.2 kB 379.5 kB/s eta 0:00:00
Installing collected packages: torcheval, activations-plus, pytorch-tabnet2
Successfully installed activations-plus-0.1.1 pytorch-tabnet2-4.5.3 torcheval-0.0.7

In [ ]:
# Restart the runtime to apply changes
import os
os._exit(00)

# **Imports**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import ngboost
from scipy.stats import randint
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.base import BaseEstimator, RegressorMixin
from sklearn.svm import SVR
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor
from gpboost import GPBoostRegressor
from ngboost import NGBRegressor
import optuna
import optunahub
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import HalvingGridSearchCV
from interpret import show
from interpret.blackbox import LimeTabular, ShapKernel
from optuna.samplers import RandomSampler
import random
import time
from ngboost.distns import Normal
from ngboost.scores import LogScore
from scipy.stats import norm
from interpret import set_visualize_provider
from interpret.provider import InlineProvider
from interpret.glassbox import ExplainableBoostingRegressor
from interpret import show
import plotly.express as px
from io import BytesIO
from openpyxl import Workbook, load_workbook
import os
import properscoring as ps
import io
from openpyxl.drawing.image import Image as openpyxlImage
import warnings
import xlsxwriter
from pgbm.sklearn import HistGradientBoostingRegressor
import torch
from pgbm.torch import PGBM
import plotly.graph_objects as go
warnings.filterwarnings('ignore')
import pickle
import json
from mapie.subsample import Subsample
from mapie.regression import MapieRegressor
from deel.puncc.metrics import regression_sharpness, regression_mean_coverage
from deel.puncc.api.prediction import BasePredictor, DualPredictor
from deel.puncc.regression import SplitCP, CVPlus, CQR
from deel.puncc.plotting import plot_prediction_intervals
from sklearn.model_selection import train_test_split
from typing_extensions import TypedDict
from typing import Union
from mapie.metrics import regression_coverage_score
from sklearn.model_selection import KFold
from PIL import Image as PImage
from pathlib import Path
from scipy.stats import norm, kstest
from pytorch_tabnet import TabNetRegressor
from treeffuser import Treeffuser, Samples
from treeffuser._score_models import TreeBasedScoreModel

In [2]:
# Go to find & replace button and replace (Data_folder) with your folder name. Rename your train and test dataset as train.csv and test.csv.
# Modify the names of the feature in the below cell.
# Replace (EWQI) with actual data label name.

In [3]:
feature_names = [
    'pH', 'TDS', 'EC', 'TH', 'Ca', 'Mg', 'CO3', 'HCO3','Na', 'K', 'Chloride', 'Sulphate', 'Nitrate', 'Fluoride'
]

In [4]:
train_data_path = "./drive/MyDrive/EWQI/Data/train.csv"
test_data_path = "./drive/MyDrive/EWQI/Data/test.csv"
train_data = pd.read_csv(train_data_path)
test_data = pd.read_csv(test_data_path)
print("Training data loaded successfully.")
print("Test data loaded successfully.")

Training data loaded successfully.
Test data loaded successfully.

In [5]:
print("\nShape of training data:", train_data.shape)
print("First 5 rows of training data:\n", train_data.head(5))
print("\nShape of test data:", test_data.shape)
print("First 5 rows of test data:\n", test_data.head(5))

Shape of training data: (47, 15)
First 5 rows of training data:
      pH   TDS    EC    TH   ca    mg  CO3  HCO3   NA    K  CHLORIDE  SULPHATE  \
0  7.90   552   865   452  272   180  0.2   4.5  260   44       375       681
1  7.52  1985  2256  1054  529   525  0.0  15.0  272   47       728       324
2  7.65  1865  2032   636  371   265  0.0   9.0  373   25       713       503
3  7.25  4855  7856  2050  795  1255  0.0  12.5  335  106        81       676
4  7.96  2855  3696   865  310   555  0.3   4.6  184  106       698       324

   NITRATE  FLUORIDE  Pre monsoon EWQI
0       60      0.40              70.52
1       10      0.65             138.78
2       54      0.85             113.07
3       17      0.69             266.32
4       25      1.20             158.05

Shape of test data: (47, 15)
First 5 rows of test data:
      pH   TDS    EC    TH     ca      mg  CO3  HCO3   NA    K  CHLORIDE  \
0  8.38   625   975   320  120.0   200.0  0.0   5.8  280   35       398
1  7.31  2020  2860   960  410.0   550.0  0.0  11.0  302   65       765
2  7.80  1630  2380   440  165.0   275.0  0.0   7.0  356   29       745
3  7.06  6300  8910  2356  776.0  1580.0  0.0  10.8  396  112       124
4  4.60  2290  3570  1080  470.0   610.0  0.0   6.2  225  125       745

   SULPHATE  NITRATE  FLUORIDE  Post monsoon EWQI
0       755       75      0.48              73.07
1       365       26      0.71             141.67
2       525       85      0.89             110.44
3       745       24      0.75             275.01
4       336       15      1.35             202.57

In [6]:
X_train = train_data.iloc[:, :-1]
y_train = train_data.iloc[:, -1]
X_test = test_data.iloc[:, :-1]
y_test = test_data.iloc[:, -1]
x_test= X_test
print("\nShape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (47, 14)
Shape of y_train: (47,)
Shape of X_test: (47, 14)
Shape of y_test: (47,)

In [7]:
# Apply z-score normalization
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Print the first five rows of the normalized data
print("\nFirst five rows of normalized X_train:")
print(X_train[:5])

print("\nFirst five rows of normalized X_test:")
print(X_test[:5])

First five rows of normalized X_train:
[[ 0.3797749  -1.15230942 -0.94309903 -0.47923131 -0.09229732 -0.56852482
  -0.03922784 -1.18768739 -0.02713192 -0.87884263 -0.2770724   1.15873613
   1.41276153 -1.25316406]
 [-0.78765707 -0.2953837  -0.52059702  0.45803078  1.31357822  0.10564733
  -0.50015494  1.61405127  0.07159325 -0.77136925  1.29937074 -0.45273785
  -1.61366471 -0.53733141]
 [-0.38827245 -0.36714301 -0.58863473 -0.19275917  0.44926563 -0.40242444
  -0.50015494  0.01305775  0.90253007 -1.55950739  1.23238307  0.35525611
   1.04959038  0.03533472]
 [-1.61714822  1.42085972  1.18034563  2.00871688  2.76868675  1.53215652
  -0.50015494  0.94697063  0.58990037  1.34227396 -1.59003071  1.13616647
  -1.18996504 -0.42279818]
 [ 0.56410627  0.22487128 -0.08321177  0.16377408  0.11557533  0.16427099
   0.19123571 -1.16100417 -0.6523913   1.34227396  1.1653954  -0.45273785
  -0.70573684  1.03750043]]

First five rows of normalized X_test:
[[ 1.85442582 -1.10865585 -0.90968766 -0.68474392 -0.92378791 -0.52944238
  -0.50015494 -0.84080546  0.13741003 -1.20126278 -0.17435797  1.49276715
   2.3206894  -1.02409761]
 [-1.43281685 -0.2744539  -0.33713821  0.31168088  0.66260861  0.15450038
  -0.50015494  0.54672225  0.31840617 -0.12652895  1.46460699 -0.26766661
  -0.64520832 -0.36553157]
 [ 0.07255596 -0.50767165 -0.48293329 -0.49791427 -0.67762293 -0.38288322
  -0.50015494 -0.52060676  0.76266941 -1.41620955  1.37529009  0.45456263
   2.92597465  0.14986794]
 [-2.2008642   2.28496138  1.50048734  2.48513249  2.66475042  2.16724622
  -0.50015494  0.4933558   1.0917533   1.55722072 -1.39799939  1.44762783
  -0.76626537 -0.25099834]
 [-9.75845017 -0.11299546 -0.12148298  0.49851054  0.99082858  0.27174771
  -0.50015494 -0.73407256 -0.31508032  2.02293872  1.37529009 -0.39857066
  -1.31102209  1.46700003]]

# **Functions:**

In [8]:
def get_best_model_params(results, model_name):
    # Map model names to dictionary keys, assuming keys are strings like 'XGBoost' and not objects
    model_keys = {
        'LightGBM': 'LightGBM',
        'XGBoost': 'XGBoost',
        'GPBoost': 'GPBoost',
        'NGBoost': 'NGBoost',
        'GradientBoosting': 'Gradient Boosting',
        'HGBR' : 'HistGradientBoosting',
        'CatBoost' : 'CatBoost',
        'PGBM' : 'PGBM'
    }

    # Ensure the requested model name is valid
    if model_name not in model_keys:
        raise ValueError(f"Model name '{model_name}' is not recognized. Available models are: {list(model_keys.keys())}")

    # Filter out entries for the specified model
    model_entries = {key: value for key, value in results.items() if key[0] == model_keys[model_name]}

    # Find the entry with the best (lowest) 'best_score'
    best_entry_key, best_entry_value = min(model_entries.items(), key=lambda item: item[1]['best_score'])

    # Return the best hyperparameters
    return best_entry_value['best_params']

In [9]:
def generate_and_save_plots(predictions_df, y_test, excel_path):
    # 1. Predicted vs. Actual Plot
    plt.figure(figsize=(12, 8))
    sns.scatterplot(x='Actual', y='Mean', data=predictions_df)
    plt.plot([predictions_df['Actual'].min(), predictions_df['Actual'].max()],
             [predictions_df['Actual'].min(), predictions_df['Actual'].max()],
             color='red', linestyle='--')
    plt.title('Predicted EWQI vs. Actual EWQI')
    plt.xlabel('Actual EWQI')
    plt.ylabel('Predicted Mean EWQI')
    plt.tight_layout()
    predicted_vs_actual_path = 'predicted_vs_actual.png'
    plt.savefig(predicted_vs_actual_path)
    plt.close()

    # 2. Uncertainty Bands
    plt.figure(figsize=(12, 8))
    plt.errorbar(x=range(len(predictions_df)), y=predictions_df['Mean'],
                 yerr=predictions_df['StdDev'], fmt='o', markersize=4, ecolor='red', elinewidth=1, capsize=5, alpha=0.7)
    plt.plot(range(len(predictions_df)), predictions_df['Mean'], color='black', linewidth=0.5, alpha=0.7)
    plt.title('Predicted Mean with Uncertainty Bands', fontsize=16)
    plt.xlabel('Sample Number', fontsize=14)
    plt.ylabel('Predicted Mean EWQI')
    plt.tight_layout()
    uncertainty_bands_path = 'uncertainty_bands.png'
    plt.savefig(uncertainty_bands_path)
    plt.close()

    # 3. Histogram of Standard Deviations
    plt.figure(figsize=(12, 8))
    sns.histplot(predictions_df['StdDev'], bins=20, kde=True)
    plt.title('Distribution of Predicted Standard Deviations')
    plt.xlabel('Standard Deviation')
    plt.ylabel('Frequency')
    plt.tight_layout()
    histogram_stddev_path = 'histogram_stddev.png'
    plt.savefig(histogram_stddev_path)
    plt.close()

    # 4. Residual Plot
    residuals = predictions_df['Actual'] - predictions_df['Mean']
    plt.figure(figsize=(12, 8))
    sns.scatterplot(x=predictions_df['Mean'], y=residuals)
    plt.axhline(0, color='red', linestyle='--')
    plt.title('Residual Plot')
    plt.xlabel('Predicted Mean EWQI')
    plt.ylabel('Residuals')
    plt.tight_layout()
    residual_plot_path = 'residual_plot.png'
    plt.savefig(residual_plot_path)
    plt.close()

    # Plot the standard deviation of the predictions
    plt.figure(figsize=(12, 6))
    plt.plot(
        predictions_df['StdDev'],
        label='Standard Deviation',
        color='green',
        marker='o',
        linestyle='dashed'
    )
    plt.xlabel('Sample Number')
    plt.ylabel('Standard Deviation')
    plt.title('Standard Deviation of Predictions')
    plt.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
    plt.tight_layout()
    stddev_plot_path = 'stddev_plot.png'
    plt.savefig(stddev_plot_path)
    plt.close()

    # Plot the actual vs predicted mean with confidence intervals
    plt.figure(figsize=(12, 6))
    plt.plot(
        y_test,
        label='Actual EWQI',
        color='black',
        marker='o',
        linestyle='dashed',
        linewidth=1,
        markersize=4
    )
    plt.plot(
        predictions_df['Mean'],
        label='Predicted Mean EWQI',
        color='red',
        marker='x',
        linestyle='dashed',
        linewidth=1,
        markersize=4
    )
    confidence_interval = 1.96 * predictions_df['StdDev']
    plt.fill_between(
        np.arange(len(predictions_df)),
        predictions_df['Mean'] - confidence_interval,
        predictions_df['Mean'] + confidence_interval,
        color='blue',
        alpha=0.2,
        label='95% Confidence Interval'
    )
    plt.xlabel('Sample Number')
    plt.ylabel(' EWQI')
    plt.title('Predictions with Confidence Intervals')
    plt.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
    plt.tight_layout()
    prediction_plot_path = 'prediction_plot.png'
    plt.savefig(prediction_plot_path)
    plt.close()

    # Create a Pandas Excel writer using XlsxWriter as the engine.
    writer = pd.ExcelWriter(excel_path, engine='xlsxwriter')

    # Write the dataframe to a worksheet.
    predictions_df.to_excel(writer, sheet_name='Predictions', index=False)

    # Access the XlsxWriter workbook and worksheet objects from the writer object.
    workbook = writer.book

    # Insert the plots into new worksheets.
    worksheet_predicted_vs_actual = workbook.add_worksheet('Predicted vs Actual')
    worksheet_predicted_vs_actual.insert_image('A1', predicted_vs_actual_path)

    worksheet_uncertainty_bands = workbook.add_worksheet('Uncertainty Bands')
    worksheet_uncertainty_bands.insert_image('A1', uncertainty_bands_path)

    worksheet_histogram_stddev = workbook.add_worksheet('Histogram StdDev')
    worksheet_histogram_stddev.insert_image('A1', histogram_stddev_path)

    worksheet_residual_plot = workbook.add_worksheet('Residual Plot')
    worksheet_residual_plot.insert_image('A1', residual_plot_path)

    worksheet_stddev = workbook.add_worksheet('StdDev Plot')
    worksheet_stddev.insert_image('A1', stddev_plot_path)

    worksheet_prediction = workbook.add_worksheet('Predictions Plot')
    worksheet_prediction.insert_image('A1', prediction_plot_path)

    # Close the Pandas Excel writer and output the Excel file.
    writer.close()
    print(f"Excel file saved at {excel_path}")

    # Optionally, remove the image files now that they're embedded in the Excel file
    os.remove(predicted_vs_actual_path)
    os.remove(uncertainty_bands_path)
    os.remove(histogram_stddev_path)
    os.remove(residual_plot_path)
    os.remove(stddev_plot_path)
    os.remove(prediction_plot_path)

In [10]:
def generate_and_save_crps_decomposition(
    predictions_df,
    y_true,
    excel_path,
    model_name="Model",
    n_bins=10
):

    # -------------------------------
    # Input handling
    # -------------------------------
    mu_pred = predictions_df['Mean'].values
    sigma_pred = predictions_df['StdDev'].values

    if 'Actual' in predictions_df.columns:
        y_true = predictions_df['Actual'].values
    else:
        y_true = np.asarray(y_true).ravel()

    y_true = np.asarray(y_true).ravel()

    # -------------------------------
    # Total CRPS
    # -------------------------------
    crps_values = ps.crps_gaussian(
        y_true, mu=mu_pred, sig=sigma_pred
    )
    total_crps = np.mean(crps_values)

    # -------------------------------
    # Uncertainty (climatology)
    # -------------------------------
    global_mu = np.mean(y_true)
    global_sigma = np.std(y_true)

    uncertainty = np.mean(
        ps.crps_gaussian(y_true, mu=global_mu, sig=global_sigma)
    )

    # -------------------------------
    # Reliability & Resolution
    # -------------------------------
    sort_idx = np.argsort(mu_pred)
    y_sorted = y_true[sort_idx]
    mu_sorted = mu_pred[sort_idx]
    sigma_sorted = sigma_pred[sort_idx]

    bins = np.array_split(np.arange(len(y_true)), n_bins)

    bin_results = []
    reliability_sum = 0.0

    for i, b in enumerate(bins):
        bin_y = y_sorted[b]
        bin_mu = mu_sorted[b]
        bin_sigma = sigma_sorted[b]

        bin_crps = np.mean(
            ps.crps_gaussian(bin_y, mu=bin_mu, sig=bin_sigma)
        )

        reliability_sum += bin_crps

        bin_results.append({
            "Bin": i + 1,
            "Bin_Size": len(b),
            "Mean_Pred_Mu": np.mean(bin_mu),
            "Mean_Pred_Sigma": np.mean(bin_sigma),
            "Bin_CRPS": bin_crps
        })

    reliability = reliability_sum / n_bins
    resolution = uncertainty - (total_crps - reliability)

    # -------------------------------
    # Summary table
    # -------------------------------
    summary_df = pd.DataFrame([{
        "Model": model_name,
        "Total_CRPS": total_crps,
        "Reliability": reliability,
        "Resolution": resolution,
        "Uncertainty": uncertainty,
        "Num_Bins": n_bins
    }])

    bin_df = pd.DataFrame(bin_results)

    # -------------------------------
    # Save to Excel
    # -------------------------------
    excel_path = Path(excel_path)
    excel_path.parent.mkdir(parents=True, exist_ok=True)

    sheet_summary = f"CRPS_Summary_{model_name}"
    sheet_bins = f"CRPS_Bins_{model_name}"

    with pd.ExcelWriter(
        excel_path,
        engine="openpyxl",
        mode="a" if excel_path.exists() else "w",
        if_sheet_exists="replace"
    ) as writer:
        summary_df.to_excel(writer, sheet_name=sheet_summary, index=False)
        bin_df.to_excel(writer, sheet_name=sheet_bins, index=False)

    print(f"✅ CRPS decomposition saved to:\n{excel_path}")
    print(f"   Sheets: {sheet_summary}, {sheet_bins}")

    return summary_df

In [11]:
def generate_and_save_pit_results(
    predictions_df,
    y_true,
    excel_path,
    model_name="Model",
    n_bins=10
):
    """
    Generate PIT values, histogram, calibration diagnostics,
    and save everything to Excel with the PIT plot EMBEDDED.
    """

    # -------------------------------
    # Input handling
    # -------------------------------
    mu_pred = predictions_df['Mean'].values
    sigma_pred = predictions_df['StdDev'].values

    if 'Actual' in predictions_df.columns:
        y_true = predictions_df['Actual'].values
    else:
        y_true = np.asarray(y_true).ravel()

    y_true = np.asarray(y_true).ravel()

    sigma_pred = np.clip(sigma_pred, 1e-6, None)

    # -------------------------------
    # Compute PIT values
    # -------------------------------
    pit_values = norm.cdf(y_true, loc=mu_pred, scale=sigma_pred)

    pit_df = pd.DataFrame({"PIT_Value": pit_values})

    # -------------------------------
    # Histogram data
    # -------------------------------
    hist_density, bin_edges = np.histogram(
        pit_values, bins=n_bins, range=(0, 1), density=True
    )
    bin_centers = 0.5 * (bin_edges[:-1] + bin_edges[1:])

    hist_df = pd.DataFrame({
        "Bin_Center": bin_centers,
        "Density": hist_density
    })

    # -------------------------------
    # Calibration diagnostics
    # -------------------------------
    pit_mean = pit_values.mean()
    pit_var = pit_values.var()
    ks_stat, ks_pvalue = kstest(pit_values, 'uniform')

    if ks_pvalue > 0.05:
        diagnosis = "Well-calibrated (Uniform PIT)"
    elif pit_var < 1/12:
        diagnosis = "Over-dispersed (Under-confident)"
    elif pit_var > 1/12:
        diagnosis = "Under-dispersed (Over-confident)"
    else:
        diagnosis = "Biased or miscalibrated"

    summary_df = pd.DataFrame([{
        "Model": model_name,
        "Mean_PIT": pit_mean,
        "Variance_PIT": pit_var,
        "Ideal_Variance_(1/12)": 1/12,
        "KS_Statistic": ks_stat,
        "KS_pvalue": ks_pvalue,
        "Calibration_Diagnosis": diagnosis
    }])

    # -------------------------------
    # Create PIT plot in memory
    # -------------------------------
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.hist(
        pit_values,
        bins=n_bins,
        density=True,
        color="skyblue",
        edgecolor="black",
        alpha=0.75
    )
    ax.axhline(1, color="red", linestyle="--", label="Perfect Calibration")
    ax.set_xlabel("PIT Value")
    ax.set_ylabel("Density")
    ax.set_title(f"PIT Histogram – {model_name}")
    ax.legend()
    fig.tight_layout()

    img_buffer = BytesIO()
    fig.savefig(img_buffer, format="png", dpi=300)
    plt.close(fig)
    img_buffer.seek(0)

    # -------------------------------
    # Save to Excel
    # -------------------------------
    excel_path = Path(excel_path)
    excel_path.parent.mkdir(parents=True, exist_ok=True)

    sheet_values = f"PIT_Values_{model_name}"
    sheet_hist = f"PIT_Histogram_{model_name}"
    sheet_summary = f"PIT_Summary_{model_name}"
    sheet_plot = f"PIT_Plot_{model_name}"

    with pd.ExcelWriter(
        excel_path,
        engine="openpyxl",
        mode="a" if excel_path.exists() else "w",
        if_sheet_exists="replace"
    ) as writer:

        pit_df.to_excel(writer, sheet_name=sheet_values, index=False)
        hist_df.to_excel(writer, sheet_name=sheet_hist, index=False)
        summary_df.to_excel(writer, sheet_name=sheet_summary, index=False)

        # Create empty sheet for plot
        workbook = writer.book
        worksheet = workbook.create_sheet(sheet_plot)

        img = openpyxlImage(img_buffer)
        img.width = img.width * 0.4
        img.height = img.height * 0.4

        img.anchor = "B2"
        worksheet.add_image(img)

    print(f"✅ PIT values, histogram, summary, and EMBEDDED plot saved to:")
    print(f"   {excel_path}")

    return pit_df

In [12]:
def generate_and_save_calibration_curve(
    predictions_df,
    y_true,
    excel_path,
    model_name="Model",
    n_quantiles=10
):
    """
    Generate quantile calibration curve (reliability diagram),
    compute calibration errors, and save everything to Excel
    with the plot EMBEDDED.
    """

    # -------------------------------
    # Input handling
    # -------------------------------
    mu_pred = predictions_df['Mean'].values
    sigma_pred = predictions_df['StdDev'].values

    if 'Actual' in predictions_df.columns:
        y_true = predictions_df['Actual'].values
    else:
        y_true = np.asarray(y_true).ravel()

    y_true = np.asarray(y_true).ravel()
    sigma_pred = np.clip(sigma_pred, 1e-6, None)

    # -------------------------------
    # Quantiles
    # -------------------------------
    quantiles = np.linspace(0, 1, n_quantiles + 1)

    observed_freq = []
    predicted_q = []

    for q in quantiles:
        # Predicted value at quantile q
        thresh = norm.ppf(q, loc=mu_pred, scale=sigma_pred)

        # Observed frequency
        obs = np.mean(y_true <= thresh)

        predicted_q.append(q)
        observed_freq.append(obs)

    predicted_q = np.array(predicted_q)
    observed_freq = np.array(observed_freq)

    # -------------------------------
    # Calibration metrics
    # -------------------------------
    mce = np.mean(np.abs(observed_freq - predicted_q))
    rmsce = np.sqrt(np.mean((observed_freq - predicted_q) ** 2))

    calib_df = pd.DataFrame({
        "Predicted_Quantile": predicted_q,
        "Observed_Frequency": observed_freq,
        "Absolute_Error": np.abs(observed_freq - predicted_q)
    })

    summary_df = pd.DataFrame([{
        "Model": model_name,
        "Mean_Calibration_Error (MCE)": mce,
        "RMS_Calibration_Error (RMSCE)": rmsce,
        "Num_Quantiles": n_quantiles
    }])

    # -------------------------------
    # Create calibration plot
    # -------------------------------
    fig, ax = plt.subplots(figsize=(7, 7))

    ax.plot([0, 1], [0, 1], 'k--', label="Perfect Calibration")
    ax.plot(
        predicted_q,
        observed_freq,
        'o-',
        color='teal',
        label=f"{model_name}"
    )

    ax.set_xlabel("Predicted Quantile (Confidence Level)")
    ax.set_ylabel("Observed Frequency")
    ax.set_title(f"Quantile Calibration Curve – {model_name}")
    ax.legend()
    fig.tight_layout()

    img_buffer = BytesIO()
    fig.savefig(img_buffer, format="png", dpi=300)
    plt.close(fig)
    img_buffer.seek(0)

    # -------------------------------
    # Save to Excel
    # -------------------------------
    excel_path = Path(excel_path)
    excel_path.parent.mkdir(parents=True, exist_ok=True)

    sheet_curve = f"Calibration_Curve_{model_name}"
    sheet_summary = f"Calibration_Summary_{model_name}"
    sheet_plot = f"Calibration_Plot_{model_name}"

    with pd.ExcelWriter(
        excel_path,
        engine="openpyxl",
        mode="a" if excel_path.exists() else "w",
        if_sheet_exists="replace"
    ) as writer:

        calib_df.to_excel(writer, sheet_name=sheet_curve, index=False)
        summary_df.to_excel(writer, sheet_name=sheet_summary, index=False)

        workbook = writer.book

        worksheet = workbook.create_sheet(sheet_plot)

        img = openpyxlImage(img_buffer)
        img.width = img.width * 0.4
        img.height = img.height * 0.4

        img.anchor = "B2"
        worksheet.add_image(img)

    print("✅ Calibration curve & metrics saved to Excel:")
    print(f"   {excel_path}")

    return calib_df

In [13]:
# Define the path to the folder
folder_path = "/content/drive/MyDrive/EWQI"

# Create the folder if it doesn't exist
os.makedirs(folder_path, exist_ok=True)

def plot_metrics_and_save_to_excel(writer, predictions_df, y_true, model_name):
    # Calculate metrics
    mean_pred = predictions_df['Mean']
    std_pred = predictions_df['StdDev']

    # Sharpness is the standard deviation
    sharpness = std_pred.mean()

    # CRPS for each prediction
    crps_values = ps.crps_gaussian(y_true, mean_pred, std_pred)

    # Negative Log Likelihood (NLL) for each prediction
    nll_values = -norm.logpdf(y_true, loc=mean_pred, scale=std_pred)
    nll = nll_values.mean()

    # Calibration (Validity)
    percentiles = np.linspace(0, 100, 101)
    calibration = [np.mean((y_true <= np.percentile(mean_pred + std_pred * np.random.randn(*mean_pred.shape), p))) for p in percentiles]

    # Create a DataFrame to store the metrics
    metrics_df = pd.DataFrame({
        'Mean Prediction': mean_pred,
        'Standard Deviation': std_pred,
        'CRPS': crps_values,
        'NLL': nll_values
    })

    # Add summary statistics
    summary_df = pd.DataFrame({
        'Metric': ['Sharpness', 'Mean CRPS', 'Mean NLL'],
        'Value': [sharpness, crps_values.mean(), nll]
    })

    # Write the metrics and summary to the Excel sheet
    metrics_sheet_name = f'{model_name} Metrics'
    metrics_df.to_excel(writer, sheet_name=metrics_sheet_name, index=False)

    summary_sheet_name = f'{model_name} Summary'
    summary_df.to_excel(writer, sheet_name=summary_sheet_name, index=False)

    # Plotting
    fig, axs = plt.subplots(2, 2, figsize=(12, 10))

    # Sharpness plot
    axs[0, 0].hist(std_pred, bins=30, color='skyblue', edgecolor='black')
    axs[0, 0].set_title(f'Sharpness (StdDev) for {model_name}')
    axs[0, 0].set_xlabel('Standard Deviation')
    axs[0, 0].set_ylabel('Frequency')

    # CRPS plot (distribution)
    axs[0, 1].hist(crps_values, bins=30, color='lightgreen', edgecolor='black')
    axs[0, 1].set_title(f'CRPS Distribution for {model_name}')
    axs[0, 1].set_xlabel('CRPS')
    axs[0, 1].set_ylabel('Frequency')

    # NLL plot (distribution)
    axs[1, 0].hist(nll_values, bins=30, color='salmon', edgecolor='black')
    axs[1, 0].set_title(f'NLL Distribution for {model_name}')
    axs[1, 0].set_xlabel('NLL')
    axs[1, 0].set_ylabel('Frequency')

    # Calibration plot
    axs[1, 1].plot(percentiles, calibration, label='Calibration Curve')
    axs[1, 1].plot(percentiles, percentiles / 100, linestyle='--', label='Perfect Calibration')
    axs[1, 1].set_title(f'Calibration (Validity) for {model_name}')
    axs[1, 1].set_xlabel('Predicted Percentile')
    axs[1, 1].set_ylabel('Observed Frequency')
    axs[1, 1].legend()

    plt.tight_layout()

    # Save plots to images
    plot_image_path = f'{model_name}_plots.png'
    fig.savefig(plot_image_path)
    plt.close(fig)

    # Insert the plot image into the Excel sheet
    sheet_name = f'{model_name} Plots'
    if sheet_name not in writer.sheets:  # Check if sheet already exists
        # If sheet doesn't exist, create a new one
        worksheet = writer.book.add_worksheet(sheet_name)
    else:
        # If sheet exists, get the existing sheet object to avoid duplicates
        worksheet = writer.sheets[sheet_name]
    worksheet.insert_image('A1', plot_image_path)

# **Tuned Parameters**

In [14]:
best_scores_autosampler = {('Random Forest', 'MedianPruner'): {'best_score': 496.77749759305107,
  'best_params': {'n_estimators': 500,
   'criterion': 'squared_error',
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.0},
  'test_mse': 496.77749759305107,
  'test_rmse': 22.288505952464625,
  'test_corr_coef': 0.956804497169129,
  'pruner': 'MedianPruner'},
 ('Random Forest', 'NopPruner'): {'best_score': 497.17260666013107,
  'best_params': {'n_estimators': 500,
   'criterion': 'squared_error',
   'max_depth': None,
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_features': 0.5,
   'max_leaf_nodes': 200,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.1},
  'test_mse': 497.17260666013107,
  'test_rmse': 22.297367706976782,
  'test_corr_coef': 0.956734599665225,
  'pruner': 'NopPruner'},
 ('Random Forest', 'PatientPruner'): {'best_score': 491.58703506641024,
  'best_params': {'n_estimators': 200,
   'criterion': 'squared_error',
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.2,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.01},
  'test_mse': 491.58703506641024,
  'test_rmse': 22.171762110089723,
  'test_corr_coef': 0.9565223125605573,
  'pruner': 'PatientPruner'},
 ('Random Forest', 'PercentilePruner'): {'best_score': 499.01334098661863,
  'best_params': {'n_estimators': 200,
   'criterion': 'absolute_error',
   'max_depth': 40,
   'min_samples_split': 0.01,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.2,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001},
  'test_mse': 499.01334098661863,
  'test_rmse': 22.338606513984228,
  'test_corr_coef': 0.9581329488959801,
  'pruner': 'PercentilePruner'},
 ('Random Forest',
  'SuccessiveHalvingPruner'): {'best_score': 504.01487183783377, 'best_params': {'n_estimators': 100,
   'criterion': 'friedman_mse',
   'max_depth': None,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.1,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.01}, 'test_mse': 504.01487183783377, 'test_rmse': 22.450275540354372, 'test_corr_coef': 0.955958931998181, 'pruner': 'SuccessiveHalvingPruner'},
 ('Random Forest', 'HyperbandPruner'): {'best_score': 499.0331708466262,
  'best_params': {'n_estimators': 700,
   'criterion': 'squared_error',
   'max_depth': None,
   'min_samples_split': 0.01,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.01,
   'max_features': 0.5,
   'max_leaf_nodes': 200,
   'min_impurity_decrease': 0.2,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.05},
  'test_mse': 499.0331708466262,
  'test_rmse': 22.3390503568667,
  'test_corr_coef': 0.9564495763116471,
  'pruner': 'HyperbandPruner'},
 ('Random Forest', 'ThresholdPruner'): {'best_score': 497.11506466625553,
  'best_params': {'n_estimators': 500,
   'criterion': 'squared_error',
   'max_depth': 10,
   'min_samples_split': 0.01,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.01,
   'max_features': 0.5,
   'max_leaf_nodes': 50,
   'min_impurity_decrease': 0.2,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.1},
  'test_mse': 497.11506466625553,
  'test_rmse': 22.296077338093703,
  'test_corr_coef': 0.9567718647561463,
  'pruner': 'ThresholdPruner'},
 ('Random Forest', 'WilcoxonPruner'): {'best_score': 491.08002163339074,
  'best_params': {'n_estimators': 200,
   'criterion': 'squared_error',
   'max_depth': 20,
   'min_samples_split': 2,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.01,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.01},
  'test_mse': 491.08002163339074,
  'test_rmse': 22.160325395476274,
  'test_corr_coef': 0.9566343173406529,
  'pruner': 'WilcoxonPruner'},
 ('Gradient Boosting', 'MedianPruner'): {'best_score': 186.2899803104867,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 500,
   'subsample': 0.7,
   'criterion': 'squared_error',
   'min_samples_split': 10,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 5,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.01},
  'test_mse': 186.2899803104867,
  'test_rmse': 13.648808750601157,
  'test_corr_coef': 0.9725621388727219,
  'pruner': 'MedianPruner'},
 ('Gradient Boosting', 'NopPruner'): {'best_score': 211.7326358072223,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 500,
   'subsample': 0.5,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 10,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': 'log2',
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 30,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.01},
  'test_mse': 211.7326358072223,
  'test_rmse': 14.551035557898356,
  'test_corr_coef': 0.9714617114917357,
  'pruner': 'NopPruner'},
 ('Gradient Boosting', 'PatientPruner'): {'best_score': 226.32308192609057,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.2,
   'n_estimators': 300,
   'subsample': 0.9,
   'criterion': 'squared_error',
   'min_samples_split': 10,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.0001,
   'ccp_alpha': 0.001},
  'test_mse': 226.32308192609057,
  'test_rmse': 15.044038085769744,
  'test_corr_coef': 0.9692168454493556,
  'pruner': 'PatientPruner'},
 ('Gradient Boosting', 'PercentilePruner'): {'best_score': 183.60943493639752,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 700,
   'subsample': 0.7,
   'criterion': 'friedman_mse',
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 10,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 30,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'tol': 0.0001,
   'ccp_alpha': 0.01},
  'test_mse': 183.60943493639752,
  'test_rmse': 13.550255899295685,
  'test_corr_coef': 0.9785532886277138,
  'pruner': 'PercentilePruner'},
 ('Gradient Boosting',
  'SuccessiveHalvingPruner'): {'best_score': 188.85720758880905, 'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 500,
   'subsample': 0.7,
   'criterion': 'squared_error',
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 3,
   'min_impurity_decrease': 0.1,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': 50,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.0001,
   'ccp_alpha': 0.0}, 'test_mse': 188.85720758880905, 'test_rmse': 13.742532793805116, 'test_corr_coef': 0.9768378796573041, 'pruner': 'SuccessiveHalvingPruner'},
 ('Gradient Boosting', 'HyperbandPruner'): {'best_score': 153.75648954584392,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 300,
   'subsample': 0.5,
   'criterion': 'squared_error',
   'min_samples_split': 10,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.05,
   'max_depth': 7,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.01},
  'test_mse': 153.75648954584392,
  'test_rmse': 12.399858448621256,
  'test_corr_coef': 0.9769080213173296,
  'pruner': 'HyperbandPruner'},
 ('Gradient Boosting', 'ThresholdPruner'): {'best_score': 163.7151008337401,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.01,
   'n_estimators': 500,
   'subsample': 0.7,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 10,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.001},
  'test_mse': 163.7151008337401,
  'test_rmse': 12.79512019614275,
  'test_corr_coef': 0.9785863457606022,
  'pruner': 'ThresholdPruner'},
 ('Gradient Boosting', 'WilcoxonPruner'): {'best_score': 203.07392186675133,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 200,
   'subsample': 0.5,
   'criterion': 'squared_error',
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 10,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.01},
  'test_mse': 203.07392186675133,
  'test_rmse': 14.250400761618998,
  'test_corr_coef': 0.9717306620069607,
  'pruner': 'WilcoxonPruner'},
 ('XGBoost', 'MedianPruner'): {'best_score': 182.4639007284696,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.1,
   'max_depth': 3,
   'min_child_weight': 1,
   'gamma': 0.5,
   'subsample': 0.6,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 182.4639007284696,
  'test_rmse': 13.507919926045965,
  'test_corr_coef': 0.9759722627311321,
  'pruner': 'MedianPruner'},
 ('XGBoost', 'NopPruner'): {'best_score': 207.7563248132366,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'max_depth': 3,
   'min_child_weight': 1,
   'gamma': 1,
   'subsample': 0.5,
   'colsample_bytree': 0.5,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0.01,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 207.7563248132366,
  'test_rmse': 14.413754709069966,
  'test_corr_coef': 0.973407103840386,
  'pruner': 'NopPruner'},
 ('XGBoost', 'PatientPruner'): {'best_score': 171.42745522951924,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.1,
   'max_depth': 3,
   'min_child_weight': 1,
   'gamma': 0.1,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 1,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 171.42745522951924,
  'test_rmse': 13.093030788534763,
  'test_corr_coef': 0.973670001338332,
  'pruner': 'PatientPruner'},
 ('XGBoost', 'PercentilePruner'): {'best_score': 159.5769088653608,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'max_depth': 3,
   'min_child_weight': 1,
   'gamma': 0.5,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 159.5769088653608,
  'test_rmse': 12.632375424494033,
  'test_corr_coef': 0.9781404799102082,
  'pruner': 'PercentilePruner'},
 ('XGBoost', 'SuccessiveHalvingPruner'): {'best_score': 278.2881193971079,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'max_depth': 7,
   'min_child_weight': 3,
   'gamma': 0.1,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 278.2881193971079,
  'test_rmse': 16.681969889587617,
  'test_corr_coef': 0.9661059064338804,
  'pruner': 'SuccessiveHalvingPruner'},
 ('XGBoost', 'HyperbandPruner'): {'best_score': 196.03189004000157,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'max_depth': 3,
   'min_child_weight': 1,
   'gamma': 0.1,
   'subsample': 0.5,
   'colsample_bytree': 0.7,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 196.03189004000157,
  'test_rmse': 14.001138883676626,
  'test_corr_coef': 0.9735341381049875,
  'pruner': 'HyperbandPruner'},
 ('XGBoost', 'ThresholdPruner'): {'best_score': 216.78222120594558,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.1,
   'max_depth': 7,
   'min_child_weight': 3,
   'gamma': 0.1,
   'subsample': 0.6,
   'colsample_bytree': 0.7,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 216.78222120594558,
  'test_rmse': 14.723526113195357,
  'test_corr_coef': 0.9718893462363486,
  'pruner': 'ThresholdPruner'},
 ('XGBoost', 'WilcoxonPruner'): {'best_score': 190.25624389977247,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.15,
   'max_depth': 3,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.6,
   'colsample_bytree': 0.7,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 190.25624389977247,
  'test_rmse': 13.793340563466577,
  'test_corr_coef': 0.9741167324497741,
  'pruner': 'WilcoxonPruner'},
 ('LightGBM', 'MedianPruner'): {'best_score': 221.50989561280434,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'num_leaves': 15,
   'max_depth': -1,
   'min_child_samples': 1,
   'subsample': 0.6,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.01,
   'reg_lambda': 1,
   'min_child_weight': 0.001,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 221.50989561280434,
  'test_rmse': 14.883208512038133,
  'test_corr_coef': 0.9699035026881411,
  'pruner': 'MedianPruner'},
 ('LightGBM', 'NopPruner'): {'best_score': 192.8091126593126,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'num_leaves': 15,
   'max_depth': 3,
   'min_child_samples': 1,
   'subsample': 0.6,
   'colsample_bytree': 0.5,
   'reg_alpha': 1,
   'reg_lambda': 0.1,
   'min_child_weight': 0.001,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 192.8091126593126,
  'test_rmse': 13.8855721041415,
  'test_corr_coef': 0.9738620305498757,
  'pruner': 'NopPruner'},
 ('LightGBM', 'PatientPruner'): {'best_score': 245.61587828860456,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.05,
   'num_leaves': 15,
   'max_depth': -1,
   'min_child_samples': 1,
   'subsample': 0.6,
   'colsample_bytree': 0.9,
   'reg_alpha': 1,
   'reg_lambda': 0.1,
   'min_child_weight': 0.01,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 245.61587828860456,
  'test_rmse': 15.672137004525087,
  'test_corr_coef': 0.9667939081895134,
  'pruner': 'PatientPruner'},
 ('LightGBM', 'PercentilePruner'): {'best_score': 229.12848855837152,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': 7,
   'min_child_samples': 1,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.01,
   'reg_lambda': 0,
   'min_child_weight': 0.01,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 229.12848855837152,
  'test_rmse': 15.136990736549043,
  'test_corr_coef': 0.969281942853518,
  'pruner': 'PercentilePruner'},
 ('LightGBM', 'SuccessiveHalvingPruner'): {'best_score': 270.7694873082848,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'num_leaves': 31,
   'max_depth': 3,
   'min_child_samples': 1,
   'subsample': 1.0,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.01,
   'reg_lambda': 10,
   'min_child_weight': 0.1,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 270.7694873082848,
  'test_rmse': 16.45507481928553,
  'test_corr_coef': 0.9623583149111405,
  'pruner': 'SuccessiveHalvingPruner'},
 ('LightGBM', 'HyperbandPruner'): {'best_score': 304.2971462391087,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'num_leaves': 63,
   'max_depth': 3,
   'min_child_samples': 5,
   'subsample': 0.6,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.01,
   'reg_lambda': 0.1,
   'min_child_weight': 0.1,
   'bagging_freq': 0,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 304.2971462391087,
  'test_rmse': 17.444114945709018,
  'test_corr_coef': 0.9595863620711319,
  'pruner': 'HyperbandPruner'},
 ('LightGBM', 'ThresholdPruner'): {'best_score': 301.83484392669357,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.1,
   'num_leaves': 15,
   'max_depth': 3,
   'min_child_samples': 5,
   'subsample': 1.0,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.01,
   'reg_lambda': 0.1,
   'min_child_weight': 0.1,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 301.83484392669357,
  'test_rmse': 17.373394715100833,
  'test_corr_coef': 0.9603069622103869,
  'pruner': 'ThresholdPruner'},
 ('LightGBM', 'WilcoxonPruner'): {'best_score': 265.1710944134933,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.15,
   'num_leaves': 31,
   'max_depth': 3,
   'min_child_samples': 1,
   'subsample': 0.9,
   'colsample_bytree': 1.0,
   'reg_alpha': 1,
   'reg_lambda': 10,
   'min_child_weight': 0.001,
   'bagging_freq': 0,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 265.1710944134933,
  'test_rmse': 16.284074871281245,
  'test_corr_coef': 0.963709781649213,
  'pruner': 'WilcoxonPruner'},
 ('GPBoost', 'MedianPruner'): {'best_score': 296.1437619859039,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'max_depth': 3,
   'num_leaves': 31,
   'min_child_samples': 5,
   'subsample': 0.8,
   'colsample_bytree': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 0,
   'min_child_weight': 0.1,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 296.1437619859039,
  'test_rmse': 17.20882802476403,
  'test_corr_coef': 0.9611953214367067,
  'pruner': 'MedianPruner'},
 ('GPBoost', 'NopPruner'): {'best_score': 291.3976432243806,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.15,
   'max_depth': 3,
   'num_leaves': 15,
   'min_child_samples': 5,
   'subsample': 1.0,
   'colsample_bytree': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 0,
   'min_child_weight': 0.1,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 291.3976432243806,
  'test_rmse': 17.070373259667775,
  'test_corr_coef': 0.9602353463338138,
  'pruner': 'NopPruner'},
 ('GPBoost', 'PatientPruner'): {'best_score': 303.30933705656224,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.15,
   'max_depth': 3,
   'num_leaves': 15,
   'min_child_samples': 5,
   'subsample': 0.8,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 1.0,
   'min_child_weight': 0.1,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 303.30933705656224,
  'test_rmse': 17.415778393645294,
  'test_corr_coef': 0.9606199387104392,
  'pruner': 'PatientPruner'},
 ('GPBoost', 'PercentilePruner'): {'best_score': 291.7690052454734,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 3,
   'num_leaves': 63,
   'min_child_samples': 5,
   'subsample': 0.7,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.5,
   'reg_lambda': 0,
   'min_child_weight': 0.01,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 291.7690052454734,
  'test_rmse': 17.081247180621016,
  'test_corr_coef': 0.9628685814302016,
  'pruner': 'PercentilePruner'},
 ('GPBoost', 'SuccessiveHalvingPruner'): {'best_score': 297.5973873766578,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.05,
   'max_depth': 3,
   'num_leaves': 63,
   'min_child_samples': 5,
   'subsample': 0.5,
   'colsample_bytree': 0.7,
   'reg_alpha': 1.0,
   'reg_lambda': 0,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 297.5973873766578,
  'test_rmse': 17.251011198670582,
  'test_corr_coef': 0.9606246023525719,
  'pruner': 'SuccessiveHalvingPruner'},
 ('GPBoost', 'HyperbandPruner'): {'best_score': 304.7762550718626,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 3,
   'num_leaves': 15,
   'min_child_samples': 5,
   'subsample': 0.8,
   'colsample_bytree': 0.7,
   'reg_alpha': 1.0,
   'reg_lambda': 0.1,
   'min_child_weight': 0.01,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 304.7762550718626,
  'test_rmse': 17.45784222267639,
  'test_corr_coef': 0.9589949879068711,
  'pruner': 'HyperbandPruner'},
 ('GPBoost', 'ThresholdPruner'): {'best_score': 283.9070495729028,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'max_depth': 3,
   'num_leaves': 31,
   'min_child_samples': 1,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'reg_alpha': 1.0,
   'reg_lambda': 1.0,
   'min_child_weight': 0.01,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 283.9070495729028,
  'test_rmse': 16.849541524115807,
  'test_corr_coef': 0.9689209328885141,
  'pruner': 'ThresholdPruner'},
 ('GPBoost', 'WilcoxonPruner'): {'best_score': 291.7690052454734,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'max_depth': 3,
   'num_leaves': 31,
   'min_child_samples': 5,
   'subsample': 0.5,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.5,
   'reg_lambda': 0,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 291.7690052454734,
  'test_rmse': 17.081247180621016,
  'test_corr_coef': 0.9628685814302016,
  'pruner': 'WilcoxonPruner'},
 ('CatBoost', 'MedianPruner'): {'best_score': 347.4429012205738,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.03,
   'depth': 4,
   'l2_leaf_reg': 5,
   'border_count': 32,
   'min_data_in_leaf': 20,
   'rsm': 0.6,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 347.4429012205738,
  'test_rmse': 18.63982031084457,
  'test_corr_coef': 0.9614771149420601,
  'pruner': 'MedianPruner'},
 ('CatBoost', 'NopPruner'): {'best_score': 370.10393301836245,
  'best_params': {'iterations': 500,
   'learning_rate': 0.1,
   'depth': 4,
   'l2_leaf_reg': 5,
   'border_count': 32,
   'min_data_in_leaf': 10,
   'rsm': 0.6,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 370.10393301836245,
  'test_rmse': 19.23808548214615,
  'test_corr_coef': 0.9594743814447798,
  'pruner': 'NopPruner'},
 ('CatBoost', 'PatientPruner'): {'best_score': 347.4429012205738,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.03,
   'depth': 4,
   'l2_leaf_reg': 5,
   'border_count': 32,
   'min_data_in_leaf': 1,
   'rsm': 0.6,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 347.4429012205738,
  'test_rmse': 18.63982031084457,
  'test_corr_coef': 0.9614771149420601,
  'pruner': 'PatientPruner'},
 ('CatBoost', 'PercentilePruner'): {'best_score': 353.61414463188675,
  'best_params': {'iterations': 500,
   'learning_rate': 0.05,
   'depth': 4,
   'l2_leaf_reg': 3,
   'border_count': 32,
   'min_data_in_leaf': 10,
   'rsm': 0.8,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 353.61414463188675,
  'test_rmse': 18.80463093580639,
  'test_corr_coef': 0.9611010440854848,
  'pruner': 'PercentilePruner'},
 ('CatBoost', 'SuccessiveHalvingPruner'): {'best_score': 368.5205933957056,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.1,
   'depth': 4,
   'l2_leaf_reg': 1,
   'border_count': 64,
   'min_data_in_leaf': 5,
   'rsm': 0.8,
   'bagging_temperature': 0,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 368.5205933957056,
  'test_rmse': 19.196890201168145,
  'test_corr_coef': 0.9564404896870229,
  'pruner': 'SuccessiveHalvingPruner'},
 ('CatBoost', 'HyperbandPruner'): {'best_score': 354.04068707098565,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.05,
   'depth': 4,
   'l2_leaf_reg': 7,
   'border_count': 64,
   'min_data_in_leaf': 5,
   'rsm': 0.8,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 354.04068707098565,
  'test_rmse': 18.815968937872576,
  'test_corr_coef': 0.9599972705368262,
  'pruner': 'HyperbandPruner'},
 ('CatBoost', 'ThresholdPruner'): {'best_score': 354.04068707098565,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.05,
   'depth': 4,
   'l2_leaf_reg': 7,
   'border_count': 64,
   'min_data_in_leaf': 10,
   'rsm': 0.8,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 354.04068707098565,
  'test_rmse': 18.815968937872576,
  'test_corr_coef': 0.9599972705368262,
  'pruner': 'ThresholdPruner'},
 ('CatBoost', 'WilcoxonPruner'): {'best_score': 353.61414463188675,
  'best_params': {'iterations': 500,
   'learning_rate': 0.05,
   'depth': 4,
   'l2_leaf_reg': 3,
   'border_count': 32,
   'min_data_in_leaf': 20,
   'rsm': 0.8,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 353.61414463188675,
  'test_rmse': 18.80463093580639,
  'test_corr_coef': 0.9611010440854848,
  'pruner': 'WilcoxonPruner'},
 ('NGBoost', 'MedianPruner'): {'best_score': 183.95772791433217,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 183.95772791433217,
  'test_rmse': 13.563101706996529,
  'test_corr_coef': 0.9747258074877652,
  'pruner': 'MedianPruner'},
 ('NGBoost', 'NopPruner'): {'best_score': 178.7588861952265,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 1.0,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 178.7588861952265,
  'test_rmse': 13.37007427785001,
  'test_corr_coef': 0.976279845474334,
  'pruner': 'NopPruner'},
 ('NGBoost', 'PatientPruner'): {'best_score': 183.86711972030236,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.7,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 183.86711972030236,
  'test_rmse': 13.559761049528209,
  'test_corr_coef': 0.9783491434299343,
  'pruner': 'PatientPruner'},
 ('NGBoost', 'PercentilePruner'): {'best_score': 175.3332984508238,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 1.0,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 175.3332984508238,
  'test_rmse': 13.241348060179666,
  'test_corr_coef': 0.976802462865663,
  'pruner': 'PercentilePruner'},
 ('NGBoost', 'SuccessiveHalvingPruner'): {'best_score': 183.54434117920928,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 183.54434117920928,
  'test_rmse': 13.547853748074242,
  'test_corr_coef': 0.9754625858555357,
  'pruner': 'SuccessiveHalvingPruner'},
 ('NGBoost', 'HyperbandPruner'): {'best_score': 177.70031452506524,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.03,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 177.70031452506524,
  'test_rmse': 13.330428144852108,
  'test_corr_coef': 0.9730672166033915,
  'pruner': 'HyperbandPruner'},
 ('NGBoost', 'ThresholdPruner'): {'best_score': 173.4748090057579,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.03,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 173.4748090057579,
  'test_rmse': 13.17098360054244,
  'test_corr_coef': 0.9765254085330761,
  'pruner': 'ThresholdPruner'},
 ('NGBoost', 'WilcoxonPruner'): {'best_score': 190.83709708753526,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 190.83709708753526,
  'test_rmse': 13.814380083360065,
  'test_corr_coef': 0.9767622115354234,
  'pruner': 'WilcoxonPruner'},
 ('TabNet', 'MedianPruner'): {'best_score': 683.1835477259349,
  'best_params': {'n_d': 32,
   'n_a': 16,
   'n_steps': 7,
   'gamma': 1.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 683.1835477259349,
  'test_rmse': 26.137780084122195,
  'test_corr_coef': 0.925708069115367,
  'pruner': 'MedianPruner'},
 ('TabNet', 'NopPruner'): {'best_score': 785.2781419779674,
  'best_params': {'n_d': 16,
   'n_a': 16,
   'n_steps': 7,
   'gamma': 1.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 2,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 785.2781419779674,
  'test_rmse': 28.02281466908646,
  'test_corr_coef': 0.9099603248947505,
  'pruner': 'NopPruner'},
 ('TabNet', 'PatientPruner'): {'best_score': 647.9527885249482,
  'best_params': {'n_d': 16,
   'n_a': 64,
   'n_steps': 10,
   'gamma': 1.0,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 2,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 647.9527885249482,
  'test_rmse': 25.45491678487573,
  'test_corr_coef': 0.940281349954927,
  'pruner': 'PatientPruner'},
 ('TabNet', 'PercentilePruner'): {'best_score': 613.3890890267845,
  'best_params': {'n_d': 8,
   'n_a': 8,
   'n_steps': 10,
   'gamma': 1.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 2,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 613.3890890267845,
  'test_rmse': 24.766693138705147,
  'test_corr_coef': 0.9166311781717991,
  'pruner': 'PercentilePruner'},
 ('TabNet', 'SuccessiveHalvingPruner'): {'best_score': 666.6390125869158,
  'best_params': {'n_d': 16,
   'n_a': 8,
   'n_steps': 10,
   'gamma': 2.0,
   'lambda_sparse': 0.01,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 666.6390125869158,
  'test_rmse': 25.819353450210865,
  'test_corr_coef': 0.9148062364563666,
  'pruner': 'SuccessiveHalvingPruner'},
 ('TabNet', 'HyperbandPruner'): {'best_score': 763.3243122810416,
  'best_params': {'n_d': 8,
   'n_a': 64,
   'n_steps': 7,
   'gamma': 1.0,
   'lambda_sparse': 0.01,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 763.3243122810416,
  'test_rmse': 27.628324456634022,
  'test_corr_coef': 0.9185520550556193,
  'pruner': 'HyperbandPruner'},
 ('TabNet', 'ThresholdPruner'): {'best_score': 600.7624887356691,
  'best_params': {'n_d': 64,
   'n_a': 32,
   'n_steps': 7,
   'gamma': 1.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 2,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 600.7624887356691,
  'test_rmse': 24.510456722298528,
  'test_corr_coef': 0.9428019464440833,
  'pruner': 'ThresholdPruner'},
 ('TabNet', 'WilcoxonPruner'): {'best_score': 561.1656802691135,
  'best_params': {'n_d': 8,
   'n_a': 8,
   'n_steps': 10,
   'gamma': 1.0,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 561.1656802691135,
  'test_rmse': 23.688935819684122,
  'test_corr_coef': 0.9318886782102657,
  'pruner': 'WilcoxonPruner'},
 ('HistGradientBoosting', 'MedianPruner'): {'best_score': 306.9466510692115,
  'best_params': {'learning_rate': 0.1,
   'max_iter': 300,
   'max_depth': 3,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 63,
   'l2_regularization': 0.5,
   'max_bins': 128,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 306.9466510692115,
  'test_rmse': 17.5198930096394,
  'test_corr_coef': 0.9571560877136178,
  'pruner': 'MedianPruner'},
 ('HistGradientBoosting', 'NopPruner'): {'best_score': 307.14533474906676,
  'best_params': {'learning_rate': 0.1,
   'max_iter': 400,
   'max_depth': 3,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 31,
   'l2_regularization': 0.5,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 15,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 307.14533474906676,
  'test_rmse': 17.52556232333407,
  'test_corr_coef': 0.9571084111490522,
  'pruner': 'NopPruner'},
 ('HistGradientBoosting', 'PatientPruner'): {'best_score': 306.9466510692115,
  'best_params': {'learning_rate': 0.1,
   'max_iter': 300,
   'max_depth': 3,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 31,
   'l2_regularization': 0.5,
   'max_bins': 128,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 15,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 306.9466510692115,
  'test_rmse': 17.5198930096394,
  'test_corr_coef': 0.9571560877136178,
  'pruner': 'PatientPruner'},
 ('HistGradientBoosting',
  'PercentilePruner'): {'best_score': 310.15497272579285, 'best_params': {'learning_rate': 0.15,
   'max_iter': 200,
   'max_depth': 3,
   'min_samples_leaf': 5,
   'max_leaf_nodes': None,
   'l2_regularization': 0.5,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 310.15497272579285, 'test_rmse': 17.611217241457016, 'test_corr_coef': 0.9578779385722576, 'pruner': 'PercentilePruner'},
 ('HistGradientBoosting',
  'SuccessiveHalvingPruner'): {'best_score': 305.50458250552157, 'best_params': {'learning_rate': 0.1,
   'max_iter': 200,
   'max_depth': 3,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 63,
   'l2_regularization': 0.5,
   'max_bins': 255,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 15,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 305.50458250552157, 'test_rmse': 17.478689381802102, 'test_corr_coef': 0.957444692058178, 'pruner': 'SuccessiveHalvingPruner'},
 ('HistGradientBoosting', 'HyperbandPruner'): {'best_score': 318.1006871717745,
  'best_params': {'learning_rate': 0.05,
   'max_iter': 500,
   'max_depth': 3,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 15,
   'l2_regularization': 1.0,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 15,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 318.1006871717745,
  'test_rmse': 17.83537740480348,
  'test_corr_coef': 0.9559058436637012,
  'pruner': 'HyperbandPruner'},
 ('HistGradientBoosting',
  'ThresholdPruner'): {'best_score': 305.50458250552157, 'best_params': {'learning_rate': 0.1,
   'max_iter': 200,
   'max_depth': 3,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 63,
   'l2_regularization': 0.5,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 15,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 305.50458250552157, 'test_rmse': 17.478689381802102, 'test_corr_coef': 0.957444692058178, 'pruner': 'ThresholdPruner'},
 ('HistGradientBoosting', 'WilcoxonPruner'): {'best_score': 308.2494075545725,
  'best_params': {'learning_rate': 0.1,
   'max_iter': 500,
   'max_depth': 3,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 31,
   'l2_regularization': 1.0,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 308.2494075545725,
  'test_rmse': 17.55703299406174,
  'test_corr_coef': 0.9571023046674804,
  'pruner': 'WilcoxonPruner'},
 ('PGBM', 'MedianPruner'): {'best_score': 219.4080278597303,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'max_leaves': 24,
   'min_split_gain': 0.1,
   'reg_lambda': 5.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.1,
   'min_data_in_leaf': 3,
   'max_bin': 128,
   'distribution': 'laplace'},
  'test_mse': 219.4080278597303,
  'test_rmse': 14.812428155428478,
  'test_corr_coef': 0.9679224562494657,
  'pruner': 'MedianPruner'},
 ('PGBM', 'NopPruner'): {'best_score': 187.25719821186112,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.1,
   'max_leaves': 46,
   'min_split_gain': 0.0,
   'reg_lambda': 0.1,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.0,
   'min_data_in_leaf': 3,
   'max_bin': 64,
   'distribution': 'normal'},
  'test_mse': 187.25719821186112,
  'test_rmse': 13.684195197813466,
  'test_corr_coef': 0.9730611883509453,
  'pruner': 'NopPruner'},
 ('PGBM', 'PatientPruner'): {'best_score': 214.12435786352063,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'max_leaves': 38,
   'min_split_gain': 0.0,
   'reg_lambda': 5.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.0,
   'min_data_in_leaf': 3,
   'max_bin': 64,
   'distribution': 'laplace'},
  'test_mse': 214.12435786352063,
  'test_rmse': 14.632988685279594,
  'test_corr_coef': 0.9692185393643218,
  'pruner': 'PatientPruner'},
 ('PGBM', 'PercentilePruner'): {'best_score': 219.808103705989,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.15,
   'max_leaves': 46,
   'min_split_gain': 0.5,
   'reg_lambda': 5.0,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 3,
   'max_bin': 64,
   'distribution': 'laplace'},
  'test_mse': 219.808103705989,
  'test_rmse': 14.825926740207136,
  'test_corr_coef': 0.9677760061638276,
  'pruner': 'PercentilePruner'},
 ('PGBM', 'SuccessiveHalvingPruner'): {'best_score': 212.56364451333772,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.1,
   'max_leaves': 58,
   'min_split_gain': 0.1,
   'reg_lambda': 5.0,
   'feature_fraction': 0.7,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.0,
   'min_data_in_leaf': 3,
   'max_bin': 64,
   'distribution': 'studentt'},
  'test_mse': 212.56364451333772,
  'test_rmse': 14.579562562482378,
  'test_corr_coef': 0.9705315993920913,
  'pruner': 'SuccessiveHalvingPruner'},
 ('PGBM', 'HyperbandPruner'): {'best_score': 224.1891995793507,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'max_leaves': 63,
   'min_split_gain': 0.1,
   'reg_lambda': 5.0,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.2,
   'min_data_in_leaf': 3,
   'max_bin': 128,
   'distribution': 'normal'},
  'test_mse': 224.1891995793507,
  'test_rmse': 14.972948927293873,
  'test_corr_coef': 0.9661198812577402,
  'pruner': 'HyperbandPruner'},
 ('PGBM', 'ThresholdPruner'): {'best_score': 198.923181819936,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'max_leaves': 60,
   'min_split_gain': 0.0,
   'reg_lambda': 1.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.0,
   'min_data_in_leaf': 3,
   'max_bin': 64,
   'distribution': 'studentt'},
  'test_mse': 198.923181819936,
  'test_rmse': 14.10401296865314,
  'test_corr_coef': 0.9722429140371318,
  'pruner': 'ThresholdPruner'},
 ('PGBM', 'WilcoxonPruner'): {'best_score': 291.82278144520916,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_leaves': 59,
   'min_split_gain': 0.1,
   'reg_lambda': 0.1,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 5,
   'max_bin': 128,
   'distribution': 'normal'},
  'test_mse': 291.82278144520916,
  'test_rmse': 17.082821237875468,
  'test_corr_coef': 0.9562602520910682,
  'pruner': 'WilcoxonPruner'}}

# **Probabilistic distributions using NGBoost**

In [15]:
# Assuming best_params is obtained correctly
best_params = get_best_model_params(best_scores_autosampler, 'NGBoost')

# Remove any conflicting parameters from best_params
incompatible_keys = ['Dist', 'Score']
for key in incompatible_keys:
    best_params.pop(key, None)

# Initialize NGBoost model with best_params
ngb_model = NGBRegressor(Dist=Normal, **best_params)

# Fit the model
ngb_model.fit(X_train, y_train)

# Predict the distribution
pred_dist = ngb_model.pred_dist(X_test)

# Extract mean and standard deviation
predictions_NGB_df = pd.DataFrame({
    'Mean': pred_dist.loc,
    'StdDev': pred_dist.scale,
    'Actual': y_test.ravel()
})

# Calculate and print the mean squared error
mse = mean_squared_error(y_test, pred_dist.loc)
print(f"Mean Squared Error: {mse:.2f}")

# Print the DataFrame with mean and standard deviation
print(predictions_NGB_df.head())

Mean Squared Error: 173.48
         Mean    StdDev  Actual
0   77.300892  0.310080   73.07
1  140.695200  0.161766  141.67
2  101.934905  0.224640  110.44
3  267.951975  0.464867  275.01
4  184.197569  0.257307  202.57

In [16]:
generate_and_save_plots(predictions_NGB_df, y_test, "./drive/MyDrive/EWQI/Probabilistic_Distribution//NGBoost_Prob.xlsx")

Excel file saved at ./drive/MyDrive/EWQI/Probabilistic_Distribution//NGBoost_Prob.xlsx

In [17]:
generate_and_save_crps_decomposition(
    predictions_NGB_df,
    y_test,
    "./drive/MyDrive/EWQI/Probabilistic_Distribution/NGBoost_Prob.xlsx",
    model_name="NGBoost",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/EWQI/Probabilistic_Distribution/NGBoost_Prob.xlsx
   Sheets: CRPS_Summary_NGBoost, CRPS_Bins_NGBoost

     Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  NGBoost     9.98961     10.41314   31.512906    31.089375        10

In [18]:
generate_and_save_pit_results(
    predictions_NGB_df,
    y_test,
    "./drive/MyDrive/EWQI/Probabilistic_Distribution/NGBoost_Prob.xlsx",
    model_name="NGBoost",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/EWQI/Probabilistic_Distribution/NGBoost_Prob.xlsx

        PIT_Value
0    1.087952e-42
1    1.000000e+00
2    1.000000e+00
3    1.000000e+00
4    1.000000e+00
5    1.000000e+00
6    7.399249e-26
7    1.000000e+00
8    0.000000e+00
9    6.533300e-13
10   1.000000e+00
11   1.000000e+00
12   1.000000e+00
13  2.737407e-285
14   4.250764e-88
15   1.000000e+00
16   5.178580e-15
17   1.000000e+00
18   0.000000e+00
19   1.000000e+00
20   1.000000e+00
21   1.000000e+00
22  7.051511e-122
23   1.000000e+00
24   9.186950e-12
25   1.000000e+00
26   1.000000e+00
27   1.000000e+00
28   1.000000e+00
29   1.000000e+00
30   4.915058e-90
31   0.000000e+00
32   1.420880e-15
33   3.986230e-34
34   0.000000e+00
35   1.000000e+00
36  1.328269e-198
37   4.210427e-12
38   1.000000e+00
39   1.000000e+00
40   1.000000e+00
41   1.002584e-13
42   0.000000e+00
43   1.000000e+00
44   1.000000e+00
45   1.000000e+00
46   0.000000e+00

In [19]:
generate_and_save_calibration_curve(
    predictions_NGB_df,
    y_test,
    "./drive/MyDrive/EWQI/Probabilistic_Distribution/NGBoost_Prob.xlsx",
    model_name="NGBoost",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/EWQI/Probabilistic_Distribution/NGBoost_Prob.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.425532        0.325532
2                  0.2            0.425532        0.225532
3                  0.3            0.425532        0.125532
4                  0.4            0.425532        0.025532
5                  0.5            0.425532        0.074468
6                  0.6            0.425532        0.174468
7                  0.7            0.425532        0.274468
8                  0.8            0.425532        0.374468
9                  0.9            0.425532        0.474468
10                 1.0            1.000000        0.000000

# **Probabilistic distributions using PGBM**

In [20]:
# Assuming best_params is obtained correctly
best_params = get_best_model_params(best_scores_autosampler, 'PGBM')

# Remove any conflicting parameters from best_params
# Note: Adjust the incompatible keys based on PGBM's requirements
incompatible_keys = ['Dist', 'Score']
for key in incompatible_keys:
    best_params.pop(key, None)

# Initialize PGBM model
pgbm_model = PGBM()

def mseloss_objective(yhat, y, sample_weight=None):
    # Ensure that yhat and y are PyTorch tensors
    if not torch.is_tensor(yhat):
        yhat = torch.from_numpy(np.array(yhat)).float()
    if not torch.is_tensor(y):
        y = torch.from_numpy(np.array(y)).float()
    gradient = yhat - y
    hessian = torch.ones_like(yhat)
    return gradient, hessian

def rmseloss_metric(yhat, y, sample_weight=None):
    # Ensure that yhat and y are PyTorch tensors
    if not torch.is_tensor(yhat):
        yhat = torch.from_numpy(np.array(yhat)).float()
    if not torch.is_tensor(y):
        y = torch.from_numpy(np.array(y)).float()
    loss = torch.sqrt(torch.mean((yhat - y) ** 2))
    return loss

X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)
# Fit the model
pgbm_model.train((X_train, y_train), objective=mseloss_objective, metric=rmseloss_metric, params = best_params)

# Predict the distribution
pred_dist = pgbm_model.predict_dist(X_test)

# Extract mean and standard deviation
# Note: PGBM might return predictions in a different format, adjust accordingly
predictions_PGBM_df = pd.DataFrame({
    'Mean': pred_dist.mean(axis=0),
    'StdDev': pred_dist.std(axis=0),
    'Actual': y_test.ravel()
})

# Calculate and print the mean squared error
mse = mean_squared_error(y_test, predictions_PGBM_df['Mean'])
print(f"Mean Squared Error: {mse:.2f}")

# Print the DataFrame with mean and standard deviation
print(predictions_PGBM_df.head())

Training on CPU
Estimator 0/200, Train metric: 51.8040
Estimator 1/200, Train metric: 47.6403
Estimator 2/200, Train metric: 44.2211
Estimator 3/200, Train metric: 40.4811
Estimator 4/200, Train metric: 37.0778
Estimator 5/200, Train metric: 34.0711
Estimator 6/200, Train metric: 32.2726
Estimator 7/200, Train metric: 30.0074
Estimator 8/200, Train metric: 27.9378
Estimator 9/200, Train metric: 25.4829
Estimator 10/200, Train metric: 23.6093
Estimator 11/200, Train metric: 22.0989
Estimator 12/200, Train metric: 20.4743
Estimator 13/200, Train metric: 19.4300
Estimator 14/200, Train metric: 18.2014
Estimator 15/200, Train metric: 17.0535
Estimator 16/200, Train metric: 16.5485
Estimator 17/200, Train metric: 15.7829
Estimator 18/200, Train metric: 15.1467
Estimator 19/200, Train metric: 14.6958
Estimator 20/200, Train metric: 14.0259
Estimator 21/200, Train metric: 13.6423
Estimator 22/200, Train metric: 12.8222
Estimator 23/200, Train metric: 12.5842
Estimator 24/200, Train metric: 12.1847
Estimator 25/200, Train metric: 11.6684
Estimator 26/200, Train metric: 11.2312
Estimator 27/200, Train metric: 10.7562
Estimator 28/200, Train metric: 10.5753
Estimator 29/200, Train metric: 10.2691
Estimator 30/200, Train metric: 9.9803
Estimator 31/200, Train metric: 9.7237
Estimator 32/200, Train metric: 9.4549
Estimator 33/200, Train metric: 9.1564
Estimator 34/200, Train metric: 8.9626
Estimator 35/200, Train metric: 8.8029
Estimator 36/200, Train metric: 8.7466
Estimator 37/200, Train metric: 8.6531
Estimator 38/200, Train metric: 8.3499
Estimator 39/200, Train metric: 8.1236
Estimator 40/200, Train metric: 7.9707
Estimator 41/200, Train metric: 7.7555
Estimator 42/200, Train metric: 7.5853
Estimator 43/200, Train metric: 7.5657
Estimator 44/200, Train metric: 7.4670
Estimator 45/200, Train metric: 7.4512
Estimator 46/200, Train metric: 7.2707
Estimator 47/200, Train metric: 7.1833
Estimator 48/200, Train metric: 7.0673
Estimator 49/200, Train metric: 7.0357
Estimator 50/200, Train metric: 6.8528
Estimator 51/200, Train metric: 6.7405
Estimator 52/200, Train metric: 6.6605
Estimator 53/200, Train metric: 6.5991
Estimator 54/200, Train metric: 6.4035
Estimator 55/200, Train metric: 6.2739
Estimator 56/200, Train metric: 6.2639
Estimator 57/200, Train metric: 6.2217
Estimator 58/200, Train metric: 6.1139
Estimator 59/200, Train metric: 6.0467
Estimator 60/200, Train metric: 6.0631
Estimator 61/200, Train metric: 5.9333
Estimator 62/200, Train metric: 5.8259
Estimator 63/200, Train metric: 5.7376
Estimator 64/200, Train metric: 5.7314
Estimator 65/200, Train metric: 5.5767
Estimator 66/200, Train metric: 5.4692
Estimator 67/200, Train metric: 5.4702
Estimator 68/200, Train metric: 5.3803
Estimator 69/200, Train metric: 5.3269
Estimator 70/200, Train metric: 5.3060
Estimator 71/200, Train metric: 5.2349
Estimator 72/200, Train metric: 5.1693
Estimator 73/200, Train metric: 4.8893
Estimator 74/200, Train metric: 4.8614
Estimator 75/200, Train metric: 4.8651
Estimator 76/200, Train metric: 4.8591
Estimator 77/200, Train metric: 4.7915
Estimator 78/200, Train metric: 4.8018
Estimator 79/200, Train metric: 4.7054
Estimator 80/200, Train metric: 4.7221
Estimator 81/200, Train metric: 4.6383
Estimator 82/200, Train metric: 4.5345
Estimator 83/200, Train metric: 4.4447
Estimator 84/200, Train metric: 4.3372
Estimator 85/200, Train metric: 4.3289
Estimator 86/200, Train metric: 4.2374
Estimator 87/200, Train metric: 4.2368
Estimator 88/200, Train metric: 4.1623
Estimator 89/200, Train metric: 4.0954
Estimator 90/200, Train metric: 4.1103
Estimator 91/200, Train metric: 4.0138
Estimator 92/200, Train metric: 3.9284
Estimator 93/200, Train metric: 3.8706
Estimator 94/200, Train metric: 3.8135
Estimator 95/200, Train metric: 3.7593
Estimator 96/200, Train metric: 3.6942
Estimator 97/200, Train metric: 3.6330
Estimator 98/200, Train metric: 3.5067
Estimator 99/200, Train metric: 3.4673
Estimator 100/200, Train metric: 3.4349
Estimator 101/200, Train metric: 3.4092
Estimator 102/200, Train metric: 3.3616
Estimator 103/200, Train metric: 3.3446
Estimator 104/200, Train metric: 3.3003
Estimator 105/200, Train metric: 3.1971
Estimator 106/200, Train metric: 3.1340
Estimator 107/200, Train metric: 3.1221
Estimator 108/200, Train metric: 3.0452
Estimator 109/200, Train metric: 3.0063
Estimator 110/200, Train metric: 2.9227
Estimator 111/200, Train metric: 2.8307
Estimator 112/200, Train metric: 2.8136
Estimator 113/200, Train metric: 2.8140
Estimator 114/200, Train metric: 2.7575
Estimator 115/200, Train metric: 2.7517
Estimator 116/200, Train metric: 2.7050
Estimator 117/200, Train metric: 2.6911
Estimator 118/200, Train metric: 2.6886
Estimator 119/200, Train metric: 2.5974
Estimator 120/200, Train metric: 2.5433
Estimator 121/200, Train metric: 2.4873
Estimator 122/200, Train metric: 2.4070
Estimator 123/200, Train metric: 2.3512
Estimator 124/200, Train metric: 2.3201
Estimator 125/200, Train metric: 2.2739
Estimator 126/200, Train metric: 2.2502
Estimator 127/200, Train metric: 2.1926
Estimator 128/200, Train metric: 2.1904
Estimator 129/200, Train metric: 2.1388
Estimator 130/200, Train metric: 2.1075
Estimator 131/200, Train metric: 2.0979
Estimator 132/200, Train metric: 2.0400
Estimator 133/200, Train metric: 2.0300
Estimator 134/200, Train metric: 1.9849
Estimator 135/200, Train metric: 1.9291
Estimator 136/200, Train metric: 1.8432
Estimator 137/200, Train metric: 1.7957
Estimator 138/200, Train metric: 1.7428
Estimator 139/200, Train metric: 1.7009
Estimator 140/200, Train metric: 1.6871
Estimator 141/200, Train metric: 1.6713
Estimator 142/200, Train metric: 1.6485
Estimator 143/200, Train metric: 1.6406
Estimator 144/200, Train metric: 1.5997
Estimator 145/200, Train metric: 1.5324
Estimator 146/200, Train metric: 1.5229
Estimator 147/200, Train metric: 1.4887
Estimator 148/200, Train metric: 1.4771
Estimator 149/200, Train metric: 1.4751
Estimator 150/200, Train metric: 1.4819
Estimator 151/200, Train metric: 1.4413
Estimator 152/200, Train metric: 1.4051
Estimator 153/200, Train metric: 1.3925
Estimator 154/200, Train metric: 1.3659
Estimator 155/200, Train metric: 1.3431
Estimator 156/200, Train metric: 1.3318
Estimator 157/200, Train metric: 1.3028
Estimator 158/200, Train metric: 1.2947
Estimator 159/200, Train metric: 1.2778
Estimator 160/200, Train metric: 1.2508
Estimator 161/200, Train metric: 1.2084
Estimator 162/200, Train metric: 1.2117
Estimator 163/200, Train metric: 1.1798
Estimator 164/200, Train metric: 1.1813
Estimator 165/200, Train metric: 1.1651
Estimator 166/200, Train metric: 1.1619
Estimator 167/200, Train metric: 1.1536
Estimator 168/200, Train metric: 1.1444
Estimator 169/200, Train metric: 1.1316
Estimator 170/200, Train metric: 1.1261
Estimator 171/200, Train metric: 1.1291
Estimator 172/200, Train metric: 1.1167
Estimator 173/200, Train metric: 1.1177
Estimator 174/200, Train metric: 1.0910
Estimator 175/200, Train metric: 1.0556
Estimator 176/200, Train metric: 1.0288
Estimator 177/200, Train metric: 1.0310
Estimator 178/200, Train metric: 1.0227
Estimator 179/200, Train metric: 1.0003
Estimator 180/200, Train metric: 0.9706
Estimator 181/200, Train metric: 0.9466
Estimator 182/200, Train metric: 0.9322
Estimator 183/200, Train metric: 0.9170
Estimator 184/200, Train metric: 0.8948
Estimator 185/200, Train metric: 0.8844
Estimator 186/200, Train metric: 0.8827
Estimator 187/200, Train metric: 0.8608
Estimator 188/200, Train metric: 0.8379
Estimator 189/200, Train metric: 0.8294
Estimator 190/200, Train metric: 0.8106
Estimator 191/200, Train metric: 0.7957
Estimator 192/200, Train metric: 0.7678
Estimator 193/200, Train metric: 0.7556
Estimator 194/200, Train metric: 0.7336
Estimator 195/200, Train metric: 0.7052
Estimator 196/200, Train metric: 0.6938
Estimator 197/200, Train metric: 0.6912
Estimator 198/200, Train metric: 0.6825
Estimator 199/200, Train metric: 0.6697
Mean Squared Error: 186.07
         Mean     StdDev  Actual
0   87.713715   8.804285   73.07
1  144.923111   6.774098  141.67
2  103.292198   3.597456  110.44
3  290.712799  23.308640  275.01
4  173.688065  11.387439  202.57

In [21]:
generate_and_save_plots(predictions_PGBM_df, y_test, "./drive/MyDrive/EWQI/Probabilistic_Distribution/PGBM_Prob.xlsx")

Excel file saved at ./drive/MyDrive/EWQI/Probabilistic_Distribution/PGBM_Prob.xlsx

In [22]:
generate_and_save_crps_decomposition(
    predictions_PGBM_df,
    y_test,
    "./drive/MyDrive/EWQI/Probabilistic_Distribution/PGBM_Prob.xlsx",
    model_name="PGBM",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/EWQI/Probabilistic_Distribution/PGBM_Prob.xlsx
   Sheets: CRPS_Summary_PGBM, CRPS_Bins_PGBM

  Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  PGBM    8.038774     8.096718   31.147319    31.089375        10

In [23]:
generate_and_save_pit_results(
    predictions_PGBM_df,
    y_test,
    "./drive/MyDrive/EWQI/Probabilistic_Distribution/PGBM_Prob.xlsx",
    model_name="PGBM",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/EWQI/Probabilistic_Distribution/PGBM_Prob.xlsx

    PIT_Value
0    0.048131
1    0.315533
2    0.976534
3    0.250254
4    0.994398
5    0.897030
6    0.036458
7    0.955386
8    0.201339
9    0.993850
10   0.994107
11   0.892068
12   0.804196
13   0.041162
14   0.404266
15   0.999863
16   0.926490
17   0.940771
18   0.239581
19   0.105514
20   0.825963
21   0.971670
22   0.392543
23   0.259698
24   0.879468
25   0.586560
26   0.999346
27   0.974610
28   0.997444
29   0.736868
30   0.065964
31   0.136006
32   0.110329
33   0.694153
34   0.115326
35   0.997707
36   0.918772
37   0.589118
38   0.987400
39   0.999790
40   0.710857
41   0.233721
42   0.559082
43   0.959113
44   0.103760
45   0.999572
46   0.356571

In [24]:
generate_and_save_calibration_curve(
    predictions_PGBM_df,
    y_test,
    "./drive/MyDrive/EWQI/Probabilistic_Distribution/PGBM_Prob.xlsx",
    model_name="PGBM",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/EWQI/Probabilistic_Distribution/PGBM_Prob.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.085106        0.014894
2                  0.2            0.191489        0.008511
3                  0.3            0.297872        0.002128
4                  0.4            0.361702        0.038298
5                  0.5            0.382979        0.117021
6                  0.6            0.446809        0.153191
7                  0.7            0.468085        0.231915
8                  0.8            0.510638        0.289362
9                  0.9            0.617021        0.282979
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using GPBoost (Treeffuser)**

In [25]:
best_params = get_best_model_params(best_scores_autosampler, 'GPBoost')

gpboost_score_engine = TreeBasedScoreModel(
    model_name='gpboost',
    model_params=best_params,
    seed=42,
    verbose=-1
)

# The fix is in the line below: '_score_model' has been corrected to 'score_model'.
model = Treeffuser(score_model=gpboost_score_engine, seed=42)
model.fit(X_train, y_train)

n_samples_for_prediction = 200
y_samples = model.sample(X_test, n_samples=n_samples_for_prediction, verbose=False)

y_samples_obj = Samples(y_samples)
mean = y_samples_obj.sample_mean()
stddev = y_samples_obj.sample_std()

predictions_GPBoost_TF_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_GPBoost_TF_df.head())

[1]	valid_0's l2: 1.95455
[2]	valid_0's l2: 1.79353
[3]	valid_0's l2: 1.68727
[4]	valid_0's l2: 1.56396
[5]	valid_0's l2: 1.51034
[6]	valid_0's l2: 1.48305
[7]	valid_0's l2: 1.36589
[8]	valid_0's l2: 1.26809
[9]	valid_0's l2: 1.26936
[10]	valid_0's l2: 1.15801
[11]	valid_0's l2: 1.16113
[12]	valid_0's l2: 1.10715
[13]	valid_0's l2: 1.03545
[14]	valid_0's l2: 1.00913
[15]	valid_0's l2: 0.973388
[16]	valid_0's l2: 0.954989
[17]	valid_0's l2: 0.951345
[18]	valid_0's l2: 0.916397
[19]	valid_0's l2: 0.926374
[20]	valid_0's l2: 0.918518
[21]	valid_0's l2: 0.900873
[22]	valid_0's l2: 0.886161
[23]	valid_0's l2: 0.886042
[24]	valid_0's l2: 0.873121
[25]	valid_0's l2: 0.861643
[26]	valid_0's l2: 0.862314
[27]	valid_0's l2: 0.852163
[28]	valid_0's l2: 0.85721
[29]	valid_0's l2: 0.84067
[30]	valid_0's l2: 0.842779
[31]	valid_0's l2: 0.842225
[32]	valid_0's l2: 0.842829
[33]	valid_0's l2: 0.836964
[34]	valid_0's l2: 0.807484
[35]	valid_0's l2: 0.770083
[36]	valid_0's l2: 0.76208
[37]	valid_0's l2: 0.757962
[38]	valid_0's l2: 0.75822
[39]	valid_0's l2: 0.750774
[40]	valid_0's l2: 0.745192
[41]	valid_0's l2: 0.735119
[42]	valid_0's l2: 0.725053
[43]	valid_0's l2: 0.726589
[44]	valid_0's l2: 0.723468
[45]	valid_0's l2: 0.723359
[46]	valid_0's l2: 0.723312
[47]	valid_0's l2: 0.717055
[48]	valid_0's l2: 0.709151
[49]	valid_0's l2: 0.70875
[50]	valid_0's l2: 0.705964
[51]	valid_0's l2: 0.706085
[52]	valid_0's l2: 0.701886
[53]	valid_0's l2: 0.697459
[54]	valid_0's l2: 0.696773
[55]	valid_0's l2: 0.696816
[56]	valid_0's l2: 0.694519
[57]	valid_0's l2: 0.694626
[58]	valid_0's l2: 0.694626
[59]	valid_0's l2: 0.69435
[60]	valid_0's l2: 0.690225
[61]	valid_0's l2: 0.687889
[62]	valid_0's l2: 0.665231
[63]	valid_0's l2: 0.659775
[64]	valid_0's l2: 0.648394
[65]	valid_0's l2: 0.64814
[66]	valid_0's l2: 0.649582
[67]	valid_0's l2: 0.649147
[68]	valid_0's l2: 0.646882
[69]	valid_0's l2: 0.643255
[70]	valid_0's l2: 0.64463
[71]	valid_0's l2: 0.63432
[72]	valid_0's l2: 0.633335
[73]	valid_0's l2: 0.633277
[74]	valid_0's l2: 0.634778
[75]	valid_0's l2: 0.630392
[76]	valid_0's l2: 0.621898
[77]	valid_0's l2: 0.621732
[78]	valid_0's l2: 0.6285
[79]	valid_0's l2: 0.628174
[80]	valid_0's l2: 0.625366
[81]	valid_0's l2: 0.623191
[82]	valid_0's l2: 0.624101
[83]	valid_0's l2: 0.623141
[84]	valid_0's l2: 0.615518
[85]	valid_0's l2: 0.61467
[86]	valid_0's l2: 0.621367
[87]	valid_0's l2: 0.620489
[88]	valid_0's l2: 0.617029
[89]	valid_0's l2: 0.61979
[90]	valid_0's l2: 0.62053
[91]	valid_0's l2: 0.61649
[92]	valid_0's l2: 0.6084
[93]	valid_0's l2: 0.608444
[94]	valid_0's l2: 0.607305
[95]	valid_0's l2: 0.6101
[96]	valid_0's l2: 0.607935
[97]	valid_0's l2: 0.613991
[98]	valid_0's l2: 0.612047
[99]	valid_0's l2: 0.618738
[100]	valid_0's l2: 0.61602
[101]	valid_0's l2: 0.616932
[102]	valid_0's l2: 0.601777
[103]	valid_0's l2: 0.595715
[104]	valid_0's l2: 0.59668
[105]	valid_0's l2: 0.597316
[106]	valid_0's l2: 0.585771
[107]	valid_0's l2: 0.575166
[108]	valid_0's l2: 0.575758
[109]	valid_0's l2: 0.575758
[110]	valid_0's l2: 0.575758
[111]	valid_0's l2: 0.579176
[112]	valid_0's l2: 0.576683
[113]	valid_0's l2: 0.576688
[114]	valid_0's l2: 0.577109
[115]	valid_0's l2: 0.57711
[116]	valid_0's l2: 0.577948
[117]	valid_0's l2: 0.578359
[118]	valid_0's l2: 0.576717
[119]	valid_0's l2: 0.576713
[120]	valid_0's l2: 0.576711
[121]	valid_0's l2: 0.581848
[122]	valid_0's l2: 0.582549
[123]	valid_0's l2: 0.57142
[124]	valid_0's l2: 0.573369
[125]	valid_0's l2: 0.574457
[126]	valid_0's l2: 0.576354
[127]	valid_0's l2: 0.577627
[128]	valid_0's l2: 0.578498
[129]	valid_0's l2: 0.573854
[130]	valid_0's l2: 0.570888
[131]	valid_0's l2: 0.569828
[132]	valid_0's l2: 0.571029
[133]	valid_0's l2: 0.571564
[134]	valid_0's l2: 0.570027
[135]	valid_0's l2: 0.569571
[136]	valid_0's l2: 0.568616
[137]	valid_0's l2: 0.573387
[138]	valid_0's l2: 0.573185
[139]	valid_0's l2: 0.573096
[140]	valid_0's l2: 0.575343
[141]	valid_0's l2: 0.571823
[142]	valid_0's l2: 0.569402
[143]	valid_0's l2: 0.563454
[144]	valid_0's l2: 0.564505
[145]	valid_0's l2: 0.564688
[146]	valid_0's l2: 0.564524
[147]	valid_0's l2: 0.564251
[148]	valid_0's l2: 0.565112
[149]	valid_0's l2: 0.565112
[150]	valid_0's l2: 0.560379
[151]	valid_0's l2: 0.559958
[152]	valid_0's l2: 0.560014
[153]	valid_0's l2: 0.55356
[154]	valid_0's l2: 0.554229
[155]	valid_0's l2: 0.554324
[156]	valid_0's l2: 0.551351
[157]	valid_0's l2: 0.552783
[158]	valid_0's l2: 0.55345
[159]	valid_0's l2: 0.547649
[160]	valid_0's l2: 0.547583
[161]	valid_0's l2: 0.54897
[162]	valid_0's l2: 0.553247
[163]	valid_0's l2: 0.548111
[164]	valid_0's l2: 0.554599
[165]	valid_0's l2: 0.553078
[166]	valid_0's l2: 0.552635
[167]	valid_0's l2: 0.554121
[168]	valid_0's l2: 0.55733
[169]	valid_0's l2: 0.555451
[170]	valid_0's l2: 0.55282
[171]	valid_0's l2: 0.548178
[172]	valid_0's l2: 0.550429
[173]	valid_0's l2: 0.551231
[174]	valid_0's l2: 0.546339
[175]	valid_0's l2: 0.540148
[176]	valid_0's l2: 0.542362
[177]	valid_0's l2: 0.542027
[178]	valid_0's l2: 0.545171
[179]	valid_0's l2: 0.542534
[180]	valid_0's l2: 0.542749
[181]	valid_0's l2: 0.547945
[182]	valid_0's l2: 0.54109
[183]	valid_0's l2: 0.542022
[184]	valid_0's l2: 0.542722
[185]	valid_0's l2: 0.542421
[186]	valid_0's l2: 0.544928
[187]	valid_0's l2: 0.542917
[188]	valid_0's l2: 0.539043
[189]	valid_0's l2: 0.534276
[190]	valid_0's l2: 0.534019
[191]	valid_0's l2: 0.532171
[192]	valid_0's l2: 0.532152
[193]	valid_0's l2: 0.527943
[194]	valid_0's l2: 0.527857
[195]	valid_0's l2: 0.530275
[196]	valid_0's l2: 0.532754
[197]	valid_0's l2: 0.528975
[198]	valid_0's l2: 0.530248
[199]	valid_0's l2: 0.532551
[200]	valid_0's l2: 0.534649
[201]	valid_0's l2: 0.532929
[202]	valid_0's l2: 0.535518
[203]	valid_0's l2: 0.536638
[204]	valid_0's l2: 0.52359
[205]	valid_0's l2: 0.520168
[206]	valid_0's l2: 0.515284
[207]	valid_0's l2: 0.51831
[208]	valid_0's l2: 0.519141
[209]	valid_0's l2: 0.511777
[210]	valid_0's l2: 0.512148
[211]	valid_0's l2: 0.512314
[212]	valid_0's l2: 0.512826
[213]	valid_0's l2: 0.511639
[214]	valid_0's l2: 0.512212
[215]	valid_0's l2: 0.512406
[216]	valid_0's l2: 0.512406
[217]	valid_0's l2: 0.510287
[218]	valid_0's l2: 0.505479
[219]	valid_0's l2: 0.505374
[220]	valid_0's l2: 0.508769
[221]	valid_0's l2: 0.508769
[222]	valid_0's l2: 0.513862
[223]	valid_0's l2: 0.518613
[224]	valid_0's l2: 0.518611
[225]	valid_0's l2: 0.516746
[226]	valid_0's l2: 0.516978
[227]	valid_0's l2: 0.517663
[228]	valid_0's l2: 0.514065
[229]	valid_0's l2: 0.51026
[230]	valid_0's l2: 0.510598
[231]	valid_0's l2: 0.514281
[232]	valid_0's l2: 0.518412
[233]	valid_0's l2: 0.51615
[234]	valid_0's l2: 0.51264
[235]	valid_0's l2: 0.510721
[236]	valid_0's l2: 0.512542
[237]	valid_0's l2: 0.514903
[238]	valid_0's l2: 0.514903
[239]	valid_0's l2: 0.514922
[240]	valid_0's l2: 0.514922
[241]	valid_0's l2: 0.512003
[242]	valid_0's l2: 0.511907
[243]	valid_0's l2: 0.510839
[244]	valid_0's l2: 0.510665
[245]	valid_0's l2: 0.509521
[246]	valid_0's l2: 0.510181
[247]	valid_0's l2: 0.514932
[248]	valid_0's l2: 0.516824
[249]	valid_0's l2: 0.511529
[250]	valid_0's l2: 0.511529
[251]	valid_0's l2: 0.509125
[252]	valid_0's l2: 0.496212
[253]	valid_0's l2: 0.497062
[254]	valid_0's l2: 0.498147
[255]	valid_0's l2: 0.502221
[256]	valid_0's l2: 0.501347
[257]	valid_0's l2: 0.501959
[258]	valid_0's l2: 0.505579
[259]	valid_0's l2: 0.507218
[260]	valid_0's l2: 0.507123
[261]	valid_0's l2: 0.507704
[262]	valid_0's l2: 0.5109
[263]	valid_0's l2: 0.511366
[264]	valid_0's l2: 0.511405
[265]	valid_0's l2: 0.513002
[266]	valid_0's l2: 0.507453
[267]	valid_0's l2: 0.505196
[268]	valid_0's l2: 0.505631
[269]	valid_0's l2: 0.505771
[270]	valid_0's l2: 0.505115
[271]	valid_0's l2: 0.503099
[272]	valid_0's l2: 0.500718
[273]	valid_0's l2: 0.497234
[274]	valid_0's l2: 0.499643
[275]	valid_0's l2: 0.499643
[276]	valid_0's l2: 0.500355
[277]	valid_0's l2: 0.498083
[278]	valid_0's l2: 0.500394
[279]	valid_0's l2: 0.500875
[280]	valid_0's l2: 0.50142
[281]	valid_0's l2: 0.497637
[282]	valid_0's l2: 0.494909
[283]	valid_0's l2: 0.494357
[284]	valid_0's l2: 0.495961
[285]	valid_0's l2: 0.497102
[286]	valid_0's l2: 0.499612
[287]	valid_0's l2: 0.491204
[288]	valid_0's l2: 0.491211
[289]	valid_0's l2: 0.488631
[290]	valid_0's l2: 0.488664
[291]	valid_0's l2: 0.488632
[292]	valid_0's l2: 0.488663
[293]	valid_0's l2: 0.488663
[294]	valid_0's l2: 0.488581
[295]	valid_0's l2: 0.488358
[296]	valid_0's l2: 0.488358
[297]	valid_0's l2: 0.490299
[298]	valid_0's l2: 0.492158
[299]	valid_0's l2: 0.491465
[300]	valid_0's l2: 0.487937
[301]	valid_0's l2: 0.486148
[302]	valid_0's l2: 0.484079
[303]	valid_0's l2: 0.484079
[304]	valid_0's l2: 0.484121
[305]	valid_0's l2: 0.484185
[306]	valid_0's l2: 0.484917
[307]	valid_0's l2: 0.483531
[308]	valid_0's l2: 0.483531
[309]	valid_0's l2: 0.482161
[310]	valid_0's l2: 0.482867
[311]	valid_0's l2: 0.48413
[312]	valid_0's l2: 0.484221
[313]	valid_0's l2: 0.482954
[314]	valid_0's l2: 0.482097
[315]	valid_0's l2: 0.483072
[316]	valid_0's l2: 0.481031
[317]	valid_0's l2: 0.478494
[318]	valid_0's l2: 0.47939
[319]	valid_0's l2: 0.47939
[320]	valid_0's l2: 0.479677
[321]	valid_0's l2: 0.47735
[322]	valid_0's l2: 0.478015
[323]	valid_0's l2: 0.475848
[324]	valid_0's l2: 0.47723
[325]	valid_0's l2: 0.474951
[326]	valid_0's l2: 0.476988
[327]	valid_0's l2: 0.477021
[328]	valid_0's l2: 0.478584
[329]	valid_0's l2: 0.473021
[330]	valid_0's l2: 0.472745
[331]	valid_0's l2: 0.472745
[332]	valid_0's l2: 0.472345
[333]	valid_0's l2: 0.472754
[334]	valid_0's l2: 0.472782
[335]	valid_0's l2: 0.473669
[336]	valid_0's l2: 0.475129
[337]	valid_0's l2: 0.476128
[338]	valid_0's l2: 0.47703
[339]	valid_0's l2: 0.479947
[340]	valid_0's l2: 0.482531
[341]	valid_0's l2: 0.480184
[342]	valid_0's l2: 0.479795
[343]	valid_0's l2: 0.477396
[344]	valid_0's l2: 0.47539
[345]	valid_0's l2: 0.475189
[346]	valid_0's l2: 0.475268
[347]	valid_0's l2: 0.476542
[348]	valid_0's l2: 0.4765
[349]	valid_0's l2: 0.474898
[350]	valid_0's l2: 0.475179
[351]	valid_0's l2: 0.476118
[352]	valid_0's l2: 0.475443
[353]	valid_0's l2: 0.47588
[354]	valid_0's l2: 0.47483
[355]	valid_0's l2: 0.474998
[356]	valid_0's l2: 0.47366
[357]	valid_0's l2: 0.4742
[358]	valid_0's l2: 0.475304
[359]	valid_0's l2: 0.475293
[360]	valid_0's l2: 0.474594
[361]	valid_0's l2: 0.473614
[362]	valid_0's l2: 0.467558
[363]	valid_0's l2: 0.467901
[364]	valid_0's l2: 0.468191
[365]	valid_0's l2: 0.467258
[366]	valid_0's l2: 0.464574
[367]	valid_0's l2: 0.464973
[368]	valid_0's l2: 0.461812
[369]	valid_0's l2: 0.460764
[370]	valid_0's l2: 0.461031
[371]	valid_0's l2: 0.461031
[372]	valid_0's l2: 0.464585
[373]	valid_0's l2: 0.464585
[374]	valid_0's l2: 0.464317
[375]	valid_0's l2: 0.464591
[376]	valid_0's l2: 0.464841
[377]	valid_0's l2: 0.464588
[378]	valid_0's l2: 0.464775
[379]	valid_0's l2: 0.464983
[380]	valid_0's l2: 0.465055
[381]	valid_0's l2: 0.465246
[382]	valid_0's l2: 0.46542
[383]	valid_0's l2: 0.465578
[384]	valid_0's l2: 0.465578
[385]	valid_0's l2: 0.465721
[386]	valid_0's l2: 0.465721
[387]	valid_0's l2: 0.465721
[388]	valid_0's l2: 0.46585
[389]	valid_0's l2: 0.465967
[390]	valid_0's l2: 0.465967
[391]	valid_0's l2: 0.465967
[392]	valid_0's l2: 0.465967
[393]	valid_0's l2: 0.465967
[394]	valid_0's l2: 0.466074
[395]	valid_0's l2: 0.466074
[396]	valid_0's l2: 0.466074
[397]	valid_0's l2: 0.466272
[398]	valid_0's l2: 0.466272
[399]	valid_0's l2: 0.466272
[400]	valid_0's l2: 0.465642
[401]	valid_0's l2: 0.466234
[402]	valid_0's l2: 0.466768
[403]	valid_0's l2: 0.466768
[404]	valid_0's l2: 0.466768
[405]	valid_0's l2: 0.466768
[406]	valid_0's l2: 0.466768
[407]	valid_0's l2: 0.466768
[408]	valid_0's l2: 0.466768
[409]	valid_0's l2: 0.466768
[410]	valid_0's l2: 0.466768
[411]	valid_0's l2: 0.466768
[412]	valid_0's l2: 0.466768
[413]	valid_0's l2: 0.466768
[414]	valid_0's l2: 0.466768
[415]	valid_0's l2: 0.466768
[416]	valid_0's l2: 0.466768
[417]	valid_0's l2: 0.466768
[418]	valid_0's l2: 0.466768
[419]	valid_0's l2: 0.466768
[420]	valid_0's l2: 0.466768
[421]	valid_0's l2: 0.466768
[422]	valid_0's l2: 0.466768
[423]	valid_0's l2: 0.466768
[424]	valid_0's l2: 0.466768
[425]	valid_0's l2: 0.466768
[426]	valid_0's l2: 0.466768
[427]	valid_0's l2: 0.466768
[428]	valid_0's l2: 0.466768
[429]	valid_0's l2: 0.466768
[430]	valid_0's l2: 0.466768
[431]	valid_0's l2: 0.466768
[432]	valid_0's l2: 0.466768
[433]	valid_0's l2: 0.466768
[434]	valid_0's l2: 0.466768
[435]	valid_0's l2: 0.466768
[436]	valid_0's l2: 0.466768
[437]	valid_0's l2: 0.466768
[438]	valid_0's l2: 0.466768
[439]	valid_0's l2: 0.466768
[440]	valid_0's l2: 0.466768
[441]	valid_0's l2: 0.466768
[442]	valid_0's l2: 0.466768
[443]	valid_0's l2: 0.466768
[444]	valid_0's l2: 0.466768
[445]	valid_0's l2: 0.466768
[446]	valid_0's l2: 0.466768
[447]	valid_0's l2: 0.466768
[448]	valid_0's l2: 0.466768
[449]	valid_0's l2: 0.466768
[450]	valid_0's l2: 0.466768
[451]	valid_0's l2: 0.466768
[452]	valid_0's l2: 0.466768
[453]	valid_0's l2: 0.466768
[454]	valid_0's l2: 0.466768
[455]	valid_0's l2: 0.466768
[456]	valid_0's l2: 0.466768
[457]	valid_0's l2: 0.466768
[458]	valid_0's l2: 0.466768
[459]	valid_0's l2: 0.466768
[460]	valid_0's l2: 0.466768
[461]	valid_0's l2: 0.466768
[462]	valid_0's l2: 0.466768
[463]	valid_0's l2: 0.466768
[464]	valid_0's l2: 0.466768
[465]	valid_0's l2: 0.466768
[466]	valid_0's l2: 0.466768
[467]	valid_0's l2: 0.466768
[468]	valid_0's l2: 0.466768
[469]	valid_0's l2: 0.466768
[470]	valid_0's l2: 0.466768
[471]	valid_0's l2: 0.466768
[472]	valid_0's l2: 0.466768
[473]	valid_0's l2: 0.466768
[474]	valid_0's l2: 0.466768
[475]	valid_0's l2: 0.466768
[476]	valid_0's l2: 0.466768
[477]	valid_0's l2: 0.466768
[478]	valid_0's l2: 0.466768
[479]	valid_0's l2: 0.466768
[480]	valid_0's l2: 0.466768
[481]	valid_0's l2: 0.466768
[482]	valid_0's l2: 0.466768
[483]	valid_0's l2: 0.466768
[484]	valid_0's l2: 0.466768
[485]	valid_0's l2: 0.466768
[486]	valid_0's l2: 0.466768
[487]	valid_0's l2: 0.466768
[488]	valid_0's l2: 0.466768
[489]	valid_0's l2: 0.466768
[490]	valid_0's l2: 0.466768
[491]	valid_0's l2: 0.466768
[492]	valid_0's l2: 0.466768
[493]	valid_0's l2: 0.466768
[494]	valid_0's l2: 0.466768
[495]	valid_0's l2: 0.466768
[496]	valid_0's l2: 0.466768
[497]	valid_0's l2: 0.466768
[498]	valid_0's l2: 0.466768
[499]	valid_0's l2: 0.466768
[500]	valid_0's l2: 0.466768
         Mean      StdDev  Actual
0  168.135851  323.303919   73.07
1  221.660834  362.081830  141.67
2  111.793167  220.596570  110.44
3  321.644361  212.827899  275.01
4  317.810199  299.016857  202.57

In [26]:
generate_and_save_plots(predictions_GPBoost_TF_df, y_test, "./drive/MyDrive/EWQI/Probabilistic_Distribution/GPBoost_Prob_TF.xlsx")

Excel file saved at ./drive/MyDrive/EWQI/Probabilistic_Distribution/GPBoost_Prob_TF.xlsx

In [27]:
generate_and_save_crps_decomposition(
    predictions_GPBoost_TF_df,
    y_test,
    "./drive/MyDrive/EWQI/Probabilistic_Distribution/GPBoost_Prob_TF.xlsx",
    model_name="GPBoost",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/EWQI/Probabilistic_Distribution/GPBoost_Prob_TF.xlsx
   Sheets: CRPS_Summary_GPBoost, CRPS_Bins_GPBoost

     Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  GPBoost   55.958642    57.101613   32.232347    31.089375        10

In [28]:
generate_and_save_pit_results(
    predictions_GPBoost_TF_df,
    y_test,
    "./drive/MyDrive/EWQI/Probabilistic_Distribution/GPBoost_Prob_TF.xlsx",
    model_name="GPBoost",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/EWQI/Probabilistic_Distribution/GPBoost_Prob_TF.xlsx

    PIT_Value
0    0.384362
1    0.412578
2    0.497553
3    0.413279
4    0.349972
5    0.488864
6    0.394689
7    0.457578
8    0.389029
9    0.411067
10   0.622333
11   0.610523
12   0.488823
13   0.406449
14   0.378627
15   0.521784
16   0.407436
17   0.593276
18   0.389266
19   0.511241
20   0.471985
21   0.414470
22   0.464353
23   0.486474
24   0.483120
25   0.470107
26   0.486701
27   0.428086
28   0.406602
29   0.365022
30   0.497572
31   0.397120
32   0.573683
33   0.485478
34   0.376225
35   0.479653
36   0.404884
37   0.479466
38   0.417926
39   0.491851
40   0.467721
41   0.434053
42   0.421184
43   0.435096
44   0.508151
45   0.508855
46   0.298323

In [29]:
generate_and_save_calibration_curve(
    predictions_GPBoost_TF_df,
    y_test,
    "./drive/MyDrive/EWQI/Probabilistic_Distribution/GPBoost_Prob_TF.xlsx",
    model_name="GPBoost",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/EWQI/Probabilistic_Distribution/GPBoost_Prob_TF.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.000000        0.100000
2                  0.2            0.000000        0.200000
3                  0.3            0.021277        0.278723
4                  0.4            0.212766        0.187234
5                  0.5            0.829787        0.329787
6                  0.6            0.957447        0.357447
7                  0.7            1.000000        0.300000
8                  0.8            1.000000        0.200000
9                  0.9            1.000000        0.100000
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using Gradient Boosting (Treeffuser)**

In [30]:
best_params = get_best_model_params(best_scores_autosampler, 'GradientBoosting')

gbr_score_engine = TreeBasedScoreModel(
    model_name='gradient_boosting',
    model_params=best_params,
    seed=42,
)

model = Treeffuser(score_model=gbr_score_engine, seed=42)
model.fit(X_train, y_train)

n_samples_for_prediction = 200
y_samples = model.sample(X_test, n_samples=n_samples_for_prediction, verbose=False)

y_samples_obj = Samples(y_samples)
mean = y_samples_obj.sample_mean()
stddev = y_samples_obj.sample_std()

predictions_GBR_TF_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_GBR_TF_df.head())

         Mean      StdDev  Actual
0  155.682241  319.176943   73.07
1  168.290389  240.913020  141.67
2  115.330971  253.203890  110.44
3  434.090385  458.666286  275.01
4  295.729459  354.746309  202.57

In [31]:
generate_and_save_plots(predictions_GBR_TF_df, y_test, "./drive/MyDrive/EWQI/Probabilistic_Distribution/GBoosting_Prob_TF.xlsx")

Excel file saved at ./drive/MyDrive/EWQI/Probabilistic_Distribution/GBoosting_Prob_TF.xlsx

In [32]:
generate_and_save_crps_decomposition(
    predictions_GBR_TF_df,
    y_test,
    "./drive/MyDrive/EWQI/Probabilistic_Distribution/GBoosting_Prob_TF.xlsx",
    model_name="Gradient Boosting",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/EWQI/Probabilistic_Distribution/GBoosting_Prob_TF.xlsx
   Sheets: CRPS_Summary_Gradient Boosting, CRPS_Bins_Gradient Boosting

,Model,Total_CRPS,Reliability,Resolution,Uncertainty,Num_Bins
0,Gradient Boosting,64.269743,65.360782,32.180413,31.089375,10

In [33]:
generate_and_save_pit_results(
    predictions_GBR_TF_df,
    y_test,
    "./drive/MyDrive/EWQI/Probabilistic_Distribution/GBoosting_Prob_TF.xlsx",
    model_name="GBoosting",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/EWQI/Probabilistic_Distribution/GBoosting_Prob_TF.xlsx

    PIT_Value
0    0.397884
1    0.456007
2    0.492294
3    0.364359
4    0.396426
5    0.488888
6    0.449655
7    0.458856
8    0.396191
9    0.443885
10   0.460585
11   0.505559
12   0.588700
13   0.467468
14   0.425613
15   0.487416
16   0.400001
17   0.424517
18   0.429902
19   0.522337
20   0.518448
21   0.420859
22   0.446247
23   0.594082
24   0.591369
25   0.447916
26   0.456837
27   0.376844
28   0.383185
29   0.355448
30   0.556411
31   0.482870
32   0.522526
33   0.516736
34   0.440823
35   0.425264
36   0.383298
37   0.498125
38   0.484531
39   0.442153
40   0.472396
41   0.448367
42   0.591035
43   0.394610
44   0.532483
45   0.430129
46   0.358067

In [34]:
generate_and_save_calibration_curve(
    predictions_GBR_TF_df,
    y_test,
    "./drive/MyDrive/EWQI/Probabilistic_Distribution/GBoosting_Prob_TF.xlsx",
    model_name="GBoosting",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/EWQI/Probabilistic_Distribution/GBoosting_Prob_TF.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.000000        0.100000
2                  0.2            0.000000        0.200000
3                  0.3            0.000000        0.300000
4                  0.4            0.212766        0.187234
5                  0.5            0.765957        0.265957
6                  0.6            1.000000        0.400000
7                  0.7            1.000000        0.300000
8                  0.8            1.000000        0.200000
9                  0.9            1.000000        0.100000
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using Catboost (Treeffuser)**

In [35]:
best_params = get_best_model_params(best_scores_autosampler, 'CatBoost')

catboost_score_engine = TreeBasedScoreModel(
    model_name='catboost',
    model_params=best_params,
    seed=42,
)

model = Treeffuser(score_model=catboost_score_engine, seed=42)
model.fit(X_train, y_train)

n_samples_for_prediction = 200
y_samples = model.sample(X_test, n_samples=n_samples_for_prediction, verbose=False)

y_samples_obj = Samples(y_samples)
mean = y_samples_obj.sample_mean()
stddev = y_samples_obj.sample_std()

predictions_CatBoost_TF_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_CatBoost_TF_df.head())

         Mean      StdDev  Actual
0  138.204453  349.217930   73.07
1  168.755494  204.336027  141.67
2  111.881237  153.669984  110.44
3  290.053029  135.915611  275.01
4  325.231026  392.927379  202.57

In [36]:
generate_and_save_plots(predictions_CatBoost_TF_df, y_test, "./drive/MyDrive/EWQI/Probabilistic_Distribution/CatBoost_Prob_TF.xlsx")

Excel file saved at ./drive/MyDrive/EWQI/Probabilistic_Distribution/CatBoost_Prob_TF.xlsx

In [37]:
generate_and_save_crps_decomposition(
    predictions_CatBoost_TF_df,
    y_test,
    "./drive/MyDrive/EWQI/Probabilistic_Distribution/CatBoost_Prob_TF.xlsx",
    model_name="CatBoost",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/EWQI/Probabilistic_Distribution/CatBoost_Prob_TF.xlsx
   Sheets: CRPS_Summary_CatBoost, CRPS_Bins_CatBoost

      Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  CatBoost   55.979664    57.002789     32.1125    31.089375        10

In [38]:
generate_and_save_pit_results(
    predictions_CatBoost_TF_df,
    y_test,
    "./drive/MyDrive/EWQI/Probabilistic_Distribution/CatBoost_Prob_TF.xlsx",
    model_name="CatBoost",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/EWQI/Probabilistic_Distribution/CatBoost_Prob_TF.xlsx

    PIT_Value
0    0.426020
1    0.447273
2    0.496258
3    0.455935
4    0.377455
5    0.475801
6    0.393784
7    0.519901
8    0.405026
9    0.413968
10   0.555701
11   0.503851
12   0.550143
13   0.425556
14   0.479498
15   0.458412
16   0.394587
17   0.451904
18   0.367889
19   0.445358
20   0.434873
21   0.475421
22   0.504547
23   0.554278
24   0.439775
25   0.470367
26   0.503749
27   0.404037
28   0.350784
29   0.347016
30   0.520548
31   0.505620
32   0.603090
33   0.409954
34   0.371488
35   0.535132
36   0.429422
37   0.480203
38   0.399674
39   0.502191
40   0.444800
41   0.409587
42   0.485820
43   0.408470
44   0.512941
45   0.450024
46   0.341665

In [39]:
generate_and_save_calibration_curve(
    predictions_CatBoost_TF_df,
    y_test,
    "./drive/MyDrive/EWQI/Probabilistic_Distribution/CatBoost_Prob_TF.xlsx",
    model_name="CatBoost",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/EWQI/Probabilistic_Distribution/CatBoost_Prob_TF.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.000000        0.100000
2                  0.2            0.000000        0.200000
3                  0.3            0.000000        0.300000
4                  0.4            0.191489        0.208511
5                  0.5            0.723404        0.223404
6                  0.6            0.978723        0.378723
7                  0.7            1.000000        0.300000
8                  0.8            1.000000        0.200000
9                  0.9            1.000000        0.100000
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using XGBoost (Treeffuser)**

In [40]:
best_params = get_best_model_params(best_scores_autosampler, 'XGBoost')

xgb_score_engine = TreeBasedScoreModel(
    model_name='xgboost',
    model_params=best_params,
    seed=42,
    verbose=-1
)

model = Treeffuser(score_model=xgb_score_engine, seed=42)
model.fit(X_train, y_train)

n_samples_for_prediction = 200
y_samples = model.sample(X_test, n_samples=n_samples_for_prediction, verbose=False)

y_samples_obj = Samples(y_samples)
mean = y_samples_obj.sample_mean()
stddev = y_samples_obj.sample_std()

predictions_XGB_TF_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_XGB_TF_df.head())

[0]	validation_0-rmse:1.43075
[1]	validation_0-rmse:1.40064
[2]	validation_0-rmse:1.40256
[3]	validation_0-rmse:1.37007
[4]	validation_0-rmse:1.34551
[5]	validation_0-rmse:1.32961
[6]	validation_0-rmse:1.32600
[7]	validation_0-rmse:1.31023
[8]	validation_0-rmse:1.28608
[9]	validation_0-rmse:1.28181
[10]	validation_0-rmse:1.28195
[11]	validation_0-rmse:1.26181
[12]	validation_0-rmse:1.23050
[13]	validation_0-rmse:1.22415
[14]	validation_0-rmse:1.21615
[15]	validation_0-rmse:1.19129
[16]	validation_0-rmse:1.17039
[17]	validation_0-rmse:1.16746
[18]	validation_0-rmse:1.15512
[19]	validation_0-rmse:1.13730
[20]	validation_0-rmse:1.12128
[21]	validation_0-rmse:1.12028
[22]	validation_0-rmse:1.11646
[23]	validation_0-rmse:1.11568
[24]	validation_0-rmse:1.11474
[25]	validation_0-rmse:1.09534
[26]	validation_0-rmse:1.09074
[27]	validation_0-rmse:1.07475
[28]	validation_0-rmse:1.06669
[29]	validation_0-rmse:1.05299
[30]	validation_0-rmse:1.04154
[31]	validation_0-rmse:1.02660
[32]	validation_0-rmse:1.02710
[33]	validation_0-rmse:1.01904
[34]	validation_0-rmse:1.01140
[35]	validation_0-rmse:1.01144
[36]	validation_0-rmse:0.98961
[37]	validation_0-rmse:0.98888
[38]	validation_0-rmse:0.98316
[39]	validation_0-rmse:0.97658
[40]	validation_0-rmse:0.96539
[41]	validation_0-rmse:0.96451
[42]	validation_0-rmse:0.95556
[43]	validation_0-rmse:0.95546
[44]	validation_0-rmse:0.95520
[45]	validation_0-rmse:0.95533
[46]	validation_0-rmse:0.94758
[47]	validation_0-rmse:0.94020
[48]	validation_0-rmse:0.92672
[49]	validation_0-rmse:0.92733
[50]	validation_0-rmse:0.92295
[51]	validation_0-rmse:0.91155
[52]	validation_0-rmse:0.90281
[53]	validation_0-rmse:0.90192
[54]	validation_0-rmse:0.90190
[55]	validation_0-rmse:0.89150
[56]	validation_0-rmse:0.88582
[57]	validation_0-rmse:0.88417
[58]	validation_0-rmse:0.87898
[59]	validation_0-rmse:0.87830
[60]	validation_0-rmse:0.87825
[61]	validation_0-rmse:0.87847
[62]	validation_0-rmse:0.86792
[63]	validation_0-rmse:0.86788
[64]	validation_0-rmse:0.86804
[65]	validation_0-rmse:0.86799
[66]	validation_0-rmse:0.86822
[67]	validation_0-rmse:0.86866
[68]	validation_0-rmse:0.86425
[69]	validation_0-rmse:0.86434
[70]	validation_0-rmse:0.86411
[71]	validation_0-rmse:0.86414
[72]	validation_0-rmse:0.86288
[73]	validation_0-rmse:0.85957
[74]	validation_0-rmse:0.85947
[75]	validation_0-rmse:0.85768
[76]	validation_0-rmse:0.85555
[77]	validation_0-rmse:0.85410
[78]	validation_0-rmse:0.85696
[79]	validation_0-rmse:0.86137
[80]	validation_0-rmse:0.86144
[81]	validation_0-rmse:0.85891
[82]	validation_0-rmse:0.86154
[83]	validation_0-rmse:0.84548
[84]	validation_0-rmse:0.84548
[85]	validation_0-rmse:0.84675
[86]	validation_0-rmse:0.83507
[87]	validation_0-rmse:0.83590
[88]	validation_0-rmse:0.83600
[89]	validation_0-rmse:0.83418
[90]	validation_0-rmse:0.82969
[91]	validation_0-rmse:0.82942
[92]	validation_0-rmse:0.82111
[93]	validation_0-rmse:0.81881
[94]	validation_0-rmse:0.81884
[95]	validation_0-rmse:0.81456
[96]	validation_0-rmse:0.81491
[97]	validation_0-rmse:0.81505
[98]	validation_0-rmse:0.81519
[99]	validation_0-rmse:0.81458
[100]	validation_0-rmse:0.80997
[101]	validation_0-rmse:0.80606
[102]	validation_0-rmse:0.80506
[103]	validation_0-rmse:0.80470
[104]	validation_0-rmse:0.80607
[105]	validation_0-rmse:0.80058
[106]	validation_0-rmse:0.79790
[107]	validation_0-rmse:0.79828
[108]	validation_0-rmse:0.79781
[109]	validation_0-rmse:0.79851
[110]	validation_0-rmse:0.79544
[111]	validation_0-rmse:0.79574
[112]	validation_0-rmse:0.78299
[113]	validation_0-rmse:0.77854
[114]	validation_0-rmse:0.77902
[115]	validation_0-rmse:0.78648
[116]	validation_0-rmse:0.78675
[117]	validation_0-rmse:0.78698
[118]	validation_0-rmse:0.78418
[119]	validation_0-rmse:0.78963
[120]	validation_0-rmse:0.78685
[121]	validation_0-rmse:0.79546
[122]	validation_0-rmse:0.79620
[123]	validation_0-rmse:0.79691
[124]	validation_0-rmse:0.79698
[125]	validation_0-rmse:0.79687
[126]	validation_0-rmse:0.79615
[127]	validation_0-rmse:0.79683
[128]	validation_0-rmse:0.79482
[129]	validation_0-rmse:0.79517
[130]	validation_0-rmse:0.79494
[131]	validation_0-rmse:0.79709
[132]	validation_0-rmse:0.80140
[133]	validation_0-rmse:0.80221
[134]	validation_0-rmse:0.79957
[135]	validation_0-rmse:0.80119
[136]	validation_0-rmse:0.79617
[137]	validation_0-rmse:0.79671
[138]	validation_0-rmse:0.79620
[139]	validation_0-rmse:0.79621
[140]	validation_0-rmse:0.79912
[141]	validation_0-rmse:0.79655
[142]	validation_0-rmse:0.79387
[143]	validation_0-rmse:0.78340
[144]	validation_0-rmse:0.78613
[145]	validation_0-rmse:0.78604
[146]	validation_0-rmse:0.77823
[147]	validation_0-rmse:0.77977
[148]	validation_0-rmse:0.77970
[149]	validation_0-rmse:0.78515
[150]	validation_0-rmse:0.77906
[151]	validation_0-rmse:0.77214
[152]	validation_0-rmse:0.77209
[153]	validation_0-rmse:0.77503
[154]	validation_0-rmse:0.77534
[155]	validation_0-rmse:0.77783
[156]	validation_0-rmse:0.77696
[157]	validation_0-rmse:0.77429
[158]	validation_0-rmse:0.77469
[159]	validation_0-rmse:0.77778
[160]	validation_0-rmse:0.77600
[161]	validation_0-rmse:0.77702
[162]	validation_0-rmse:0.77167
[163]	validation_0-rmse:0.77355
[164]	validation_0-rmse:0.77215
[165]	validation_0-rmse:0.77232
[166]	validation_0-rmse:0.77150
[167]	validation_0-rmse:0.76452
[168]	validation_0-rmse:0.76450
[169]	validation_0-rmse:0.76522
[170]	validation_0-rmse:0.76578
[171]	validation_0-rmse:0.76502
[172]	validation_0-rmse:0.76521
[173]	validation_0-rmse:0.76391
[174]	validation_0-rmse:0.76251
[175]	validation_0-rmse:0.76057
[176]	validation_0-rmse:0.75947
[177]	validation_0-rmse:0.75927
[178]	validation_0-rmse:0.75928
[179]	validation_0-rmse:0.75807
[180]	validation_0-rmse:0.75822
[181]	validation_0-rmse:0.75828
[182]	validation_0-rmse:0.76013
[183]	validation_0-rmse:0.75958
[184]	validation_0-rmse:0.76335
[185]	validation_0-rmse:0.76548
[186]	validation_0-rmse:0.76546
[187]	validation_0-rmse:0.76553
[188]	validation_0-rmse:0.77084
[189]	validation_0-rmse:0.77056
[190]	validation_0-rmse:0.77668
[191]	validation_0-rmse:0.77669
[192]	validation_0-rmse:0.77725
[193]	validation_0-rmse:0.77371
[194]	validation_0-rmse:0.77379
[195]	validation_0-rmse:0.77745
[196]	validation_0-rmse:0.77451
[197]	validation_0-rmse:0.77469
[198]	validation_0-rmse:0.78209
[199]	validation_0-rmse:0.78384
[200]	validation_0-rmse:0.78303
[201]	validation_0-rmse:0.78707
[202]	validation_0-rmse:0.78514
[203]	validation_0-rmse:0.78539
[204]	validation_0-rmse:0.78310
[205]	validation_0-rmse:0.78565
[206]	validation_0-rmse:0.78452
[207]	validation_0-rmse:0.78349
[208]	validation_0-rmse:0.78352
[209]	validation_0-rmse:0.78202
[210]	validation_0-rmse:0.78213
[211]	validation_0-rmse:0.77678
[212]	validation_0-rmse:0.77470
[213]	validation_0-rmse:0.77667
[214]	validation_0-rmse:0.77976
[215]	validation_0-rmse:0.78062
[216]	validation_0-rmse:0.77851
[217]	validation_0-rmse:0.77115
[218]	validation_0-rmse:0.76700
[219]	validation_0-rmse:0.77044
[220]	validation_0-rmse:0.77040
[221]	validation_0-rmse:0.76959
[222]	validation_0-rmse:0.76917
[223]	validation_0-rmse:0.76380
[224]	validation_0-rmse:0.76268
[225]	validation_0-rmse:0.76581
[226]	validation_0-rmse:0.76487
[227]	validation_0-rmse:0.76260
[228]	validation_0-rmse:0.76254
[229]	validation_0-rmse:0.76541
[230]	validation_0-rmse:0.76879
[231]	validation_0-rmse:0.76830
[232]	validation_0-rmse:0.76832
[233]	validation_0-rmse:0.77050
[234]	validation_0-rmse:0.77152
[235]	validation_0-rmse:0.76541
[236]	validation_0-rmse:0.76559
[237]	validation_0-rmse:0.76253
[238]	validation_0-rmse:0.75772
[239]	validation_0-rmse:0.74596
[240]	validation_0-rmse:0.74706
[241]	validation_0-rmse:0.74898
[242]	validation_0-rmse:0.74921
[243]	validation_0-rmse:0.74857
[244]	validation_0-rmse:0.74091
[245]	validation_0-rmse:0.74460
[246]	validation_0-rmse:0.74579
[247]	validation_0-rmse:0.74562
[248]	validation_0-rmse:0.74722
[249]	validation_0-rmse:0.74662
[250]	validation_0-rmse:0.74882
[251]	validation_0-rmse:0.74882
[252]	validation_0-rmse:0.75026
[253]	validation_0-rmse:0.75232
[254]	validation_0-rmse:0.75451
[255]	validation_0-rmse:0.74534
[256]	validation_0-rmse:0.74470
[257]	validation_0-rmse:0.74444
[258]	validation_0-rmse:0.74448
[259]	validation_0-rmse:0.74295
[260]	validation_0-rmse:0.74289
[261]	validation_0-rmse:0.74286
[262]	validation_0-rmse:0.74282
[263]	validation_0-rmse:0.74142
[264]	validation_0-rmse:0.74002
[265]	validation_0-rmse:0.73997
[266]	validation_0-rmse:0.73987
[267]	validation_0-rmse:0.73903
[268]	validation_0-rmse:0.73622
[269]	validation_0-rmse:0.74169
[270]	validation_0-rmse:0.74152
[271]	validation_0-rmse:0.74160
[272]	validation_0-rmse:0.73939
[273]	validation_0-rmse:0.73849
[274]	validation_0-rmse:0.73946
[275]	validation_0-rmse:0.74111
[276]	validation_0-rmse:0.74576
[277]	validation_0-rmse:0.74347
[278]	validation_0-rmse:0.74221
[279]	validation_0-rmse:0.74242
[280]	validation_0-rmse:0.73898
[281]	validation_0-rmse:0.74124
[282]	validation_0-rmse:0.73861
[283]	validation_0-rmse:0.73698
[284]	validation_0-rmse:0.73688
[285]	validation_0-rmse:0.73764
[286]	validation_0-rmse:0.73862
[287]	validation_0-rmse:0.73869
[288]	validation_0-rmse:0.74258
[289]	validation_0-rmse:0.74287
[290]	validation_0-rmse:0.74005
[291]	validation_0-rmse:0.74007
[292]	validation_0-rmse:0.74101
[293]	validation_0-rmse:0.74104
[294]	validation_0-rmse:0.74361
[295]	validation_0-rmse:0.74361
[296]	validation_0-rmse:0.75057
[297]	validation_0-rmse:0.74752
[298]	validation_0-rmse:0.74229
[299]	validation_0-rmse:0.74330
[300]	validation_0-rmse:0.74204
[301]	validation_0-rmse:0.74201
[302]	validation_0-rmse:0.74194
[303]	validation_0-rmse:0.74214
[304]	validation_0-rmse:0.74640
[305]	validation_0-rmse:0.74707
[306]	validation_0-rmse:0.74791
[307]	validation_0-rmse:0.74788
[308]	validation_0-rmse:0.74972
[309]	validation_0-rmse:0.75060
[310]	validation_0-rmse:0.75252
[311]	validation_0-rmse:0.75901
[312]	validation_0-rmse:0.75721
[313]	validation_0-rmse:0.75593
[314]	validation_0-rmse:0.75484
[315]	validation_0-rmse:0.75187
[316]	validation_0-rmse:0.75180
[317]	validation_0-rmse:0.75305
[318]	validation_0-rmse:0.74690
[319]	validation_0-rmse:0.74734
[320]	validation_0-rmse:0.74696
[321]	validation_0-rmse:0.74690
[322]	validation_0-rmse:0.74748
[323]	validation_0-rmse:0.74978
[324]	validation_0-rmse:0.74919
[325]	validation_0-rmse:0.74553
[326]	validation_0-rmse:0.74556
[327]	validation_0-rmse:0.74417
[328]	validation_0-rmse:0.74414
[329]	validation_0-rmse:0.74410
[330]	validation_0-rmse:0.74635
[331]	validation_0-rmse:0.75032
[332]	validation_0-rmse:0.74878
[333]	validation_0-rmse:0.75149
[334]	validation_0-rmse:0.75055
[335]	validation_0-rmse:0.75055
[336]	validation_0-rmse:0.75056
[337]	validation_0-rmse:0.75056
[338]	validation_0-rmse:0.74943
[339]	validation_0-rmse:0.74390
[340]	validation_0-rmse:0.74126
[341]	validation_0-rmse:0.74003
[342]	validation_0-rmse:0.73880
[343]	validation_0-rmse:0.73841
[344]	validation_0-rmse:0.73877
[345]	validation_0-rmse:0.73671
[346]	validation_0-rmse:0.73674
[347]	validation_0-rmse:0.73672
[348]	validation_0-rmse:0.73672
[349]	validation_0-rmse:0.73671
[350]	validation_0-rmse:0.73736
[351]	validation_0-rmse:0.73749
[352]	validation_0-rmse:0.73748
[353]	validation_0-rmse:0.73749
[354]	validation_0-rmse:0.73957
[355]	validation_0-rmse:0.73944
[356]	validation_0-rmse:0.73707
[357]	validation_0-rmse:0.73737
[358]	validation_0-rmse:0.74215
[359]	validation_0-rmse:0.74023
[360]	validation_0-rmse:0.73930
[361]	validation_0-rmse:0.73954
[362]	validation_0-rmse:0.73954
[363]	validation_0-rmse:0.73954
[364]	validation_0-rmse:0.73954
[365]	validation_0-rmse:0.73850
[366]	validation_0-rmse:0.73774
[367]	validation_0-rmse:0.74024
[368]	validation_0-rmse:0.74024
[369]	validation_0-rmse:0.74023
[370]	validation_0-rmse:0.74465
[371]	validation_0-rmse:0.74835
[372]	validation_0-rmse:0.74663
[373]	validation_0-rmse:0.74650
[374]	validation_0-rmse:0.74722
[375]	validation_0-rmse:0.74918
[376]	validation_0-rmse:0.74916
[377]	validation_0-rmse:0.74547
[378]	validation_0-rmse:0.74581
[379]	validation_0-rmse:0.74581
[380]	validation_0-rmse:0.74241
[381]	validation_0-rmse:0.74243
[382]	validation_0-rmse:0.74321
[383]	validation_0-rmse:0.74259
[384]	validation_0-rmse:0.74358
[385]	validation_0-rmse:0.74357
[386]	validation_0-rmse:0.74278
[387]	validation_0-rmse:0.74104
[388]	validation_0-rmse:0.74393
[389]	validation_0-rmse:0.74392
[390]	validation_0-rmse:0.74563
[391]	validation_0-rmse:0.74854
[392]	validation_0-rmse:0.74853
[393]	validation_0-rmse:0.74607
[394]	validation_0-rmse:0.74606
[395]	validation_0-rmse:0.74762
[396]	validation_0-rmse:0.74480
[397]	validation_0-rmse:0.74552
[398]	validation_0-rmse:0.74553
[399]	validation_0-rmse:0.74553
[400]	validation_0-rmse:0.74447
[401]	validation_0-rmse:0.74394
[402]	validation_0-rmse:0.75096
[403]	validation_0-rmse:0.75107
[404]	validation_0-rmse:0.75112
[405]	validation_0-rmse:0.75332
[406]	validation_0-rmse:0.75333
[407]	validation_0-rmse:0.75333
[408]	validation_0-rmse:0.75484
[409]	validation_0-rmse:0.75484
[410]	validation_0-rmse:0.75709
[411]	validation_0-rmse:0.75943
[412]	validation_0-rmse:0.75957
[413]	validation_0-rmse:0.75829
[414]	validation_0-rmse:0.75828
[415]	validation_0-rmse:0.75681
[416]	validation_0-rmse:0.75681
[417]	validation_0-rmse:0.75893
[418]	validation_0-rmse:0.75893
[419]	validation_0-rmse:0.75629
[420]	validation_0-rmse:0.75629
[421]	validation_0-rmse:0.75629
[422]	validation_0-rmse:0.75629
[423]	validation_0-rmse:0.75632
[424]	validation_0-rmse:0.75745
[425]	validation_0-rmse:0.75450
[426]	validation_0-rmse:0.75453
[427]	validation_0-rmse:0.75851
[428]	validation_0-rmse:0.75928
[429]	validation_0-rmse:0.76198
[430]	validation_0-rmse:0.76194
[431]	validation_0-rmse:0.76195
[432]	validation_0-rmse:0.76305
[433]	validation_0-rmse:0.76170
[434]	validation_0-rmse:0.76126
[435]	validation_0-rmse:0.76127
[436]	validation_0-rmse:0.76398
[437]	validation_0-rmse:0.76926
[438]	validation_0-rmse:0.76885
[439]	validation_0-rmse:0.76883
[440]	validation_0-rmse:0.76883
[441]	validation_0-rmse:0.77679
[442]	validation_0-rmse:0.77679
[443]	validation_0-rmse:0.77543
[444]	validation_0-rmse:0.77545
[445]	validation_0-rmse:0.77536
[446]	validation_0-rmse:0.77535
[447]	validation_0-rmse:0.77610
[448]	validation_0-rmse:0.77821
[449]	validation_0-rmse:0.77819
[450]	validation_0-rmse:0.77819
[451]	validation_0-rmse:0.77848
[452]	validation_0-rmse:0.77802
[453]	validation_0-rmse:0.77803
[454]	validation_0-rmse:0.77769
[455]	validation_0-rmse:0.77768
[456]	validation_0-rmse:0.77712
[457]	validation_0-rmse:0.78246
[458]	validation_0-rmse:0.77890
[459]	validation_0-rmse:0.77971
[460]	validation_0-rmse:0.78021
[461]	validation_0-rmse:0.78020
[462]	validation_0-rmse:0.77731
[463]	validation_0-rmse:0.77732
[464]	validation_0-rmse:0.77535
[465]	validation_0-rmse:0.77710
[466]	validation_0-rmse:0.77711
[467]	validation_0-rmse:0.77711
[468]	validation_0-rmse:0.77712
[469]	validation_0-rmse:0.77794
[470]	validation_0-rmse:0.77792
[471]	validation_0-rmse:0.77792
[472]	validation_0-rmse:0.77794
[473]	validation_0-rmse:0.77624
[474]	validation_0-rmse:0.77806
[475]	validation_0-rmse:0.77730
[476]	validation_0-rmse:0.77732
[477]	validation_0-rmse:0.77730
[478]	validation_0-rmse:0.77730
[479]	validation_0-rmse:0.77732
[480]	validation_0-rmse:0.77867
[481]	validation_0-rmse:0.77871
[482]	validation_0-rmse:0.77946
[483]	validation_0-rmse:0.77946
[484]	validation_0-rmse:0.77948
[485]	validation_0-rmse:0.77945
[486]	validation_0-rmse:0.77944
[487]	validation_0-rmse:0.77944
[488]	validation_0-rmse:0.77945
[489]	validation_0-rmse:0.77944
[490]	validation_0-rmse:0.77944
[491]	validation_0-rmse:0.77943
[492]	validation_0-rmse:0.77943
[493]	validation_0-rmse:0.78134
[494]	validation_0-rmse:0.78136
[495]	validation_0-rmse:0.78607
[496]	validation_0-rmse:0.78905
[497]	validation_0-rmse:0.78803
[498]	validation_0-rmse:0.78802
[499]	validation_0-rmse:0.78801
         Mean      StdDev  Actual
0   66.528476  186.762259   73.07
1  133.422260  137.931437  141.67
2   98.326392  166.692161  110.44
3  319.275761  206.456315  275.01
4  296.867228  296.956604  202.57

In [41]:
generate_and_save_plots(predictions_XGB_TF_df, y_test, "./drive/MyDrive/EWQI/Probabilistic_Distribution/XGB_Prob_TF.xlsx")

Excel file saved at ./drive/MyDrive/EWQI/Probabilistic_Distribution/XGB_Prob_TF.xlsx

In [42]:
generate_and_save_crps_decomposition(
    predictions_XGB_TF_df,
    y_test,
    "./drive/MyDrive/EWQI/Probabilistic_Distribution/XGB_Prob_TF.xlsx",
    model_name="XGBoost",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/EWQI/Probabilistic_Distribution/XGB_Prob_TF.xlsx
   Sheets: CRPS_Summary_XGBoost, CRPS_Bins_XGBoost

     Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  XGBoost   54.567056     55.79619   32.318509    31.089375        10

In [43]:
generate_and_save_pit_results(
    predictions_XGB_TF_df,
    y_test,
    "./drive/MyDrive/EWQI/Probabilistic_Distribution/XGB_Prob_TF.xlsx",
    model_name="XGBoost",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/EWQI/Probabilistic_Distribution/XGB_Prob_TF.xlsx

    PIT_Value
0    0.513970
1    0.523841
2    0.528966
3    0.415115
4    0.375415
5    0.528300
6    0.334634
7    0.452958
8    0.444442
9    0.464190
10   0.525993
11   0.559240
12   0.499553
13   0.532968
14   0.504200
15   0.560706
16   0.392770
17   0.459595
18   0.437580
19   0.515775
20   0.506482
21   0.438858
22   0.486870
23   0.526884
24   0.507564
25   0.448964
26   0.563880
27   0.464525
28   0.396669
29   0.322637
30   0.500764
31   0.449610
32   0.638354
33   0.474118
34   0.387581
35   0.552814
36   0.478552
37   0.457535
38   0.426798
39   0.442459
40   0.478771
41   0.525310
42   0.558307
43   0.399795
44   0.555793
45   0.482716
46   0.386395

In [44]:
generate_and_save_calibration_curve(
    predictions_XGB_TF_df,
    y_test,
    "./drive/MyDrive/EWQI/Probabilistic_Distribution/XGB_Prob_TF.xlsx",
    model_name="XGBoost",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/EWQI/Probabilistic_Distribution/XGB_Prob_TF.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.000000        0.100000
2                  0.2            0.000000        0.200000
3                  0.3            0.000000        0.300000
4                  0.4            0.170213        0.229787
5                  0.5            0.574468        0.074468
6                  0.6            0.978723        0.378723
7                  0.7            1.000000        0.300000
8                  0.8            1.000000        0.200000
9                  0.9            1.000000        0.100000
10                 1.0            1.000000        0.000000

# **Probabilistic Distribution using LGBM (Treeffuser)**

In [45]:
best_params = get_best_model_params(best_scores_autosampler, 'LightGBM')

lgbm_score_engine = TreeBasedScoreModel(
    model_name='lightgbm',
    model_params=best_params,
    seed=42,
    verbose=-1
)

model = Treeffuser(score_model=lgbm_score_engine, seed=42)
model.fit(X_train, y_train)

n_samples_for_prediction = 200
y_samples = model.sample(X_test, n_samples=n_samples_for_prediction, verbose=False)

y_samples_obj = Samples(y_samples)
mean = y_samples_obj.sample_mean()
stddev = y_samples_obj.sample_std()

predictions_LGBM_TF_df = pd.DataFrame({
    'Mean': mean,
    'StdDev': stddev,
    'Actual': y_test
})

print(predictions_LGBM_TF_df.head())

         Mean      StdDev  Actual
0   36.402633  250.017205   73.07
1  146.090400  318.346441  141.67
2  137.810386  277.240228  110.44
3  367.473777  294.059114  275.01
4  484.539384  510.833832  202.57

In [46]:
generate_and_save_plots(predictions_LGBM_TF_df, y_test, "./drive/MyDrive/EWQI/Probabilistic_Distribution/LGBM_Prob_TF.xlsx")

Excel file saved at ./drive/MyDrive/EWQI/Probabilistic_Distribution/LGBM_Prob_TF.xlsx

In [47]:
generate_and_save_crps_decomposition(
    predictions_LGBM_TF_df,
    y_test,
    "./drive/MyDrive/EWQI/Probabilistic_Distribution/LGBM_Prob_TF.xlsx",
    model_name="LightGBM",
    n_bins=10
)

✅ CRPS decomposition saved to:
drive/MyDrive/EWQI/Probabilistic_Distribution/LGBM_Prob_TF.xlsx
   Sheets: CRPS_Summary_LightGBM, CRPS_Bins_LightGBM

      Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  LightGBM   79.917004    81.607586   32.779958    31.089375        10

In [48]:
generate_and_save_pit_results(
    predictions_LGBM_TF_df,
    y_test,
    "./drive/MyDrive/EWQI/Probabilistic_Distribution/LGBM_Prob_TF.xlsx",
    model_name="LightGBM",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   drive/MyDrive/EWQI/Probabilistic_Distribution/LGBM_Prob_TF.xlsx

    PIT_Value
0    0.558300
1    0.494461
2    0.460679
3    0.376594
4    0.290481
5    0.446392
6    0.383932
7    0.366125
8    0.467307
9    0.371256
10   0.462916
11   0.462724
12   0.500783
13   0.462027
14   0.383238
15   0.513142
16   0.350252
17   0.368838
18   0.351017
19   0.449730
20   0.438190
21   0.440881
22   0.429167
23   0.456443
24   0.537027
25   0.609174
26   0.440629
27   0.446087
28   0.345388
29   0.338356
30   0.545723
31   0.457030
32   0.526548
33   0.364625
34   0.349427
35   0.391197
36   0.367401
37   0.519206
38   0.439435
39   0.440059
40   0.466458
41   0.463804
42   0.438851
43   0.430584
44   0.454464
45   0.436193
46   0.315845

In [49]:
generate_and_save_calibration_curve(
    predictions_LGBM_TF_df,
    y_test,
    "./drive/MyDrive/EWQI/Probabilistic_Distribution/LGBM_Prob_TF.xlsx",
    model_name="LightGBM",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   drive/MyDrive/EWQI/Probabilistic_Distribution/LGBM_Prob_TF.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.000000        0.100000
2                  0.2            0.000000        0.200000
3                  0.3            0.021277        0.278723
4                  0.4            0.340426        0.059574
5                  0.5            0.829787        0.329787
6                  0.6            0.978723        0.378723
7                  0.7            1.000000        0.300000
8                  0.8            1.000000        0.200000
9                  0.9            1.000000        0.100000
10                 1.0            1.000000        0.000000

# **IBUG Installation**

In [50]:
# Clone the repository
!git clone https://github.com/jjbrophy47/ibug.git
%cd ibug

# Build extensions if needed
!python setup.py build_ext --inplace

# Install the package
!pip install .

# Verify installation
try:
    from ibug import IBUGWrapper
    print("IBUGWrapper imported successfully!")
except ImportError as e:
    print("Error importing IBUGWrapper:", e)

Cloning into 'ibug'...
remote: Enumerating objects: 1763, done.
remote: Counting objects: 100% (37/37), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 1763 (delta 18), reused 15 (delta 4), pack-reused 1726 (from 1)
Receiving objects: 100% (1763/1763), 1.31 MiB | 12.06 MiB/s, done.
Resolving deltas: 100% (967/967), done.
/content/ibug
Compiling ibug/parsers/_tree32.pyx because it changed.
Compiling ibug/parsers/_tree64.pyx because it changed.
[1/2] Cythonizing ibug/parsers/_tree32.pyx
performance hint: ibug/parsers/_tree32.pyx:84:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:112:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:140:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:238:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:266:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:312:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:344:47: Exception check after calling '_initialize_node' will always require the GIL to be acquired. Declare '_initialize_node' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:352:48: Exception check after calling '_add_node' will always require the GIL to be acquired. Declare '_add_node' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:355:49: Exception check after calling '_add_node' will always require the GIL to be acquired. Declare '_add_node' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree32.pyx:400:33: Exception check after calling '_get_leaf_values' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_values' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_values' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:401:33: Exception check after calling '_get_leaf_values' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_values' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_values' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:417:34: Exception check after calling '_get_leaf_weights' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_weights' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_weights' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:418:34: Exception check after calling '_get_leaf_weights' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_weights' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_weights' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:434:33: Exception check after calling '_get_leaf_depths' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_depths' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_depths' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:435:33: Exception check after calling '_get_leaf_depths' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_depths' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_depths' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:464:21: Exception check after calling '_dealloc' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_dealloc' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_dealloc' to allow an error code to be returned.
performance hint: ibug/parsers/_tree32.pyx:465:21: Exception check after calling '_dealloc' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_dealloc' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_dealloc' to allow an error code to be returned.
[2/2] Cythonizing ibug/parsers/_tree64.pyx
performance hint: ibug/parsers/_tree64.pyx:93:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:121:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:149:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:247:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:275:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:321:43: Exception check after calling '_test_threshold' will always require the GIL to be acquired. Declare '_test_threshold' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:353:47: Exception check after calling '_initialize_node' will always require the GIL to be acquired. Declare '_initialize_node' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:361:48: Exception check after calling '_add_node' will always require the GIL to be acquired. Declare '_add_node' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:364:49: Exception check after calling '_add_node' will always require the GIL to be acquired. Declare '_add_node' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
performance hint: ibug/parsers/_tree64.pyx:409:33: Exception check after calling '_get_leaf_values' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_values' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_values' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:410:33: Exception check after calling '_get_leaf_values' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_values' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_values' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:426:34: Exception check after calling '_get_leaf_weights' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_weights' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_weights' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:427:34: Exception check after calling '_get_leaf_weights' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_weights' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_weights' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:443:33: Exception check after calling '_get_leaf_depths' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_depths' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_depths' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:444:33: Exception check after calling '_get_leaf_depths' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_get_leaf_depths' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_get_leaf_depths' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:473:21: Exception check after calling '_dealloc' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_dealloc' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_dealloc' to allow an error code to be returned.
performance hint: ibug/parsers/_tree64.pyx:474:21: Exception check after calling '_dealloc' will always require the GIL to be acquired.
Possible solutions:
	1. Declare '_dealloc' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
	2. Use an 'int' return type on '_dealloc' to allow an error code to be returned.
running build_ext
building 'ibug.parsers._tree32' extension
creating build/temp.linux-x86_64-cpython-312/ibug/parsers
x86_64-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/local/lib/python3.12/dist-packages/numpy/core/include -I/usr/include/python3.12 -c ibug/parsers/_tree32.c -o build/temp.linux-x86_64-cpython-312/ibug/parsers/_tree32.o
In file included from /usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1929,
                 from /usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from ibug/parsers/_tree32.c:1257:
/usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wcpp-Wcpp]8;;]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
creating build/lib.linux-x86_64-cpython-312/ibug/parsers
x86_64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-x86_64-cpython-312/ibug/parsers/_tree32.o -L/usr/lib/x86_64-linux-gnu -o build/lib.linux-x86_64-cpython-312/ibug/parsers/_tree32.cpython-312-x86_64-linux-gnu.so
building 'ibug.parsers._tree64' extension
x86_64-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/local/lib/python3.12/dist-packages/numpy/core/include -I/usr/include/python3.12 -c ibug/parsers/_tree64.c -o build/temp.linux-x86_64-cpython-312/ibug/parsers/_tree64.o
In file included from /usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1929,
                 from /usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from ibug/parsers/_tree64.c:1257:
/usr/local/lib/python3.12/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wcpp-Wcpp]8;;]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
x86_64-linux-gnu-gcc -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 build/temp.linux-x86_64-cpython-312/ibug/parsers/_tree64.o -L/usr/lib/x86_64-linux-gnu -o build/lib.linux-x86_64-cpython-312/ibug/parsers/_tree64.cpython-312-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-cpython-312/ibug/parsers/_tree32.cpython-312-x86_64-linux-gnu.so -> ibug/parsers
copying build/lib.linux-x86_64-cpython-312/ibug/parsers/_tree64.cpython-312-x86_64-linux-gnu.so -> ibug/parsers
Processing /content/ibug
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.22 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (1.26.4)
Collecting uncertainty-toolbox>=0.1.0 (from ibug==0.0.12)
  Downloading uncertainty_toolbox-0.1.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: joblib>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (1.5.3)
Requirement already satisfied: scikit-learn>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (1.6.1)
Requirement already satisfied: scipy>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (1.16.3)
Requirement already satisfied: pandas>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (2.2.2)
Requirement already satisfied: Cython>=0.29.23 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (3.0.12)
Requirement already satisfied: xgboost>=1.6.1 in /usr/local/lib/python3.12/dist-packages (from ibug==0.0.12) (3.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.3->ibug==0.0.12) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.3->ibug==0.0.12) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.3->ibug==0.0.12) (2025.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.5.0->ibug==0.0.12) (3.6.0)
Requirement already satisfied: matplotlib>=3.2.2 in /usr/local/lib/python3.12/dist-packages (from uncertainty-toolbox>=0.1.0->ibug==0.0.12) (3.10.0)
Requirement already satisfied: tqdm>=4.54.0 in /usr/local/lib/python3.12/dist-packages (from uncertainty-toolbox>=0.1.0->ibug==0.0.12) (4.67.3)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost>=1.6.1->ibug==0.0.12) (2.29.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.2->uncertainty-toolbox>=0.1.0->ibug==0.0.12) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.4.3->ibug==0.0.12) (1.17.0)
Downloading uncertainty_toolbox-0.1.1-py3-none-any.whl (24 kB)
Building wheels for collected packages: ibug
  Building wheel for ibug (pyproject.toml) ... done
  Created wheel for ibug: filename=ibug-0.0.12-cp312-cp312-linux_x86_64.whl size=1457994 sha256=a98dace230d722629e23d9447db31770c10e2ec9a8748ef5e3d9b414db426ef0
  Stored in directory: /tmp/pip-ephem-wheel-cache-mjw6f54_/wheels/bc/4c/24/9707d9556afa0b36e8ea6c7b2641eb7474f791664f4bb187cd
Successfully built ibug
Installing collected packages: uncertainty-toolbox, ibug
Successfully installed ibug-0.0.12 uncertainty-toolbox-0.1.1
IBUGWrapper imported successfully!

In [51]:
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.3)

# **Probabilistic Distributions using LGBM (IBUG)**

In [52]:
# y_train = y_train.to_numpy()
# y_val = y_val.to_numpy()

In [53]:
# Assume hyperparameter tuning has been done and best_params are obtained
best_params = get_best_model_params(best_scores_autosampler, 'LightGBM')

# --- Ensure IBUG compatibility ---
best_params['reg_alpha'] = 0
best_params['class_weight'] = None
best_params['boosting_type'] = 'gbdt'

# Initialize and train the LightGBM regressor using the best_params
model = LGBMRegressor(**best_params)
model.fit(X_train, y_train)

# Extend the trained model into a probabilistic predictor using IBUGWrapper
prob_model = IBUGWrapper().fit(model, X_train, y_train, X_val=X_val, y_val=y_val)

# Use the model to predict the probabilistic distribution on the test data.
location, scale = prob_model.pred_dist(X_test)

# Optionally, to also get the k-nearest training indices and their values used in modeling
location2, scale2, train_idxs, train_vals = prob_model.pred_dist(X_test, return_kneighbors=True)

dev = scale**0.5
# Create a DataFrame for clarity
predictions_LGBM_df = pd.DataFrame({
    'Mean': location,
    'StdDev': dev,
    'Actual': y_test,
})

print(predictions_LGBM_df.head())

         Mean    StdDev  Actual
0  100.020111  5.008641   73.07
1  146.215985  5.872415  141.67
2   84.441468  4.270518  110.44
3  276.772090  8.315507  275.01
4  176.225670  5.508779  202.57

In [56]:
%cd ..

/

In [ ]:
%cd ..

In [57]:
generate_and_save_plots(predictions_LGBM_df, y_test, "./content/drive/MyDrive/EWQI/Probabilistic_Distribution/LGBM_Prob.xlsx")

Excel file saved at ./content/drive/MyDrive/EWQI/Probabilistic_Distribution/LGBM_Prob.xlsx

In [58]:
generate_and_save_crps_decomposition(
    predictions_LGBM_df,
    y_test,
    "/content/drive/MyDrive/EWQI/Probabilistic_Distribution/LGBM_Prob.xlsx",
    model_name="LGBM",
    n_bins=10
)

✅ CRPS decomposition saved to:
/content/drive/MyDrive/EWQI/Probabilistic_Distribution/LGBM_Prob.xlsx
   Sheets: CRPS_Summary_LGBM, CRPS_Bins_LGBM

  Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0  LGBM   12.238566    12.137285   30.988094    31.089375        10

In [59]:
generate_and_save_pit_results(
    predictions_LGBM_df,
    y_test,
    "/content/drive/MyDrive/EWQI/Probabilistic_Distribution/LGBM_Prob.xlsx",
    model_name="LGBM",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   /content/drive/MyDrive/EWQI/Probabilistic_Distribution/LGBM_Prob.xlsx

       PIT_Value
0   3.709355e-08
1   2.194283e-01
2   1.000000e+00
3   4.160909e-01
4   9.999991e-01
5   9.999977e-01
6   7.949654e-04
7   9.999510e-01
8   1.043572e-03
9   6.312612e-01
10  1.000000e+00
11  6.679526e-01
12  9.925397e-01
13  3.871793e-01
14  3.938695e-01
15  9.983069e-01
16  8.841540e-01
17  1.000000e+00
18  7.051373e-03
19  8.071130e-02
20  9.619989e-01
21  9.994991e-01
22  9.948511e-01
23  4.061009e-01
24  9.998814e-01
25  3.405245e-03
26  1.000000e+00
27  9.081050e-01
28  9.954572e-01
29  9.026057e-01
30  3.963808e-06
31  1.133363e-01
32  1.573049e-02
33  9.996356e-01
34  8.062848e-02
35  9.999463e-01
36  2.983155e-01
37  4.773419e-01
38  9.997124e-01
39  1.000000e+00
40  9.997934e-01
41  9.954044e-01
42  1.597538e-01
43  1.150424e-01
44  9.960627e-01
45  9.995267e-01
46  5.516520e-01

In [60]:
generate_and_save_calibration_curve(
    predictions_LGBM_df,
    y_test,
    "/content/drive/MyDrive/EWQI/Probabilistic_Distribution/LGBM_Prob.xlsx",
    model_name="LGBM",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   /content/drive/MyDrive/EWQI/Probabilistic_Distribution/LGBM_Prob.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.191489        0.091489
2                  0.2            0.255319        0.055319
3                  0.3            0.297872        0.002128
4                  0.4            0.340426        0.059574
5                  0.5            0.404255        0.095745
6                  0.6            0.425532        0.174468
7                  0.7            0.468085        0.231915
8                  0.8            0.468085        0.331915
9                  0.9            0.489362        0.410638
10                 1.0            1.000000        0.000000

# **Probabilistic Distributions using XGBoost (IBUG)**

In [61]:
# Assume hyperparameter tuning has been done and best_params are obtained
best_params = get_best_model_params(best_scores_autosampler, 'XGBoost')

best_params['reg_alpha'] = 0
best_params['scale_pos_weight'] = 1
best_params['base_score'] = 0.5

# Initialize and train the XGBoost regressor using the best_params
model = XGBRegressor(**best_params)
model.fit(X_train, y_train)

# Extend the trained model into a probabilistic predictor using IBUGWrapper
prob_model = IBUGWrapper().fit(model, X_train, y_train, X_val=X_val, y_val=y_val)

# Use the model to predict the probabilistic distribution on the test data.
# This returns the predicted mean (location) and uncertainty (scale, variance proxy)
location, scale = prob_model.pred_dist(X_test)

# Optionally, to also get the k-nearest training indices and their values used in modeling
location, scale, train_idxs, train_vals = prob_model.pred_dist(X_test, return_kneighbors=True)

# Calculate the standard deviation from the variance (scale)
std_dev = scale ** 0.5

# Create a DataFrame for clarity
predictions_XGB_df = pd.DataFrame({
    'Mean': location,
    'StdDev': std_dev,
    'Actual': y_test
})

print(predictions_XGB_df.head())

         Mean    StdDev  Actual
0   78.070244  4.405204   73.07
1  133.852631  4.498013  141.67
2   85.081604  3.911250  110.44
3  267.400208  8.574677  275.01
4  159.221817  5.075841  202.57

In [62]:
generate_and_save_plots(predictions_LGBM_df, y_test, "./content/drive/MyDrive/EWQI/Probabilistic_Distribution/XGB_Prob.xlsx")

Excel file saved at ./content/drive/MyDrive/EWQI/Probabilistic_Distribution/XGB_Prob.xlsx

In [63]:
generate_and_save_crps_decomposition(
    predictions_XGB_df,
    y_test,
    "/content/drive/MyDrive/EWQI/Probabilistic_Distribution/XGB_Prob.xlsx",
    model_name="XGB",
    n_bins=10
)

✅ CRPS decomposition saved to:
/content/drive/MyDrive/EWQI/Probabilistic_Distribution/XGB_Prob.xlsx
   Sheets: CRPS_Summary_XGB, CRPS_Bins_XGB

  Model  Total_CRPS  Reliability  Resolution  Uncertainty  Num_Bins
0   XGB   13.048478    13.007305   31.048203    31.089375        10

In [64]:
generate_and_save_pit_results(
    predictions_XGB_df,
    y_test,
    "/content/drive/MyDrive/EWQI/Probabilistic_Distribution/XGB_Prob.xlsx",
    model_name="XGB",
    n_bins=10
)

✅ PIT values, histogram, summary, and EMBEDDED plot saved to:
   /content/drive/MyDrive/EWQI/Probabilistic_Distribution/XGB_Prob.xlsx

       PIT_Value
0   1.281716e-01
1   9.588911e-01
2   1.000000e+00
3   8.125878e-01
4   1.000000e+00
5   9.999998e-01
6   1.514255e-07
7   6.675177e-01
8   1.670604e-01
9   2.104343e-01
10  1.000000e+00
11  8.735495e-01
12  5.643871e-01
13  8.462673e-01
14  9.643170e-01
15  9.999999e-01
16  9.992769e-01
17  9.999999e-01
18  1.564082e-03
19  9.042960e-02
20  9.967465e-01
21  9.997543e-01
22  9.573767e-01
23  5.870350e-01
24  9.983955e-01
25  9.987819e-01
26  1.000000e+00
27  9.999551e-01
28  1.000000e+00
29  9.958752e-01
30  1.212951e-12
31  3.241285e-01
32  7.412726e-13
33  9.989198e-01
34  7.726950e-01
35  7.967382e-01
36  9.045527e-01
37  9.129616e-01
38  9.105580e-01
39  1.000000e+00
40  9.998803e-01
41  9.991921e-01
42  2.453642e-01
43  6.508741e-01
44  9.997134e-01
45  9.933578e-01
46  8.555962e-01

In [65]:
generate_and_save_calibration_curve(
    predictions_XGB_df,
    y_test,
    "/content/drive/MyDrive/EWQI/Probabilistic_Distribution/XGB_Prob.xlsx",
    model_name="XGB",
    n_quantiles=10
)

✅ Calibration curve & metrics saved to Excel:
   /content/drive/MyDrive/EWQI/Probabilistic_Distribution/XGB_Prob.xlsx

    Predicted_Quantile  Observed_Frequency  Absolute_Error
0                  0.0            0.000000        0.000000
1                  0.1            0.106383        0.006383
2                  0.2            0.148936        0.051064
3                  0.3            0.191489        0.108511
4                  0.4            0.212766        0.187234
5                  0.5            0.212766        0.287234
6                  0.6            0.255319        0.344681
7                  0.7            0.297872        0.402128
8                  0.8            0.340426        0.459574
9                  0.9            0.425532        0.474468
10                 1.0            1.000000        0.000000

# **Matrix Evaulation**

In [66]:
# Create a Pandas Excel writer using XlsxWriter as the engine.
folder_path = "/content/drive/MyDrive/EWQI"
excel_path = os.path.join(folder_path, "/content/drive/MyDrive/EWQI/Probabilistic_Distribution/Matrix Evaluation.xlsx")
with pd.ExcelWriter(excel_path, engine='xlsxwriter') as writer:
    plot_metrics_and_save_to_excel(writer, predictions_NGB_df, y_test, 'NGBoost')
    plot_metrics_and_save_to_excel(writer, predictions_PGBM_df, y_test, 'PGBM')
    plot_metrics_and_save_to_excel(writer, predictions_LGBM_df, y_test, 'LGBM')
    plot_metrics_and_save_to_excel(writer, predictions_XGB_df, y_test, 'XGBoost')
    plot_metrics_and_save_to_excel(writer, predictions_LGBM_TF_df, y_test, "LightGBM_TF")
    plot_metrics_and_save_to_excel(writer, predictions_XGB_TF_df, y_test, "XGBoost_TF")
    plot_metrics_and_save_to_excel(writer, predictions_CatBoost_TF_df, y_test, "CatBoost_TF")
    plot_metrics_and_save_to_excel(writer, predictions_GPBoost_TF_df, y_test, "GPBoost_TF")
    plot_metrics_and_save_to_excel(writer, predictions_GBR_TF_df, y_test, "GradientBoosting_TF")