# **Start Section:**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# Uninstall existing scikit-learn to avoid conflicts
!pip uninstall -y scikit-learn
# Install specific versions of libraries to avoid conflicts
!pip install scikit-learn==1.5.2
!pip install bayesian-optimization==3.2.0
!pip install optuna==4.6.0
!pip install gpboost==1.6.1
!pip install shap==0.50.0
!pip install ngboost==0.5.8
!pip install dask[dataframe]==2025.12.0
!pip install torch==2.9.0+cpu
!pip install seaborn==0.13.2
!pip install lightgbm==4.6.0
!pip install xgboost==3.1.2
!pip install lime==0.2.0.1
!pip install interpret==0.7.4
!pip install optunahub==0.4.0
!pip install cmaes==0.12.0
!pip install plotly==5.24.1
!pip install kaleido==1.2.0
!pip install openpyxl==3.1.5
!pip install properscoring==0.1
!pip install XlsxWriter==3.2.9
!pip install cython==3.0.12
!pip install pgbm==2.2.0
!pip install cp==2020.12.3
!pip install mapie==0.6.0
!pip install skorch==1.3.1
!pip install puncc==0.8.0
# Reinstall scikit-learn to the version required by ngboost
!pip uninstall -y scikit-learn
!pip install scikit-learn==1.6.1
# Reinstall numpy first
!pip install numpy==1.26.4  # Use the version compatible with catboost
# Reinstall catboost
!pip install catboost==1.2.8
!pip install pytorch-tabnet2==4.5.3

Found existing installation: scikit-learn 1.6.1
Uninstalling scikit-learn-1.6.1:
  Successfully uninstalled scikit-learn-1.6.1
Collecting scikit-learn==1.5.2
  Downloading scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (3.6.0)
Downloading scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 108.1 MB/s eta 0:00:00
Installing collected packages: scikit-learn
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
umap-learn 0.5.11 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
hdbscan 0.8.41 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
Successfully installed scikit-learn-1.5.2
Collecting bayesian-optimization==3.2.0
  Downloading bayesian_optimization-3.2.0-py3-none-any.whl.metadata (11 kB)
Collecting colorama>=0.4.6 (from bayesian-optimization==3.2.0)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from bayesian-optimization==3.2.0) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from bayesian-optimization==3.2.0) (26.0)
Requirement already satisfied: scikit-learn>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bayesian-optimization==3.2.0) (1.5.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bayesian-optimization==3.2.0) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.0->bayesian-optimization==3.2.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.0->bayesian-optimization==3.2.0) (3.6.0)
Downloading bayesian_optimization-3.2.0-py3-none-any.whl (37 kB)
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Installing collected packages: colorama, bayesian-optimization
Successfully installed bayesian-optimization-3.2.0 colorama-0.4.6
Collecting optuna==4.6.0
  Downloading optuna-4.6.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna==4.6.0) (1.18.4)
Collecting colorlog (from optuna==4.6.0)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna==4.6.0) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna==4.6.0) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna==4.6.0) (2.0.46)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna==4.6.0) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna==4.6.0) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna==4.6.0) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna==4.6.0) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna==4.6.0) (3.3.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna==4.6.0) (3.0.3)
Downloading optuna-4.6.0-py3-none-any.whl (404 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 404.7/404.7 kB 8.2 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.6.0
Collecting gpboost==1.6.1
  Downloading gpboost-1.6.1-py3-none-manylinux1_x86_64.whl.metadata (7.9 kB)
Requirement already satisfied: wheel in /usr/local/lib/python3.12/dist-packages (from gpboost==1.6.1) (0.46.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from gpboost==1.6.1) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from gpboost==1.6.1) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from gpboost==1.6.1) (1.16.3)
Requirement already satisfied: scikit-learn!=0.22.0 in /usr/local/lib/python3.12/dist-packages (from gpboost==1.6.1) (1.5.2)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (from gpboost==1.6.1) (4.6.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn!=0.22.0->gpboost==1.6.1) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn!=0.22.0->gpboost==1.6.1) (3.6.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna->gpboost==1.6.1) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna->gpboost==1.6.1) (6.10.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna->gpboost==1.6.1) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->gpboost==1.6.1) (2.0.46)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna->gpboost==1.6.1) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna->gpboost==1.6.1) (6.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->gpboost==1.6.1) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->gpboost==1.6.1) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->gpboost==1.6.1) (2025.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->gpboost==1.6.1) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->gpboost==1.6.1) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->gpboost==1.6.1) (1.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna->gpboost==1.6.1) (3.3.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna->gpboost==1.6.1) (3.0.3)
Downloading gpboost-1.6.1-py3-none-manylinux1_x86_64.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 10.9 MB/s eta 0:00:00
Installing collected packages: gpboost
Successfully installed gpboost-1.6.1
Requirement already satisfied: shap==0.50.0 in /usr/local/lib/python3.12/dist-packages (0.50.0)
Requirement already satisfied: numpy>=2 in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (1.16.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (1.5.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (2.2.2)
Requirement already satisfied: tqdm>=4.27.0 in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (4.67.3)
Requirement already satisfied: packaging>20.9 in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (26.0)
Requirement already satisfied: slicer==0.0.8 in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (0.0.8)
Requirement already satisfied: numba>=0.54 in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (0.60.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (3.1.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (4.15.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.54->shap==0.50.0) (0.43.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->shap==0.50.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->shap==0.50.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->shap==0.50.0) (2025.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->shap==0.50.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->shap==0.50.0) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->shap==0.50.0) (1.17.0)
Collecting ngboost==0.5.8
  Downloading ngboost-0.5.8-py3-none-any.whl.metadata (4.2 kB)
Collecting lifelines>=0.25 (from ngboost==0.5.8)
  Downloading lifelines-0.30.1-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: numpy>=1.21.2 in /usr/local/lib/python3.12/dist-packages (from ngboost==0.5.8) (2.0.2)
Collecting scikit-learn<2.0,>=1.6 (from ngboost==0.5.8)
  Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: scipy>=1.7.2 in /usr/local/lib/python3.12/dist-packages (from ngboost==0.5.8) (1.16.3)
Requirement already satisfied: tqdm>=4.3 in /usr/local/lib/python3.12/dist-packages (from ngboost==0.5.8) (4.67.3)
Requirement already satisfied: pandas<3.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from lifelines>=0.25->ngboost==0.5.8) (2.2.2)
Requirement already satisfied: matplotlib>=3.0 in /usr/local/lib/python3.12/dist-packages (from lifelines>=0.25->ngboost==0.5.8) (3.10.0)
Requirement already satisfied: autograd>=1.5 in /usr/local/lib/python3.12/dist-packages (from lifelines>=0.25->ngboost==0.5.8) (1.8.0)
Collecting autograd-gamma>=0.3 (from lifelines>=0.25->ngboost==0.5.8)
  Downloading autograd-gamma-0.5.0.tar.gz (4.0 kB)
  Preparing metadata (setup.py) ... done
Collecting formulaic>=0.2.2 (from lifelines>=0.25->ngboost==0.5.8)
  Downloading formulaic-1.2.1-py3-none-any.whl.metadata (7.0 kB)
Requirement already satisfied: joblib>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0,>=1.6->ngboost==0.5.8) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0,>=1.6->ngboost==0.5.8) (3.6.0)
Collecting interface-meta>=1.2.0 (from formulaic>=0.2.2->lifelines>=0.25->ngboost==0.5.8)
  Downloading interface_meta-1.3.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines>=0.25->ngboost==0.5.8) (2.16.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines>=0.25->ngboost==0.5.8) (4.15.0)
Requirement already satisfied: wrapt>=1.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines>=0.25->ngboost==0.5.8) (2.1.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=2.1->lifelines>=0.25->ngboost==0.5.8) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=2.1->lifelines>=0.25->ngboost==0.5.8) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (1.17.0)
Downloading ngboost-0.5.8-py3-none-any.whl (36 kB)
Downloading lifelines-0.30.1-py3-none-any.whl (350 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 350.0/350.0 kB 9.7 MB/s eta 0:00:00
Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 95.7 MB/s eta 0:00:00
Downloading formulaic-1.2.1-py3-none-any.whl (117 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.3/117.3 kB 11.4 MB/s eta 0:00:00
Downloading interface_meta-1.3.0-py3-none-any.whl (14 kB)
Building wheels for collected packages: autograd-gamma
  Building wheel for autograd-gamma (setup.py) ... done
  Created wheel for autograd-gamma: filename=autograd_gamma-0.5.0-py3-none-any.whl size=4030 sha256=010cc6ca840cdb0ded423668590c12ec4f5eb56cdcc14d9f30e120945f1c058c
  Stored in directory: /root/.cache/pip/wheels/50/37/21/0a719b9d89c635e89ff24bd93b862882ad675279552013b2fb
Successfully built autograd-gamma
Installing collected packages: interface-meta, scikit-learn, autograd-gamma, formulaic, lifelines, ngboost
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.5.2
    Uninstalling scikit-learn-1.5.2:
      Successfully uninstalled scikit-learn-1.5.2
Successfully installed autograd-gamma-0.5.0 formulaic-1.2.1 interface-meta-1.3.0 lifelines-0.30.1 ngboost-0.5.8 scikit-learn-1.8.0
Requirement already satisfied: dask==2025.12.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]==2025.12.0) (2025.12.0)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (8.3.1)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (3.1.2)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (2025.3.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (26.0)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (6.0.3)
Requirement already satisfied: toolz>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (0.12.1)
Requirement already satisfied: pandas>=2.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]==2025.12.0) (2.2.2)
Requirement already satisfied: pyarrow>=14.0.1 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]==2025.12.0) (18.1.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]==2025.12.0) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]==2025.12.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]==2025.12.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]==2025.12.0) (2025.3)
Requirement already satisfied: locket in /usr/local/lib/python3.12/dist-packages (from partd>=1.4.0->dask==2025.12.0->dask[dataframe]==2025.12.0) (1.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0->dask[dataframe]==2025.12.0) (1.17.0)
ERROR: Could not find a version that satisfies the requirement torch==2.9.0+cpu (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.5.0, 2.5.1, 2.6.0, 2.7.0, 2.7.1, 2.8.0, 2.9.0, 2.9.1, 2.10.0)
ERROR: No matching distribution found for torch==2.9.0+cpu
Requirement already satisfied: seaborn==0.13.2 in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from seaborn==0.13.2) (2.0.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from seaborn==0.13.2) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.12/dist-packages (from seaborn==0.13.2) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn==0.13.2) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn==0.13.2) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (1.17.0)

Collecting catboost==1.2.8
  Downloading catboost-1.2.8-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (1.26.4)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost==1.2.8) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost==1.2.8) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost==1.2.8) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost==1.2.8) (9.1.4)
Downloading catboost-1.2.8-cp312-cp312-manylinux2014_x86_64.whl (99.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 MB 5.9 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.8
Collecting pytorch-tabnet2==4.5.3
  Downloading pytorch_tabnet2-4.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting activations-plus>=0.1.1 (from pytorch-tabnet2==4.5.3)
  Downloading activations_plus-0.1.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pytorch-tabnet2==4.5.3) (1.26.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from pytorch-tabnet2==4.5.3) (1.6.1)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from pytorch-tabnet2==4.5.3) (2.10.0+cpu)
Collecting torcheval (from pytorch-tabnet2==4.5.3)
  Downloading torcheval-0.0.7-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->pytorch-tabnet2==4.5.3) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->pytorch-tabnet2==4.5.3) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->pytorch-tabnet2==4.5.3) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (3.24.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (2025.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->pytorch-tabnet2==4.5.3) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->pytorch-tabnet2==4.5.3) (3.0.3)
Downloading pytorch_tabnet2-4.5.3-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.9/70.9 kB 3.0 MB/s eta 0:00:00
Downloading activations_plus-0.1.1-py3-none-any.whl (15 kB)
Downloading torcheval-0.0.7-py3-none-any.whl (179 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.2/179.2 kB 7.9 MB/s eta 0:00:00
Installing collected packages: torcheval, activations-plus, pytorch-tabnet2
Successfully installed activations-plus-0.1.1 pytorch-tabnet2-4.5.3 torcheval-0.0.7

In [ ]:
# Restart the runtime to apply changes
import os
os._exit(00)

# **Imports**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import randint
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.base import BaseEstimator, RegressorMixin
from sklearn.svm import SVR
import ngboost
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor
from gpboost import GPBoostRegressor
from ngboost import NGBRegressor
import optuna
import optunahub
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import HalvingGridSearchCV
from interpret import show
from interpret.blackbox import LimeTabular, ShapKernel
from optuna.samplers import RandomSampler
import random
import time
from ngboost.distns import Normal
from ngboost.scores import LogScore
from scipy.stats import norm
from optuna.samplers import BaseSampler
from optuna.samplers import GridSampler
from optuna.samplers import TPESampler
from optuna.samplers import PartialFixedSampler
from optuna.samplers import CmaEsSampler
from optuna.samplers import QMCSampler
from optuna.samplers import NSGAIIISampler
from optuna.samplers import NSGAIISampler
from optuna.samplers import BruteForceSampler
from optuna.samplers import GPSampler
from interpret import set_visualize_provider
from interpret.provider import InlineProvider
from interpret.glassbox import ExplainableBoostingRegressor
from interpret import show
import plotly.express as px
from io import BytesIO
from openpyxl import Workbook, load_workbook
import os
import properscoring as ps
import io
from openpyxl.drawing.image import Image as openpyxlImage
import warnings
import xlsxwriter
from openpyxl.drawing.image import Image
from pgbm.sklearn import HistGradientBoostingRegressor
import torch
from pgbm.torch import PGBM
import plotly.graph_objects as go
warnings.filterwarnings('ignore')
import pickle
import json
from mapie.subsample import Subsample
from mapie.regression import MapieRegressor
from deel.puncc.metrics import regression_sharpness, regression_mean_coverage
from deel.puncc.api.prediction import BasePredictor, DualPredictor
from deel.puncc.regression import SplitCP, CVPlus, CQR
from deel.puncc.plotting import plot_prediction_intervals
from sklearn.model_selection import train_test_split
from typing_extensions import TypedDict
from typing import Union
from mapie.metrics import regression_coverage_score
from sklearn.model_selection import KFold
from PIL import Image as PImage
from openpyxl.utils.dataframe import dataframe_to_rows
from scipy.stats import genpareto
from pytorch_tabnet import TabNetRegressor
import torch.nn as nn
import warnings
import io
import time
import numpy as np
import pandas as pd
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
from openpyxl import load_workbook
from openpyxl.drawing.image import Image
from openpyxl.utils.dataframe import dataframe_to_rows

In [2]:
# Go to find & replace button and replace (EWQI) with your folder name. Rename your train and test dataset as train.csv and test.csv.
# Modify the names of the feature in the below cell.
# Replace (EWQI) with actual data label name.

In [3]:
feature_names = [
    'pH', 'TDS', 'EC', 'TH', 'Ca', 'Mg', 'CO3', 'HCO3','Na', 'K', 'Chloride', 'Sulphate', 'Nitrate', 'Fluoride'
]

In [4]:
train_data_path = "./drive/MyDrive/EWQI/Data/train.csv"
test_data_path = "./drive/MyDrive/EWQI/Data/test.csv"
train_data = pd.read_csv(train_data_path)
test_data = pd.read_csv(test_data_path)
print("Training data loaded successfully.")
print("Test data loaded successfully.")

Training data loaded successfully.
Test data loaded successfully.

In [5]:
print("\nShape of training data:", train_data.shape)
print("First 5 rows of training data:\n", train_data.head(5))
print("\nShape of test data:", test_data.shape)
print("First 5 rows of test data:\n", test_data.head(5))

Shape of training data: (47, 15)
First 5 rows of training data:
      pH   TDS    EC    TH   ca    mg  CO3  HCO3   NA    K  CHLORIDE  SULPHATE  \
0  7.90   552   865   452  272   180  0.2   4.5  260   44       375       681
1  7.52  1985  2256  1054  529   525  0.0  15.0  272   47       728       324
2  7.65  1865  2032   636  371   265  0.0   9.0  373   25       713       503
3  7.25  4855  7856  2050  795  1255  0.0  12.5  335  106        81       676
4  7.96  2855  3696   865  310   555  0.3   4.6  184  106       698       324

   NITRATE  FLUORIDE  Pre monsoon EWQI
0       60      0.40              70.52
1       10      0.65             138.78
2       54      0.85             113.07
3       17      0.69             266.32
4       25      1.20             158.05

Shape of test data: (47, 15)
First 5 rows of test data:
      pH   TDS    EC    TH     ca      mg  CO3  HCO3   NA    K  CHLORIDE  \
0  8.38   625   975   320  120.0   200.0  0.0   5.8  280   35       398
1  7.31  2020  2860   960  410.0   550.0  0.0  11.0  302   65       765
2  7.80  1630  2380   440  165.0   275.0  0.0   7.0  356   29       745
3  7.06  6300  8910  2356  776.0  1580.0  0.0  10.8  396  112       124
4  4.60  2290  3570  1080  470.0   610.0  0.0   6.2  225  125       745

   SULPHATE  NITRATE  FLUORIDE  Post monsoon EWQI
0       755       75      0.48              73.07
1       365       26      0.71             141.67
2       525       85      0.89             110.44
3       745       24      0.75             275.01
4       336       15      1.35             202.57

In [6]:
X_train = train_data.iloc[:, :-1]
y_train = train_data.iloc[:, -1]
X_test = test_data.iloc[:, :-1]
y_test = test_data.iloc[:, -1]
x_test= X_test
print("\nShape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (47, 14)
Shape of y_train: (47,)
Shape of X_test: (47, 14)
Shape of y_test: (47,)

In [7]:
# Apply z-score normalization
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Print the first five rows of the normalized data
print("\nFirst five rows of normalized X_train:")
print(X_train[:5])

print("\nFirst five rows of normalized X_test:")
print(X_test[:5])

First five rows of normalized X_train:
[[ 0.3797749  -1.15230942 -0.94309903 -0.47923131 -0.09229732 -0.56852482
  -0.03922784 -1.18768739 -0.02713192 -0.87884263 -0.2770724   1.15873613
   1.41276153 -1.25316406]
 [-0.78765707 -0.2953837  -0.52059702  0.45803078  1.31357822  0.10564733
  -0.50015494  1.61405127  0.07159325 -0.77136925  1.29937074 -0.45273785
  -1.61366471 -0.53733141]
 [-0.38827245 -0.36714301 -0.58863473 -0.19275917  0.44926563 -0.40242444
  -0.50015494  0.01305775  0.90253007 -1.55950739  1.23238307  0.35525611
   1.04959038  0.03533472]
 [-1.61714822  1.42085972  1.18034563  2.00871688  2.76868675  1.53215652
  -0.50015494  0.94697063  0.58990037  1.34227396 -1.59003071  1.13616647
  -1.18996504 -0.42279818]
 [ 0.56410627  0.22487128 -0.08321177  0.16377408  0.11557533  0.16427099
   0.19123571 -1.16100417 -0.6523913   1.34227396  1.1653954  -0.45273785
  -0.70573684  1.03750043]]

First five rows of normalized X_test:
[[ 1.85442582 -1.10865585 -0.90968766 -0.68474392 -0.92378791 -0.52944238
  -0.50015494 -0.84080546  0.13741003 -1.20126278 -0.17435797  1.49276715
   2.3206894  -1.02409761]
 [-1.43281685 -0.2744539  -0.33713821  0.31168088  0.66260861  0.15450038
  -0.50015494  0.54672225  0.31840617 -0.12652895  1.46460699 -0.26766661
  -0.64520832 -0.36553157]
 [ 0.07255596 -0.50767165 -0.48293329 -0.49791427 -0.67762293 -0.38288322
  -0.50015494 -0.52060676  0.76266941 -1.41620955  1.37529009  0.45456263
   2.92597465  0.14986794]
 [-2.2008642   2.28496138  1.50048734  2.48513249  2.66475042  2.16724622
  -0.50015494  0.4933558   1.0917533   1.55722072 -1.39799939  1.44762783
  -0.76626537 -0.25099834]
 [-9.75845017 -0.11299546 -0.12148298  0.49851054  0.99082858  0.27174771
  -0.50015494 -0.73407256 -0.31508032  2.02293872  1.37529009 -0.39857066
  -1.31102209  1.46700003]]

# **Functions:**

In [8]:
def get_best_model_params(results, model_name):
    # Map model names to dictionary keys, assuming keys are strings like 'XGBoost' and not objects
    model_keys = {
        'LightGBM': 'LightGBM',
        'XGBoost': 'XGBoost',
        'GPBoost': 'GPBoost',
        'NGBoost': 'NGBoost',
        'GradientBoosting': 'Gradient Boosting',
        'HGBR' : 'HistGradientBoosting',
        'CatBoost' : 'CatBoost',
        'TabNet' : 'TabNet',
        'PGBM' : 'PGBM'
    }

    # Ensure the requested model name is valid
    if model_name not in model_keys:
        raise ValueError(f"Model name '{model_name}' is not recognized. Available models are: {list(model_keys.keys())}")

    # Filter out entries for the specified model
    model_entries = {key: value for key, value in results.items() if key[0] == model_keys[model_name]}

    # Find the entry with the best (lowest) 'best_score'
    best_entry_key, best_entry_value = min(model_entries.items(), key=lambda item: item[1]['best_score'])

    # Return the best hyperparameters
    return best_entry_value['best_params']

In [9]:
class validate:
    @staticmethod
    def coverage(int_pred, y_test):
        return {strat_name: np.mean((y_test.to_numpy() >= int_pred[strat_name][:, 0]) & (y_test.to_numpy() <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred): # Corrected: Removed y_test argument as it's not defined and not used
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        return {strat_name: np.sqrt(mean_squared_error(y_test, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = validate.width(int_pred)
        coverages = validate.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}

    @staticmethod
    def cond_coverage(int_pred, y_test, num_bins=10):
        cond_coverages = {}
        for strat_name in int_pred:
            widths = int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]
            bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
            digitized_widths = np.digitize(widths, bin_edges)
            strategy_cond_coverage = []
            for bin_num in range(1, num_bins + 1):
                indices_in_bin = np.where(digitized_widths == bin_num)[0]
                if len(indices_in_bin) > 0:
                    bin_coverage = np.mean((y_test.to_numpy()[indices_in_bin] >= int_pred[strat_name][indices_in_bin, 0]) & (y_test.to_numpy()[indices_in_bin] <= int_pred[strat_name][indices_in_bin, 1]))
                    strategy_cond_coverage.append(bin_coverage)
                else:
                    strategy_cond_coverage.append(np.nan) # or handle empty bins as needed
            cond_coverages[strat_name] = strategy_cond_coverage
        return cond_coverages


class visualize:
    @staticmethod
    def coverage(int_pred, y_test):
        return {strat_name: np.mean((y_test.to_numpy() >= int_pred[strat_name][:, 0]) & (y_test.to_numpy() <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred):
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        return {strat_name: np.sqrt(mean_squared_error(y_test, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = visualize.width(int_pred)
        coverages = visualize.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}
    @staticmethod
    def goodness(y_true, y_pred, y_pred_low, y_pred_up, coverage, width, rmse, cwc, ax=None, title="Goodness Plot"):
        if ax is None:
            fig, ax = plt.subplots()
        n_samples = len(y_true)
        y_true_np = y_true.to_numpy().ravel() # Ensure y_true is numpy array and flattened

        # Determine points inside and outside the interval
        inside_interval = (y_true_np >= y_pred_low) & (y_true_np <= y_pred_up)
        outside_interval = ~inside_interval

        # Plot points inside the interval in green
        ax.scatter(y_true_np[inside_interval], y_pred[inside_interval], color='green', s=10, label='Inside Interval')
        # Plot points outside the interval in orange
        ax.scatter(y_true_np[outside_interval], y_pred[outside_interval], color='orange', s=10, label='Outside Interval')

        # Plot all ground truth values as blue crosses
        ax.scatter(y_true_np, y_true_np, color='blue', marker='x', s=30, linewidths=0.7, label='Ground Truth Values')


        ax.vlines(y_true_np, y_pred_low, y_pred_up, color='gray', alpha=0.5, label='Prediction Intervals')
        ax.plot([min(y_true_np), max(y_true_np)], [min(y_true_np), max(y_true_np)], linestyle='--', color='blue', label='Ideal Prediction Line') # Changed label for clarity
        ax.set_xlabel('Ground Truth')
        ax.set_ylabel('Predictions')
        ax.set_title(f'{title}\nCoverage: {coverage*100:.2f}%, Width: {width:.2f}, RMSE: {rmse:.2f}, CWC: {cwc:.2f}')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def width_size_occurrence(int_pred, train_intervals, num_bins=10, ax=None, x_lim=None, title="Width Size Occurrence"):
        if ax is None:
            fig, ax = plt.subplots()

        # Calculate interval widths for test and train sets
        widths_test = np.abs(int_pred[:, 1] - int_pred[:, 0])
        widths_train = np.abs(train_intervals[:, 1] - train_intervals[:, 0])

        # Plot histograms for both train and test widths
        ax.hist(widths_test, bins=num_bins, alpha=0.6, label='Test Interval Widths', color='red')
        ax.hist(widths_train, bins=num_bins, alpha=0.4, label='Train Interval Widths', color='blue')


        if x_lim is not None:
            ax.set_xlim(x_lim)
        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Occurrence (Frequency)')
        ax.set_title(f'{title} - Interval Width Occurrence')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def coverage_by_width(y_test, int_pred, miscoverage, cond_coverages, num_bins=10, ax=None, title="Coverage vs Width"):
        if ax is None:
            fig, ax = plt.subplots()

        widths = int_pred[:, 1] - int_pred[:, 0]
        bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
        bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
        bin_width = bin_edges[1] - bin_edges[0]

        ax.bar(bin_centers, cond_coverages, width=bin_width, color='blue', alpha=0.7, edgecolor='black', linewidth=0.8, label='Conditional Coverage')
        ax.axhline(1 - miscoverage, color='red', linestyle='--', label=f'Nominal Coverage ({(1 - miscoverage)*100:.0f}%)')

        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Conditional Coverage')
        ax.set_title(f'{title} - Coverage vs Interval Width')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax


def weighted_quantile(values, weights, q):
    sorter = np.argsort(values)
    values = values[sorter]
    weights = weights[sorter]
    cum_weights = np.cumsum(weights)
    cum_weights = cum_weights / cum_weights[-1]
    return np.interp(q, cum_weights, values)

In [10]:
def conformal_predictions_NEXCP(
    model_class,
    best_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    decay=0.99,
    n_folds=5,
    n_bootstrap=50,
):

    warnings.filterwarnings("ignore")

    SEED = 123
    np.random.seed(SEED)

    strategies_names = {
        "NexCP-Split": "NexCP Split",
        "NexCP-Full": "NexCP Full",
        "NexCP-J+aB": "NexCP Jackknife+ aB",
        "NexCP-CV+": "NexCP CV+",
    }

    y_pred, int_pred = {}, {}

    # =========================================================
    # NexCP – Split
    # =========================================================
    model = model_class(**best_params)
    model.fit(X_train, y_train)

    yhat_train = model.predict(X_train)
    yhat_test = model.predict(X_test)

    res = np.abs(y_train.to_numpy() - yhat_train)
    weights = decay ** np.arange(len(res) - 1, -1, -1)
    q = weighted_quantile(res, weights, 1 - alpha)

    y_pred["NexCP-Split"] = yhat_test
    int_pred["NexCP-Split"] = np.c_[yhat_test - q, yhat_test + q]

    # =========================================================
    # NexCP – Full
    # =========================================================
    model = model_class(**best_params)
    model.fit(X_train, y_train)

    yhat_train = model.predict(X_train)
    yhat_test = model.predict(X_test)

    q = np.quantile(np.abs(y_train.to_numpy() - yhat_train), 1 - alpha)

    y_pred["NexCP-Full"] = yhat_test
    int_pred["NexCP-Full"] = np.c_[yhat_test - q, yhat_test + q]

    # =========================================================
    # NexCP – Jackknife+ after Bootstrap
    # =========================================================
    rng = np.random.default_rng(SEED)
    lowers_t, uppers_t, preds_t = [], [], []

    for _ in range(n_bootstrap):
        idx = rng.choice(len(X_train), len(X_train), replace=True)

        model = model_class(**best_params)
        model.fit(X_train[idx], y_train.iloc[idx])

        yte = model.predict(X_test)

        q = np.quantile(
            np.abs(y_train.iloc[idx].to_numpy() - model.predict(X_train[idx])),
            1 - alpha,
        )

        lowers_t.append(yte - q)
        uppers_t.append(yte + q)
        preds_t.append(yte)

    y_pred["NexCP-J+aB"] = np.mean(preds_t, axis=0)
    int_pred["NexCP-J+aB"] = np.c_[np.min(lowers_t, axis=0), np.max(uppers_t, axis=0)]

    # =========================================================
    # NexCP – CV+
    # =========================================================
    kf = KFold(n_splits=n_folds, shuffle=True, random_state=SEED)

    lowers_t, uppers_t, preds_t = [], [], []

    for tr, cal in kf.split(X_train):
        model = model_class(**best_params)
        model.fit(X_train[tr], y_train.iloc[tr])

        y_cal = model.predict(X_train[cal])
        q = np.quantile(np.abs(y_train.iloc[cal].to_numpy() - y_cal), 1 - alpha)

        yte = model.predict(X_test)

        lowers_t.append(yte - q)
        uppers_t.append(yte + q)
        preds_t.append(yte)

    y_pred["NexCP-CV+"] = np.mean(preds_t, axis=0)
    int_pred["NexCP-CV+"] = np.c_[np.mean(lowers_t, axis=0), np.mean(uppers_t, axis=0)]

    # =========================================================
    # Metrics
    # =========================================================
    def coverage(y, l, u):
        return np.mean((y >= l) & (y <= u))

    def width(l, u):
        return np.mean(u - l)

    def cwc(l, u, y, alpha):
        cov = coverage(y, l, u)
        w = width(l, u)
        penalty = np.exp(-50 * (cov - (1 - alpha)))
        return w * (1 + penalty if cov < (1 - alpha) else 1)

    y_true = y_test.to_numpy()

    summary_rows = []

    print("\n===== NEXCP RESULTS =====")

    for s in strategies_names:
        cov = coverage(y_true, int_pred[s][:, 0], int_pred[s][:, 1])
        wid = width(int_pred[s][:, 0], int_pred[s][:, 1])
        rmse = np.sqrt(mean_squared_error(y_true, y_pred[s]))
        cwc_val = cwc(int_pred[s][:, 0], int_pred[s][:, 1], y_true, alpha)

        summary_rows.append([
            strategies_names[s],
            cov,
            wid,
            rmse,
            cwc_val,
        ])

        print(f"{strategies_names[s]} - Coverage: {cov*100:.3f}% | Width: {wid:.3f}")

    summary_df = pd.DataFrame(
        summary_rows,
        columns=["Strategy", "Coverage", "Width", "RMSE", "CWC"],
    )

    # =========================================================
    # Plotting (SAVE ONLY — NO SHOW)
    # =========================================================
    idx = np.arange(len(y_test))
    plot_buffers = {}

    for s in strategies_names:
        fig, ax = plt.subplots(figsize=(10, 4))

        ax.scatter(idx, y_test, color="blue", s=10, alpha=0.7, label="True")
        ax.fill_between(
            idx,
            int_pred[s][:, 0],
            int_pred[s][:, 1],
            color="gray",
            alpha=0.5,
            label="Prediction interval",
        )
        ax.plot(idx, y_pred[s], color="red", linewidth=1, label="Predicted mean")

        ax.set_title(strategies_names[s])
        ax.set_xlabel("Sample Number")
        ax.set_ylabel("EWQI")
        ax.legend(loc="upper left")

        plt.tight_layout()

        buf = io.BytesIO()
        fig.savefig(buf, format="png")
        buf.seek(0)
        plot_buffers[s] = buf

        plt.close(fig)

    # =========================================================
    # Excel Export
    # =========================================================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary sheet ----
        sheet_name = "NEXCP_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name, 0)
        for r_idx, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c_idx, val in enumerate(row, 1):
                ws.cell(row=r_idx, column=c_idx, value=val)

        # ---- Plot sheets ----
        for s, buf in plot_buffers.items():
            img = Image(buf)

            sheet_name = f"NEXCP_Plot_{s}"
            base = sheet_name
            i = 1
            while sheet_name in wb.sheetnames:
                sheet_name = f"{base}_{i}"
                i += 1

            ws = wb.create_sheet(sheet_name)
            ws.add_image(img, "A1")

        # ---- Values sheet ----
        results_dict = {}
        for s in strategies_names:
            results_dict[f"{s}_true"] = y_true
            results_dict[f"{s}_pred"] = y_pred[s]
            results_dict[f"{s}_lower"] = int_pred[s][:, 0]
            results_dict[f"{s}_upper"] = int_pred[s][:, 1]

        df_vals = pd.DataFrame(results_dict)

        sheet_name = "NEXCP_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r_idx, row in enumerate(dataframe_to_rows(df_vals, index=False, header=True), 1):
            for c_idx, val in enumerate(row, 1):
                ws.cell(row=r_idx, column=c_idx, value=val)

        wb.save(excel_file_path)

    return summary_df

In [11]:
def conformal_predictions_online_super(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    strategies="all",
    window_min=50,
    window_max=500,
    window_grid=(25, 50, 100, 200, 400),
    n_bootstrap=30,
):

    warnings.filterwarnings("ignore")

    SEED = 123
    np.random.seed(SEED)

    STRATEGY_NAMES = {
        "Online-Split": "Online Split",
        "Online-CV+": "Online CV+",
        "Online-J+aB": "Online Jackknife+ aB",
        "SAOCP": "SAOCP",
        "SF-OGD": "SF-OGD",
        "FACI": "FACI",
        "MFCS-Split": "MFCS Split",
        "MFCS-Full": "MFCS Full",
    }

    ALL_STRATEGIES = list(STRATEGY_NAMES.keys())
    if strategies == "all":
        strategies = ALL_STRATEGIES

    # =========================================================
    # Base model
    # =========================================================
    base_model = model_class(**model_params)
    base_model.fit(X_train, y_train)

    yhat_train = base_model.predict(X_train)

    X_all = np.vstack([X_train, X_test])
    y_all = np.concatenate([y_train.to_numpy(), y_test.to_numpy()])

    n_train = len(X_train)
    T = len(y_all)

    y_hat_all = np.zeros(T)
    y_hat_all[:n_train] = yhat_train
    for t in range(n_train, T):
        y_hat_all[t] = base_model.predict(X_all[t:t + 1])[0]

    residuals = np.abs(y_all - y_hat_all)

    y_pred, int_pred = {}, {}

    # =========================================================
    # Online methods (UNCHANGED LOGIC)
    # =========================================================
    if "Online-Split" in strategies:
        q = np.quantile(residuals[:n_train], 1 - alpha)
        y_pred["Online-Split"] = y_hat_all[n_train:]
        int_pred["Online-Split"] = np.c_[y_hat_all[n_train:] - q,
                                         y_hat_all[n_train:] + q]

    if "Online-CV+" in strategies:
        lower, upper = [], []
        for t in range(n_train, T):
            q = np.quantile(residuals[:t], 1 - alpha)
            lower.append(y_hat_all[t] - q)
            upper.append(y_hat_all[t] + q)
        y_pred["Online-CV+"] = y_hat_all[n_train:]
        int_pred["Online-CV+"] = np.c_[lower, upper]

    if "Online-J+aB" in strategies:
        lowers, uppers, preds = [], [], []
        for _ in range(n_bootstrap):
            idx = np.random.choice(n_train, n_train, replace=True)
            m = model_class(**model_params)
            m.fit(X_train[idx], y_train.iloc[idx])
            res = np.abs(y_train.iloc[idx] - m.predict(X_train[idx]))
            q = np.quantile(res, 1 - alpha)
            p = m.predict(X_test)
            preds.append(p)
            lowers.append(p - q)
            uppers.append(p + q)
        y_pred["Online-J+aB"] = np.mean(preds, axis=0)
        int_pred["Online-J+aB"] = np.c_[np.min(lowers, axis=0),
                                        np.max(uppers, axis=0)]

    if "SAOCP" in strategies:
        lower, upper = [], []
        for t in range(n_train, T):
            w = min(max(window_min, t // 2), window_max)
            start = max(0, t - w)
            q = np.quantile(residuals[start:t], 1 - alpha)
            lower.append(y_hat_all[t] - q)
            upper.append(y_hat_all[t] + q)
        y_pred["SAOCP"] = y_hat_all[n_train:]
        int_pred["SAOCP"] = np.c_[lower, upper]

    if "SF-OGD" in strategies:
        q_t = np.quantile(residuals[:n_train], 1 - alpha)
        lower, upper = [], []
        for t in range(n_train, T):
            r_t = residuals[t]
            grad = alpha - (r_t <= q_t)
            eta = 1.0 / np.sqrt(t - n_train + 1)
            q_t = max(0.0, q_t - eta * grad)
            lower.append(y_hat_all[t] - q_t)
            upper.append(y_hat_all[t] + q_t)
        y_pred["SF-OGD"] = y_hat_all[n_train:]
        int_pred["SF-OGD"] = np.c_[lower, upper]

    if "FACI" in strategies:
        windows = list(window_grid)
        losses = np.zeros(len(windows))
        lower, upper = [], []
        for t in range(n_train, T):
            r_t = residuals[t]
            qs = []
            for i, w in enumerate(windows):
                start = max(0, t - w)
                q = np.quantile(residuals[start:t], 1 - alpha)
                qs.append(q)
                losses[i] += alpha * q + (r_t - q) * (r_t > q)
            q_star = qs[np.argmin(losses)]
            lower.append(y_hat_all[t] - q_star)
            upper.append(y_hat_all[t] + q_star)
        y_pred["FACI"] = y_hat_all[n_train:]
        int_pred["FACI"] = np.c_[lower, upper]

    if "MFCS-Split" in strategies:
        q = np.quantile(residuals[:n_train], 1 - alpha)
        y_pred["MFCS-Split"] = y_hat_all[n_train:]
        int_pred["MFCS-Split"] = np.c_[y_hat_all[n_train:] - q,
                                       y_hat_all[n_train:] + q]

    if "MFCS-Full" in strategies:
        lower, upper, preds = [], [], []
        for t in range(n_train, T):
            m = model_class(**model_params)
            m.fit(X_all[:t], y_all[:t])
            yhat = m.predict(X_all[t:t + 1])[0]
            preds.append(yhat)
            res = np.abs(y_all[:t] - m.predict(X_all[:t]))
            q = np.quantile(res, 1 - alpha)
            lower.append(yhat - q)
            upper.append(yhat + q)
        y_pred["MFCS-Full"] = np.array(preds)
        int_pred["MFCS-Full"] = np.c_[lower, upper]

    # =========================================================
    # METRICS
    # =========================================================
    y_true = y_test.to_numpy().ravel()

    rows = []
    for s in y_pred:
        ymin, ymax = int_pred[s].T
        cov = np.mean((y_true >= ymin) & (y_true <= ymax))
        wid = np.mean(ymax - ymin)
        rmse = np.sqrt(mean_squared_error(y_true, y_pred[s]))
        cwc = wid * (1 + (cov < (1 - alpha)) * (1 - cov))

        rows.append([STRATEGY_NAMES[s], cov, wid, rmse, cwc])

    summary_df = pd.DataFrame(
        rows, columns=["Strategy", "Coverage", "Width", "RMSE", "CWC"]
    )

    print("\n===== ONLINE CP RESULTS =====")
    print(summary_df)

    # =========================================================
    # PLOTTING (SAVE ONLY)
    # =========================================================
    plot_buffers = {}
    idx = np.arange(len(y_test))

    for s in y_pred:
        fig, ax = plt.subplots(figsize=(10, 4))

        ax.scatter(idx, y_true, color="blue", s=10, alpha=0.7, label="True")
        ax.fill_between(idx,
                        int_pred[s][:, 0],
                        int_pred[s][:, 1],
                        color="gray",
                        alpha=0.5,
                        label="Prediction interval")
        ax.plot(idx, y_pred[s], color="red", linewidth=1, label="Predicted mean")

        ax.set_title(f"{STRATEGY_NAMES[s]} ({model_name})")
        ax.set_xlabel("Sample Number")
        ax.set_ylabel("EWQI")
        ax.legend(loc="upper left")

        plt.tight_layout()

        buf = io.BytesIO()
        fig.savefig(buf, format="png")
        buf.seek(0)
        plot_buffers[s] = buf

        plt.close(fig)

    # =========================================================
    # EXCEL EXPORT (APPEND SAFE)
    # =========================================================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary ----
        sheet_name = "ONLINECP_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plots ----
        for s, buf in plot_buffers.items():
            img = Image(buf)
            sheet_name = f"ONLINECP_Plot_{s}"
            base = sheet_name
            i = 1
            while sheet_name in wb.sheetnames:
                sheet_name = f"{base}_{i}"
                i += 1
            ws = wb.create_sheet(sheet_name)
            ws.add_image(img, "A1")

        # ---- Values ----
        values = {}
        for s in y_pred:
            values[f"{s}_true"] = y_true
            values[f"{s}_pred"] = y_pred[s]
            values[f"{s}_lower"] = int_pred[s][:, 0]
            values[f"{s}_upper"] = int_pred[s][:, 1]

        df_vals = pd.DataFrame(values)

        sheet_name = "ONLINECP_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(df_vals, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)

    return summary_df

In [12]:
def conformal_predictions_COP(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    lr=0.05,          # Learning rate for COP
    T_burnin=50,      # Window size for distribution estimation
    scale=0.5,        # Scale factor for the integrator
    random_state=123,
):
    """
    Conformal Optimistic Prediction (COP)
    ✔ Implements the Distribution-Informed Gradient logic from the repository.
    ✔ Matches the "Excel-safe" and plotting structure of your previous functions.
    """

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)

    # =========================================================
    # 1. Train Base Model & Generate Test Predictions
    # =========================================================
    # COP is an online calibration method, but we usually start with a pre-trained model
    # or an online model. Here we fit on Train and calibrate on Test stream.
    model = model_class(**model_params)
    model.fit(X_train, y_train)

    # Predict on test set
    y_pred_test = model.predict(X_test).ravel()
    y_true_test = y_test.to_numpy().ravel()

    # Calculate non-conformity scores (Absolute Residuals)
    # This assumes symmetric intervals.
    scores = np.abs(y_true_test - y_pred_test)
    T_test = len(scores)

    # =========================================================
    # 2. COP Initialization
    # =========================================================
    # Initialize quantiles based on training data residuals if possible
    y_pred_train = model.predict(X_train).ravel()
    scores_train = np.abs(y_train.to_numpy().ravel() - y_pred_train)
    init_q = np.quantile(scores_train, 1 - alpha)

    # Arrays to store history
    qs = np.zeros(T_test)          # Final adaptive quantile
    qts = np.zeros(T_test)         # Base quantile term
    integrators = np.zeros(T_test) # Optimistic integrator term
    covereds = np.zeros(T_test)    # Coverage boolean

    # Set initial values
    qs[0] = init_q
    qts[0] = init_q

    # =========================================================
    # 3. Online COP Loop
    # =========================================================
    # Logic adapted from `core/methods.py` function `COP`

    for t in range(T_test - 1):
        # 1. Observe coverage at current step t
        covereds[t] = 1 if qs[t] >= scores[t] else 0

        # 2. Calculate Standard Gradient
        # If covered, we decrease q (grad is positive). If not, increase q.
        grad = alpha if covereds[t] else -(1 - alpha)

        # 3. Calculate Distribution-Informed Gradient (The "Optimistic" part)
        if t < T_burnin:
            grad_i = 0
        else:
            # Look at the window of recent scores
            window_s = scores[t - T_burnin : t]

            # Calculate ECDF at the predicted next quantile step
            # logic: np.mean(window_s <= qts[t] - lr * grad) - (1 - alpha)
            current_target = qts[t] - lr * grad
            grad_i = np.mean(window_s <= current_target) - (1 - alpha)

        # 4. Update Terms
        integrator = -scale * grad_i

        # Update base quantile (Gradient Descent)
        qts[t + 1] = qts[t] - lr * grad

        # Update integrator state
        integrators[t + 1] = lr * integrator

        # Combine for final quantile
        qs[t + 1] = qts[t + 1] + integrators[t + 1]

        # Safety: Ensure quantile implies non-negative width
        qs[t + 1] = max(0, qs[t + 1])

    # Handle the final step coverage for metrics
    covereds[-1] = 1 if qs[-1] >= scores[-1] else 0

    # =========================================================
    # 4. Construct Prediction Intervals
    # =========================================================
    ymin = y_pred_test - qs
    ymax = y_pred_test + qs

    # =========================================================
    # 5. Metrics
    # =========================================================
    rmse = np.sqrt(mean_squared_error(y_true_test, y_pred_test))
    coverage = np.mean(covereds)
    avg_width = np.mean(ymax - ymin)

    print(f"\n===== CONFORMAL OPTIMISTIC PREDICTION ({model_name}) =====")
    print(f"Coverage : {coverage*100:.3f}%")
    print(f"Avg Width: {avg_width:.3f}")
    print(f"RMSE     : {rmse:.3f}")
    print(f"Final q  : {qs[-1]:.3f}")

    # =========================================================
    # 6. Summary Tables
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy": "COP",
        "Coverage": coverage,
        "Width": avg_width,
        "RMSE": rmse,
        "Alpha": alpha,
        "LR": lr,
        "Scale": scale
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(y_true_test)),
        "y_true": y_true_test,
        "y_pred": y_pred_test,
        "ymin": ymin,
        "ymax": ymax,
        "width": ymax - ymin,
        "is_covered": covereds.astype(int),
        "score_residual": scores,
        "adaptive_q": qs
    })

    # =========================================================
    # 7. Plotting
    # =========================================================
    idx = np.arange(len(y_true_test))
    fig, ax = plt.subplots(figsize=(10, 4))

    ax.scatter(idx, y_true_test, color="blue", s=10, alpha=0.7, label="True")
    ax.fill_between(idx, ymin, ymax, color="gray", alpha=0.5, label="COP Interval")
    ax.plot(idx, y_pred_test, color="red", linewidth=1, label="Predicted mean")

    ax.set_title(f"Conformal Optimistic Prediction (COP) - {model_name}")
    ax.set_xlabel("Sample Number")
    ax.set_ylabel("EWQI")
    ax.legend(loc="upper left")

    plt.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    buf.seek(0)
    plt.close(fig)

    # =========================================================
    # 8. Excel Export
    # =========================================================
    if excel_file_path:
        try:
            wb = load_workbook(excel_file_path)
        except FileNotFoundError:
            # Create a new workbook if it doesn't exist
            from openpyxl import Workbook
            wb = Workbook()
            wb.remove(wb.active) # Remove default sheet

        # ---- Summary ----
        sheet_name = "COP_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot ----
        img = Image(buf)
        sheet_name = "COP_Plot"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "COP_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)

    return summary_df

In [13]:
def conformal_predictions_EXTREME(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    calib_size=0.2,
    gpd_threshold_quantile=0.95,
    n_bootstrap=30,
    random_state=123,
):
    """
    Extreme Conformal Prediction (upper-tail, single-sided)
    ✔ Same structure as NexCP & OnlineCP
    ✔ No return values
    ✔ Excel-safe
    """

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)

    # =========================================================
    # Train / calibration split
    # =========================================================
    X_fit, X_calib, y_fit, y_calib = train_test_split(
        X_train,
        y_train,
        test_size=calib_size,
        random_state=random_state,
        shuffle=True,
    )

    # =========================================================
    # Train model
    # =========================================================
    model = model_class(**model_params)
    model.fit(X_fit, y_fit)

    y_pred_test = model.predict(X_test).ravel()
    y_pred_calib = model.predict(X_calib).ravel()

    # =========================================================
    # Nonconformity scores (upper tail only)
    # =========================================================
    scores = y_calib.to_numpy().ravel() - y_pred_calib
    scores = scores[scores > 0]

    if len(scores) < 30:
        raise RuntimeError("Too few calibration exceedances for GPD fitting.")

    # =========================================================
    # Peaks-over-threshold
    # =========================================================
    u = np.quantile(scores, gpd_threshold_quantile)
    excesses = scores[scores > u] - u

    # =========================================================
    # Bootstrap GPD extreme quantile
    # =========================================================
    boot_q = []
    n_exc = len(excesses)
    n_scores = len(scores)

    for _ in range(n_bootstrap):
        resampled = np.random.choice(excesses, size=n_exc, replace=True)
        xi_b, _, sigma_b = genpareto.fit(resampled, floc=0)

        q_b = (
            u
            + (sigma_b / xi_b)
            * ((n_scores / (n_scores * alpha)) ** xi_b - 1)
        )
        boot_q.append(q_b)

    q_extreme = np.quantile(boot_q, 0.95)

    # =========================================================
    # Finite prediction intervals (for plotting & width)
    # =========================================================
    ymin = y_pred_test - q_extreme
    ymax = y_pred_test + q_extreme

    # =========================================================
    # Metrics
    # =========================================================
    y_true = y_test.to_numpy().ravel()

    rmse = np.sqrt(mean_squared_error(y_true, y_pred_test))
    coverage = np.mean(y_true <= ymax)
    width = q_extreme  # meaningful one-sided width

    print(f"\n===== EXTREME CONFORMAL PREDICTION ({model_name}) =====")
    print(f"Coverage : {coverage*100:.3f}%")
    print(f"Width    : {width:.3f}")
    print(f"RMSE     : {rmse:.3f}")
    print(f"q_extreme: {q_extreme:.3f}")
    print(f"u        : {u:.3f}")
    print(f"#Exceed. : {len(scores)}")

    # =========================================================
    # Summary table
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy": "EXTREME CP",
        "Coverage": coverage,
        "Width": width,
        "RMSE": rmse,
        "q_extreme": q_extreme,
        "threshold_u": u,
        "n_exceedances": len(scores),
    }])

    # =========================================================
    # Values table
    # =========================================================
    values_df = pd.DataFrame({
        "sample_index": np.arange(len(y_true)),
        "y_true": y_true,
        "y_pred": y_pred_test,
        "ymin": ymin,
        "ymax": ymax,
        "width": ymax - ymin,
        "is_covered": (y_true <= ymax).astype(int),
        "residual": y_true - y_pred_test,
    })

    # =========================================================
    # Plot (SAVE ONLY)
    # =========================================================
    idx = np.arange(len(y_true))

    fig, ax = plt.subplots(figsize=(10, 4))
    ax.scatter(idx, y_true, s=10, alpha=0.7, label="True")
    ax.fill_between(idx, ymin, ymax, alpha=0.4, label="Extreme PI")
    ax.plot(idx, y_pred_test, color="red", lw=1, label="Prediction")

    ax.set_title(f"Extreme Conformal Prediction ({model_name})")
    ax.set_xlabel("Sample Number")
    ax.set_ylabel("EWQI")
    ax.legend(loc="upper left")

    plt.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    buf.seek(0)
    plt.close(fig)

    # =========================================================
    # Excel export (append-safe, SAME FILE)
    # =========================================================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary ----
        sheet_name = "EXTREMECP_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot ----
        img = Image(buf)
        sheet_name = "EXTREMECP_Plot"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "EXTREMECP_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)

In [14]:


try:
    from tqdm.auto import tqdm
    HAS_TQDM = True
except ImportError:
    HAS_TQDM = False
    print("[Info] Install tqdm for progress bars: pip install tqdm")


# ═══════════════════════════════════════════════════════════
# AlphaNet Architecture  (FIXED)
# ═══════════════════════════════════════════════════════════
class AlphaNet(nn.Module):
    """
    Maps a feature vector (sum of LOO scores) → learned α̃.
    Output is clamped to (alpha_min, 1) so that the conformal
    denominator α̃·(n+1)−1 is always positive.
    """

    def __init__(self, input_dim, alpha_min=0.05):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, 32)
        self.fc2 = nn.Linear(32, 1)
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()
        self.alpha_min = alpha_min  # lower bound for valid α̃
        self._initialize_near_one()

    def _initialize_near_one(self):
        """Bias output toward α̃ ≈ 1 at init (sigmoid(5) ≈ 0.993)."""
        with torch.no_grad():
            self.fc2.weight.data.normal_(0, 0.01)
            self.fc2.bias.data.fill_(5.0)

    def forward(self, x):
        x = self.relu(self.fc1(x))
        raw = self.sigmoid(self.fc2(x)).squeeze(-1)
        # Remap from (0,1) → (alpha_min, 1) so denominator stays positive
        return self.alpha_min + (1.0 - self.alpha_min) * raw


def _interval_size(scores, alpha, eps=1e-8):
    """
    Conformal interval width = 2 * Σscores / (α̃·(n+1) − 1).
    Denominator is clamped to be strictly positive.
    """
    n = len(scores)
    denom = alpha * (n + 1) - 1
    denom = torch.clamp(denom, min=eps)   # ← KEY FIX: prevent negative/zero
    r = scores.sum() / denom
    return 2 * r


def _fmt_time(seconds):
    """Format seconds into human-readable string."""
    if seconds < 60:
        return f"{seconds:.0f}s"
    elif seconds < 3600:
        return f"{seconds/60:.1f}min"
    else:
        return f"{seconds/3600:.1f}hr"


# ═══════════════════════════════════════════════════════════
# Main function  (CORRECTED + PROGRESS TRACKING)
# ═══════════════════════════════════════════════════════════
def conformal_predictions_AlphaNet(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    lambda_reg=20.0,
    num_epochs=50,
    batch_size=32,
    lr_alpha=1e-3,
    calib_fraction=0.5,
    num_runs=4,
    random_state=123,
):
    """
    Learned-α Conformal Prediction via AlphaNet.
    - FIXED: α̃ clamped to valid range (no negative intervals)
    - FIXED: LOO scores precomputed (massive speedup)
    - ADDED: tqdm progress bars + ETA estimates
    """

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)
    torch.manual_seed(random_state)
    device = "cuda" if torch.cuda.is_available() else "cpu"

    t_start_total = time.time()

    # --- numpy-ify if pandas ---
    y_train_np = y_train.to_numpy().ravel() if hasattr(y_train, "to_numpy") else np.asarray(y_train).ravel()
    y_test_np  = y_test.to_numpy().ravel()  if hasattr(y_test,  "to_numpy") else np.asarray(y_test).ravel()
    X_train_np = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    X_test_np  = X_test.to_numpy()  if hasattr(X_test,  "to_numpy") else np.asarray(X_test)

    # =================================================================
    # 1.  Split training data → fit + calibration
    # =================================================================
    n_total = len(X_train_np)
    n_fit   = int(n_total * (1 - calib_fraction))
    perm    = np.random.permutation(n_total)

    fit_idx   = perm[:n_fit]
    calib_idx = perm[n_fit:]

    X_fit,   y_fit   = X_train_np[fit_idx],   y_train_np[fit_idx]
    X_calib, y_calib = X_train_np[calib_idx],  y_train_np[calib_idx]
    n_calib = len(X_calib)

    # Compute alpha_min: must satisfy α̃·(n+1) − 1 > 0  →  α̃ > 1/(n+1)
    alpha_min = 1.0 / (n_calib + 1) + 0.01   # small margin above threshold
    print(f"  [Info] n_calib={n_calib} | alpha_min={alpha_min:.4f}")

    # =================================================================
    # 2.  Train base regression model
    # =================================================================
    print(f"  [Step 2/9] Training base {model_name} model...")
    t0 = time.time()
    base_model = model_class(**model_params)
    base_model.fit(X_fit, y_fit)
    print(f"  [Step 2/9] Done in {_fmt_time(time.time()-t0)}")

    # =================================================================
    # 3.  PRECOMPUTE all LOO scores  (KEY SPEEDUP)
    # =================================================================
    print(f"  [Step 3/9] Precomputing {n_calib} LOO score vectors...")
    t0 = time.time()

    precomputed_scores = []
    precomputed_sums   = []

    iterator = tqdm(range(n_calib), desc="    LOO precompute", leave=False) if HAS_TQDM else range(n_calib)

    for i in iterator:
        loo_X = np.delete(X_calib, i, axis=0)
        loo_y = np.delete(y_calib, i, axis=0)
        scores_loo = np.abs(base_model.predict(loo_X).ravel() - loo_y)

        scores_tensor = torch.tensor(scores_loo, dtype=torch.float32).to(device)
        precomputed_scores.append(scores_tensor)
        precomputed_sums.append(scores_loo.sum())

    elapsed_precompute = time.time() - t0
    print(f"  [Step 3/9] Done in {_fmt_time(elapsed_precompute)}")

    # Build feature matrix (sum of LOO scores per sample)
    X_alpha = torch.tensor(
        np.array(precomputed_sums).reshape(-1, 1),
        dtype=torch.float32,
    ).to(device)

    # =================================================================
    # 4.  Train AlphaNet (multiple runs, keep best)
    # =================================================================
    print(f"  [Step 4/9] Training AlphaNet: {num_runs} runs × {num_epochs} epochs")

    best_net   = None
    best_loss  = np.inf
    history    = {"losses": [], "sizes": [], "alphas": []}

    t0_train = time.time()

    for run in range(num_runs):
        np.random.seed(run)
        torch.manual_seed(run)

        alpha_net = AlphaNet(input_dim=1, alpha_min=alpha_min).to(device)
        optimizer = optim.Adam(alpha_net.parameters(), lr=lr_alpha)

        dataset = TensorDataset(X_alpha, torch.arange(n_calib))
        loader  = DataLoader(dataset, batch_size=batch_size, shuffle=True)

        run_losses, run_sizes, run_alphas = [], [], []

        epoch_iter = (
            tqdm(range(num_epochs), desc=f"    Run {run+1}/{num_runs}", leave=False)
            if HAS_TQDM else range(num_epochs)
        )

        for epoch in epoch_iter:
            t_epoch_start = time.time()
            epoch_loss = epoch_size = epoch_alpha = 0.0

            for x_batch, idx_batch in loader:
                x_batch = x_batch.to(device)
                alpha_pred = alpha_net(x_batch)

                batch_sizes = []
                for j, idx in enumerate(idx_batch):
                    # USE PRECOMPUTED scores instead of calling predict()
                    scores_t = precomputed_scores[idx.item()]
                    size_j = _interval_size(scores_t, alpha_pred[j])
                    batch_sizes.append(size_j)

                batch_sizes = torch.stack(batch_sizes)
                loss = (batch_sizes + lambda_reg * alpha_pred).mean()

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

                epoch_loss  += loss.item()
                epoch_size  += batch_sizes.mean().item()
                epoch_alpha += alpha_pred.mean().item()

            n_batches = len(loader)
            run_losses.append(epoch_loss  / n_batches)
            run_sizes.append(epoch_size   / n_batches)
            run_alphas.append(epoch_alpha / n_batches)

            epoch_time = time.time() - t_epoch_start

            if epoch % 10 == 0 or epoch == num_epochs - 1:
                epochs_done = (run * num_epochs) + epoch + 1
                epochs_total = num_runs * num_epochs
                elapsed_train = time.time() - t0_train
                eta = (elapsed_train / epochs_done) * (epochs_total - epochs_done)

                print(
                    f"  λ={lambda_reg} | Run {run+1}/{num_runs} | "
                    f"Epoch {epoch}/{num_epochs} | "
                    f"Loss: {run_losses[-1]:.4f} | "
                    f"Size: {run_sizes[-1]:.4f} | "
                    f"α̃: {run_alphas[-1]:.4f} | "
                    f"⏱ {epoch_time:.2f}s/epoch | "
                    f"ETA: {_fmt_time(eta)}"
                )

        if run_losses[-1] < best_loss:
            best_loss = run_losses[-1]
            best_net  = alpha_net

        history["losses"].append(run_losses)
        history["sizes"].append(run_sizes)
        history["alphas"].append(run_alphas)

        print(f"  ✓ Run {run+1} complete | Final loss: {run_losses[-1]:.4f}")

    train_time = time.time() - t0_train
    print(f"  [Step 4/9] Training done in {_fmt_time(train_time)}")

    alpha_net = best_net
    alpha_net.eval()

    # =================================================================
    # 5.  Compute conformal intervals on the TEST set
    # =================================================================
    print(f"  [Step 5/9] Computing conformal intervals on test set...")

    scores_calib = np.abs(base_model.predict(X_calib).ravel() - y_calib)
    sum_scores   = scores_calib.sum()

    with torch.no_grad():
        feat_test = torch.tensor([sum_scores], dtype=torch.float32).to(device)
        alpha_val = alpha_net(feat_test).item()

    denom = alpha_val * (n_calib + 1) - 1
    if denom <= 0:
        q = np.quantile(scores_calib, 1 - alpha)
        half_width = q
        print(f"  [Warning] α̃ too small (denom={denom:.4f}); fallback q={q:.4f}")
    else:
        half_width = sum_scores / denom

    y_pred_test = base_model.predict(X_test_np).ravel()
    ymin = y_pred_test - half_width
    ymax = y_pred_test + half_width

    # =================================================================
    # 6.  Metrics
    # =================================================================
    y_true_test = y_test_np
    is_covered  = ((y_true_test >= ymin) & (y_true_test <= ymax)).astype(int)
    coverage    = is_covered.mean()
    avg_width   = np.mean(ymax - ymin)
    rmse        = np.sqrt(mean_squared_error(y_true_test, y_pred_test))

    total_time = time.time() - t_start_total

    print(f"\n{'='*55}")
    print(f"  ALPHANET CONFORMAL ({model_name})")
    print(f"{'='*55}")
    print(f"  Learned α̃     : {alpha_val:.4f}")
    print(f"  Half-width (r) : {half_width:.4f}")
    print(f"  Coverage       : {coverage*100:.3f}%")
    print(f"  Avg Width      : {avg_width:.4f}")
    print(f"  RMSE           : {rmse:.4f}")
    print(f"  Total time     : {_fmt_time(total_time)}")
    print(f"    ├─ Precompute: {_fmt_time(elapsed_precompute)}")
    print(f"    └─ Training  : {_fmt_time(train_time)}")
    print(f"{'='*55}")

    # =================================================================
    # 7.  Summary & values DataFrames
    # =================================================================
    summary_df = pd.DataFrame([{
        "Strategy":       "AlphaNet Conformal",
        "Coverage":       coverage,
        "Width":          avg_width,
        "RMSE":           rmse,
        "Alpha_nominal":  alpha,
        "Alpha_learned":  alpha_val,
        "Lambda_reg":     lambda_reg,
        "Total_time_sec": round(total_time, 2),
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(y_true_test)),
        "y_true":       y_true_test,
        "y_pred":       y_pred_test,
        "ymin":         ymin,
        "ymax":         ymax,
        "width":        ymax - ymin,
        "is_covered":   is_covered,
    })

    # =================================================================
    # 8.  Plotting (SAVE ONLY — NO SHOW)
    # =================================================================
    print(f"  [Step 8/9] Generating plots...")
    idx = np.arange(len(y_true_test))

    # --- PI plot ---
    fig_pi, ax_pi = plt.subplots(figsize=(10, 4))
    ax_pi.scatter(idx, y_true_test, color="blue", s=10, alpha=0.7, label="True")
    ax_pi.fill_between(idx, ymin, ymax, color="gray", alpha=0.5,
                       label=f"AlphaNet Interval (α̃={alpha_val:.3f})")
    ax_pi.plot(idx, y_pred_test, color="red", linewidth=1, label="Predicted mean")
    ax_pi.set_title(f"AlphaNet Conformal – {model_name}")
    ax_pi.set_xlabel("Sample Number")
    ax_pi.set_ylabel("EWQI")
    ax_pi.legend(loc="upper left")
    plt.tight_layout()

    buf_pi = io.BytesIO()
    fig_pi.savefig(buf_pi, format="png")
    buf_pi.seek(0)
    plt.close(fig_pi)

    # --- Training curves ---
    arr_losses = np.array(history["losses"])
    arr_sizes  = np.array(history["sizes"])
    arr_alphas = np.array(history["alphas"])
    epochs_arr = np.arange(1, num_epochs + 1)

    fig_tc, axs = plt.subplots(1, 3, figsize=(14, 4))
    for ax, data, ylabel, title in zip(
        axs,
        [arr_losses, arr_sizes, arr_alphas],
        ["Loss", "Mean Interval Size", r"Mean $\tilde{\alpha}$"],
        ["Training Loss", "Interval Size", r"Learned $\tilde{\alpha}$"],
    ):
        m = data.mean(axis=0)
        s = data.std(axis=0)
        ax.plot(epochs_arr, m, color="#0077bb")
        ax.fill_between(epochs_arr, m - s, m + s, color="#0077bb", alpha=0.25)
        ax.set_xlabel("Epoch")
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.grid(True, linewidth=0.5)
    plt.tight_layout()

    buf_tc = io.BytesIO()
    fig_tc.savefig(buf_tc, format="png")
    buf_tc.seek(0)
    plt.close(fig_tc)

    # =================================================================
    # 9.  Excel Export
    # =================================================================
    if excel_file_path:
        print(f"  [Step 9/9] Saving to Excel...")
        try:
            wb = load_workbook(excel_file_path)
        except FileNotFoundError:
            from openpyxl import Workbook
            wb = Workbook()
            wb.remove(wb.active)

        def _unique_sheet(wb, name):
            base, i = name, 1
            while name in wb.sheetnames:
                name = f"{base}_{i}"; i += 1
            return name

        sn = _unique_sheet(wb, "AlphaNet_Summary")
        ws = wb.create_sheet(sn, 0)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        sn = _unique_sheet(wb, "AlphaNet_Plot_PI")
        ws = wb.create_sheet(sn)
        ws.add_image(Image(buf_pi), "A1")

        sn = _unique_sheet(wb, "AlphaNet_Plot_Train")
        ws = wb.create_sheet(sn)
        ws.add_image(Image(buf_tc), "A1")

        sn = _unique_sheet(wb, "AlphaNet_Values")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)
        print(f"  [Step 9/9] Saved!")

    print(f"\n  ✅ AlphaNet Conformal complete in {_fmt_time(total_time)}")
    return summary_df

# **Tuned Parameters**

In [15]:
best_scores_autosampler = {('Random Forest', 'MedianPruner'): {'best_score': 496.77749759305107,
  'best_params': {'n_estimators': 500,
   'criterion': 'squared_error',
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.0},
  'test_mse': 496.77749759305107,
  'test_rmse': 22.288505952464625,
  'test_corr_coef': 0.956804497169129,
  'pruner': 'MedianPruner'},
 ('Random Forest', 'NopPruner'): {'best_score': 497.17260666013107,
  'best_params': {'n_estimators': 500,
   'criterion': 'squared_error',
   'max_depth': None,
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_features': 0.5,
   'max_leaf_nodes': 200,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.1},
  'test_mse': 497.17260666013107,
  'test_rmse': 22.297367706976782,
  'test_corr_coef': 0.956734599665225,
  'pruner': 'NopPruner'},
 ('Random Forest', 'PatientPruner'): {'best_score': 491.58703506641024,
  'best_params': {'n_estimators': 200,
   'criterion': 'squared_error',
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.2,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.01},
  'test_mse': 491.58703506641024,
  'test_rmse': 22.171762110089723,
  'test_corr_coef': 0.9565223125605573,
  'pruner': 'PatientPruner'},
 ('Random Forest', 'PercentilePruner'): {'best_score': 499.01334098661863,
  'best_params': {'n_estimators': 200,
   'criterion': 'absolute_error',
   'max_depth': 40,
   'min_samples_split': 0.01,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.2,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001},
  'test_mse': 499.01334098661863,
  'test_rmse': 22.338606513984228,
  'test_corr_coef': 0.9581329488959801,
  'pruner': 'PercentilePruner'},
 ('Random Forest',
  'SuccessiveHalvingPruner'): {'best_score': 504.01487183783377, 'best_params': {'n_estimators': 100,
   'criterion': 'friedman_mse',
   'max_depth': None,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.1,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.01}, 'test_mse': 504.01487183783377, 'test_rmse': 22.450275540354372, 'test_corr_coef': 0.955958931998181, 'pruner': 'SuccessiveHalvingPruner'},
 ('Random Forest', 'HyperbandPruner'): {'best_score': 499.0331708466262,
  'best_params': {'n_estimators': 700,
   'criterion': 'squared_error',
   'max_depth': None,
   'min_samples_split': 0.01,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.01,
   'max_features': 0.5,
   'max_leaf_nodes': 200,
   'min_impurity_decrease': 0.2,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.05},
  'test_mse': 499.0331708466262,
  'test_rmse': 22.3390503568667,
  'test_corr_coef': 0.9564495763116471,
  'pruner': 'HyperbandPruner'},
 ('Random Forest', 'ThresholdPruner'): {'best_score': 497.11506466625553,
  'best_params': {'n_estimators': 500,
   'criterion': 'squared_error',
   'max_depth': 10,
   'min_samples_split': 0.01,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.01,
   'max_features': 0.5,
   'max_leaf_nodes': 50,
   'min_impurity_decrease': 0.2,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.1},
  'test_mse': 497.11506466625553,
  'test_rmse': 22.296077338093703,
  'test_corr_coef': 0.9567718647561463,
  'pruner': 'ThresholdPruner'},
 ('Random Forest', 'WilcoxonPruner'): {'best_score': 491.08002163339074,
  'best_params': {'n_estimators': 200,
   'criterion': 'squared_error',
   'max_depth': 20,
   'min_samples_split': 2,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.01,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.01},
  'test_mse': 491.08002163339074,
  'test_rmse': 22.160325395476274,
  'test_corr_coef': 0.9566343173406529,
  'pruner': 'WilcoxonPruner'},
 ('Gradient Boosting', 'MedianPruner'): {'best_score': 186.2899803104867,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 500,
   'subsample': 0.7,
   'criterion': 'squared_error',
   'min_samples_split': 10,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 5,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.01},
  'test_mse': 186.2899803104867,
  'test_rmse': 13.648808750601157,
  'test_corr_coef': 0.9725621388727219,
  'pruner': 'MedianPruner'},
 ('Gradient Boosting', 'NopPruner'): {'best_score': 211.7326358072223,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 500,
   'subsample': 0.5,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 10,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': 'log2',
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 30,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.01},
  'test_mse': 211.7326358072223,
  'test_rmse': 14.551035557898356,
  'test_corr_coef': 0.9714617114917357,
  'pruner': 'NopPruner'},
 ('Gradient Boosting', 'PatientPruner'): {'best_score': 226.32308192609057,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.2,
   'n_estimators': 300,
   'subsample': 0.9,
   'criterion': 'squared_error',
   'min_samples_split': 10,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.0001,
   'ccp_alpha': 0.001},
  'test_mse': 226.32308192609057,
  'test_rmse': 15.044038085769744,
  'test_corr_coef': 0.9692168454493556,
  'pruner': 'PatientPruner'},
 ('Gradient Boosting', 'PercentilePruner'): {'best_score': 183.60943493639752,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 700,
   'subsample': 0.7,
   'criterion': 'friedman_mse',
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 10,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 30,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'tol': 0.0001,
   'ccp_alpha': 0.01},
  'test_mse': 183.60943493639752,
  'test_rmse': 13.550255899295685,
  'test_corr_coef': 0.9785532886277138,
  'pruner': 'PercentilePruner'},
 ('Gradient Boosting',
  'SuccessiveHalvingPruner'): {'best_score': 188.85720758880905, 'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 500,
   'subsample': 0.7,
   'criterion': 'squared_error',
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 3,
   'min_impurity_decrease': 0.1,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': 50,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.0001,
   'ccp_alpha': 0.0}, 'test_mse': 188.85720758880905, 'test_rmse': 13.742532793805116, 'test_corr_coef': 0.9768378796573041, 'pruner': 'SuccessiveHalvingPruner'},
 ('Gradient Boosting', 'HyperbandPruner'): {'best_score': 153.75648954584392,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 300,
   'subsample': 0.5,
   'criterion': 'squared_error',
   'min_samples_split': 10,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.05,
   'max_depth': 7,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.01},
  'test_mse': 153.75648954584392,
  'test_rmse': 12.399858448621256,
  'test_corr_coef': 0.9769080213173296,
  'pruner': 'HyperbandPruner'},
 ('Gradient Boosting', 'ThresholdPruner'): {'best_score': 163.7151008337401,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.01,
   'n_estimators': 500,
   'subsample': 0.7,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 10,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.001},
  'test_mse': 163.7151008337401,
  'test_rmse': 12.79512019614275,
  'test_corr_coef': 0.9785863457606022,
  'pruner': 'ThresholdPruner'},
 ('Gradient Boosting', 'WilcoxonPruner'): {'best_score': 203.07392186675133,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 200,
   'subsample': 0.5,
   'criterion': 'squared_error',
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 10,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.01},
  'test_mse': 203.07392186675133,
  'test_rmse': 14.250400761618998,
  'test_corr_coef': 0.9717306620069607,
  'pruner': 'WilcoxonPruner'},
 ('XGBoost', 'MedianPruner'): {'best_score': 182.4639007284696,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.1,
   'max_depth': 3,
   'min_child_weight': 1,
   'gamma': 0.5,
   'subsample': 0.6,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 182.4639007284696,
  'test_rmse': 13.507919926045965,
  'test_corr_coef': 0.9759722627311321,
  'pruner': 'MedianPruner'},
 ('XGBoost', 'NopPruner'): {'best_score': 207.7563248132366,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'max_depth': 3,
   'min_child_weight': 1,
   'gamma': 1,
   'subsample': 0.5,
   'colsample_bytree': 0.5,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0.01,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 207.7563248132366,
  'test_rmse': 14.413754709069966,
  'test_corr_coef': 0.973407103840386,
  'pruner': 'NopPruner'},
 ('XGBoost', 'PatientPruner'): {'best_score': 171.42745522951924,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.1,
   'max_depth': 3,
   'min_child_weight': 1,
   'gamma': 0.1,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 1,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 171.42745522951924,
  'test_rmse': 13.093030788534763,
  'test_corr_coef': 0.973670001338332,
  'pruner': 'PatientPruner'},
 ('XGBoost', 'PercentilePruner'): {'best_score': 159.5769088653608,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'max_depth': 3,
   'min_child_weight': 1,
   'gamma': 0.5,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 159.5769088653608,
  'test_rmse': 12.632375424494033,
  'test_corr_coef': 0.9781404799102082,
  'pruner': 'PercentilePruner'},
 ('XGBoost', 'SuccessiveHalvingPruner'): {'best_score': 278.2881193971079,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'max_depth': 7,
   'min_child_weight': 3,
   'gamma': 0.1,
   'subsample': 0.9,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 278.2881193971079,
  'test_rmse': 16.681969889587617,
  'test_corr_coef': 0.9661059064338804,
  'pruner': 'SuccessiveHalvingPruner'},
 ('XGBoost', 'HyperbandPruner'): {'best_score': 196.03189004000157,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'max_depth': 3,
   'min_child_weight': 1,
   'gamma': 0.1,
   'subsample': 0.5,
   'colsample_bytree': 0.7,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 196.03189004000157,
  'test_rmse': 14.001138883676626,
  'test_corr_coef': 0.9735341381049875,
  'pruner': 'HyperbandPruner'},
 ('XGBoost', 'ThresholdPruner'): {'best_score': 216.78222120594558,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.1,
   'max_depth': 7,
   'min_child_weight': 3,
   'gamma': 0.1,
   'subsample': 0.6,
   'colsample_bytree': 0.7,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 216.78222120594558,
  'test_rmse': 14.723526113195357,
  'test_corr_coef': 0.9718893462363486,
  'pruner': 'ThresholdPruner'},
 ('XGBoost', 'WilcoxonPruner'): {'best_score': 190.25624389977247,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.15,
   'max_depth': 3,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.6,
   'colsample_bytree': 0.7,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 190.25624389977247,
  'test_rmse': 13.793340563466577,
  'test_corr_coef': 0.9741167324497741,
  'pruner': 'WilcoxonPruner'},
 ('LightGBM', 'MedianPruner'): {'best_score': 221.50989561280434,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'num_leaves': 15,
   'max_depth': -1,
   'min_child_samples': 1,
   'subsample': 0.6,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.01,
   'reg_lambda': 1,
   'min_child_weight': 0.001,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 221.50989561280434,
  'test_rmse': 14.883208512038133,
  'test_corr_coef': 0.9699035026881411,
  'pruner': 'MedianPruner'},
 ('LightGBM', 'NopPruner'): {'best_score': 192.8091126593126,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'num_leaves': 15,
   'max_depth': 3,
   'min_child_samples': 1,
   'subsample': 0.6,
   'colsample_bytree': 0.5,
   'reg_alpha': 1,
   'reg_lambda': 0.1,
   'min_child_weight': 0.001,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 192.8091126593126,
  'test_rmse': 13.8855721041415,
  'test_corr_coef': 0.9738620305498757,
  'pruner': 'NopPruner'},
 ('LightGBM', 'PatientPruner'): {'best_score': 245.61587828860456,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.05,
   'num_leaves': 15,
   'max_depth': -1,
   'min_child_samples': 1,
   'subsample': 0.6,
   'colsample_bytree': 0.9,
   'reg_alpha': 1,
   'reg_lambda': 0.1,
   'min_child_weight': 0.01,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 245.61587828860456,
  'test_rmse': 15.672137004525087,
  'test_corr_coef': 0.9667939081895134,
  'pruner': 'PatientPruner'},
 ('LightGBM', 'PercentilePruner'): {'best_score': 229.12848855837152,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': 7,
   'min_child_samples': 1,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.01,
   'reg_lambda': 0,
   'min_child_weight': 0.01,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 229.12848855837152,
  'test_rmse': 15.136990736549043,
  'test_corr_coef': 0.969281942853518,
  'pruner': 'PercentilePruner'},
 ('LightGBM', 'SuccessiveHalvingPruner'): {'best_score': 270.7694873082848,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'num_leaves': 31,
   'max_depth': 3,
   'min_child_samples': 1,
   'subsample': 1.0,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.01,
   'reg_lambda': 10,
   'min_child_weight': 0.1,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 270.7694873082848,
  'test_rmse': 16.45507481928553,
  'test_corr_coef': 0.9623583149111405,
  'pruner': 'SuccessiveHalvingPruner'},
 ('LightGBM', 'HyperbandPruner'): {'best_score': 304.2971462391087,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'num_leaves': 63,
   'max_depth': 3,
   'min_child_samples': 5,
   'subsample': 0.6,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.01,
   'reg_lambda': 0.1,
   'min_child_weight': 0.1,
   'bagging_freq': 0,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 304.2971462391087,
  'test_rmse': 17.444114945709018,
  'test_corr_coef': 0.9595863620711319,
  'pruner': 'HyperbandPruner'},
 ('LightGBM', 'ThresholdPruner'): {'best_score': 301.83484392669357,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.1,
   'num_leaves': 15,
   'max_depth': 3,
   'min_child_samples': 5,
   'subsample': 1.0,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.01,
   'reg_lambda': 0.1,
   'min_child_weight': 0.1,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 301.83484392669357,
  'test_rmse': 17.373394715100833,
  'test_corr_coef': 0.9603069622103869,
  'pruner': 'ThresholdPruner'},
 ('LightGBM', 'WilcoxonPruner'): {'best_score': 265.1710944134933,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.15,
   'num_leaves': 31,
   'max_depth': 3,
   'min_child_samples': 1,
   'subsample': 0.9,
   'colsample_bytree': 1.0,
   'reg_alpha': 1,
   'reg_lambda': 10,
   'min_child_weight': 0.001,
   'bagging_freq': 0,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 265.1710944134933,
  'test_rmse': 16.284074871281245,
  'test_corr_coef': 0.963709781649213,
  'pruner': 'WilcoxonPruner'},
 ('GPBoost', 'MedianPruner'): {'best_score': 296.1437619859039,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'max_depth': 3,
   'num_leaves': 31,
   'min_child_samples': 5,
   'subsample': 0.8,
   'colsample_bytree': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 0,
   'min_child_weight': 0.1,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 296.1437619859039,
  'test_rmse': 17.20882802476403,
  'test_corr_coef': 0.9611953214367067,
  'pruner': 'MedianPruner'},
 ('GPBoost', 'NopPruner'): {'best_score': 291.3976432243806,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.15,
   'max_depth': 3,
   'num_leaves': 15,
   'min_child_samples': 5,
   'subsample': 1.0,
   'colsample_bytree': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 0,
   'min_child_weight': 0.1,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 291.3976432243806,
  'test_rmse': 17.070373259667775,
  'test_corr_coef': 0.9602353463338138,
  'pruner': 'NopPruner'},
 ('GPBoost', 'PatientPruner'): {'best_score': 303.30933705656224,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.15,
   'max_depth': 3,
   'num_leaves': 15,
   'min_child_samples': 5,
   'subsample': 0.8,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 1.0,
   'min_child_weight': 0.1,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 303.30933705656224,
  'test_rmse': 17.415778393645294,
  'test_corr_coef': 0.9606199387104392,
  'pruner': 'PatientPruner'},
 ('GPBoost', 'PercentilePruner'): {'best_score': 291.7690052454734,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 3,
   'num_leaves': 63,
   'min_child_samples': 5,
   'subsample': 0.7,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.5,
   'reg_lambda': 0,
   'min_child_weight': 0.01,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 291.7690052454734,
  'test_rmse': 17.081247180621016,
  'test_corr_coef': 0.9628685814302016,
  'pruner': 'PercentilePruner'},
 ('GPBoost', 'SuccessiveHalvingPruner'): {'best_score': 297.5973873766578,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.05,
   'max_depth': 3,
   'num_leaves': 63,
   'min_child_samples': 5,
   'subsample': 0.5,
   'colsample_bytree': 0.7,
   'reg_alpha': 1.0,
   'reg_lambda': 0,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 297.5973873766578,
  'test_rmse': 17.251011198670582,
  'test_corr_coef': 0.9606246023525719,
  'pruner': 'SuccessiveHalvingPruner'},
 ('GPBoost', 'HyperbandPruner'): {'best_score': 304.7762550718626,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 3,
   'num_leaves': 15,
   'min_child_samples': 5,
   'subsample': 0.8,
   'colsample_bytree': 0.7,
   'reg_alpha': 1.0,
   'reg_lambda': 0.1,
   'min_child_weight': 0.01,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 304.7762550718626,
  'test_rmse': 17.45784222267639,
  'test_corr_coef': 0.9589949879068711,
  'pruner': 'HyperbandPruner'},
 ('GPBoost', 'ThresholdPruner'): {'best_score': 283.9070495729028,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'max_depth': 3,
   'num_leaves': 31,
   'min_child_samples': 1,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'reg_alpha': 1.0,
   'reg_lambda': 1.0,
   'min_child_weight': 0.01,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 283.9070495729028,
  'test_rmse': 16.849541524115807,
  'test_corr_coef': 0.9689209328885141,
  'pruner': 'ThresholdPruner'},
 ('GPBoost', 'WilcoxonPruner'): {'best_score': 291.7690052454734,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'max_depth': 3,
   'num_leaves': 31,
   'min_child_samples': 5,
   'subsample': 0.5,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.5,
   'reg_lambda': 0,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 291.7690052454734,
  'test_rmse': 17.081247180621016,
  'test_corr_coef': 0.9628685814302016,
  'pruner': 'WilcoxonPruner'},
 ('CatBoost', 'MedianPruner'): {'best_score': 347.4429012205738,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.03,
   'depth': 4,
   'l2_leaf_reg': 5,
   'border_count': 32,
   'min_data_in_leaf': 20,
   'rsm': 0.6,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 347.4429012205738,
  'test_rmse': 18.63982031084457,
  'test_corr_coef': 0.9614771149420601,
  'pruner': 'MedianPruner'},
 ('CatBoost', 'NopPruner'): {'best_score': 370.10393301836245,
  'best_params': {'iterations': 500,
   'learning_rate': 0.1,
   'depth': 4,
   'l2_leaf_reg': 5,
   'border_count': 32,
   'min_data_in_leaf': 10,
   'rsm': 0.6,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 370.10393301836245,
  'test_rmse': 19.23808548214615,
  'test_corr_coef': 0.9594743814447798,
  'pruner': 'NopPruner'},
 ('CatBoost', 'PatientPruner'): {'best_score': 347.4429012205738,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.03,
   'depth': 4,
   'l2_leaf_reg': 5,
   'border_count': 32,
   'min_data_in_leaf': 1,
   'rsm': 0.6,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 347.4429012205738,
  'test_rmse': 18.63982031084457,
  'test_corr_coef': 0.9614771149420601,
  'pruner': 'PatientPruner'},
 ('CatBoost', 'PercentilePruner'): {'best_score': 353.61414463188675,
  'best_params': {'iterations': 500,
   'learning_rate': 0.05,
   'depth': 4,
   'l2_leaf_reg': 3,
   'border_count': 32,
   'min_data_in_leaf': 10,
   'rsm': 0.8,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 353.61414463188675,
  'test_rmse': 18.80463093580639,
  'test_corr_coef': 0.9611010440854848,
  'pruner': 'PercentilePruner'},
 ('CatBoost', 'SuccessiveHalvingPruner'): {'best_score': 368.5205933957056,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.1,
   'depth': 4,
   'l2_leaf_reg': 1,
   'border_count': 64,
   'min_data_in_leaf': 5,
   'rsm': 0.8,
   'bagging_temperature': 0,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 368.5205933957056,
  'test_rmse': 19.196890201168145,
  'test_corr_coef': 0.9564404896870229,
  'pruner': 'SuccessiveHalvingPruner'},
 ('CatBoost', 'HyperbandPruner'): {'best_score': 354.04068707098565,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.05,
   'depth': 4,
   'l2_leaf_reg': 7,
   'border_count': 64,
   'min_data_in_leaf': 5,
   'rsm': 0.8,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 354.04068707098565,
  'test_rmse': 18.815968937872576,
  'test_corr_coef': 0.9599972705368262,
  'pruner': 'HyperbandPruner'},
 ('CatBoost', 'ThresholdPruner'): {'best_score': 354.04068707098565,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.05,
   'depth': 4,
   'l2_leaf_reg': 7,
   'border_count': 64,
   'min_data_in_leaf': 10,
   'rsm': 0.8,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 354.04068707098565,
  'test_rmse': 18.815968937872576,
  'test_corr_coef': 0.9599972705368262,
  'pruner': 'ThresholdPruner'},
 ('CatBoost', 'WilcoxonPruner'): {'best_score': 353.61414463188675,
  'best_params': {'iterations': 500,
   'learning_rate': 0.05,
   'depth': 4,
   'l2_leaf_reg': 3,
   'border_count': 32,
   'min_data_in_leaf': 20,
   'rsm': 0.8,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 353.61414463188675,
  'test_rmse': 18.80463093580639,
  'test_corr_coef': 0.9611010440854848,
  'pruner': 'WilcoxonPruner'},
 ('NGBoost', 'MedianPruner'): {'best_score': 183.95772791433217,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 183.95772791433217,
  'test_rmse': 13.563101706996529,
  'test_corr_coef': 0.9747258074877652,
  'pruner': 'MedianPruner'},
 ('NGBoost', 'NopPruner'): {'best_score': 178.7588861952265,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 1.0,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 178.7588861952265,
  'test_rmse': 13.37007427785001,
  'test_corr_coef': 0.976279845474334,
  'pruner': 'NopPruner'},
 ('NGBoost', 'PatientPruner'): {'best_score': 183.86711972030236,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.7,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 183.86711972030236,
  'test_rmse': 13.559761049528209,
  'test_corr_coef': 0.9783491434299343,
  'pruner': 'PatientPruner'},
 ('NGBoost', 'PercentilePruner'): {'best_score': 175.3332984508238,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 1.0,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 175.3332984508238,
  'test_rmse': 13.241348060179666,
  'test_corr_coef': 0.976802462865663,
  'pruner': 'PercentilePruner'},
 ('NGBoost', 'SuccessiveHalvingPruner'): {'best_score': 183.54434117920928,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 183.54434117920928,
  'test_rmse': 13.547853748074242,
  'test_corr_coef': 0.9754625858555357,
  'pruner': 'SuccessiveHalvingPruner'},
 ('NGBoost', 'HyperbandPruner'): {'best_score': 177.70031452506524,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.03,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 177.70031452506524,
  'test_rmse': 13.330428144852108,
  'test_corr_coef': 0.9730672166033915,
  'pruner': 'HyperbandPruner'},
 ('NGBoost', 'ThresholdPruner'): {'best_score': 173.4748090057579,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.03,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 173.4748090057579,
  'test_rmse': 13.17098360054244,
  'test_corr_coef': 0.9765254085330761,
  'pruner': 'ThresholdPruner'},
 ('NGBoost', 'WilcoxonPruner'): {'best_score': 190.83709708753526,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 190.83709708753526,
  'test_rmse': 13.814380083360065,
  'test_corr_coef': 0.9767622115354234,
  'pruner': 'WilcoxonPruner'},
 ('TabNet', 'MedianPruner'): {'best_score': 683.1835477259349,
  'best_params': {'n_d': 32,
   'n_a': 16,
   'n_steps': 7,
   'gamma': 1.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 683.1835477259349,
  'test_rmse': 26.137780084122195,
  'test_corr_coef': 0.925708069115367,
  'pruner': 'MedianPruner'},
 ('TabNet', 'NopPruner'): {'best_score': 785.2781419779674,
  'best_params': {'n_d': 16,
   'n_a': 16,
   'n_steps': 7,
   'gamma': 1.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 2,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 785.2781419779674,
  'test_rmse': 28.02281466908646,
  'test_corr_coef': 0.9099603248947505,
  'pruner': 'NopPruner'},
 ('TabNet', 'PatientPruner'): {'best_score': 647.9527885249482,
  'best_params': {'n_d': 16,
   'n_a': 64,
   'n_steps': 10,
   'gamma': 1.0,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 2,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 647.9527885249482,
  'test_rmse': 25.45491678487573,
  'test_corr_coef': 0.940281349954927,
  'pruner': 'PatientPruner'},
 ('TabNet', 'PercentilePruner'): {'best_score': 613.3890890267845,
  'best_params': {'n_d': 8,
   'n_a': 8,
   'n_steps': 10,
   'gamma': 1.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 2,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 613.3890890267845,
  'test_rmse': 24.766693138705147,
  'test_corr_coef': 0.9166311781717991,
  'pruner': 'PercentilePruner'},
 ('TabNet', 'SuccessiveHalvingPruner'): {'best_score': 666.6390125869158,
  'best_params': {'n_d': 16,
   'n_a': 8,
   'n_steps': 10,
   'gamma': 2.0,
   'lambda_sparse': 0.01,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 666.6390125869158,
  'test_rmse': 25.819353450210865,
  'test_corr_coef': 0.9148062364563666,
  'pruner': 'SuccessiveHalvingPruner'},
 ('TabNet', 'HyperbandPruner'): {'best_score': 763.3243122810416,
  'best_params': {'n_d': 8,
   'n_a': 64,
   'n_steps': 7,
   'gamma': 1.0,
   'lambda_sparse': 0.01,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 763.3243122810416,
  'test_rmse': 27.628324456634022,
  'test_corr_coef': 0.9185520550556193,
  'pruner': 'HyperbandPruner'},
 ('TabNet', 'ThresholdPruner'): {'best_score': 600.7624887356691,
  'best_params': {'n_d': 64,
   'n_a': 32,
   'n_steps': 7,
   'gamma': 1.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 2,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 600.7624887356691,
  'test_rmse': 24.510456722298528,
  'test_corr_coef': 0.9428019464440833,
  'pruner': 'ThresholdPruner'},
 ('TabNet', 'WilcoxonPruner'): {'best_score': 561.1656802691135,
  'best_params': {'n_d': 8,
   'n_a': 8,
   'n_steps': 10,
   'gamma': 1.0,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 561.1656802691135,
  'test_rmse': 23.688935819684122,
  'test_corr_coef': 0.9318886782102657,
  'pruner': 'WilcoxonPruner'},
 ('HistGradientBoosting', 'MedianPruner'): {'best_score': 306.9466510692115,
  'best_params': {'learning_rate': 0.1,
   'max_iter': 300,
   'max_depth': 3,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 63,
   'l2_regularization': 0.5,
   'max_bins': 128,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 306.9466510692115,
  'test_rmse': 17.5198930096394,
  'test_corr_coef': 0.9571560877136178,
  'pruner': 'MedianPruner'},
 ('HistGradientBoosting', 'NopPruner'): {'best_score': 307.14533474906676,
  'best_params': {'learning_rate': 0.1,
   'max_iter': 400,
   'max_depth': 3,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 31,
   'l2_regularization': 0.5,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 15,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 307.14533474906676,
  'test_rmse': 17.52556232333407,
  'test_corr_coef': 0.9571084111490522,
  'pruner': 'NopPruner'},
 ('HistGradientBoosting', 'PatientPruner'): {'best_score': 306.9466510692115,
  'best_params': {'learning_rate': 0.1,
   'max_iter': 300,
   'max_depth': 3,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 31,
   'l2_regularization': 0.5,
   'max_bins': 128,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 15,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 306.9466510692115,
  'test_rmse': 17.5198930096394,
  'test_corr_coef': 0.9571560877136178,
  'pruner': 'PatientPruner'},
 ('HistGradientBoosting',
  'PercentilePruner'): {'best_score': 310.15497272579285, 'best_params': {'learning_rate': 0.15,
   'max_iter': 200,
   'max_depth': 3,
   'min_samples_leaf': 5,
   'max_leaf_nodes': None,
   'l2_regularization': 0.5,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 310.15497272579285, 'test_rmse': 17.611217241457016, 'test_corr_coef': 0.9578779385722576, 'pruner': 'PercentilePruner'},
 ('HistGradientBoosting',
  'SuccessiveHalvingPruner'): {'best_score': 305.50458250552157, 'best_params': {'learning_rate': 0.1,
   'max_iter': 200,
   'max_depth': 3,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 63,
   'l2_regularization': 0.5,
   'max_bins': 255,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 15,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 305.50458250552157, 'test_rmse': 17.478689381802102, 'test_corr_coef': 0.957444692058178, 'pruner': 'SuccessiveHalvingPruner'},
 ('HistGradientBoosting', 'HyperbandPruner'): {'best_score': 318.1006871717745,
  'best_params': {'learning_rate': 0.05,
   'max_iter': 500,
   'max_depth': 3,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 15,
   'l2_regularization': 1.0,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 15,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 318.1006871717745,
  'test_rmse': 17.83537740480348,
  'test_corr_coef': 0.9559058436637012,
  'pruner': 'HyperbandPruner'},
 ('HistGradientBoosting',
  'ThresholdPruner'): {'best_score': 305.50458250552157, 'best_params': {'learning_rate': 0.1,
   'max_iter': 200,
   'max_depth': 3,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 63,
   'l2_regularization': 0.5,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 15,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 305.50458250552157, 'test_rmse': 17.478689381802102, 'test_corr_coef': 0.957444692058178, 'pruner': 'ThresholdPruner'},
 ('HistGradientBoosting', 'WilcoxonPruner'): {'best_score': 308.2494075545725,
  'best_params': {'learning_rate': 0.1,
   'max_iter': 500,
   'max_depth': 3,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 31,
   'l2_regularization': 1.0,
   'max_bins': 64,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 308.2494075545725,
  'test_rmse': 17.55703299406174,
  'test_corr_coef': 0.9571023046674804,
  'pruner': 'WilcoxonPruner'},
 ('PGBM', 'MedianPruner'): {'best_score': 219.4080278597303,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'max_leaves': 24,
   'min_split_gain': 0.1,
   'reg_lambda': 5.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.1,
   'min_data_in_leaf': 3,
   'max_bin': 128,
   'distribution': 'laplace'},
  'test_mse': 219.4080278597303,
  'test_rmse': 14.812428155428478,
  'test_corr_coef': 0.9679224562494657,
  'pruner': 'MedianPruner'},
 ('PGBM', 'NopPruner'): {'best_score': 187.25719821186112,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.1,
   'max_leaves': 46,
   'min_split_gain': 0.0,
   'reg_lambda': 0.1,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.0,
   'min_data_in_leaf': 3,
   'max_bin': 64,
   'distribution': 'normal'},
  'test_mse': 187.25719821186112,
  'test_rmse': 13.684195197813466,
  'test_corr_coef': 0.9730611883509453,
  'pruner': 'NopPruner'},
 ('PGBM', 'PatientPruner'): {'best_score': 214.12435786352063,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'max_leaves': 38,
   'min_split_gain': 0.0,
   'reg_lambda': 5.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.0,
   'min_data_in_leaf': 3,
   'max_bin': 64,
   'distribution': 'laplace'},
  'test_mse': 214.12435786352063,
  'test_rmse': 14.632988685279594,
  'test_corr_coef': 0.9692185393643218,
  'pruner': 'PatientPruner'},
 ('PGBM', 'PercentilePruner'): {'best_score': 219.808103705989,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.15,
   'max_leaves': 46,
   'min_split_gain': 0.5,
   'reg_lambda': 5.0,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 3,
   'max_bin': 64,
   'distribution': 'laplace'},
  'test_mse': 219.808103705989,
  'test_rmse': 14.825926740207136,
  'test_corr_coef': 0.9677760061638276,
  'pruner': 'PercentilePruner'},
 ('PGBM', 'SuccessiveHalvingPruner'): {'best_score': 212.56364451333772,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.1,
   'max_leaves': 58,
   'min_split_gain': 0.1,
   'reg_lambda': 5.0,
   'feature_fraction': 0.7,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.0,
   'min_data_in_leaf': 3,
   'max_bin': 64,
   'distribution': 'studentt'},
  'test_mse': 212.56364451333772,
  'test_rmse': 14.579562562482378,
  'test_corr_coef': 0.9705315993920913,
  'pruner': 'SuccessiveHalvingPruner'},
 ('PGBM', 'HyperbandPruner'): {'best_score': 224.1891995793507,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'max_leaves': 63,
   'min_split_gain': 0.1,
   'reg_lambda': 5.0,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.2,
   'min_data_in_leaf': 3,
   'max_bin': 128,
   'distribution': 'normal'},
  'test_mse': 224.1891995793507,
  'test_rmse': 14.972948927293873,
  'test_corr_coef': 0.9661198812577402,
  'pruner': 'HyperbandPruner'},
 ('PGBM', 'ThresholdPruner'): {'best_score': 198.923181819936,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'max_leaves': 60,
   'min_split_gain': 0.0,
   'reg_lambda': 1.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.0,
   'min_data_in_leaf': 3,
   'max_bin': 64,
   'distribution': 'studentt'},
  'test_mse': 198.923181819936,
  'test_rmse': 14.10401296865314,
  'test_corr_coef': 0.9722429140371318,
  'pruner': 'ThresholdPruner'},
 ('PGBM', 'WilcoxonPruner'): {'best_score': 291.82278144520916,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_leaves': 59,
   'min_split_gain': 0.1,
   'reg_lambda': 0.1,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 5,
   'max_bin': 128,
   'distribution': 'normal'},
  'test_mse': 291.82278144520916,
  'test_rmse': 17.082821237875468,
  'test_corr_coef': 0.9562602520910682,
  'pruner': 'WilcoxonPruner'}}

# **Conformal Predictions with Lightgbm**

In [16]:
best_params = get_best_model_params(best_scores_autosampler, 'LightGBM')

In [17]:
conformal_predictions_NEXCP(
    model_class=LGBMRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="LightGBM",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/LightGBM.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 6.383% | Width: 1.190
NexCP Full - Coverage: 6.383% | Width: 1.188
NexCP Jackknife+ aB - Coverage: 76.596% | Width: 53.135
NexCP CV+ - Coverage: 100.000% | Width: 93.254

              Strategy  Coverage      Width       RMSE           CWC
0          NexCP Split  0.063830   1.189580  13.885572  2.081304e+19
1           NexCP Full  0.063830   1.187615  13.885572  2.077865e+19
2  NexCP Jackknife+ aB  0.765957  53.134559  20.032534  5.270528e+05
3            NexCP CV+  1.000000  93.253630  17.728060  9.325363e+01

In [18]:
conformal_predictions_online_super(
    model_class=LGBMRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="LightGBM",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/LightGBM.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.063830   1.187615  13.885572   2.299425
1            Online CV+  0.744681  37.326846  13.885572  46.857105
2  Online Jackknife+ aB  0.765957  51.760297  19.450302  63.874409
3                 SAOCP  0.744681  40.324597  13.885572  50.620239
4                SF-OGD  0.042553   0.699784  13.885572   1.369790
5                  FACI  0.808511  45.411290  13.885572  54.107069
6            MFCS Split  0.063830   1.187615  13.885572   2.299425
7             MFCS Full  0.000000   1.513194  16.357038   3.026389

               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.063830   1.187615  13.885572   2.299425
1            Online CV+  0.744681  37.326846  13.885572  46.857105
2  Online Jackknife+ aB  0.765957  51.760297  19.450302  63.874409
3                 SAOCP  0.744681  40.324597  13.885572  50.620239
4                SF-OGD  0.042553   0.699784  13.885572   1.369790
5                  FACI  0.808511  45.411290  13.885572  54.107069
6            MFCS Split  0.063830   1.187615  13.885572   2.299425
7             MFCS Full  0.000000   1.513194  16.357038   3.026389

In [19]:
conformal_predictions_COP(
    model_class=LGBMRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="LightGBM",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/LightGBM.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (LightGBM) =====
Coverage : 8.511%
Avg Width: 3.256
RMSE     : 13.886
Final q  : 2.579

  Strategy  Coverage     Width       RMSE  Alpha    LR  Scale
0      COP  0.085106  3.255594  13.885572   0.05  0.05    0.5

In [20]:
# conformal_predictions_EXTREME(
#     model_class=LGBMRegressor,
#     model_params=best_params,
#     X_train=X_train,
#     y_train=y_train,
#     X_test=X_test,
#     y_test=y_test,
#     model_name="LightGBM",
#     excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/LightGBM.xlsx",
#     alpha=0.05,
#     calib_size=0.3,
# )

In [21]:
conformal_predictions_AlphaNet(
    model_class=LGBMRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="LightGBM",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/LightGBM.xlsx",
    alpha=0.05,
)

  [Info] n_calib=24 | alpha_min=0.0500
  [Step 2/9] Training base LightGBM model...
  [Step 2/9] Done in 0s
  [Step 3/9] Precomputing 24 LOO score vectors...

    LOO precompute:   0%|          | 0/24 [00:00<?, ?it/s]

  [Step 3/9] Done in 0s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 70.6937 | Size: 55.9268 | α̃: 0.7383 | ⏱ 0.15s/epoch | ETA: 40s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 60.5948 | Size: 40.5948 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 4s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 60.5948 | Size: 40.5948 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 2s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 60.5948 | Size: 40.5948 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 2s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 60.5948 | Size: 40.5948 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 60.5948 | Size: 40.5948 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 1s
  ✓ Run 1 complete | Final loss: 60.5948

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 60.5961 | Size: 40.5972 | α̃: 0.9999 | ⏱ 0.01s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 60.5948 | Size: 40.5948 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 60.5948 | Size: 40.5948 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 60.5948 | Size: 40.5948 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 60.5948 | Size: 40.5948 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 60.5948 | Size: 40.5948 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  ✓ Run 2 complete | Final loss: 60.5948

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 60.5948 | Size: 40.5948 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 1s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 60.5948 | Size: 40.5948 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 60.5948 | Size: 40.5948 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 60.5948 | Size: 40.5948 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 60.5948 | Size: 40.5948 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 60.5948 | Size: 40.5948 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  ✓ Run 3 complete | Final loss: 60.5948

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 60.5983 | Size: 40.6016 | α̃: 0.9998 | ⏱ 0.01s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 60.5948 | Size: 40.5948 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 60.5948 | Size: 40.5948 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 60.5948 | Size: 40.5948 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 60.5948 | Size: 40.5948 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 60.5948 | Size: 40.5948 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 60.5948
  [Step 4/9] Training done in 1s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (LightGBM)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 20.2974
  Coverage       : 74.468%
  Avg Width      : 40.5948
  RMSE           : 20.8501
  Total time     : 1s
    ├─ Precompute: 0s
    └─ Training  : 1s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 1s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.744681,40.594763,20.850119,0.05,1.0,20.0,1.47

# **Conformal Predictions with XGBoost**

In [22]:
best_params = get_best_model_params(best_scores_autosampler, 'XGBoost')

In [23]:
conformal_predictions_NEXCP(
    model_class=XGBRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="XGBoost",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/XGBoost.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 10.638% | Width: 1.154
NexCP Full - Coverage: 10.638% | Width: 1.153
NexCP Jackknife+ aB - Coverage: 72.340% | Width: 52.838
NexCP CV+ - Coverage: 100.000% | Width: 99.235

              Strategy  Coverage      Width       RMSE           CWC
0          NexCP Split  0.106383   1.153740  12.632375  2.404467e+18
1           NexCP Full  0.106383   1.153410  12.632375  2.403779e+18
2  NexCP Jackknife+ aB  0.723404  52.838009  20.834809  4.399626e+06
3            NexCP CV+  1.000000  99.235245  16.848936  9.923524e+01

In [24]:
conformal_predictions_online_super(
    model_class=XGBRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="XGBoost",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/XGBoost.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.106383   1.153410  12.632375   2.184117
1            Online CV+  0.744681  35.351932  12.632375  44.377958
2  Online Jackknife+ aB  0.723404  50.421009  20.156891  64.367246
3                 SAOCP  0.808511  38.417565  12.632375  45.774120
4                SF-OGD  0.021277   0.580545  12.632375   1.148738
5                  FACI  0.893617  45.039575  12.632375  49.831019
6            MFCS Split  0.106383   1.153410  12.632375   2.184117
7             MFCS Full  0.148936   1.308147  16.081387   2.421463

               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.106383   1.153410  12.632375   2.184117
1            Online CV+  0.744681  35.351932  12.632375  44.377958
2  Online Jackknife+ aB  0.723404  50.421009  20.156891  64.367246
3                 SAOCP  0.808511  38.417565  12.632375  45.774120
4                SF-OGD  0.021277   0.580545  12.632375   1.148738
5                  FACI  0.893617  45.039575  12.632375  49.831019
6            MFCS Split  0.106383   1.153410  12.632375   2.184117
7             MFCS Full  0.148936   1.308147  16.081387   2.421463

In [25]:
conformal_predictions_COP(
    model_class=XGBRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="XGBoost",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/XGBoost.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (XGBoost) =====
Coverage : 14.894%
Avg Width: 3.089
RMSE     : 12.632
Final q  : 2.412

  Strategy  Coverage     Width       RMSE  Alpha    LR  Scale
0      COP  0.148936  3.089474  12.632375   0.05  0.05    0.5

In [26]:
# conformal_predictions_EXTREME(
#     model_class=XGBRegressor,
#     model_params=best_params,
#     X_train=X_train,
#     y_train=y_train,
#     X_test=X_test,
#     y_test=y_test,
#     model_name="XGBoost",
#     excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/XGBoost.xlsx",
#     alpha=0.05,
#     calib_size=0.3,
# )

In [27]:
conformal_predictions_AlphaNet(
    model_class=XGBRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="XGBoost",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/XGBoost.xlsx",
    alpha=0.05,
)

  [Info] n_calib=24 | alpha_min=0.0500
  [Step 2/9] Training base XGBoost model...
  [Step 2/9] Done in 0s
  [Step 3/9] Precomputing 24 LOO score vectors...

    LOO precompute:   0%|          | 0/24 [00:00<?, ?it/s]

  [Step 3/9] Done in 0s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 63.2775 | Size: 47.3492 | α̃: 0.7964 | ⏱ 0.01s/epoch | ETA: 6s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 57.2372 | Size: 37.2373 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 57.2372 | Size: 37.2372 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 57.2372 | Size: 37.2372 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 57.2372 | Size: 37.2372 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 57.2372 | Size: 37.2372 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 1s
  ✓ Run 1 complete | Final loss: 57.2372

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 57.2388 | Size: 37.2406 | α̃: 0.9999 | ⏱ 0.01s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 57.2372 | Size: 37.2372 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 57.2372 | Size: 37.2372 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 57.2372 | Size: 37.2372 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 57.2372 | Size: 37.2372 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 57.2372 | Size: 37.2372 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  ✓ Run 2 complete | Final loss: 57.2372

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 57.2372 | Size: 37.2372 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 57.2372 | Size: 37.2372 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 57.2372 | Size: 37.2372 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 57.2372 | Size: 37.2372 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 57.2372 | Size: 37.2372 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 57.2372 | Size: 37.2372 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  ✓ Run 3 complete | Final loss: 57.2372

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 57.2413 | Size: 37.2457 | α̃: 0.9998 | ⏱ 0.01s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 57.2372 | Size: 37.2372 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 57.2372 | Size: 37.2372 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 57.2372 | Size: 37.2372 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 57.2372 | Size: 37.2372 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 57.2372 | Size: 37.2372 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 57.2372
  [Step 4/9] Training done in 1s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (XGBoost)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 18.6186
  Coverage       : 61.702%
  Avg Width      : 37.2372
  RMSE           : 26.5445
  Total time     : 1s
    ├─ Precompute: 0s
    └─ Training  : 1s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 1s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.617021,37.237209,26.54453,0.05,1.0,20.0,0.96

# **Conformal Predictions with GPBoost**

In [28]:
best_params = get_best_model_params(best_scores_autosampler, 'GPBoost')

In [29]:
conformal_predictions_NEXCP(
    model_class=GPBoostRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GPBoost",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/GPBoost.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 2.128% | Width: 1.528
NexCP Full - Coverage: 2.128% | Width: 1.530
NexCP Jackknife+ aB - Coverage: 87.234% | Width: 75.137
NexCP CV+ - Coverage: 100.000% | Width: 103.946

              Strategy  Coverage       Width       RMSE           CWC
0          NexCP Split  0.021277    1.527805  16.849542  2.244091e+20
1           NexCP Full  0.021277    1.530108  16.849542  2.247473e+20
2  NexCP Jackknife+ aB  0.872340   75.136618  21.201393  3.724422e+03
3            NexCP CV+  1.000000  103.945710  20.650426  1.039457e+02

In [30]:
conformal_predictions_online_super(
    model_class=GPBoostRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GPBoost",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/GPBoost.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.021277   1.530108  16.849542   3.027660
1            Online CV+  0.744681  40.771881  16.849542  51.181723
2  Online Jackknife+ aB  0.851064  71.355598  20.369468  81.983028
3                 SAOCP  0.787234  52.454751  16.849542  63.615337
4                SF-OGD  0.021277   1.122094  16.849542   2.220315
5                  FACI  0.829787  58.309395  16.849542  68.234398
6            MFCS Split  0.021277   1.530108  16.849542   3.027660
7             MFCS Full  0.021277   1.307222  19.676661   2.586630

               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.021277   1.530108  16.849542   3.027660
1            Online CV+  0.744681  40.771881  16.849542  51.181723
2  Online Jackknife+ aB  0.851064  71.355598  20.369468  81.983028
3                 SAOCP  0.787234  52.454751  16.849542  63.615337
4                SF-OGD  0.021277   1.122094  16.849542   2.220315
5                  FACI  0.829787  58.309395  16.849542  68.234398
6            MFCS Split  0.021277   1.530108  16.849542   3.027660
7             MFCS Full  0.021277   1.307222  19.676661   2.586630

In [31]:
conformal_predictions_COP(
    model_class=GPBoostRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GPBoost",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/GPBoost.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (GPBoost) =====
Coverage : 8.511%
Avg Width: 3.504
RMSE     : 16.850
Final q  : 2.750

  Strategy  Coverage     Width       RMSE  Alpha    LR  Scale
0      COP  0.085106  3.504469  16.849542   0.05  0.05    0.5

In [32]:
# conformal_predictions_EXTREME(
#     model_class=GPBoostRegressor,
#     model_params=best_params,
#     X_train=X_train,
#     y_train=y_train,
#     X_test=X_test,
#     y_test=y_test,
#     model_name="GPBoost",
#     excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/GPBoost.xlsx",
#     alpha=0.05,
#     calib_size=0.3,
# )

In [33]:
conformal_predictions_AlphaNet(
    model_class=GPBoostRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GPBoost",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/GPBoost.xlsx",
    alpha=0.05,
)

  [Info] n_calib=24 | alpha_min=0.0500
  [Step 2/9] Training base GPBoost model...
  [Step 2/9] Done in 0s
  [Step 3/9] Precomputing 24 LOO score vectors...

    LOO precompute:   0%|          | 0/24 [00:00<?, ?it/s]

  [Step 3/9] Done in 0s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 86.1752 | Size: 73.4232 | α̃: 0.6376 | ⏱ 0.01s/epoch | ETA: 6s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 65.4642 | Size: 45.4642 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 65.4642 | Size: 45.4642 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 65.4642 | Size: 45.4642 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 65.4642 | Size: 45.4642 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 65.4642 | Size: 45.4642 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  ✓ Run 1 complete | Final loss: 65.4642

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 65.4651 | Size: 45.4658 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 65.4642 | Size: 45.4642 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 65.4642 | Size: 45.4642 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 65.4642 | Size: 45.4642 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 65.4642 | Size: 45.4642 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 65.4642 | Size: 45.4642 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  ✓ Run 2 complete | Final loss: 65.4642

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 65.4642 | Size: 45.4642 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 65.4642 | Size: 45.4642 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 65.4642 | Size: 45.4642 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 65.4642 | Size: 45.4642 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 65.4642 | Size: 45.4642 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 65.4642 | Size: 45.4642 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 0s
  ✓ Run 3 complete | Final loss: 65.4642

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 65.4670 | Size: 45.4691 | α̃: 0.9999 | ⏱ 0.01s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 65.4642 | Size: 45.4642 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 65.4642 | Size: 45.4642 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 65.4642 | Size: 45.4642 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 65.4642 | Size: 45.4642 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 65.4642 | Size: 45.4642 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 65.4642
  [Step 4/9] Training done in 1s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (GPBoost)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 22.7321
  Coverage       : 70.213%
  Avg Width      : 45.4642
  RMSE           : 25.4432
  Total time     : 1s
    ├─ Precompute: 0s
    └─ Training  : 1s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 1s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.702128,45.464178,25.443238,0.05,1.0,20.0,0.9

# **Conformal Predictions with NGBoost**

In [34]:
best_params = get_best_model_params(best_scores_autosampler, 'NGBoost')

In [35]:
conformal_predictions_NEXCP(
    model_class=NGBRegressor,
    best_params={**best_params, "Dist": Normal},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="NGBoost",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/NGBoost.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 2.128% | Width: 0.786
NexCP Full - Coverage: 6.383% | Width: 0.877
NexCP Jackknife+ aB - Coverage: 82.979% | Width: 55.196
NexCP CV+ - Coverage: 100.000% | Width: 98.229

              Strategy  Coverage      Width       RMSE           CWC
0          NexCP Split  0.021277   0.786000  14.600391  1.154502e+20
1           NexCP Full  0.063830   0.876812  14.533163  1.534081e+19
2  NexCP Jackknife+ aB  0.829787  55.195798  18.998039  2.256092e+04
3            NexCP CV+  1.000000  98.229081  15.998740  9.822908e+01

In [36]:
conformal_predictions_online_super(
    model_class=NGBRegressor,
    model_params={**best_params, "Dist": Normal},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="NGBoost",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/NGBoost.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.021277   0.787075  14.600391   1.557403
1            Online CV+  0.723404  36.177581  14.600391  46.184146
2  Online Jackknife+ aB  0.829787  48.788256  19.338467  57.092640
3                 SAOCP  0.744681  42.465166  14.600391  53.307336
4                SF-OGD  0.000000   0.126889  14.600391   0.253778
5                  FACI  0.765957  48.052344  14.600391  59.298637
6            MFCS Split  0.021277   0.787075  14.600391   1.557403
7             MFCS Full  0.063830   1.342649  14.358789   2.599597

               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.021277   0.787075  14.600391   1.557403
1            Online CV+  0.723404  36.177581  14.600391  46.184146
2  Online Jackknife+ aB  0.829787  48.788256  19.338467  57.092640
3                 SAOCP  0.744681  42.465166  14.600391  53.307336
4                SF-OGD  0.000000   0.126889  14.600391   0.253778
5                  FACI  0.765957  48.052344  14.600391  59.298637
6            MFCS Split  0.021277   0.787075  14.600391   1.557403
7             MFCS Full  0.063830   1.342649  14.358789   2.599597

In [37]:
conformal_predictions_COP(
    model_class=NGBRegressor,
    model_params={**best_params, "Dist": Normal},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="NGBoost",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/NGBoost.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (NGBoost) =====
Coverage : 2.128%
Avg Width: 2.902
RMSE     : 14.600
Final q  : 2.529

  Strategy  Coverage     Width       RMSE  Alpha    LR  Scale
0      COP  0.021277  2.901862  14.600391   0.05  0.05    0.5

In [38]:
# conformal_predictions_EXTREME(
#     model_class=NGBRegressor,
#     model_params={**best_params, "Dist": Normal},
#     X_train=X_train,
#     y_train=y_train,
#     X_test=X_test,
#     y_test=y_test,
#     model_name="NGBoost",
#     excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/NGBoost.xlsx",
#     alpha=0.05,
#     calib_size=0.3,
# )

In [39]:
conformal_predictions_AlphaNet(
    model_class=NGBRegressor,
    model_params={**best_params, "Dist": Normal},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="NGBoost",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/NGBoost.xlsx",
    alpha=0.05,
)

  [Info] n_calib=24 | alpha_min=0.0500
  [Step 2/9] Training base NGBoost model...
  [Step 2/9] Done in 3s
  [Step 3/9] Precomputing 24 LOO score vectors...

    LOO precompute:   0%|          | 0/24 [00:00<?, ?it/s]

  [Step 3/9] Done in 4s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 103.4372 | Size: 92.3467 | α̃: 0.5545 | ⏱ 0.01s/epoch | ETA: 5s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 69.0928 | Size: 49.0928 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 69.0928 | Size: 49.0928 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 69.0928 | Size: 49.0928 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 69.0928 | Size: 49.0928 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 69.0928 | Size: 49.0928 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  ✓ Run 1 complete | Final loss: 69.0928

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 69.0935 | Size: 49.0939 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 69.0928 | Size: 49.0928 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 69.0928 | Size: 49.0928 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 69.0928 | Size: 49.0928 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 69.0928 | Size: 49.0928 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 69.0928 | Size: 49.0928 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  ✓ Run 2 complete | Final loss: 69.0928

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 69.0928 | Size: 49.0928 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 69.0928 | Size: 49.0928 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 69.0928 | Size: 49.0928 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 69.0928 | Size: 49.0928 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 69.0928 | Size: 49.0928 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 69.0928 | Size: 49.0928 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  ✓ Run 3 complete | Final loss: 69.0928

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 69.0951 | Size: 49.0966 | α̃: 0.9999 | ⏱ 0.01s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 69.0928 | Size: 49.0928 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 69.0928 | Size: 49.0928 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 69.0928 | Size: 49.0928 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 69.0928 | Size: 49.0928 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 69.0928 | Size: 49.0928 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 69.0928
  [Step 4/9] Training done in 1s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (NGBoost)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 24.5464
  Coverage       : 74.468%
  Avg Width      : 49.0928
  RMSE           : 27.5441
  Total time     : 8s
    ├─ Precompute: 4s
    └─ Training  : 1s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 8s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.744681,49.092821,27.54407,0.05,1.0,20.0,8.2

# **Conformal Predictions with Gradient Boosting**

In [40]:
best_params = get_best_model_params(best_scores_autosampler, 'GradientBoosting')

In [41]:
conformal_predictions_NEXCP(
    model_class=GradientBoostingRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GradientBoosting",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/Gradient Boosting.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 27.660% | Width: 8.644
NexCP Full - Coverage: 27.660% | Width: 8.813
NexCP Jackknife+ aB - Coverage: 89.362% | Width: 60.678
NexCP CV+ - Coverage: 100.000% | Width: 105.238

              Strategy  Coverage       Width       RMSE           CWC
0          NexCP Split  0.276596    8.644052  12.399858  3.626645e+15
1           NexCP Full  0.276596    8.813038  12.399858  3.697543e+15
2  NexCP Jackknife+ aB  0.893617   60.678299  17.055547  1.077803e+03
3            NexCP CV+  1.000000  105.238458  13.748790  1.052385e+02

In [42]:
conformal_predictions_online_super(
    model_class=GradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GradientBoosting",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/Gradient Boosting.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.276596   8.813038  12.399858  15.188427
1            Online CV+  0.723404  29.036725  12.399858  37.068160
2  Online Jackknife+ aB  0.872340  61.165422  16.037405  68.973774
3                 SAOCP  0.765957  32.973690  12.399858  40.690936
4                SF-OGD  0.425532  13.643791  12.399858  21.481713
5                  FACI  0.851064  39.315192  12.399858  45.170646
6            MFCS Split  0.276596   8.813038  12.399858  15.188427
7             MFCS Full  0.127660   5.969463  14.367812  11.176868

               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.276596   8.813038  12.399858  15.188427
1            Online CV+  0.723404  29.036725  12.399858  37.068160
2  Online Jackknife+ aB  0.872340  61.165422  16.037405  68.973774
3                 SAOCP  0.765957  32.973690  12.399858  40.690936
4                SF-OGD  0.425532  13.643791  12.399858  21.481713
5                  FACI  0.851064  39.315192  12.399858  45.170646
6            MFCS Split  0.276596   8.813038  12.399858  15.188427
7             MFCS Full  0.127660   5.969463  14.367812  11.176868

In [43]:
conformal_predictions_COP(
    model_class=GradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GradientBoosting",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/Gradient Boosting.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (GradientBoosting) =====
Coverage : 31.915%
Avg Width: 10.315
RMSE     : 12.400
Final q  : 5.842

  Strategy  Coverage      Width       RMSE  Alpha    LR  Scale
0      COP  0.319149  10.315059  12.399858   0.05  0.05    0.5

In [44]:
# conformal_predictions_EXTREME(
#     model_class=GradientBoostingRegressor,
#     model_params=best_params,
#     X_train=X_train,
#     y_train=y_train,
#     X_test=X_test,
#     y_test=y_test,
#     model_name="GradientBoosting",
#     excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/Gradient Boosting.xlsx",
#     alpha=0.05,
#     calib_size=0.3,
# )

In [45]:
conformal_predictions_AlphaNet(
    model_class=GradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GradientBoosting",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/Gradient Boosting.xlsx",
    alpha=0.05,
)

  [Info] n_calib=24 | alpha_min=0.0500
  [Step 2/9] Training base GradientBoosting model...
  [Step 2/9] Done in 0s
  [Step 3/9] Precomputing 24 LOO score vectors...

    LOO precompute:   0%|          | 0/24 [00:00<?, ?it/s]

  [Step 3/9] Done in 0s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 91.3016 | Size: 79.0987 | α̃: 0.6101 | ⏱ 0.01s/epoch | ETA: 4s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 66.6876 | Size: 46.6876 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 66.6876 | Size: 46.6876 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 66.6876 | Size: 46.6876 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 66.6876 | Size: 46.6876 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 66.6876 | Size: 46.6876 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  ✓ Run 1 complete | Final loss: 66.6876

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 66.6885 | Size: 46.6890 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 66.6876 | Size: 46.6876 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 66.6876 | Size: 46.6876 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 66.6876 | Size: 46.6876 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 66.6876 | Size: 46.6876 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 66.6876 | Size: 46.6876 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  ✓ Run 2 complete | Final loss: 66.6876

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 66.6876 | Size: 46.6876 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 66.6876 | Size: 46.6876 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 66.6876 | Size: 46.6876 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 66.6876 | Size: 46.6876 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 66.6876 | Size: 46.6876 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 66.6876 | Size: 46.6876 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  ✓ Run 3 complete | Final loss: 66.6876

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 66.6903 | Size: 46.6921 | α̃: 0.9999 | ⏱ 0.01s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 66.6876 | Size: 46.6876 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 66.6876 | Size: 46.6876 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 66.6876 | Size: 46.6876 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 66.6876 | Size: 46.6876 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 66.6876 | Size: 46.6876 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 66.6876
  [Step 4/9] Training done in 1s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (GradientBoosting)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 23.3438
  Coverage       : 74.468%
  Avg Width      : 46.6876
  RMSE           : 25.1569
  Total time     : 1s
    ├─ Precompute: 0s
    └─ Training  : 1s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 1s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.744681,46.68764,25.156895,0.05,1.0,20.0,0.99

# **Conformal Predictions with CatBoost**

In [46]:
best_params = get_best_model_params(best_scores_autosampler, 'CatBoost')

In [47]:
conformal_predictions_NEXCP(
    model_class=CatBoostRegressor,
    best_params={**best_params, "verbose": False},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="CatBoost",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/CatBoost.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 4.255% | Width: 2.296
NexCP Full - Coverage: 4.255% | Width: 2.306
NexCP Jackknife+ aB - Coverage: 65.957% | Width: 43.910
NexCP CV+ - Coverage: 95.745% | Width: 99.750

              Strategy  Coverage      Width       RMSE           CWC
0          NexCP Split  0.042553   2.296085  18.639820  1.163978e+20
1           NexCP Full  0.042553   2.306033  18.639820  1.169022e+20
2  NexCP Jackknife+ aB  0.659574  43.909578  24.800862  8.893440e+07
3            NexCP CV+  0.957447  99.750252  22.150668  9.975025e+01

In [48]:
conformal_predictions_online_super(
    model_class=CatBoostRegressor,
    model_params={**best_params, "verbose": False},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="CatBoost",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/CatBoost.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.042553   2.306033  18.639820   4.513936
1            Online CV+  0.744681  36.228476  18.639820  45.478300
2  Online Jackknife+ aB  0.638298  41.206100  24.130540  56.110434
3                 SAOCP  0.808511  53.278218  18.639820  63.480431
4                SF-OGD  0.000000   1.511344  18.639820   3.022687
5                  FACI  0.808511  63.620508  18.639820  75.803159
6            MFCS Split  0.042553   2.306033  18.639820   4.513936
7             MFCS Full  0.106383   3.994073  22.186694   7.563245

               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.042553   2.306033  18.639820   4.513936
1            Online CV+  0.744681  36.228476  18.639820  45.478300
2  Online Jackknife+ aB  0.638298  41.206100  24.130540  56.110434
3                 SAOCP  0.808511  53.278218  18.639820  63.480431
4                SF-OGD  0.000000   1.511344  18.639820   3.022687
5                  FACI  0.808511  63.620508  18.639820  75.803159
6            MFCS Split  0.042553   2.306033  18.639820   4.513936
7             MFCS Full  0.106383   3.994073  22.186694   7.563245

In [49]:
conformal_predictions_COP(
    model_class=CatBoostRegressor,
    model_params={**best_params, "verbose": False},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="CatBoost",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/CatBoost.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (CatBoost) =====
Coverage : 19.149%
Avg Width: 4.148
RMSE     : 18.640
Final q  : 2.938

  Strategy  Coverage     Width      RMSE  Alpha    LR  Scale
0      COP  0.191489  4.148479  18.63982   0.05  0.05    0.5

In [50]:
# conformal_predictions_EXTREME(
#     model_class=CatBoostRegressor,
#     model_params={**best_params, "verbose": False},
#     X_train=X_train,
#     y_train=y_train,
#     X_test=X_test,
#     y_test=y_test,
#     model_name="CatBoost",
#     excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/CatBoost.xlsx",
#     alpha=0.05,
#     calib_size=0.3,
# )

In [51]:
conformal_predictions_AlphaNet(
    model_class=CatBoostRegressor,
    model_params={**best_params, "verbose": False},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="CatBoost",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/CatBoost.xlsx",
    alpha=0.05,
)

  [Info] n_calib=24 | alpha_min=0.0500
  [Step 2/9] Training base CatBoost model...
  [Step 2/9] Done in 0s
  [Step 3/9] Precomputing 24 LOO score vectors...

    LOO precompute:   0%|          | 0/24 [00:00<?, ?it/s]

  [Step 3/9] Done in 0s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 57.1614 | Size: 40.2364 | α̃: 0.8462 | ⏱ 0.01s/epoch | ETA: 6s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 53.7387 | Size: 33.7387 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 53.7386 | Size: 33.7387 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 53.7386 | Size: 33.7386 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 53.7386 | Size: 33.7386 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 53.7386 | Size: 33.7386 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  ✓ Run 1 complete | Final loss: 53.7386

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 53.7406 | Size: 33.7432 | α̃: 0.9999 | ⏱ 0.01s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 53.7386 | Size: 33.7386 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 53.7386 | Size: 33.7386 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 53.7386 | Size: 33.7386 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 53.7386 | Size: 33.7386 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 53.7386 | Size: 33.7386 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  ✓ Run 2 complete | Final loss: 53.7386

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 53.7387 | Size: 33.7387 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 53.7386 | Size: 33.7386 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 53.7386 | Size: 33.7386 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 53.7386 | Size: 33.7386 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 53.7386 | Size: 33.7386 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 53.7386 | Size: 33.7386 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  ✓ Run 3 complete | Final loss: 53.7386

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 53.7432 | Size: 33.7492 | α̃: 0.9997 | ⏱ 0.01s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 53.7386 | Size: 33.7386 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 53.7386 | Size: 33.7386 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 53.7386 | Size: 33.7386 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 53.7386 | Size: 33.7386 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 53.7386 | Size: 33.7386 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 53.7386
  [Step 4/9] Training done in 1s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (CatBoost)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 16.8693
  Coverage       : 68.085%
  Avg Width      : 33.7386
  RMSE           : 27.7258
  Total time     : 1s
    ├─ Precompute: 0s
    └─ Training  : 1s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 1s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.680851,33.738648,27.725806,0.05,1.0,20.0,1.02

# **Conformal Predictions with HistGradientBoosting**

In [52]:
best_params = get_best_model_params(best_scores_autosampler, 'HGBR')

In [53]:
conformal_predictions_NEXCP(
    model_class=HistGradientBoostingRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="HGBR",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/HGBM.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 12.766% | Width: 4.036
NexCP Full - Coverage: 12.766% | Width: 4.077
NexCP Jackknife+ aB - Coverage: 91.489% | Width: 71.002
NexCP CV+ - Coverage: 97.872% | Width: 108.795

              Strategy  Coverage       Width       RMSE           CWC
0          NexCP Split  0.127660    4.035555  17.478689  2.902677e+18
1           NexCP Full  0.127660    4.077037  17.478689  2.932514e+18
2  NexCP Jackknife+ aB  0.914894   71.001967  20.036142  4.817692e+02
3            NexCP CV+  0.978723  108.795204  18.881751  1.087952e+02

In [54]:
conformal_predictions_online_super(
    model_class=HistGradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="HGBR",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/HGBM.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.127660   4.077037  17.478689   7.633602
1            Online CV+  0.808511  46.286907  17.478689  55.150358
2  Online Jackknife+ aB  0.851064  66.175202  18.951503  76.031083
3                 SAOCP  0.808511  55.045940  17.478689  65.586652
4                SF-OGD  0.127660   5.552076  17.478689  10.395377
5                  FACI  0.851064  61.622300  17.478689  70.800089
6            MFCS Split  0.127660   4.077037  17.478689   7.633602
7             MFCS Full  0.063830   3.198868  18.525339   6.193553

               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.127660   4.077037  17.478689   7.633602
1            Online CV+  0.808511  46.286907  17.478689  55.150358
2  Online Jackknife+ aB  0.851064  66.175202  18.951503  76.031083
3                 SAOCP  0.808511  55.045940  17.478689  65.586652
4                SF-OGD  0.127660   5.552076  17.478689  10.395377
5                  FACI  0.851064  61.622300  17.478689  70.800089
6            MFCS Split  0.127660   4.077037  17.478689   7.633602
7             MFCS Full  0.063830   3.198868  18.525339   6.193553

In [55]:
conformal_predictions_COP(
    model_class=HistGradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="HGBR",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/HGBM.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (HGBR) =====
Coverage : 17.021%
Avg Width: 5.954
RMSE     : 17.479
Final q  : 3.874

  Strategy  Coverage     Width       RMSE  Alpha    LR  Scale
0      COP  0.170213  5.953527  17.478689   0.05  0.05    0.5

In [56]:
# conformal_predictions_EXTREME(
#     model_class=HistGradientBoostingRegressor,
#     model_params=best_params,
#     X_train=X_train,
#     y_train=y_train,
#     X_test=X_test,
#     y_test=y_test,
#     model_name="HGBR",
#     excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/HGBM.xlsx",
#     alpha=0.05,
#     calib_size=0.3,
# )

In [57]:
conformal_predictions_AlphaNet(
    model_class=HistGradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="HGBR",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/HGBM.xlsx",
    alpha=0.05,
)

  [Info] n_calib=24 | alpha_min=0.0500
  [Step 2/9] Training base HGBR model...
  [Step 2/9] Done in 0s
  [Step 3/9] Precomputing 24 LOO score vectors...

    LOO precompute:   0%|          | 0/24 [00:00<?, ?it/s]

  [Step 3/9] Done in 0s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 196.4395 | Size: 189.5754 | α̃: 0.3432 | ⏱ 0.01s/epoch | ETA: 5s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 78.5357 | Size: 58.5357 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 78.5357 | Size: 58.5357 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 78.5357 | Size: 58.5357 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 78.5357 | Size: 58.5357 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 78.5357 | Size: 58.5357 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  ✓ Run 1 complete | Final loss: 78.5357

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 78.5360 | Size: 58.5361 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 78.5357 | Size: 58.5357 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 78.5357 | Size: 58.5357 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 78.5357 | Size: 58.5357 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 78.5357 | Size: 58.5357 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 78.5357 | Size: 58.5357 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  ✓ Run 2 complete | Final loss: 78.5357

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 78.5357 | Size: 58.5357 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 78.5357 | Size: 58.5357 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 78.5357 | Size: 58.5357 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 78.5357 | Size: 58.5357 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 78.5357 | Size: 58.5357 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 78.5357 | Size: 58.5357 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  ✓ Run 3 complete | Final loss: 78.5357

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 78.5370 | Size: 58.5376 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 78.5357 | Size: 58.5357 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 78.5357 | Size: 58.5357 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 78.5357 | Size: 58.5357 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 78.5357 | Size: 58.5357 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 78.5357 | Size: 58.5357 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 78.5357
  [Step 4/9] Training done in 1s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (HGBR)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 29.2678
  Coverage       : 70.213%
  Avg Width      : 58.5357
  RMSE           : 29.1994
  Total time     : 1s
    ├─ Precompute: 0s
    └─ Training  : 1s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 1s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.702128,58.535694,29.199401,0.05,1.0,20.0,0.99

# **Conformal Predictions with PGBM**

In [58]:
class PGBMWrapper(BaseEstimator, RegressorMixin):
    def __init__(self, **params):
        self.params = params
        self.model = None

    def fit(self, X, y):
        X_ = X.to_numpy() if hasattr(X, "to_numpy") else np.array(X)
        y_ = y.to_numpy() if hasattr(y, "to_numpy") else np.array(y)
        self.model = PGBM()
        self.model.train(
            train_set=(X_, y_),
            objective=mseloss_objective,
            metric=rmseloss_metric,
            params=self.params
        )
        return self

    def predict(self, X):
        X_ = X.to_numpy() if hasattr(X, "to_numpy") else np.array(X)
        return self.model.predict(X_).numpy()

In [59]:
# Assuming best_params is obtained correctly
best_params = get_best_model_params(best_scores_autosampler, 'PGBM')

# Remove any conflicting parameters from best_params
incompatible_keys = ['Dist', 'Score']
for key in incompatible_keys:
    best_params.pop(key, None)

# Initialize PGBM model
pgbm_model = PGBM()
def mseloss_objective(yhat, y, sample_weight=None):
    # Ensure that yhat and y are PyTorch tensors
    if not torch.is_tensor(yhat):
        yhat = torch.from_numpy(np.array(yhat)).float()
    if not torch.is_tensor(y):
        y = torch.from_numpy(np.array(y)).float()
    gradient = yhat - y
    hessian = torch.ones_like(yhat)
    return gradient, hessian

def rmseloss_metric(yhat, y, sample_weight=None):
    # Ensure that yhat and y are PyTorch tensors
    if not torch.is_tensor(yhat):
        yhat = torch.from_numpy(np.array(yhat)).float()
    if not torch.is_tensor(y):
        y = torch.from_numpy(np.array(y)).float()
    loss = torch.sqrt(torch.mean((yhat - y) ** 2))
    return loss

X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)

# Fit the model
pgbm_model.train((X_train, y_train), objective=mseloss_objective, metric=rmseloss_metric, params=best_params)

# Predict the distribution
pred_dist = pgbm_model.predict_dist(X_test)

# Define the quantiles you want to predict
quantiles = [0.05, 0.1, 0.15, 0.2, 0.3,
             0.4, 0.5, 0.6, 0.7, 0.8,
             0.85, 0.9, 0.95]

# DataFrame to store predictions
predictions_PGBM_df = pd.DataFrame()

# Calculate and store quantiles
for q in quantiles:
    predictions_PGBM_df[q] = np.quantile(pred_dist, q, axis=0)

# Add actual EWQI to the DataFrame
predictions_PGBM_df['Actual'] = y_test.ravel()

# Print the DataFrame with predictions for each quantile
print(predictions_PGBM_df.head())

Training on CPU
Estimator 0/200, Train metric: 51.8040
Estimator 1/200, Train metric: 47.6403
Estimator 2/200, Train metric: 44.2211
Estimator 3/200, Train metric: 40.4811
Estimator 4/200, Train metric: 37.0778
Estimator 5/200, Train metric: 34.0711
Estimator 6/200, Train metric: 32.2726
Estimator 7/200, Train metric: 30.0074
Estimator 8/200, Train metric: 27.9378
Estimator 9/200, Train metric: 25.4829
Estimator 10/200, Train metric: 23.6093
Estimator 11/200, Train metric: 22.0989
Estimator 12/200, Train metric: 20.4743
Estimator 13/200, Train metric: 19.4300
Estimator 14/200, Train metric: 18.2014
Estimator 15/200, Train metric: 17.0535
Estimator 16/200, Train metric: 16.5485
Estimator 17/200, Train metric: 15.7829
Estimator 18/200, Train metric: 15.1467
Estimator 19/200, Train metric: 14.6958
Estimator 20/200, Train metric: 14.0259
Estimator 21/200, Train metric: 13.6423
Estimator 22/200, Train metric: 12.8222
Estimator 23/200, Train metric: 12.5842
Estimator 24/200, Train metric: 12.1847
Estimator 25/200, Train metric: 11.6684
Estimator 26/200, Train metric: 11.2312
Estimator 27/200, Train metric: 10.7562
Estimator 28/200, Train metric: 10.5753
Estimator 29/200, Train metric: 10.2691
Estimator 30/200, Train metric: 9.9803
Estimator 31/200, Train metric: 9.7237
Estimator 32/200, Train metric: 9.4549
Estimator 33/200, Train metric: 9.1564
Estimator 34/200, Train metric: 8.9626
Estimator 35/200, Train metric: 8.8029
Estimator 36/200, Train metric: 8.7466
Estimator 37/200, Train metric: 8.6531
Estimator 38/200, Train metric: 8.3499
Estimator 39/200, Train metric: 8.1236
Estimator 40/200, Train metric: 7.9707
Estimator 41/200, Train metric: 7.7555
Estimator 42/200, Train metric: 7.5853
Estimator 43/200, Train metric: 7.5657
Estimator 44/200, Train metric: 7.4670
Estimator 45/200, Train metric: 7.4512
Estimator 46/200, Train metric: 7.2707
Estimator 47/200, Train metric: 7.1833
Estimator 48/200, Train metric: 7.0673
Estimator 49/200, Train metric: 7.0357
Estimator 50/200, Train metric: 6.8528
Estimator 51/200, Train metric: 6.7405
Estimator 52/200, Train metric: 6.6605
Estimator 53/200, Train metric: 6.5991
Estimator 54/200, Train metric: 6.4035
Estimator 55/200, Train metric: 6.2739
Estimator 56/200, Train metric: 6.2639
Estimator 57/200, Train metric: 6.2217
Estimator 58/200, Train metric: 6.1139
Estimator 59/200, Train metric: 6.0467
Estimator 60/200, Train metric: 6.0631
Estimator 61/200, Train metric: 5.9333
Estimator 62/200, Train metric: 5.8259
Estimator 63/200, Train metric: 5.7376
Estimator 64/200, Train metric: 5.7314
Estimator 65/200, Train metric: 5.5767
Estimator 66/200, Train metric: 5.4692
Estimator 67/200, Train metric: 5.4702
Estimator 68/200, Train metric: 5.3803
Estimator 69/200, Train metric: 5.3269
Estimator 70/200, Train metric: 5.3060
Estimator 71/200, Train metric: 5.2349
Estimator 72/200, Train metric: 5.1693
Estimator 73/200, Train metric: 4.8893
Estimator 74/200, Train metric: 4.8614
Estimator 75/200, Train metric: 4.8651
Estimator 76/200, Train metric: 4.8591
Estimator 77/200, Train metric: 4.7915
Estimator 78/200, Train metric: 4.8018
Estimator 79/200, Train metric: 4.7054
Estimator 80/200, Train metric: 4.7221
Estimator 81/200, Train metric: 4.6383
Estimator 82/200, Train metric: 4.5345
Estimator 83/200, Train metric: 4.4447
Estimator 84/200, Train metric: 4.3372
Estimator 85/200, Train metric: 4.3289
Estimator 86/200, Train metric: 4.2374
Estimator 87/200, Train metric: 4.2368
Estimator 88/200, Train metric: 4.1623
Estimator 89/200, Train metric: 4.0954
Estimator 90/200, Train metric: 4.1103
Estimator 91/200, Train metric: 4.0138
Estimator 92/200, Train metric: 3.9284
Estimator 93/200, Train metric: 3.8706
Estimator 94/200, Train metric: 3.8135
Estimator 95/200, Train metric: 3.7593
Estimator 96/200, Train metric: 3.6942
Estimator 97/200, Train metric: 3.6330
Estimator 98/200, Train metric: 3.5067
Estimator 99/200, Train metric: 3.4673
Estimator 100/200, Train metric: 3.4349
Estimator 101/200, Train metric: 3.4092
Estimator 102/200, Train metric: 3.3616
Estimator 103/200, Train metric: 3.3446
Estimator 104/200, Train metric: 3.3003
Estimator 105/200, Train metric: 3.1971
Estimator 106/200, Train metric: 3.1340
Estimator 107/200, Train metric: 3.1221
Estimator 108/200, Train metric: 3.0452
Estimator 109/200, Train metric: 3.0063
Estimator 110/200, Train metric: 2.9227
Estimator 111/200, Train metric: 2.8307
Estimator 112/200, Train metric: 2.8136
Estimator 113/200, Train metric: 2.8140
Estimator 114/200, Train metric: 2.7575
Estimator 115/200, Train metric: 2.7517
Estimator 116/200, Train metric: 2.7050
Estimator 117/200, Train metric: 2.6911
Estimator 118/200, Train metric: 2.6886
Estimator 119/200, Train metric: 2.5974
Estimator 120/200, Train metric: 2.5433
Estimator 121/200, Train metric: 2.4873
Estimator 122/200, Train metric: 2.4070
Estimator 123/200, Train metric: 2.3512
Estimator 124/200, Train metric: 2.3201
Estimator 125/200, Train metric: 2.2739
Estimator 126/200, Train metric: 2.2502
Estimator 127/200, Train metric: 2.1926
Estimator 128/200, Train metric: 2.1904
Estimator 129/200, Train metric: 2.1388
Estimator 130/200, Train metric: 2.1075
Estimator 131/200, Train metric: 2.0979
Estimator 132/200, Train metric: 2.0400
Estimator 133/200, Train metric: 2.0300
Estimator 134/200, Train metric: 1.9849
Estimator 135/200, Train metric: 1.9291
Estimator 136/200, Train metric: 1.8432
Estimator 137/200, Train metric: 1.7957
Estimator 138/200, Train metric: 1.7428
Estimator 139/200, Train metric: 1.7009
Estimator 140/200, Train metric: 1.6871
Estimator 141/200, Train metric: 1.6713
Estimator 142/200, Train metric: 1.6485
Estimator 143/200, Train metric: 1.6406
Estimator 144/200, Train metric: 1.5997
Estimator 145/200, Train metric: 1.5324
Estimator 146/200, Train metric: 1.5229
Estimator 147/200, Train metric: 1.4887
Estimator 148/200, Train metric: 1.4771
Estimator 149/200, Train metric: 1.4751
Estimator 150/200, Train metric: 1.4819
Estimator 151/200, Train metric: 1.4413
Estimator 152/200, Train metric: 1.4051
Estimator 153/200, Train metric: 1.3925
Estimator 154/200, Train metric: 1.3659
Estimator 155/200, Train metric: 1.3431
Estimator 156/200, Train metric: 1.3318
Estimator 157/200, Train metric: 1.3028
Estimator 158/200, Train metric: 1.2947
Estimator 159/200, Train metric: 1.2778
Estimator 160/200, Train metric: 1.2508
Estimator 161/200, Train metric: 1.2084
Estimator 162/200, Train metric: 1.2117
Estimator 163/200, Train metric: 1.1798
Estimator 164/200, Train metric: 1.1813
Estimator 165/200, Train metric: 1.1651
Estimator 166/200, Train metric: 1.1619
Estimator 167/200, Train metric: 1.1536
Estimator 168/200, Train metric: 1.1444
Estimator 169/200, Train metric: 1.1316
Estimator 170/200, Train metric: 1.1261
Estimator 171/200, Train metric: 1.1291
Estimator 172/200, Train metric: 1.1167
Estimator 173/200, Train metric: 1.1177
Estimator 174/200, Train metric: 1.0910
Estimator 175/200, Train metric: 1.0556
Estimator 176/200, Train metric: 1.0288
Estimator 177/200, Train metric: 1.0310
Estimator 178/200, Train metric: 1.0227
Estimator 179/200, Train metric: 1.0003
Estimator 180/200, Train metric: 0.9706
Estimator 181/200, Train metric: 0.9466
Estimator 182/200, Train metric: 0.9322
Estimator 183/200, Train metric: 0.9170
Estimator 184/200, Train metric: 0.8948
Estimator 185/200, Train metric: 0.8844
Estimator 186/200, Train metric: 0.8827
Estimator 187/200, Train metric: 0.8608
Estimator 188/200, Train metric: 0.8379
Estimator 189/200, Train metric: 0.8294
Estimator 190/200, Train metric: 0.8106
Estimator 191/200, Train metric: 0.7957
Estimator 192/200, Train metric: 0.7678
Estimator 193/200, Train metric: 0.7556
Estimator 194/200, Train metric: 0.7336
Estimator 195/200, Train metric: 0.7052
Estimator 196/200, Train metric: 0.6938
Estimator 197/200, Train metric: 0.6912
Estimator 198/200, Train metric: 0.6825
Estimator 199/200, Train metric: 0.6697
         0.05         0.1        0.15         0.2         0.3         0.4  \
0   73.331170   76.963454   78.706729   80.299623   82.623032   85.213333
1  134.578171  136.350563  137.057008  138.653137  141.424834  143.566956
2   97.637093   98.908497   99.602512  100.563068  101.246420  101.761000
3  254.963478  261.581815  266.621846  271.245599  278.660550  284.553992
4  153.973439  158.399155  162.699047  164.609485  168.893564  171.323245

          0.5         0.6         0.7         0.8        0.85         0.9  \
0   87.389343   89.120586   93.286205   96.014438   97.953654   99.349920
1  145.042831  146.968692  148.823199  150.386713  151.410044  153.207747
2  103.114811  104.212129  104.866873  106.157747  107.601744  108.034795
3  291.739685  297.993756  302.166556  308.086664  311.610832  317.340619
4  173.808105  177.121759  180.490869  183.003940  185.041256  186.906075

         0.95  Actual
0  101.633885   73.07
1  156.314043  141.67
2  108.886061  110.44
3  328.862376  275.01
4  189.895798  202.57

In [60]:
class validate:
    @staticmethod
    def coverage(int_pred, y_test):
        return {strat_name: np.mean((y_test >= int_pred[strat_name][:, 0]) & (y_test <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred): # Corrected: Removed y_test argument as it's not defined and not used
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        return {strat_name: np.sqrt(mean_squared_error(y_test, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = validate.width(int_pred)
        coverages = validate.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}

    @staticmethod
    def cond_coverage(int_pred, y_test, num_bins=10):
        cond_coverages = {}
        for strat_name in int_pred:
            widths = int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]
            bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
            digitized_widths = np.digitize(widths, bin_edges)
            strategy_cond_coverage = []
            for bin_num in range(1, num_bins + 1):
                indices_in_bin = np.where(digitized_widths == bin_num)[0]
                if len(indices_in_bin) > 0:
                    bin_coverage = np.mean((y_test[indices_in_bin] >= int_pred[strat_name][indices_in_bin, 0]) & (y_test[indices_in_bin] <= int_pred[strat_name][indices_in_bin, 1]))
                    strategy_cond_coverage.append(bin_coverage)
                else:
                    strategy_cond_coverage.append(np.nan) # or handle empty bins as needed
            cond_coverages[strat_name] = strategy_cond_coverage
        return cond_coverages


class visualize:
    @staticmethod
    def coverage(int_pred, y_test):
        return {strat_name: np.mean((y_test >= int_pred[strat_name][:, 0]) & (y_test.to_numpy() <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred):
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        return {strat_name: np.sqrt(mean_squared_error(y_test, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = visualize.width(int_pred)
        coverages = visualize.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}
    @staticmethod
    def goodness(y_true, y_pred, y_pred_low, y_pred_up, coverage, width, rmse, cwc, ax=None, title="Goodness Plot"):
        if ax is None:
            fig, ax = plt.subplots()
        n_samples = len(y_true)
        y_true_np = y_true.ravel() # Ensure y_true is numpy array and flattened

        # Determine points inside and outside the interval
        inside_interval = (y_true_np >= y_pred_low) & (y_true_np <= y_pred_up)
        outside_interval = ~inside_interval

        # Plot points inside the interval in green
        ax.scatter(y_true_np[inside_interval], y_pred[inside_interval], color='green', s=10, label='Inside Interval')
        # Plot points outside the interval in orange
        ax.scatter(y_true_np[outside_interval], y_pred[outside_interval], color='orange', s=10, label='Outside Interval')

        # Plot all ground truth values as blue crosses
        ax.scatter(y_true_np, y_true_np, color='blue', marker='x', s=30, linewidths=0.7, label='Ground Truth Values')


        ax.vlines(y_true_np, y_pred_low, y_pred_up, color='gray', alpha=0.5, label='Prediction Intervals')
        ax.plot([min(y_true_np), max(y_true_np)], [min(y_true_np), max(y_true_np)], linestyle='--', color='blue', label='Ideal Prediction Line') # Changed label for clarity
        ax.set_xlabel('Ground Truth')
        ax.set_ylabel('Predictions')
        ax.set_title(f'{title}\nCoverage: {coverage*100:.2f}%, Width: {width:.2f}, RMSE: {rmse:.2f}, CWC: {cwc:.2f}')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def width_size_occurrence(int_pred, train_intervals, num_bins=10, ax=None, x_lim=None, title="Width Size Occurrence"):
        if ax is None:
            fig, ax = plt.subplots()

        # Calculate interval widths for test and train sets
        widths_test = np.abs(int_pred[:, 1] - int_pred[:, 0])
        widths_train = np.abs(train_intervals[:, 1] - train_intervals[:, 0])

        # Plot histograms for both train and test widths
        ax.hist(widths_test, bins=num_bins, alpha=0.6, label='Test Interval Widths', color='red')
        ax.hist(widths_train, bins=num_bins, alpha=0.4, label='Train Interval Widths', color='blue')


        if x_lim is not None:
            ax.set_xlim(x_lim)
        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Occurrence (Frequency)')
        ax.set_title(f'{title} - Interval Width Occurrence')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def coverage_by_width(y_test, int_pred, miscoverage, cond_coverages, num_bins=10, ax=None, title="Coverage vs Width"):
        if ax is None:
            fig, ax = plt.subplots()

        widths = int_pred[:, 1] - int_pred[:, 0]
        bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
        bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
        bin_width = bin_edges[1] - bin_edges[0]

        ax.bar(bin_centers, cond_coverages, width=bin_width, color='blue', alpha=0.7, edgecolor='black', linewidth=0.8, label='Conditional Coverage')
        ax.axhline(1 - miscoverage, color='red', linestyle='--', label=f'Nominal Coverage ({(1 - miscoverage)*100:.0f}%)')

        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Conditional Coverage')
        ax.set_title(f'{title} - Coverage vs Interval Width')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

In [61]:

def to_numpy_1d(y):
    return y.to_numpy().ravel() if hasattr(y, "to_numpy") else np.asarray(y).ravel()


def weighted_quantile(values, weights, q):
    sorter = np.argsort(values)
    values, weights = values[sorter], weights[sorter]
    cdf = np.cumsum(weights) / np.sum(weights)
    return np.interp(q, cdf, values)



# ============================================================
# NexCP for PGBM (Excel-safe, NexCP-style, NO RETURNS)
# ============================================================

def conformal_predictions_NEXCP_PGBM(
    model_class,
    best_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    decay=0.99,
    n_folds=5,
    n_bootstrap=50,
    seed=123,
):

    warnings.filterwarnings("ignore")
    np.random.seed(seed)

    # ========================================================
    # Data conversion (PGBM-specific)
    # ========================================================
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy() if hasattr(X_test, "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    STRATEGIES = {
        "NexCP-Split": "NexCP Split",
        "NexCP-Full": "NexCP Full",
        "NexCP-J+aB": "NexCP Jackknife+ aB",
        "NexCP-CV+": "NexCP CV+",
    }

    y_pred, int_pred = {}, {}

    # ========================================================
    # Fit base model
    # ========================================================
    base_model = model_class(**best_params)
    base_model.fit(Xtr, ytr)

    yhat_tr = base_model.predict(Xtr)
    yhat_te = base_model.predict(Xte)
    residuals = np.abs(ytr - yhat_tr)

    # ========================================================
    # NexCP – Split (Exponentially Weighted)
    # ========================================================
    weights = decay ** np.arange(len(residuals) - 1, -1, -1)
    q = weighted_quantile(residuals, weights, 1 - alpha)

    y_pred["NexCP-Split"] = yhat_te
    int_pred["NexCP-Split"] = np.c_[yhat_te - q, yhat_te + q]

    # ========================================================
    # NexCP – Full
    # ========================================================
    q = np.quantile(residuals, 1 - alpha)
    y_pred["NexCP-Full"] = yhat_te
    int_pred["NexCP-Full"] = np.c_[yhat_te - q, yhat_te + q]

    # ========================================================
    # NexCP – Jackknife+ aB
    # ========================================================
    rng = np.random.default_rng(seed)
    lowers, uppers, preds = [], [], []

    for _ in range(n_bootstrap):
        idx = rng.choice(len(Xtr), len(Xtr), replace=True)
        m = model_class(**best_params)
        m.fit(Xtr[idx], ytr[idx])

        q = np.quantile(np.abs(ytr[idx] - m.predict(Xtr[idx])), 1 - alpha)
        p = m.predict(Xte)

        preds.append(p)
        lowers.append(p - q)
        uppers.append(p + q)

    y_pred["NexCP-J+aB"] = np.mean(preds, axis=0)
    int_pred["NexCP-J+aB"] = np.c_[np.min(lowers, axis=0), np.max(uppers, axis=0)]

    # ========================================================
    # NexCP – CV+
    # ========================================================
    kf = KFold(n_splits=n_folds, shuffle=True, random_state=seed)
    lowers, uppers, preds = [], [], []

    for tr_idx, cal_idx in kf.split(Xtr):
        m = model_class(**best_params)
        m.fit(Xtr[tr_idx], ytr[tr_idx])

        q = np.quantile(np.abs(ytr[cal_idx] - m.predict(Xtr[cal_idx])), 1 - alpha)
        p = m.predict(Xte)

        preds.append(p)
        lowers.append(p - q)
        uppers.append(p + q)

    y_pred["NexCP-CV+"] = np.mean(preds, axis=0)
    int_pred["NexCP-CV+"] = np.c_[np.mean(lowers, axis=0), np.mean(uppers, axis=0)]

    # ========================================================
    # Metrics + Summary
    # ========================================================
    summary_rows = []
    values_dict = {}

    print("\n===== NEXCP (PGBM) RESULTS =====")

    for s in STRATEGIES:
        ymin, ymax = int_pred[s].T
        yhat = y_pred[s]

        coverage = np.mean((yte >= ymin) & (yte <= ymax))
        width = np.mean(ymax - ymin)
        rmse = np.sqrt(mean_squared_error(yte, yhat))

        print(f"{STRATEGIES[s]} - Coverage: {coverage*100:.3f}% | Width: {width:.3f}")

        summary_rows.append({
            "Strategy": STRATEGIES[s],
            "Coverage": coverage,
            "Width": width,
            "RMSE": rmse,
        })

        values_dict[f"{s}_true"] = yte
        values_dict[f"{s}_pred"] = yhat
        values_dict[f"{s}_lower"] = ymin
        values_dict[f"{s}_upper"] = ymax

    summary_df = pd.DataFrame(summary_rows)
    values_df = pd.DataFrame(values_dict)

    # ========================================================
    # Plotting (SAVE ONLY — NO SHOW)
    # ========================================================
    idx = np.arange(len(yte))
    plot_buffers = {}

    for s in STRATEGIES:
        fig, ax = plt.subplots(figsize=(10, 4))

        ax.scatter(idx, yte, s=10, color="blue", alpha=0.7, label="True")
        ax.fill_between(idx, int_pred[s][:, 0], int_pred[s][:, 1],
                        color="gray", alpha=0.5, label="Prediction interval")
        ax.plot(idx, y_pred[s], color="red", lw=1, label="Predicted mean")

        ax.set_title(f"{STRATEGIES[s]} ({model_name})")
        ax.set_xlabel("Sample Number")
        ax.set_ylabel("EWQI")
        ax.legend(loc="upper left")

        plt.tight_layout()

        buf = io.BytesIO()
        fig.savefig(buf, format="png")
        buf.seek(0)
        plot_buffers[s] = buf

        plt.close(fig)

    # ========================================================
    # Excel Export (append-safe)
    # ========================================================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary sheet ----
        sheet_name = "NEXCP_PGBM_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot sheets ----
        for s, buf in plot_buffers.items():
            img = Image(buf)
            sheet_name = f"NEXCP_PGBM_Plot_{s}"
            base = sheet_name
            i = 1
            while sheet_name in wb.sheetnames:
                sheet_name = f"{base}_{i}"
                i += 1
            ws = wb.create_sheet(sheet_name)
            ws.add_image(img, "A1")

        # ---- Values sheet ----
        sheet_name = "NEXCP_PGBM_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)


conformal_predictions_NEXCP_PGBM(
    model_class=PGBMWrapper,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="PGBM",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/PGBM.xlsx",
    alpha=0.05,
)

Streaming output truncated to the last 5000 lines.
Estimator 30/200, Train metric: 11.8576
Estimator 31/200, Train metric: 11.8692
Estimator 32/200, Train metric: 11.5886
Estimator 33/200, Train metric: 11.3054
Estimator 34/200, Train metric: 10.9890
Estimator 35/200, Train metric: 10.9951
Estimator 36/200, Train metric: 10.7527
Estimator 37/200, Train metric: 10.4485
Estimator 38/200, Train metric: 10.2137
Estimator 39/200, Train metric: 9.9624
Estimator 40/200, Train metric: 9.9813
Estimator 41/200, Train metric: 9.7673
Estimator 42/200, Train metric: 9.6456
Estimator 43/200, Train metric: 9.4282
Estimator 44/200, Train metric: 9.3345
Estimator 45/200, Train metric: 9.0863
Estimator 46/200, Train metric: 9.1038
Estimator 47/200, Train metric: 8.9025
Estimator 48/200, Train metric: 8.9130
Estimator 49/200, Train metric: 8.8415
Estimator 50/200, Train metric: 8.6416
Estimator 51/200, Train metric: 8.4170
Estimator 52/200, Train metric: 8.3368
Estimator 53/200, Train metric: 8.3509
Estimator 54/200, Train metric: 8.1555
Estimator 55/200, Train metric: 8.0009
Estimator 56/200, Train metric: 7.8027
Estimator 57/200, Train metric: 7.6334
Estimator 58/200, Train metric: 7.6568
Estimator 59/200, Train metric: 7.5764
Estimator 60/200, Train metric: 7.4261
Estimator 61/200, Train metric: 7.2616
Estimator 62/200, Train metric: 7.1306
Estimator 63/200, Train metric: 6.9063
Estimator 64/200, Train metric: 6.8732
Estimator 65/200, Train metric: 6.7160
Estimator 66/200, Train metric: 6.5963
Estimator 67/200, Train metric: 6.6073
Estimator 68/200, Train metric: 6.4784
Estimator 69/200, Train metric: 6.4062
Estimator 70/200, Train metric: 6.2847
Estimator 71/200, Train metric: 6.0890
Estimator 72/200, Train metric: 6.0910
Estimator 73/200, Train metric: 6.0064
Estimator 74/200, Train metric: 6.0222
Estimator 75/200, Train metric: 5.8801
Estimator 76/200, Train metric: 5.7605
Estimator 77/200, Train metric: 5.6601
Estimator 78/200, Train metric: 5.5325
Estimator 79/200, Train metric: 5.5480
Estimator 80/200, Train metric: 5.4437
Estimator 81/200, Train metric: 5.3367
Estimator 82/200, Train metric: 5.3289
Estimator 83/200, Train metric: 5.3413
Estimator 84/200, Train metric: 5.2223
Estimator 85/200, Train metric: 5.0942
Estimator 86/200, Train metric: 4.9732
Estimator 87/200, Train metric: 4.8635
Estimator 88/200, Train metric: 4.7544
Estimator 89/200, Train metric: 4.6361
Estimator 90/200, Train metric: 4.5642
Estimator 91/200, Train metric: 4.5737
Estimator 92/200, Train metric: 4.5888
Estimator 93/200, Train metric: 4.4894
Estimator 94/200, Train metric: 4.3888
Estimator 95/200, Train metric: 4.3065
Estimator 96/200, Train metric: 4.2168
Estimator 97/200, Train metric: 4.1192
Estimator 98/200, Train metric: 4.0364
Estimator 99/200, Train metric: 3.9456
Estimator 100/200, Train metric: 3.9368
Estimator 101/200, Train metric: 3.8685
Estimator 102/200, Train metric: 3.8734
Estimator 103/200, Train metric: 3.7772
Estimator 104/200, Train metric: 3.7230
Estimator 105/200, Train metric: 3.6378
Estimator 106/200, Train metric: 3.5769
Estimator 107/200, Train metric: 3.4822
Estimator 108/200, Train metric: 3.4200
Estimator 109/200, Train metric: 3.3518
Estimator 110/200, Train metric: 3.2892
Estimator 111/200, Train metric: 3.1909
Estimator 112/200, Train metric: 3.1806
Estimator 113/200, Train metric: 3.1066
Estimator 114/200, Train metric: 3.0422
Estimator 115/200, Train metric: 2.9085
Estimator 116/200, Train metric: 2.8626
Estimator 117/200, Train metric: 2.8201
Estimator 118/200, Train metric: 2.8013
Estimator 119/200, Train metric: 2.8122
Estimator 120/200, Train metric: 2.8163
Estimator 121/200, Train metric: 2.7215
Estimator 122/200, Train metric: 2.6665
Estimator 123/200, Train metric: 2.6109
Estimator 124/200, Train metric: 2.5646
Estimator 125/200, Train metric: 2.5700
Estimator 126/200, Train metric: 2.5294
Estimator 127/200, Train metric: 2.4650
Estimator 128/200, Train metric: 2.4182
Estimator 129/200, Train metric: 2.3497
Estimator 130/200, Train metric: 2.3218
Estimator 131/200, Train metric: 2.3185
Estimator 132/200, Train metric: 2.2743
Estimator 133/200, Train metric: 2.2798
Estimator 134/200, Train metric: 2.2301
Estimator 135/200, Train metric: 2.1877
Estimator 136/200, Train metric: 2.1930
Estimator 137/200, Train metric: 2.1523
Estimator 138/200, Train metric: 2.1139
Estimator 139/200, Train metric: 2.0493
Estimator 140/200, Train metric: 2.0157
Estimator 141/200, Train metric: 1.9773
Estimator 142/200, Train metric: 1.9483
Estimator 143/200, Train metric: 1.9577
Estimator 144/200, Train metric: 1.9544
Estimator 145/200, Train metric: 1.8917
Estimator 146/200, Train metric: 1.9009
Estimator 147/200, Train metric: 1.8675
Estimator 148/200, Train metric: 1.8347
Estimator 149/200, Train metric: 1.8136
Estimator 150/200, Train metric: 1.7835
Estimator 151/200, Train metric: 1.7379
Estimator 152/200, Train metric: 1.6989
Estimator 153/200, Train metric: 1.6988
Estimator 154/200, Train metric: 1.6592
Estimator 155/200, Train metric: 1.6380
Estimator 156/200, Train metric: 1.6178
Estimator 157/200, Train metric: 1.5834
Estimator 158/200, Train metric: 1.5503
Estimator 159/200, Train metric: 1.5137
Estimator 160/200, Train metric: 1.5049
Estimator 161/200, Train metric: 1.4707
Estimator 162/200, Train metric: 1.4456
Estimator 163/200, Train metric: 1.4082
Estimator 164/200, Train metric: 1.3814
Estimator 165/200, Train metric: 1.3564
Estimator 166/200, Train metric: 1.3377
Estimator 167/200, Train metric: 1.3008
Estimator 168/200, Train metric: 1.2647
Estimator 169/200, Train metric: 1.2351
Estimator 170/200, Train metric: 1.2309
Estimator 171/200, Train metric: 1.2155
Estimator 172/200, Train metric: 1.1992
Estimator 173/200, Train metric: 1.1693
Estimator 174/200, Train metric: 1.1172
Estimator 175/200, Train metric: 1.1146
Estimator 176/200, Train metric: 1.0951
Estimator 177/200, Train metric: 1.0828
Estimator 178/200, Train metric: 1.0519
Estimator 179/200, Train metric: 1.0344
Estimator 180/200, Train metric: 1.0325
Estimator 181/200, Train metric: 1.0340
Estimator 182/200, Train metric: 1.0213
Estimator 183/200, Train metric: 0.9966
Estimator 184/200, Train metric: 0.9738
Estimator 185/200, Train metric: 0.9534
Estimator 186/200, Train metric: 0.9364
Estimator 187/200, Train metric: 0.9110
Estimator 188/200, Train metric: 0.8915
Estimator 189/200, Train metric: 0.8703
Estimator 190/200, Train metric: 0.8674
Estimator 191/200, Train metric: 0.8510
Estimator 192/200, Train metric: 0.8500
Estimator 193/200, Train metric: 0.8335
Estimator 194/200, Train metric: 0.8131
Estimator 195/200, Train metric: 0.7950
Estimator 196/200, Train metric: 0.7828
Estimator 197/200, Train metric: 0.7676
Estimator 198/200, Train metric: 0.7697
Estimator 199/200, Train metric: 0.7499
Training on CPU
Estimator 0/200, Train metric: 36.2460
Estimator 1/200, Train metric: 34.3978
Estimator 2/200, Train metric: 32.1582
Estimator 3/200, Train metric: 29.2977
Estimator 4/200, Train metric: 27.0400
Estimator 5/200, Train metric: 24.9290
Estimator 6/200, Train metric: 23.2369
Estimator 7/200, Train metric: 21.5256
Estimator 8/200, Train metric: 19.5964
Estimator 9/200, Train metric: 17.7625
Estimator 10/200, Train metric: 16.4821
Estimator 11/200, Train metric: 15.4246
Estimator 12/200, Train metric: 14.2245
Estimator 13/200, Train metric: 13.4513
Estimator 14/200, Train metric: 13.0012
Estimator 15/200, Train metric: 12.6714
Estimator 16/200, Train metric: 12.3560
Estimator 17/200, Train metric: 11.8467
Estimator 18/200, Train metric: 11.5335
Estimator 19/200, Train metric: 10.9884
Estimator 20/200, Train metric: 10.5369
Estimator 21/200, Train metric: 10.2827
Estimator 22/200, Train metric: 10.0131
Estimator 23/200, Train metric: 9.7570
Estimator 24/200, Train metric: 9.4244
Estimator 25/200, Train metric: 9.3375
Estimator 26/200, Train metric: 9.0694
Estimator 27/200, Train metric: 8.8846
Estimator 28/200, Train metric: 8.5693
Estimator 29/200, Train metric: 8.3825
Estimator 30/200, Train metric: 8.1137
Estimator 31/200, Train metric: 7.9316
Estimator 32/200, Train metric: 7.7938
Estimator 33/200, Train metric: 7.6905
Estimator 34/200, Train metric: 7.4578
Estimator 35/200, Train metric: 7.2429
Estimator 36/200, Train metric: 7.0685
Estimator 37/200, Train metric: 6.7209
Estimator 38/200, Train metric: 6.5644
Estimator 39/200, Train metric: 6.3972
Estimator 40/200, Train metric: 6.2398
Estimator 41/200, Train metric: 6.0869
Estimator 42/200, Train metric: 6.0903
Estimator 43/200, Train metric: 5.9525
Estimator 44/200, Train metric: 5.9541
Estimator 45/200, Train metric: 5.9093
Estimator 46/200, Train metric: 5.7739
Estimator 47/200, Train metric: 5.6576
Estimator 48/200, Train metric: 5.5154
Estimator 49/200, Train metric: 5.3814
Estimator 50/200, Train metric: 5.2772
Estimator 51/200, Train metric: 5.1834
Estimator 52/200, Train metric: 5.1250
Estimator 53/200, Train metric: 5.0734
Estimator 54/200, Train metric: 4.9864
Estimator 55/200, Train metric: 4.9865
Estimator 56/200, Train metric: 4.8683
Estimator 57/200, Train metric: 4.7721
Estimator 58/200, Train metric: 4.6779
Estimator 59/200, Train metric: 4.6101
Estimator 60/200, Train metric: 4.5208
Estimator 61/200, Train metric: 4.4368
Estimator 62/200, Train metric: 4.3707
Estimator 63/200, Train metric: 4.2589
Estimator 64/200, Train metric: 4.2641
Estimator 65/200, Train metric: 4.1679
Estimator 66/200, Train metric: 4.1538
Estimator 67/200, Train metric: 4.1599
Estimator 68/200, Train metric: 4.0799
Estimator 69/200, Train metric: 4.0113
Estimator 70/200, Train metric: 3.9515
Estimator 71/200, Train metric: 3.8346
Estimator 72/200, Train metric: 3.7755
Estimator 73/200, Train metric: 3.7808
Estimator 74/200, Train metric: 3.6927
Estimator 75/200, Train metric: 3.6164
Estimator 76/200, Train metric: 3.5182
Estimator 77/200, Train metric: 3.4582
Estimator 78/200, Train metric: 3.4094
Estimator 79/200, Train metric: 3.3581
Estimator 80/200, Train metric: 3.3664
Estimator 81/200, Train metric: 3.3647
Estimator 82/200, Train metric: 3.3101
Estimator 83/200, Train metric: 3.3089
Estimator 84/200, Train metric: 3.2549
Estimator 85/200, Train metric: 3.1826
Estimator 86/200, Train metric: 3.1411
Estimator 87/200, Train metric: 3.1431
Estimator 88/200, Train metric: 3.1431
Estimator 89/200, Train metric: 3.1485
Estimator 90/200, Train metric: 3.1689
Estimator 91/200, Train metric: 3.1039
Estimator 92/200, Train metric: 3.0507
Estimator 93/200, Train metric: 3.0271
Estimator 94/200, Train metric: 2.9359
Estimator 95/200, Train metric: 2.9500
Estimator 96/200, Train metric: 2.9689
Estimator 97/200, Train metric: 2.8844
Estimator 98/200, Train metric: 2.8205
Estimator 99/200, Train metric: 2.8338
Estimator 100/200, Train metric: 2.7852
Estimator 101/200, Train metric: 2.7200
Estimator 102/200, Train metric: 2.6689
Estimator 103/200, Train metric: 2.6769
Estimator 104/200, Train metric: 2.6273
Estimator 105/200, Train metric: 2.5864
Estimator 106/200, Train metric: 2.5498
Estimator 107/200, Train metric: 2.5337
Estimator 108/200, Train metric: 2.5379
Estimator 109/200, Train metric: 2.5021
Estimator 110/200, Train metric: 2.4329
Estimator 111/200, Train metric: 2.3813
Estimator 112/200, Train metric: 2.2922
Estimator 113/200, Train metric: 2.2525
Estimator 114/200, Train metric: 2.1973
Estimator 115/200, Train metric: 2.1427
Estimator 116/200, Train metric: 2.1441
Estimator 117/200, Train metric: 2.0668
Estimator 118/200, Train metric: 2.0320
Estimator 119/200, Train metric: 2.0033
Estimator 120/200, Train metric: 2.0134
Estimator 121/200, Train metric: 1.9740
Estimator 122/200, Train metric: 1.9776
Estimator 123/200, Train metric: 1.9044
Estimator 124/200, Train metric: 1.9069
Estimator 125/200, Train metric: 1.8835
Estimator 126/200, Train metric: 1.8423
Estimator 127/200, Train metric: 1.8116
Estimator 128/200, Train metric: 1.8120
Estimator 129/200, Train metric: 1.7900
Estimator 130/200, Train metric: 1.7508
Estimator 131/200, Train metric: 1.7311
Estimator 132/200, Train metric: 1.7218
Estimator 133/200, Train metric: 1.6595
Estimator 134/200, Train metric: 1.6438
Estimator 135/200, Train metric: 1.6044
Estimator 136/200, Train metric: 1.5644
Estimator 137/200, Train metric: 1.5072
Estimator 138/200, Train metric: 1.5096
Estimator 139/200, Train metric: 1.4682
Estimator 140/200, Train metric: 1.4411
Estimator 141/200, Train metric: 1.4147
Estimator 142/200, Train metric: 1.4158
Estimator 143/200, Train metric: 1.4030
Estimator 144/200, Train metric: 1.3853
Estimator 145/200, Train metric: 1.3303
Estimator 146/200, Train metric: 1.3312
Estimator 147/200, Train metric: 1.3079
Estimator 148/200, Train metric: 1.2831
Estimator 149/200, Train metric: 1.2521
Estimator 150/200, Train metric: 1.2536
Estimator 151/200, Train metric: 1.2098
Estimator 152/200, Train metric: 1.2119
Estimator 153/200, Train metric: 1.1794
Estimator 154/200, Train metric: 1.1587
Estimator 155/200, Train metric: 1.1372
Estimator 156/200, Train metric: 1.0945
Estimator 157/200, Train metric: 1.0664
Estimator 158/200, Train metric: 1.0663
Estimator 159/200, Train metric: 1.0340
Estimator 160/200, Train metric: 1.0305
Estimator 161/200, Train metric: 1.0080
Estimator 162/200, Train metric: 0.9898
Estimator 163/200, Train metric: 0.9659
Estimator 164/200, Train metric: 0.9504
Estimator 165/200, Train metric: 0.9302
Estimator 166/200, Train metric: 0.9291
Estimator 167/200, Train metric: 0.9271
Estimator 168/200, Train metric: 0.9137
Estimator 169/200, Train metric: 0.8943
Estimator 170/200, Train metric: 0.8807
Estimator 171/200, Train metric: 0.8747
Estimator 172/200, Train metric: 0.8768
Estimator 173/200, Train metric: 0.8594
Estimator 174/200, Train metric: 0.8441
Estimator 175/200, Train metric: 0.8348
Estimator 176/200, Train metric: 0.8312
Estimator 177/200, Train metric: 0.8313
Estimator 178/200, Train metric: 0.8179
Estimator 179/200, Train metric: 0.7877
Estimator 180/200, Train metric: 0.7750
Estimator 181/200, Train metric: 0.7643
Estimator 182/200, Train metric: 0.7517
Estimator 183/200, Train metric: 0.7530
Estimator 184/200, Train metric: 0.7397
Estimator 185/200, Train metric: 0.7143
Estimator 186/200, Train metric: 0.6898
Estimator 187/200, Train metric: 0.6776
Estimator 188/200, Train metric: 0.6676
Estimator 189/200, Train metric: 0.6689
Estimator 190/200, Train metric: 0.6458
Estimator 191/200, Train metric: 0.6337
Estimator 192/200, Train metric: 0.6211
Estimator 193/200, Train metric: 0.6072
Estimator 194/200, Train metric: 0.5879
Estimator 195/200, Train metric: 0.5876
Estimator 196/200, Train metric: 0.5861
Estimator 197/200, Train metric: 0.5717
Estimator 198/200, Train metric: 0.5710
Estimator 199/200, Train metric: 0.5601
Training on CPU
Estimator 0/200, Train metric: 49.9442
Estimator 1/200, Train metric: 45.6901
Estimator 2/200, Train metric: 42.1540
Estimator 3/200, Train metric: 38.3658
Estimator 4/200, Train metric: 34.8890
Estimator 5/200, Train metric: 32.0652
Estimator 6/200, Train metric: 29.8386
Estimator 7/200, Train metric: 27.7887
Estimator 8/200, Train metric: 25.6123
Estimator 9/200, Train metric: 24.8523
Estimator 10/200, Train metric: 23.5015
Estimator 11/200, Train metric: 22.2908
Estimator 12/200, Train metric: 20.7529
Estimator 13/200, Train metric: 20.0761
Estimator 14/200, Train metric: 18.9424
Estimator 15/200, Train metric: 18.4312
Estimator 16/200, Train metric: 17.6468
Estimator 17/200, Train metric: 16.9185
Estimator 18/200, Train metric: 16.0708
Estimator 19/200, Train metric: 15.1186
Estimator 20/200, Train metric: 14.3603
Estimator 21/200, Train metric: 13.6184
Estimator 22/200, Train metric: 12.7483
Estimator 23/200, Train metric: 12.0155
Estimator 24/200, Train metric: 11.4326
Estimator 25/200, Train metric: 11.1496
Estimator 26/200, Train metric: 10.6256
Estimator 27/200, Train metric: 10.4669
Estimator 28/200, Train metric: 10.1207
Estimator 29/200, Train metric: 9.8211
Estimator 30/200, Train metric: 9.6949
Estimator 31/200, Train metric: 9.6122
Estimator 32/200, Train metric: 9.2830
Estimator 33/200, Train metric: 9.0849
Estimator 34/200, Train metric: 8.8397
Estimator 35/200, Train metric: 8.5954
Estimator 36/200, Train metric: 8.3932
Estimator 37/200, Train metric: 8.3955
Estimator 38/200, Train metric: 8.2620
Estimator 39/200, Train metric: 8.0055
Estimator 40/200, Train metric: 7.8390
Estimator 41/200, Train metric: 7.8288
Estimator 42/200, Train metric: 7.5932
Estimator 43/200, Train metric: 7.3608
Estimator 44/200, Train metric: 7.0507
Estimator 45/200, Train metric: 6.8788
Estimator 46/200, Train metric: 6.7210
Estimator 47/200, Train metric: 6.5643
Estimator 48/200, Train metric: 6.5737
Estimator 49/200, Train metric: 6.4030
Estimator 50/200, Train metric: 6.2949
Estimator 51/200, Train metric: 6.1507
Estimator 52/200, Train metric: 6.1427
Estimator 53/200, Train metric: 6.0105
Estimator 54/200, Train metric: 5.8896
Estimator 55/200, Train metric: 5.7141
Estimator 56/200, Train metric: 5.6035
Estimator 57/200, Train metric: 5.5090
Estimator 58/200, Train metric: 5.4010
Estimator 59/200, Train metric: 5.2831
Estimator 60/200, Train metric: 5.2802
Estimator 61/200, Train metric: 5.1647
Estimator 62/200, Train metric: 5.1644
Estimator 63/200, Train metric: 5.1707
Estimator 64/200, Train metric: 5.0479
Estimator 65/200, Train metric: 4.9500
Estimator 66/200, Train metric: 4.8502
Estimator 67/200, Train metric: 4.7353
Estimator 68/200, Train metric: 4.7392
Estimator 69/200, Train metric: 4.6378
Estimator 70/200, Train metric: 4.5500
Estimator 71/200, Train metric: 4.5533
Estimator 72/200, Train metric: 4.5734
Estimator 73/200, Train metric: 4.4493
Estimator 74/200, Train metric: 4.4660
Estimator 75/200, Train metric: 4.3755
Estimator 76/200, Train metric: 4.3034
Estimator 77/200, Train metric: 4.2225
Estimator 78/200, Train metric: 4.0993
Estimator 79/200, Train metric: 3.9871
Estimator 80/200, Train metric: 3.9957
Estimator 81/200, Train metric: 3.8900
Estimator 82/200, Train metric: 3.7908
Estimator 83/200, Train metric: 3.7497
Estimator 84/200, Train metric: 3.6590
Estimator 85/200, Train metric: 3.6733
Estimator 86/200, Train metric: 3.6145
Estimator 87/200, Train metric: 3.5666
Estimator 88/200, Train metric: 3.5055
Estimator 89/200, Train metric: 3.4262
Estimator 90/200, Train metric: 3.3969
Estimator 91/200, Train metric: 3.3938
Estimator 92/200, Train metric: 3.3922
Estimator 93/200, Train metric: 3.2974
Estimator 94/200, Train metric: 3.3046
Estimator 95/200, Train metric: 3.3166
Estimator 96/200, Train metric: 3.3119
Estimator 97/200, Train metric: 3.2326
Estimator 98/200, Train metric: 3.1614
Estimator 99/200, Train metric: 3.1218
Estimator 100/200, Train metric: 3.0954
Estimator 101/200, Train metric: 3.0537
Estimator 102/200, Train metric: 2.9655
Estimator 103/200, Train metric: 2.9191
Estimator 104/200, Train metric: 2.8337
Estimator 105/200, Train metric: 2.8294
Estimator 106/200, Train metric: 2.8333
Estimator 107/200, Train metric: 2.8458
Estimator 108/200, Train metric: 2.7927
Estimator 109/200, Train metric: 2.8018
Estimator 110/200, Train metric: 2.8128
Estimator 111/200, Train metric: 2.7403
Estimator 112/200, Train metric: 2.6777
Estimator 113/200, Train metric: 2.6322
Estimator 114/200, Train metric: 2.5840
Estimator 115/200, Train metric: 2.5822
Estimator 116/200, Train metric: 2.5141
Estimator 117/200, Train metric: 2.4572
Estimator 118/200, Train metric: 2.3978
Estimator 119/200, Train metric: 2.3343
Estimator 120/200, Train metric: 2.2881
Estimator 121/200, Train metric: 2.2381
Estimator 122/200, Train metric: 2.1889
Estimator 123/200, Train metric: 2.1957
Estimator 124/200, Train metric: 2.1945
Estimator 125/200, Train metric: 2.1464
Estimator 126/200, Train metric: 2.0896
Estimator 127/200, Train metric: 2.0490
Estimator 128/200, Train metric: 1.9916
Estimator 129/200, Train metric: 1.9655
Estimator 130/200, Train metric: 1.9398
Estimator 131/200, Train metric: 1.8888
Estimator 132/200, Train metric: 1.8866

In [62]:
def conformal_predictions_online_super_PGBM(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    strategies="all",
    window_min=50,
    window_max=500,
    window_grid=(25, 50, 100, 200, 400),
    n_bootstrap=30,
    seed=123,
):

    warnings.filterwarnings("ignore")
    np.random.seed(seed)

    STRATEGIES = {
        "Online-Split": "Online Split",
        "Online-CV+": "Online CV+",
        "Online-J+aB": "Online Jackknife+ aB",
        "SAOCP": "SAOCP",
        "SF-OGD": "SF-OGD",
        "FACI": "FACI",
        "MFCS-Split": "MFCS Split",
        "MFCS-Full": "MFCS Full",
    }

    if strategies == "all":
        strategies = list(STRATEGIES.keys())

    # --------------------------------------------------------
    # Safe NumPy conversion (PGBM-specific)
    # --------------------------------------------------------
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy() if hasattr(X_test, "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # --------------------------------------------------------
    # Base model (trained once)
    # --------------------------------------------------------
    base_model = model_class(**model_params)
    base_model.fit(Xtr, ytr)

    yhat_train = base_model.predict(Xtr)

    # --------------------------------------------------------
    # Streaming predictions
    # --------------------------------------------------------
    X_all = np.vstack([Xtr, Xte])
    y_all = np.concatenate([ytr, yte])

    n_train = len(Xtr)
    T = len(y_all)

    y_hat_all = np.zeros(T)
    y_hat_all[:n_train] = yhat_train

    for t in range(n_train, T):
        y_hat_all[t] = base_model.predict(X_all[t:t + 1])[0]

    residuals = np.abs(y_all - y_hat_all)

    y_pred, int_pred = {}, {}

    # ========================================================
    # Online Split
    # ========================================================
    if "Online-Split" in strategies:
        q = np.quantile(residuals[:n_train], 1 - alpha)
        y_pred["Online-Split"] = y_hat_all[n_train:]
        int_pred["Online-Split"] = np.c_[y_pred["Online-Split"] - q,
                                          y_pred["Online-Split"] + q]

    # ========================================================
    # Online CV+
    # ========================================================
    if "Online-CV+" in strategies:
        lower, upper = [], []
        for t in range(n_train, T):
            q = np.quantile(residuals[:t], 1 - alpha)
            lower.append(y_hat_all[t] - q)
            upper.append(y_hat_all[t] + q)
        y_pred["Online-CV+"] = y_hat_all[n_train:]
        int_pred["Online-CV+"] = np.c_[lower, upper]

    # ========================================================
    # Online Jackknife+ aB
    # ========================================================
    if "Online-J+aB" in strategies:
        lowers, uppers, preds = [], [], []
        for _ in range(n_bootstrap):
            idx = np.random.choice(n_train, n_train, replace=True)
            m = model_class(**model_params)
            m.fit(Xtr[idx], ytr[idx])

            q = np.quantile(np.abs(ytr[idx] - m.predict(Xtr[idx])), 1 - alpha)
            p = m.predict(Xte)

            preds.append(p)
            lowers.append(p - q)
            uppers.append(p + q)

        y_pred["Online-J+aB"] = np.mean(preds, axis=0)
        int_pred["Online-J+aB"] = np.c_[np.min(lowers, axis=0),
                                        np.max(uppers, axis=0)]

    # ========================================================
    # SAOCP
    # ========================================================
    if "SAOCP" in strategies:
        lower, upper = [], []
        for t in range(n_train, T):
            w = min(max(window_min, t // 2), window_max)
            start = max(0, t - w)
            q = np.quantile(residuals[start:t], 1 - alpha)
            lower.append(y_hat_all[t] - q)
            upper.append(y_hat_all[t] + q)
        y_pred["SAOCP"] = y_hat_all[n_train:]
        int_pred["SAOCP"] = np.c_[lower, upper]

    # ========================================================
    # SF-OGD
    # ========================================================
    if "SF-OGD" in strategies:
        q_t = np.quantile(residuals[:n_train], 1 - alpha)
        lower, upper = [], []
        for t in range(n_train, T):
            grad = alpha - (residuals[t] <= q_t)
            eta = 1.0 / np.sqrt(t - n_train + 1)
            q_t = max(0.0, q_t - eta * grad)
            lower.append(y_hat_all[t] - q_t)
            upper.append(y_hat_all[t] + q_t)
        y_pred["SF-OGD"] = y_hat_all[n_train:]
        int_pred["SF-OGD"] = np.c_[lower, upper]

    # ========================================================
    # FACI
    # ========================================================
    if "FACI" in strategies:
        windows = list(window_grid)
        losses = np.zeros(len(windows))
        lower, upper = [], []
        for t in range(n_train, T):
            r_t = residuals[t]
            qs = []
            for i, w in enumerate(windows):
                start = max(0, t - w)
                q = np.quantile(residuals[start:t], 1 - alpha)
                qs.append(q)
                losses[i] += alpha * q + (r_t - q) * (r_t > q)
            q_star = qs[np.argmin(losses)]
            lower.append(y_hat_all[t] - q_star)
            upper.append(y_hat_all[t] + q_star)
        y_pred["FACI"] = y_hat_all[n_train:]
        int_pred["FACI"] = np.c_[lower, upper]

    # ========================================================
    # MFCS-Split ✅ (ADDED)
    # ========================================================
    if "MFCS-Split" in strategies:
        q = np.quantile(residuals[:n_train], 1 - alpha)
        y_pred["MFCS-Split"] = y_hat_all[n_train:]
        int_pred["MFCS-Split"] = np.c_[y_pred["MFCS-Split"] - q,
                                       y_pred["MFCS-Split"] + q]

    # ========================================================
    # MFCS-Full
    # ========================================================
    if "MFCS-Full" in strategies:
        lower, upper, preds = [], [], []
        for t in range(n_train, T):
            m = model_class(**model_params)
            m.fit(X_all[:t], y_all[:t])
            yhat = m.predict(X_all[t:t + 1])[0]
            q = np.quantile(np.abs(y_all[:t] - m.predict(X_all[:t])), 1 - alpha)
            preds.append(yhat)
            lower.append(yhat - q)
            upper.append(yhat + q)
        y_pred["MFCS-Full"] = np.array(preds)
        int_pred["MFCS-Full"] = np.c_[lower, upper]

    # ========================================================
    # Metrics + Summary
    # ========================================================
    summary_rows = []
    values_dict = {}

    print("\n===== ONLINE CP (PGBM) RESULTS =====")

    for s in y_pred:
        ymin, ymax = int_pred[s].T
        yhat = y_pred[s]

        coverage = np.mean((yte >= ymin) & (yte <= ymax))
        width = np.mean(ymax - ymin)
        rmse = np.sqrt(mean_squared_error(yte, yhat))

        print(f"{STRATEGIES[s]} - Coverage: {coverage*100:.3f}% | Width: {width:.3f}")

        summary_rows.append({
            "Strategy": STRATEGIES[s],
            "Coverage": coverage,
            "Width": width,
            "RMSE": rmse,
        })

        values_dict[f"{s}_true"] = yte
        values_dict[f"{s}_pred"] = yhat
        values_dict[f"{s}_lower"] = ymin
        values_dict[f"{s}_upper"] = ymax

    summary_df = pd.DataFrame(summary_rows)
    values_df = pd.DataFrame(values_dict)

    # ========================================================
    # Plotting (SAVE ONLY — NO SHOW)
    # ========================================================
    idx = np.arange(len(yte))
    plot_buffers = {}

    for s in y_pred:
        fig, ax = plt.subplots(figsize=(10, 4))

        ax.scatter(idx, yte, s=10, color="blue", alpha=0.7, label="True")
        ax.fill_between(idx, int_pred[s][:, 0], int_pred[s][:, 1],
                        color="gray", alpha=0.5, label="Prediction interval")
        ax.plot(idx, y_pred[s], color="red", lw=1, label="Predicted mean")

        ax.set_title(f"{STRATEGIES[s]} ({model_name})")
        ax.set_xlabel("Sample Number")
        ax.set_ylabel("EWQI")
        ax.legend(loc="upper left")

        plt.tight_layout()

        buf = io.BytesIO()
        fig.savefig(buf, format="png")
        buf.seek(0)
        plot_buffers[s] = buf

        plt.close(fig)

    # ========================================================
    # Excel Export (append-safe)
    # ========================================================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary ----
        sheet_name = "ONLINECP_PGBM_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plots ----
        for s, buf in plot_buffers.items():
            img = Image(buf)
            sheet_name = f"ONLINECP_PGBM_Plot_{s}"
            base = sheet_name
            i = 1
            while sheet_name in wb.sheetnames:
                sheet_name = f"{base}_{i}"
                i += 1
            ws = wb.create_sheet(sheet_name)
            ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "ONLINECP_PGBM_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)


conformal_predictions_online_super_PGBM(
    model_class=PGBMWrapper,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="PGBM",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/PGBM.xlsx",
    alpha=0.05,
    strategies="all",
)

Streaming output truncated to the last 5000 lines.
Estimator 34/200, Train metric: 6.0544
Estimator 35/200, Train metric: 5.9714
Estimator 36/200, Train metric: 5.8015
Estimator 37/200, Train metric: 5.6599
Estimator 38/200, Train metric: 5.6688
Estimator 39/200, Train metric: 5.4652
Estimator 40/200, Train metric: 5.2625
Estimator 41/200, Train metric: 5.0623
Estimator 42/200, Train metric: 4.9337
Estimator 43/200, Train metric: 4.8505
Estimator 44/200, Train metric: 4.7432
Estimator 45/200, Train metric: 4.5284
Estimator 46/200, Train metric: 4.4001
Estimator 47/200, Train metric: 4.2799
Estimator 48/200, Train metric: 4.1598
Estimator 49/200, Train metric: 4.0375
Estimator 50/200, Train metric: 3.9546
Estimator 51/200, Train metric: 3.8285
Estimator 52/200, Train metric: 3.7675
Estimator 53/200, Train metric: 3.6534
Estimator 54/200, Train metric: 3.5144
Estimator 55/200, Train metric: 3.4126
Estimator 56/200, Train metric: 3.3337
Estimator 57/200, Train metric: 3.2913
Estimator 58/200, Train metric: 3.2374
Estimator 59/200, Train metric: 3.1381
Estimator 60/200, Train metric: 3.0176
Estimator 61/200, Train metric: 2.8796
Estimator 62/200, Train metric: 2.8217
Estimator 63/200, Train metric: 2.6770
Estimator 64/200, Train metric: 2.6222
Estimator 65/200, Train metric: 2.5665
Estimator 66/200, Train metric: 2.4679
Estimator 67/200, Train metric: 2.4141
Estimator 68/200, Train metric: 2.3110
Estimator 69/200, Train metric: 2.2482
Estimator 70/200, Train metric: 2.2136
Estimator 71/200, Train metric: 2.1261
Estimator 72/200, Train metric: 2.0173
Estimator 73/200, Train metric: 1.9663
Estimator 74/200, Train metric: 1.9108
Estimator 75/200, Train metric: 1.8449
Estimator 76/200, Train metric: 1.7871
Estimator 77/200, Train metric: 1.7223
Estimator 78/200, Train metric: 1.6938
Estimator 79/200, Train metric: 1.6619
Estimator 80/200, Train metric: 1.6154
Estimator 81/200, Train metric: 1.5387
Estimator 82/200, Train metric: 1.4939
Estimator 83/200, Train metric: 1.4794
Estimator 84/200, Train metric: 1.4502
Estimator 85/200, Train metric: 1.4239
Estimator 86/200, Train metric: 1.4063
Estimator 87/200, Train metric: 1.3883
Estimator 88/200, Train metric: 1.3359
Estimator 89/200, Train metric: 1.3044
Estimator 90/200, Train metric: 1.2636
Estimator 91/200, Train metric: 1.2427
Estimator 92/200, Train metric: 1.2223
Estimator 93/200, Train metric: 1.1870
Estimator 94/200, Train metric: 1.1506
Estimator 95/200, Train metric: 1.1025
Estimator 96/200, Train metric: 1.0797
Estimator 97/200, Train metric: 1.0682
Estimator 98/200, Train metric: 1.0419
Estimator 99/200, Train metric: 1.0235
Estimator 100/200, Train metric: 0.9889
Estimator 101/200, Train metric: 0.9810
Estimator 102/200, Train metric: 0.9550
Estimator 103/200, Train metric: 0.9373
Estimator 104/200, Train metric: 0.9211
Estimator 105/200, Train metric: 0.8940
Estimator 106/200, Train metric: 0.8763
Estimator 107/200, Train metric: 0.8654
Estimator 108/200, Train metric: 0.8440
Estimator 109/200, Train metric: 0.8251
Estimator 110/200, Train metric: 0.8032
Estimator 111/200, Train metric: 0.7829
Estimator 112/200, Train metric: 0.7626
Estimator 113/200, Train metric: 0.7355
Estimator 114/200, Train metric: 0.7160
Estimator 115/200, Train metric: 0.7041
Estimator 116/200, Train metric: 0.6803
Estimator 117/200, Train metric: 0.6656
Estimator 118/200, Train metric: 0.6612
Estimator 119/200, Train metric: 0.6425
Estimator 120/200, Train metric: 0.6325
Estimator 121/200, Train metric: 0.6121
Estimator 122/200, Train metric: 0.5921
Estimator 123/200, Train metric: 0.5813
Estimator 124/200, Train metric: 0.5760
Estimator 125/200, Train metric: 0.5669
Estimator 126/200, Train metric: 0.5590
Estimator 127/200, Train metric: 0.5376
Estimator 128/200, Train metric: 0.5198
Estimator 129/200, Train metric: 0.5086
Estimator 130/200, Train metric: 0.5009
Estimator 131/200, Train metric: 0.4971
Estimator 132/200, Train metric: 0.4805
Estimator 133/200, Train metric: 0.4646
Estimator 134/200, Train metric: 0.4633
Estimator 135/200, Train metric: 0.4530
Estimator 136/200, Train metric: 0.4405
Estimator 137/200, Train metric: 0.4304
Estimator 138/200, Train metric: 0.4217
Estimator 139/200, Train metric: 0.4184
Estimator 140/200, Train metric: 0.4073
Estimator 141/200, Train metric: 0.4036
Estimator 142/200, Train metric: 0.3913
Estimator 143/200, Train metric: 0.3920
Estimator 144/200, Train metric: 0.3838
Estimator 145/200, Train metric: 0.3811
Estimator 146/200, Train metric: 0.3783
Estimator 147/200, Train metric: 0.3696
Estimator 148/200, Train metric: 0.3615
Estimator 149/200, Train metric: 0.3508
Estimator 150/200, Train metric: 0.3410
Estimator 151/200, Train metric: 0.3345
Estimator 152/200, Train metric: 0.3241
Estimator 153/200, Train metric: 0.3212
Estimator 154/200, Train metric: 0.3200
Estimator 155/200, Train metric: 0.3198
Estimator 156/200, Train metric: 0.3140
Estimator 157/200, Train metric: 0.3051
Estimator 158/200, Train metric: 0.3032
Estimator 159/200, Train metric: 0.2958
Estimator 160/200, Train metric: 0.2898
Estimator 161/200, Train metric: 0.2830
Estimator 162/200, Train metric: 0.2766
Estimator 163/200, Train metric: 0.2713
Estimator 164/200, Train metric: 0.2656
Estimator 165/200, Train metric: 0.2602
Estimator 166/200, Train metric: 0.2509
Estimator 167/200, Train metric: 0.2466
Estimator 168/200, Train metric: 0.2434
Estimator 169/200, Train metric: 0.2352
Estimator 170/200, Train metric: 0.2297
Estimator 171/200, Train metric: 0.2296
Estimator 172/200, Train metric: 0.2228
Estimator 173/200, Train metric: 0.2222
Estimator 174/200, Train metric: 0.2176
Estimator 175/200, Train metric: 0.2149
Estimator 176/200, Train metric: 0.2089
Estimator 177/200, Train metric: 0.2075
Estimator 178/200, Train metric: 0.2021
Estimator 179/200, Train metric: 0.1976
Estimator 180/200, Train metric: 0.1936
Estimator 181/200, Train metric: 0.1928
Estimator 182/200, Train metric: 0.1907
Estimator 183/200, Train metric: 0.1870
Estimator 184/200, Train metric: 0.1861
Estimator 185/200, Train metric: 0.1812
Estimator 186/200, Train metric: 0.1772
Estimator 187/200, Train metric: 0.1715
Estimator 188/200, Train metric: 0.1688
Estimator 189/200, Train metric: 0.1660
Estimator 190/200, Train metric: 0.1630
Estimator 191/200, Train metric: 0.1593
Estimator 192/200, Train metric: 0.1585
Estimator 193/200, Train metric: 0.1548
Estimator 194/200, Train metric: 0.1506
Estimator 195/200, Train metric: 0.1482
Estimator 196/200, Train metric: 0.1456
Estimator 197/200, Train metric: 0.1439
Estimator 198/200, Train metric: 0.1399
Estimator 199/200, Train metric: 0.1383
Training on CPU
Estimator 0/200, Train metric: 53.9711
Estimator 1/200, Train metric: 49.4718
Estimator 2/200, Train metric: 45.0353
Estimator 3/200, Train metric: 41.3290
Estimator 4/200, Train metric: 37.7304
Estimator 5/200, Train metric: 34.9688
Estimator 6/200, Train metric: 31.7979
Estimator 7/200, Train metric: 29.5458
Estimator 8/200, Train metric: 26.9805
Estimator 9/200, Train metric: 25.1939
Estimator 10/200, Train metric: 23.2923
Estimator 11/200, Train metric: 21.6152
Estimator 12/200, Train metric: 20.1606
Estimator 13/200, Train metric: 18.5683
Estimator 14/200, Train metric: 17.1619
Estimator 15/200, Train metric: 16.3024
Estimator 16/200, Train metric: 15.1450
Estimator 17/200, Train metric: 14.2723
Estimator 18/200, Train metric: 13.2816
Estimator 19/200, Train metric: 12.3546
Estimator 20/200, Train metric: 11.6570
Estimator 21/200, Train metric: 10.9986
Estimator 22/200, Train metric: 10.2906
Estimator 23/200, Train metric: 9.6652
Estimator 24/200, Train metric: 9.0837
Estimator 25/200, Train metric: 8.7125
Estimator 26/200, Train metric: 8.1628
Estimator 27/200, Train metric: 7.7704
Estimator 28/200, Train metric: 7.3728
Estimator 29/200, Train metric: 7.1411
Estimator 30/200, Train metric: 6.8642
Estimator 31/200, Train metric: 6.5784
Estimator 32/200, Train metric: 6.3028
Estimator 33/200, Train metric: 6.1374
Estimator 34/200, Train metric: 5.8894
Estimator 35/200, Train metric: 5.8071
Estimator 36/200, Train metric: 5.5463
Estimator 37/200, Train metric: 5.4742
Estimator 38/200, Train metric: 5.2758
Estimator 39/200, Train metric: 5.0856
Estimator 40/200, Train metric: 4.8726
Estimator 41/200, Train metric: 4.7214
Estimator 42/200, Train metric: 4.5503
Estimator 43/200, Train metric: 4.4011
Estimator 44/200, Train metric: 4.2377
Estimator 45/200, Train metric: 4.1279
Estimator 46/200, Train metric: 4.1038
Estimator 47/200, Train metric: 3.9462
Estimator 48/200, Train metric: 3.8339
Estimator 49/200, Train metric: 3.6851
Estimator 50/200, Train metric: 3.5988
Estimator 51/200, Train metric: 3.4680
Estimator 52/200, Train metric: 3.4076
Estimator 53/200, Train metric: 3.2801
Estimator 54/200, Train metric: 3.1920
Estimator 55/200, Train metric: 3.1225
Estimator 56/200, Train metric: 3.0847
Estimator 57/200, Train metric: 3.0384
Estimator 58/200, Train metric: 2.9586
Estimator 59/200, Train metric: 2.9174
Estimator 60/200, Train metric: 2.8420
Estimator 61/200, Train metric: 2.7566
Estimator 62/200, Train metric: 2.7060
Estimator 63/200, Train metric: 2.5913
Estimator 64/200, Train metric: 2.5307
Estimator 65/200, Train metric: 2.4835
Estimator 66/200, Train metric: 2.4272
Estimator 67/200, Train metric: 2.3909
Estimator 68/200, Train metric: 2.3363
Estimator 69/200, Train metric: 2.2847
Estimator 70/200, Train metric: 2.2196
Estimator 71/200, Train metric: 2.1466
Estimator 72/200, Train metric: 2.1495
Estimator 73/200, Train metric: 2.1135
Estimator 74/200, Train metric: 2.0620
Estimator 75/200, Train metric: 2.0201
Estimator 76/200, Train metric: 1.9790
Estimator 77/200, Train metric: 1.9314
Estimator 78/200, Train metric: 1.8658
Estimator 79/200, Train metric: 1.8455
Estimator 80/200, Train metric: 1.7971
Estimator 81/200, Train metric: 1.7396
Estimator 82/200, Train metric: 1.7179
Estimator 83/200, Train metric: 1.7046
Estimator 84/200, Train metric: 1.6528
Estimator 85/200, Train metric: 1.6337
Estimator 86/200, Train metric: 1.5779
Estimator 87/200, Train metric: 1.5436
Estimator 88/200, Train metric: 1.5023
Estimator 89/200, Train metric: 1.4797
Estimator 90/200, Train metric: 1.4235
Estimator 91/200, Train metric: 1.3591
Estimator 92/200, Train metric: 1.3237
Estimator 93/200, Train metric: 1.3095
Estimator 94/200, Train metric: 1.2860
Estimator 95/200, Train metric: 1.1977
Estimator 96/200, Train metric: 1.1504
Estimator 97/200, Train metric: 1.1383
Estimator 98/200, Train metric: 1.1189
Estimator 99/200, Train metric: 1.0985
Estimator 100/200, Train metric: 1.0588
Estimator 101/200, Train metric: 1.0308
Estimator 102/200, Train metric: 1.0204
Estimator 103/200, Train metric: 1.0082
Estimator 104/200, Train metric: 0.9764
Estimator 105/200, Train metric: 0.9504
Estimator 106/200, Train metric: 0.9386
Estimator 107/200, Train metric: 0.9068
Estimator 108/200, Train metric: 0.8776
Estimator 109/200, Train metric: 0.8488
Estimator 110/200, Train metric: 0.8371
Estimator 111/200, Train metric: 0.8303
Estimator 112/200, Train metric: 0.8020
Estimator 113/200, Train metric: 0.7907
Estimator 114/200, Train metric: 0.7849
Estimator 115/200, Train metric: 0.7629
Estimator 116/200, Train metric: 0.7465
Estimator 117/200, Train metric: 0.7268
Estimator 118/200, Train metric: 0.7172
Estimator 119/200, Train metric: 0.7012
Estimator 120/200, Train metric: 0.6937
Estimator 121/200, Train metric: 0.6795
Estimator 122/200, Train metric: 0.6587
Estimator 123/200, Train metric: 0.6522
Estimator 124/200, Train metric: 0.6308
Estimator 125/200, Train metric: 0.6121
Estimator 126/200, Train metric: 0.5996
Estimator 127/200, Train metric: 0.5859
Estimator 128/200, Train metric: 0.5708
Estimator 129/200, Train metric: 0.5668
Estimator 130/200, Train metric: 0.5548
Estimator 131/200, Train metric: 0.5462
Estimator 132/200, Train metric: 0.5348
Estimator 133/200, Train metric: 0.5326
Estimator 134/200, Train metric: 0.5236
Estimator 135/200, Train metric: 0.5074
Estimator 136/200, Train metric: 0.4973
Estimator 137/200, Train metric: 0.4864
Estimator 138/200, Train metric: 0.4683
Estimator 139/200, Train metric: 0.4607
Estimator 140/200, Train metric: 0.4404
Estimator 141/200, Train metric: 0.4291
Estimator 142/200, Train metric: 0.4267
Estimator 143/200, Train metric: 0.4153
Estimator 144/200, Train metric: 0.4081
Estimator 145/200, Train metric: 0.4002
Estimator 146/200, Train metric: 0.3905
Estimator 147/200, Train metric: 0.3860
Estimator 148/200, Train metric: 0.3833
Estimator 149/200, Train metric: 0.3727
Estimator 150/200, Train metric: 0.3645
Estimator 151/200, Train metric: 0.3569
Estimator 152/200, Train metric: 0.3478
Estimator 153/200, Train metric: 0.3384
Estimator 154/200, Train metric: 0.3294
Estimator 155/200, Train metric: 0.3168
Estimator 156/200, Train metric: 0.3110
Estimator 157/200, Train metric: 0.3052
Estimator 158/200, Train metric: 0.3002
Estimator 159/200, Train metric: 0.2977
Estimator 160/200, Train metric: 0.2963
Estimator 161/200, Train metric: 0.2940
Estimator 162/200, Train metric: 0.2909
Estimator 163/200, Train metric: 0.2886
Estimator 164/200, Train metric: 0.2775
Estimator 165/200, Train metric: 0.2750
Estimator 166/200, Train metric: 0.2685
Estimator 167/200, Train metric: 0.2669
Estimator 168/200, Train metric: 0.2630
Estimator 169/200, Train metric: 0.2509
Estimator 170/200, Train metric: 0.2487
Estimator 171/200, Train metric: 0.2422
Estimator 172/200, Train metric: 0.2405
Estimator 173/200, Train metric: 0.2365
Estimator 174/200, Train metric: 0.2354
Estimator 175/200, Train metric: 0.2322
Estimator 176/200, Train metric: 0.2265
Estimator 177/200, Train metric: 0.2170
Estimator 178/200, Train metric: 0.2153
Estimator 179/200, Train metric: 0.2118
Estimator 180/200, Train metric: 0.2033
Estimator 181/200, Train metric: 0.1972
Estimator 182/200, Train metric: 0.1909
Estimator 183/200, Train metric: 0.1883
Estimator 184/200, Train metric: 0.1865
Estimator 185/200, Train metric: 0.1810
Estimator 186/200, Train metric: 0.1764
Estimator 187/200, Train metric: 0.1711
Estimator 188/200, Train metric: 0.1686
Estimator 189/200, Train metric: 0.1641
Estimator 190/200, Train metric: 0.1615
Estimator 191/200, Train metric: 0.1600
Estimator 192/200, Train metric: 0.1578
Estimator 193/200, Train metric: 0.1521
Estimator 194/200, Train metric: 0.1507
Estimator 195/200, Train metric: 0.1501
Estimator 196/200, Train metric: 0.1482
Estimator 197/200, Train metric: 0.1440
Estimator 198/200, Train metric: 0.1396
Estimator 199/200, Train metric: 0.1379
Training on CPU
Estimator 0/200, Train metric: 55.4316
Estimator 1/200, Train metric: 50.5004
Estimator 2/200, Train metric: 45.8681
Estimator 3/200, Train metric: 41.7206
Estimator 4/200, Train metric: 38.0193
Estimator 5/200, Train metric: 34.6205
Estimator 6/200, Train metric: 32.0989
Estimator 7/200, Train metric: 29.4609
Estimator 8/200, Train metric: 26.8698
Estimator 9/200, Train metric: 24.8458
Estimator 10/200, Train metric: 23.0458
Estimator 11/200, Train metric: 21.1926
Estimator 12/200, Train metric: 19.6714
Estimator 13/200, Train metric: 18.5023
Estimator 14/200, Train metric: 17.2789
Estimator 15/200, Train metric: 16.3415
Estimator 16/200, Train metric: 15.1690
Estimator 17/200, Train metric: 14.2223
Estimator 18/200, Train metric: 13.1757
Estimator 19/200, Train metric: 12.3394
Estimator 20/200, Train metric: 11.6186
Estimator 21/200, Train metric: 11.1686
Estimator 22/200, Train metric: 10.3551
Estimator 23/200, Train metric: 9.6635
Estimator 24/200, Train metric: 9.0346
Estimator 25/200, Train metric: 8.5936
Estimator 26/200, Train metric: 8.0436
Estimator 27/200, Train metric: 7.7066
Estimator 28/200, Train metric: 7.2599
Estimator 29/200, Train metric: 6.9380
Estimator 30/200, Train metric: 6.5893
Estimator 31/200, Train metric: 6.2542
Estimator 32/200, Train metric: 5.9877
Estimator 33/200, Train metric: 5.9195
Estimator 34/200, Train metric: 5.7686
Estimator 35/200, Train metric: 5.6061
Estimator 36/200, Train metric: 5.4330
Estimator 37/200, Train metric: 5.2201
Estimator 38/200, Train metric: 5.1230
Estimator 39/200, Train metric: 4.9209
Estimator 40/200, Train metric: 4.8437
Estimator 41/200, Train metric: 4.6688
Estimator 42/200, Train metric: 4.4692
Estimator 43/200, Train metric: 4.3407
Estimator 44/200, Train metric: 4.2336
Estimator 45/200, Train metric: 4.1029
Estimator 46/200, Train metric: 4.0150
Estimator 47/200, Train metric: 3.8982
Estimator 48/200, Train metric: 3.8064
Estimator 49/200, Train metric: 3.6836
Estimator 50/200, Train metric: 3.6064
Estimator 51/200, Train metric: 3.5150
Estimator 52/200, Train metric: 3.3911
Estimator 53/200, Train metric: 3.3425
Estimator 54/200, Train metric: 3.2284
Estimator 55/200, Train metric: 3.1594
Estimator 56/200, Train metric: 3.0429
Estimator 57/200, Train metric: 2.9350
Estimator 58/200, Train metric: 2.8148
Estimator 59/200, Train metric: 2.7828
Estimator 60/200, Train metric: 2.7020
Estimator 61/200, Train metric: 2.6409
Estimator 62/200, Train metric: 2.5825
Estimator 63/200, Train metric: 2.5613
Estimator 64/200, Train metric: 2.4858
Estimator 65/200, Train metric: 2.4063
Estimator 66/200, Train metric: 2.3427
Estimator 67/200, Train metric: 2.2843
Estimator 68/200, Train metric: 2.2243
Estimator 69/200, Train metric: 2.1667
Estimator 70/200, Train metric: 2.0956
Estimator 71/200, Train metric: 2.0139
Estimator 72/200, Train metric: 1.9620
Estimator 73/200, Train metric: 1.9612
Estimator 74/200, Train metric: 1.9164
Estimator 75/200, Train metric: 1.8523
Estimator 76/200, Train metric: 1.8317
Estimator 77/200, Train metric: 1.7962
Estimator 78/200, Train metric: 1.7598
Estimator 79/200, Train metric: 1.7198
Estimator 80/200, Train metric: 1.7069
Estimator 81/200, Train metric: 1.6397
Estimator 82/200, Train metric: 1.6165
Estimator 83/200, Train metric: 1.5718
Estimator 84/200, Train metric: 1.5471
Estimator 85/200, Train metric: 1.4878
Estimator 86/200, Train metric: 1.4777
Estimator 87/200, Train metric: 1.4192
Estimator 88/200, Train metric: 1.4062
Estimator 89/200, Train metric: 1.3394
Estimator 90/200, Train metric: 1.2848
Estimator 91/200, Train metric: 1.2293
Estimator 92/200, Train metric: 1.1920
Estimator 93/200, Train metric: 1.1836
Estimator 94/200, Train metric: 1.1475
Estimator 95/200, Train metric: 1.1232
Estimator 96/200, Train metric: 1.1021
Estimator 97/200, Train metric: 1.0985
Estimator 98/200, Train metric: 1.0829
Estimator 99/200, Train metric: 1.0518
Estimator 100/200, Train metric: 1.0279
Estimator 101/200, Train metric: 0.9930
Estimator 102/200, Train metric: 0.9839
Estimator 103/200, Train metric: 0.9730
Estimator 104/200, Train metric: 0.9533
Estimator 105/200, Train metric: 0.9127
Estimator 106/200, Train metric: 0.8961
Estimator 107/200, Train metric: 0.8849
Estimator 108/200, Train metric: 0.8773
Estimator 109/200, Train metric: 0.8660
Estimator 110/200, Train metric: 0.8367
Estimator 111/200, Train metric: 0.8334
Estimator 112/200, Train metric: 0.7888
Estimator 113/200, Train metric: 0.7667
Estimator 114/200, Train metric: 0.7618
Estimator 115/200, Train metric: 0.7338
Estimator 116/200, Train metric: 0.7234
Estimator 117/200, Train metric: 0.6995
Estimator 118/200, Train metric: 0.6866
Estimator 119/200, Train metric: 0.6646
Estimator 120/200, Train metric: 0.6475
Estimator 121/200, Train metric: 0.6375
Estimator 122/200, Train metric: 0.6147
Estimator 123/200, Train metric: 0.6097
Estimator 124/200, Train metric: 0.5974
Estimator 125/200, Train metric: 0.5819
Estimator 126/200, Train metric: 0.5602
Estimator 127/200, Train metric: 0.5484
Estimator 128/200, Train metric: 0.5367
Estimator 129/200, Train metric: 0.5235
Estimator 130/200, Train metric: 0.5045
Estimator 131/200, Train metric: 0.4893
Estimator 132/200, Train metric: 0.4814
Estimator 133/200, Train metric: 0.4637
Estimator 134/200, Train metric: 0.4541
Estimator 135/200, Train metric: 0.4505
Estimator 136/200, Train metric: 0.4400

In [63]:
def conformal_predictions_COP_PGBM(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    lr=0.05,
    T_burnin=50,
    scale=0.5,
    random_state=123,
):

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)

    # =========================================================
    # Safe NumPy conversion (PGBM-specific)
    # =========================================================
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy() if hasattr(X_test, "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # =========================================================
    # Train base PGBM model
    # =========================================================
    model = model_class(**model_params)
    model.fit(Xtr, ytr)

    y_pred_test = model.predict(Xte).ravel()
    y_pred_train = model.predict(Xtr).ravel()

    # Absolute residuals (symmetric COP)
    scores_test = np.abs(yte - y_pred_test)
    scores_train = np.abs(ytr - y_pred_train)

    T_test = len(scores_test)

    # =========================================================
    # COP initialization
    # =========================================================
    init_q = np.quantile(scores_train, 1 - alpha)

    qs = np.zeros(T_test)
    qts = np.zeros(T_test)
    integrators = np.zeros(T_test)
    covereds = np.zeros(T_test)

    qs[0] = init_q
    qts[0] = init_q

    # =========================================================
    # Online COP loop
    # =========================================================
    for t in range(T_test - 1):

        covereds[t] = 1 if qs[t] >= scores_test[t] else 0

        # Standard COP gradient
        grad = alpha if covereds[t] else -(1 - alpha)

        # Distribution-informed (optimistic) gradient
        if t < T_burnin:
            grad_i = 0.0
        else:
            window_s = scores_test[t - T_burnin : t]
            target = qts[t] - lr * grad
            grad_i = np.mean(window_s <= target) - (1 - alpha)

        # Updates
        integrator = -scale * grad_i
        qts[t + 1] = qts[t] - lr * grad
        integrators[t + 1] = lr * integrator
        qs[t + 1] = max(0.0, qts[t + 1] + integrators[t + 1])

    covereds[-1] = 1 if qs[-1] >= scores_test[-1] else 0

    # =========================================================
    # Prediction intervals
    # =========================================================
    ymin = y_pred_test - qs
    ymax = y_pred_test + qs

    # =========================================================
    # Metrics
    # =========================================================
    rmse = np.sqrt(mean_squared_error(yte, y_pred_test))
    coverage = np.mean(covereds)
    avg_width = np.mean(ymax - ymin)

    print(f"\n===== COP (PGBM) =====")
    print(f"Coverage : {coverage*100:.3f}%")
    print(f"Width    : {avg_width:.3f}")
    print(f"RMSE     : {rmse:.3f}")
    print(f"Final q  : {qs[-1]:.3f}")

    # =========================================================
    # Tables
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy": "COP",
        "Coverage": coverage,
        "Width": avg_width,
        "RMSE": rmse,
        "Alpha": alpha,
        "LR": lr,
        "Scale": scale,
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(yte)),
        "y_true": yte,
        "y_pred": y_pred_test,
        "ymin": ymin,
        "ymax": ymax,
        "width": ymax - ymin,
        "is_covered": covereds.astype(int),
        "score": scores_test,
        "adaptive_q": qs,
    })

    # =========================================================
    # Plot (SAVE ONLY)
    # =========================================================
    idx = np.arange(len(yte))
    fig, ax = plt.subplots(figsize=(10, 4))

    ax.scatter(idx, yte, s=10, color="blue", alpha=0.7, label="True")
    ax.fill_between(idx, ymin, ymax, color="gray", alpha=0.5, label="COP Interval")
    ax.plot(idx, y_pred_test, color="red", lw=1, label="Predicted mean")


    ax.set_title(f"COP ({model_name})")
    ax.set_xlabel("Sample Number")
    ax.set_ylabel("EWQI")
    ax.legend(loc="upper left")

    plt.tight_layout()
    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    buf.seek(0)
    plt.close(fig)

    # =========================================================
    # Excel export (append-safe)
    # =========================================================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary ----
        sheet_name = "COP_PGBM_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot ----
        img = Image(buf)
        sheet_name = "COP_PGBM_Plot"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1
        ws = wb.create_sheet(sheet_name)
        ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "COP_PGBM_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)

    return summary_df

conformal_predictions_COP_PGBM(
    model_class=PGBMWrapper,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="PGBM",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/PGBM.xlsx",
    alpha=0.05,
)

Training on CPU
Estimator 0/200, Train metric: 51.8040
Estimator 1/200, Train metric: 47.6403
Estimator 2/200, Train metric: 44.2211
Estimator 3/200, Train metric: 40.4811
Estimator 4/200, Train metric: 37.0778
Estimator 5/200, Train metric: 34.0711
Estimator 6/200, Train metric: 32.2726
Estimator 7/200, Train metric: 30.0074
Estimator 8/200, Train metric: 27.9378
Estimator 9/200, Train metric: 25.4829
Estimator 10/200, Train metric: 23.6093
Estimator 11/200, Train metric: 22.0989
Estimator 12/200, Train metric: 20.4743
Estimator 13/200, Train metric: 19.4300
Estimator 14/200, Train metric: 18.2014
Estimator 15/200, Train metric: 17.0535
Estimator 16/200, Train metric: 16.5485
Estimator 17/200, Train metric: 15.7829
Estimator 18/200, Train metric: 15.1467
Estimator 19/200, Train metric: 14.6958
Estimator 20/200, Train metric: 14.0259
Estimator 21/200, Train metric: 13.6423
Estimator 22/200, Train metric: 12.8222
Estimator 23/200, Train metric: 12.5842
Estimator 24/200, Train metric: 12.1847
Estimator 25/200, Train metric: 11.6684
Estimator 26/200, Train metric: 11.2312
Estimator 27/200, Train metric: 10.7562
Estimator 28/200, Train metric: 10.5753
Estimator 29/200, Train metric: 10.2691
Estimator 30/200, Train metric: 9.9803
Estimator 31/200, Train metric: 9.7237
Estimator 32/200, Train metric: 9.4549
Estimator 33/200, Train metric: 9.1564
Estimator 34/200, Train metric: 8.9626
Estimator 35/200, Train metric: 8.8029
Estimator 36/200, Train metric: 8.7466
Estimator 37/200, Train metric: 8.6531
Estimator 38/200, Train metric: 8.3499
Estimator 39/200, Train metric: 8.1236
Estimator 40/200, Train metric: 7.9707
Estimator 41/200, Train metric: 7.7555
Estimator 42/200, Train metric: 7.5853
Estimator 43/200, Train metric: 7.5657
Estimator 44/200, Train metric: 7.4670
Estimator 45/200, Train metric: 7.4512
Estimator 46/200, Train metric: 7.2707
Estimator 47/200, Train metric: 7.1833
Estimator 48/200, Train metric: 7.0673
Estimator 49/200, Train metric: 7.0357
Estimator 50/200, Train metric: 6.8528
Estimator 51/200, Train metric: 6.7405
Estimator 52/200, Train metric: 6.6605
Estimator 53/200, Train metric: 6.5991
Estimator 54/200, Train metric: 6.4035
Estimator 55/200, Train metric: 6.2739
Estimator 56/200, Train metric: 6.2639
Estimator 57/200, Train metric: 6.2217
Estimator 58/200, Train metric: 6.1139
Estimator 59/200, Train metric: 6.0467
Estimator 60/200, Train metric: 6.0631
Estimator 61/200, Train metric: 5.9333
Estimator 62/200, Train metric: 5.8259
Estimator 63/200, Train metric: 5.7376
Estimator 64/200, Train metric: 5.7314
Estimator 65/200, Train metric: 5.5767
Estimator 66/200, Train metric: 5.4692
Estimator 67/200, Train metric: 5.4702
Estimator 68/200, Train metric: 5.3803
Estimator 69/200, Train metric: 5.3269
Estimator 70/200, Train metric: 5.3060
Estimator 71/200, Train metric: 5.2349
Estimator 72/200, Train metric: 5.1693
Estimator 73/200, Train metric: 4.8893
Estimator 74/200, Train metric: 4.8614
Estimator 75/200, Train metric: 4.8651
Estimator 76/200, Train metric: 4.8591
Estimator 77/200, Train metric: 4.7915
Estimator 78/200, Train metric: 4.8018
Estimator 79/200, Train metric: 4.7054
Estimator 80/200, Train metric: 4.7221
Estimator 81/200, Train metric: 4.6383
Estimator 82/200, Train metric: 4.5345
Estimator 83/200, Train metric: 4.4447
Estimator 84/200, Train metric: 4.3372
Estimator 85/200, Train metric: 4.3289
Estimator 86/200, Train metric: 4.2374
Estimator 87/200, Train metric: 4.2368
Estimator 88/200, Train metric: 4.1623
Estimator 89/200, Train metric: 4.0954
Estimator 90/200, Train metric: 4.1103
Estimator 91/200, Train metric: 4.0138
Estimator 92/200, Train metric: 3.9284
Estimator 93/200, Train metric: 3.8706
Estimator 94/200, Train metric: 3.8135
Estimator 95/200, Train metric: 3.7593
Estimator 96/200, Train metric: 3.6942
Estimator 97/200, Train metric: 3.6330
Estimator 98/200, Train metric: 3.5067
Estimator 99/200, Train metric: 3.4673
Estimator 100/200, Train metric: 3.4349
Estimator 101/200, Train metric: 3.4092
Estimator 102/200, Train metric: 3.3616
Estimator 103/200, Train metric: 3.3446
Estimator 104/200, Train metric: 3.3003
Estimator 105/200, Train metric: 3.1971
Estimator 106/200, Train metric: 3.1340
Estimator 107/200, Train metric: 3.1221
Estimator 108/200, Train metric: 3.0452
Estimator 109/200, Train metric: 3.0063
Estimator 110/200, Train metric: 2.9227
Estimator 111/200, Train metric: 2.8307
Estimator 112/200, Train metric: 2.8136
Estimator 113/200, Train metric: 2.8140
Estimator 114/200, Train metric: 2.7575
Estimator 115/200, Train metric: 2.7517
Estimator 116/200, Train metric: 2.7050
Estimator 117/200, Train metric: 2.6911
Estimator 118/200, Train metric: 2.6886
Estimator 119/200, Train metric: 2.5974
Estimator 120/200, Train metric: 2.5433
Estimator 121/200, Train metric: 2.4873
Estimator 122/200, Train metric: 2.4070
Estimator 123/200, Train metric: 2.3512
Estimator 124/200, Train metric: 2.3201
Estimator 125/200, Train metric: 2.2739
Estimator 126/200, Train metric: 2.2502
Estimator 127/200, Train metric: 2.1926
Estimator 128/200, Train metric: 2.1904
Estimator 129/200, Train metric: 2.1388
Estimator 130/200, Train metric: 2.1075
Estimator 131/200, Train metric: 2.0979
Estimator 132/200, Train metric: 2.0400
Estimator 133/200, Train metric: 2.0300
Estimator 134/200, Train metric: 1.9849
Estimator 135/200, Train metric: 1.9291
Estimator 136/200, Train metric: 1.8432
Estimator 137/200, Train metric: 1.7957
Estimator 138/200, Train metric: 1.7428
Estimator 139/200, Train metric: 1.7009
Estimator 140/200, Train metric: 1.6871
Estimator 141/200, Train metric: 1.6713
Estimator 142/200, Train metric: 1.6485
Estimator 143/200, Train metric: 1.6406
Estimator 144/200, Train metric: 1.5997
Estimator 145/200, Train metric: 1.5324
Estimator 146/200, Train metric: 1.5229
Estimator 147/200, Train metric: 1.4887
Estimator 148/200, Train metric: 1.4771
Estimator 149/200, Train metric: 1.4751
Estimator 150/200, Train metric: 1.4819
Estimator 151/200, Train metric: 1.4413
Estimator 152/200, Train metric: 1.4051
Estimator 153/200, Train metric: 1.3925
Estimator 154/200, Train metric: 1.3659
Estimator 155/200, Train metric: 1.3431
Estimator 156/200, Train metric: 1.3318
Estimator 157/200, Train metric: 1.3028
Estimator 158/200, Train metric: 1.2947
Estimator 159/200, Train metric: 1.2778
Estimator 160/200, Train metric: 1.2508
Estimator 161/200, Train metric: 1.2084
Estimator 162/200, Train metric: 1.2117
Estimator 163/200, Train metric: 1.1798
Estimator 164/200, Train metric: 1.1813
Estimator 165/200, Train metric: 1.1651
Estimator 166/200, Train metric: 1.1619
Estimator 167/200, Train metric: 1.1536
Estimator 168/200, Train metric: 1.1444
Estimator 169/200, Train metric: 1.1316
Estimator 170/200, Train metric: 1.1261
Estimator 171/200, Train metric: 1.1291
Estimator 172/200, Train metric: 1.1167
Estimator 173/200, Train metric: 1.1177
Estimator 174/200, Train metric: 1.0910
Estimator 175/200, Train metric: 1.0556
Estimator 176/200, Train metric: 1.0288
Estimator 177/200, Train metric: 1.0310
Estimator 178/200, Train metric: 1.0227
Estimator 179/200, Train metric: 1.0003
Estimator 180/200, Train metric: 0.9706
Estimator 181/200, Train metric: 0.9466
Estimator 182/200, Train metric: 0.9322
Estimator 183/200, Train metric: 0.9170
Estimator 184/200, Train metric: 0.8948
Estimator 185/200, Train metric: 0.8844
Estimator 186/200, Train metric: 0.8827
Estimator 187/200, Train metric: 0.8608
Estimator 188/200, Train metric: 0.8379
Estimator 189/200, Train metric: 0.8294
Estimator 190/200, Train metric: 0.8106
Estimator 191/200, Train metric: 0.7957
Estimator 192/200, Train metric: 0.7678
Estimator 193/200, Train metric: 0.7556
Estimator 194/200, Train metric: 0.7336
Estimator 195/200, Train metric: 0.7052
Estimator 196/200, Train metric: 0.6938
Estimator 197/200, Train metric: 0.6912
Estimator 198/200, Train metric: 0.6825
Estimator 199/200, Train metric: 0.6697

===== COP (PGBM) =====
Coverage : 6.383%
Width    : 4.148
RMSE     : 13.684
Final q  : 3.053

  Strategy  Coverage     Width       RMSE  Alpha    LR  Scale
0      COP   0.06383  4.148357  13.684195   0.05  0.05    0.5

In [64]:
def conformal_predictions_EXTREME_PGBM(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    calib_size=0.2,
    gpd_threshold_quantile=0.95,
    n_bootstrap=30,
    random_state=123,
):

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)

    # --------------------------------------------------------
    # Safe NumPy conversion (PGBM-specific)
    # --------------------------------------------------------
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy() if hasattr(X_test, "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # --------------------------------------------------------
    # Train / calibration split
    # --------------------------------------------------------
    X_fit, X_cal, y_fit, y_cal = train_test_split(
        Xtr, ytr, test_size=calib_size, random_state=random_state, shuffle=True
    )

    # --------------------------------------------------------
    # Train model
    # --------------------------------------------------------
    model = model_class(**model_params)
    model.fit(X_fit, y_fit)

    y_pred_test = model.predict(Xte)
    y_pred_cal = model.predict(X_cal)

    # --------------------------------------------------------
    # Upper-tail nonconformity scores
    # --------------------------------------------------------
    scores = y_cal - y_pred_cal
    scores = scores[scores > 0]

    if len(scores) < 30:
        raise RuntimeError("Too few exceedances for EVT fitting.")

    # --------------------------------------------------------
    # Peaks-over-threshold
    # --------------------------------------------------------
    u = np.quantile(scores, gpd_threshold_quantile)
    excesses = scores[scores > u] - u

    # --------------------------------------------------------
    # Bootstrap EVT quantile
    # --------------------------------------------------------
    boot_q = []
    n_exc = len(excesses)
    n_scores = len(scores)

    for _ in range(n_bootstrap):
        res = np.random.choice(excesses, size=n_exc, replace=True)
        xi, _, sigma = genpareto.fit(res, floc=0)
        q = u + (sigma / xi) * ((n_scores / (n_scores * alpha)) ** xi - 1)
        boot_q.append(q)

    q_extreme = np.quantile(boot_q, 0.95)

    # --------------------------------------------------------
    # FINITE prediction intervals (for plotting & width)
    # --------------------------------------------------------
    ymin = y_pred_test - q_extreme
    ymax = y_pred_test + q_extreme

    # --------------------------------------------------------
    # Metrics (one-sided coverage)
    # --------------------------------------------------------
    rmse = np.sqrt(mean_squared_error(yte, y_pred_test))
    coverage = np.mean(yte <= ymax)
    width = q_extreme

    print(f"\n===== EXTREME CP (PGBM) =====")
    print(f"Coverage     : {coverage*100:.3f}%")
    print(f"Width        : {width:.3f}")
    print(f"RMSE         : {rmse:.3f}")
    print(f"q_extreme    : {q_extreme:.3f}")
    print(f"threshold_u  : {u:.3f}")
    print(f"#Exceedances : {len(scores)}")

    # --------------------------------------------------------
    # Summary table
    # --------------------------------------------------------
    summary_df = pd.DataFrame([{
        "Strategy": "EXTREME CP",
        "Coverage": coverage,
        "Width": width,
        "RMSE": rmse,
        "q_extreme": q_extreme,
        "threshold_u": u,
        "n_exceedances": len(scores),
    }])

    # --------------------------------------------------------
    # Values table
    # --------------------------------------------------------
    values_df = pd.DataFrame({
        "sample_index": np.arange(len(yte)),
        "y_true": yte,
        "y_pred": y_pred_test,
        "ymin": ymin,
        "ymax": ymax,
        "width": ymax - ymin,
        "is_covered": (yte <= ymax).astype(int),
        "residual": yte - y_pred_test,
    })

    # --------------------------------------------------------
    # Plot (SAVE ONLY — NO SHOW)
    # --------------------------------------------------------
    idx = np.arange(len(yte))
    fig, ax = plt.subplots(figsize=(10, 4))

    ax.scatter(idx, yte, s=10, color="blue", alpha=0.7, label="True")
    ax.fill_between(idx, ymin, ymax, alpha=0.4, label="Extreme PI")
    ax.plot(idx, y_pred_test, color="red", lw=1, label="Prediction")

    ax.set_title(f"Extreme CP ({model_name})")
    ax.set_xlabel("Sample Number")
    ax.set_ylabel("EWQI")
    ax.legend(loc="upper left")

    plt.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    buf.seek(0)
    plt.close(fig)

    # --------------------------------------------------------
    # Excel export (append-safe)
    # --------------------------------------------------------
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary ----
        sheet_name = "EXTREMECP_PGBM_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot ----
        img = Image(buf)
        sheet_name = "EXTREMECP_PGBM_Plot"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "EXTREMECP_PGBM_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)


# conformal_predictions_EXTREME_PGBM(
#     model_class=PGBMWrapper,
#     model_params=best_params,
#     X_train=X_train,
#     y_train=y_train,
#     X_test=X_test,
#     y_test=y_test,
#     model_name="PGBM",
#     excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/PGBM.xlsx",
#     alpha=0.05,
#     calib_size=0.3,
# )

In [65]:
def conformal_predictions_AlphaNet_PGBM(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    lambda_reg=20.0,
    num_epochs=50,
    batch_size=32,
    lr_alpha=1e-3,
    calib_fraction=0.5,
    num_runs=4,
    random_state=123,
):
    warnings.filterwarnings("ignore")
    np.random.seed(random_state)
    torch.manual_seed(random_state)
    device = "cuda" if torch.cuda.is_available() else "cpu"

    t_start_total = time.time()

    # =========================================================
    # Data conversion (PGBM-specific)
    # =========================================================
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy()  if hasattr(X_test,  "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # =========================================================
    # 1. Split training data → fit + calibration
    # =========================================================
    n_total = len(Xtr)
    n_fit   = int(n_total * (1 - calib_fraction))
    perm    = np.random.permutation(n_total)

    fit_idx   = perm[:n_fit]
    calib_idx = perm[n_fit:]

    X_fit,   y_fit   = Xtr[fit_idx],   ytr[fit_idx]
    X_calib, y_calib = Xtr[calib_idx],  ytr[calib_idx]
    n_calib = len(X_calib)

    alpha_min = 1.0 / (n_calib + 1) + 0.01
    print(f"  [Info] n_calib={n_calib} | alpha_min={alpha_min:.4f}")

    # =========================================================
    # 2. Train base PGBM model
    # =========================================================
    print(f"  [Step 2/9] Training base {model_name} model...")
    t0 = time.time()
    base_model = model_class(**model_params)
    base_model.fit(X_fit, y_fit)
    print(f"  [Step 2/9] Done in {_fmt_time(time.time()-t0)}")

    def _safe_predict(m, X):
        p = m.predict(X)
        return p.ravel() if hasattr(p, "ravel") else np.asarray(p).ravel()

    # =========================================================
    # 3. PRECOMPUTE all LOO scores
    # =========================================================
    print(f"  [Step 3/9] Precomputing {n_calib} LOO score vectors...")
    t0 = time.time()

    precomputed_scores = []
    precomputed_sums   = []

    iterator = tqdm(range(n_calib), desc="    LOO precompute", leave=False) if HAS_TQDM else range(n_calib)

    for i in iterator:
        loo_X = np.delete(X_calib, i, axis=0)
        loo_y = np.delete(y_calib, i, axis=0)
        scores_loo = np.abs(_safe_predict(base_model, loo_X) - loo_y)

        scores_tensor = torch.tensor(scores_loo, dtype=torch.float32).to(device)
        precomputed_scores.append(scores_tensor)
        precomputed_sums.append(scores_loo.sum())

    elapsed_precompute = time.time() - t0
    print(f"  [Step 3/9] Done in {_fmt_time(elapsed_precompute)}")

    X_alpha = torch.tensor(
        np.array(precomputed_sums).reshape(-1, 1),
        dtype=torch.float32,
    ).to(device)

    # =========================================================
    # 4. Train AlphaNet
    # =========================================================
    print(f"  [Step 4/9] Training AlphaNet: {num_runs} runs × {num_epochs} epochs")

    best_net  = None
    best_loss = np.inf
    history   = {"losses": [], "sizes": [], "alphas": []}

    t0_train = time.time()

    for run in range(num_runs):
        np.random.seed(run)
        torch.manual_seed(run)

        alpha_net = AlphaNet(input_dim=1, alpha_min=alpha_min).to(device)
        optimizer = optim.Adam(alpha_net.parameters(), lr=lr_alpha)

        dataset = TensorDataset(X_alpha, torch.arange(n_calib))
        loader  = DataLoader(dataset, batch_size=batch_size, shuffle=True)

        run_losses, run_sizes, run_alphas = [], [], []

        epoch_iter = (
            tqdm(range(num_epochs), desc=f"    Run {run+1}/{num_runs}", leave=False)
            if HAS_TQDM else range(num_epochs)
        )

        for epoch in epoch_iter:
            t_epoch_start = time.time()
            epoch_loss = epoch_size = epoch_alpha = 0.0

            for x_batch, idx_batch in loader:
                x_batch = x_batch.to(device)
                alpha_pred = alpha_net(x_batch)

                batch_sizes = []
                for j, idx in enumerate(idx_batch):
                    scores_t = precomputed_scores[idx.item()]
                    size_j = _interval_size(scores_t, alpha_pred[j])
                    batch_sizes.append(size_j)

                batch_sizes = torch.stack(batch_sizes)
                loss = (batch_sizes + lambda_reg * alpha_pred).mean()

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

                epoch_loss  += loss.item()
                epoch_size  += batch_sizes.mean().item()
                epoch_alpha += alpha_pred.mean().item()

            n_batches = len(loader)
            run_losses.append(epoch_loss  / n_batches)
            run_sizes.append(epoch_size   / n_batches)
            run_alphas.append(epoch_alpha / n_batches)

            epoch_time = time.time() - t_epoch_start

            if epoch % 10 == 0 or epoch == num_epochs - 1:
                epochs_done  = (run * num_epochs) + epoch + 1
                epochs_total = num_runs * num_epochs
                elapsed_train = time.time() - t0_train
                eta = (elapsed_train / epochs_done) * (epochs_total - epochs_done)

                print(
                    f"  λ={lambda_reg} | Run {run+1}/{num_runs} | "
                    f"Epoch {epoch}/{num_epochs} | "
                    f"Loss: {run_losses[-1]:.4f} | "
                    f"Size: {run_sizes[-1]:.4f} | "
                    f"α̃: {run_alphas[-1]:.4f} | "
                    f"⏱ {epoch_time:.2f}s/epoch | "
                    f"ETA: {_fmt_time(eta)}"
                )

        if run_losses[-1] < best_loss:
            best_loss = run_losses[-1]
            best_net  = alpha_net

        history["losses"].append(run_losses)
        history["sizes"].append(run_sizes)
        history["alphas"].append(run_alphas)

        print(f"  ✓ Run {run+1} complete | Final loss: {run_losses[-1]:.4f}")

    train_time = time.time() - t0_train
    print(f"  [Step 4/9] Training done in {_fmt_time(train_time)}")

    alpha_net = best_net
    alpha_net.eval()

    # =========================================================
    # 5. Compute conformal intervals on TEST set
    # =========================================================
    print(f"  [Step 5/9] Computing conformal intervals...")
    scores_calib = np.abs(_safe_predict(base_model, X_calib) - y_calib)
    sum_scores   = scores_calib.sum()

    with torch.no_grad():
        feat_test = torch.tensor([sum_scores], dtype=torch.float32).to(device)
        alpha_val = alpha_net(feat_test).item()

    denom = alpha_val * (n_calib + 1) - 1
    if denom <= 0:
        q = np.quantile(scores_calib, 1 - alpha)
        half_width = q
        print(f"  [Warning] α̃ too small; fallback q={q:.4f}")
    else:
        half_width = sum_scores / denom

    y_pred_test = _safe_predict(base_model, Xte)
    ymin = y_pred_test - half_width
    ymax = y_pred_test + half_width

    # =========================================================
    # 6. Metrics
    # =========================================================
    is_covered = ((yte >= ymin) & (yte <= ymax)).astype(int)
    coverage   = is_covered.mean()
    avg_width  = np.mean(ymax - ymin)
    rmse       = np.sqrt(mean_squared_error(yte, y_pred_test))

    total_time = time.time() - t_start_total

    print(f"\n{'='*55}")
    print(f"  ALPHANET CONFORMAL ({model_name})")
    print(f"{'='*55}")
    print(f"  Learned α̃     : {alpha_val:.4f}")
    print(f"  Half-width (r) : {half_width:.4f}")
    print(f"  Coverage       : {coverage*100:.3f}%")
    print(f"  Avg Width      : {avg_width:.4f}")
    print(f"  RMSE           : {rmse:.4f}")
    print(f"  Total time     : {_fmt_time(total_time)}")
    print(f"    ├─ Precompute: {_fmt_time(elapsed_precompute)}")
    print(f"    └─ Training  : {_fmt_time(train_time)}")
    print(f"{'='*55}")

    # =========================================================
    # 7. Summary & Values
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy":       "AlphaNet Conformal",
        "Coverage":       coverage,
        "Width":          avg_width,
        "RMSE":           rmse,
        "Alpha_nominal":  alpha,
        "Alpha_learned":  alpha_val,
        "Lambda_reg":     lambda_reg,
        "Total_time_sec": round(total_time, 2),
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(yte)),
        "y_true":       yte,
        "y_pred":       y_pred_test,
        "ymin":         ymin,
        "ymax":         ymax,
        "width":        ymax - ymin,
        "is_covered":   is_covered,
    })

    # =========================================================
    # 8. Plotting (SAVE ONLY)
    # =========================================================
    print(f"  [Step 8/9] Generating plots...")
    idx_arr = np.arange(len(yte))

    fig_pi, ax_pi = plt.subplots(figsize=(10, 4))
    ax_pi.scatter(idx_arr, yte, color="blue", s=10, alpha=0.7, label="True")
    ax_pi.fill_between(idx_arr, ymin, ymax, color="gray", alpha=0.5,
                       label=f"AlphaNet Interval (α̃={alpha_val:.3f})")
    ax_pi.plot(idx_arr, y_pred_test, color="red", lw=1, label="Predicted mean")
    ax_pi.set_title(f"AlphaNet Conformal ({model_name})")
    ax_pi.set_xlabel("Sample Number")
    ax_pi.set_ylabel("EWQI")
    ax_pi.legend(loc="upper left")
    plt.tight_layout()

    buf_pi = io.BytesIO()
    fig_pi.savefig(buf_pi, format="png")
    buf_pi.seek(0)
    plt.close(fig_pi)

    arr_losses = np.array(history["losses"])
    arr_sizes  = np.array(history["sizes"])
    arr_alphas = np.array(history["alphas"])
    epochs_arr = np.arange(1, num_epochs + 1)

    fig_tc, axs = plt.subplots(1, 3, figsize=(14, 4))
    for ax, data, ylabel, title in zip(
        axs,
        [arr_losses, arr_sizes, arr_alphas],
        ["Loss", "Mean Interval Size", r"Mean $\tilde{\alpha}$"],
        ["Training Loss", "Interval Size", r"Learned $\tilde{\alpha}$"],
    ):
        m = data.mean(axis=0)
        s = data.std(axis=0)
        ax.plot(epochs_arr, m, color="#0077bb")
        ax.fill_between(epochs_arr, m - s, m + s, color="#0077bb", alpha=0.25)
        ax.set_xlabel("Epoch")
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.grid(True, linewidth=0.5)
    plt.tight_layout()

    buf_tc = io.BytesIO()
    fig_tc.savefig(buf_tc, format="png")
    buf_tc.seek(0)
    plt.close(fig_tc)

    # =========================================================
    # 9. Excel Export
    # =========================================================
    if excel_file_path:
        print(f"  [Step 9/9] Saving to Excel...")
        try:
            wb = load_workbook(excel_file_path)
        except FileNotFoundError:
            from openpyxl import Workbook
            wb = Workbook()
            wb.remove(wb.active)

        def _unique_sheet(wb, name):
            base, i = name, 1
            while name in wb.sheetnames:
                name = f"{base}_{i}"; i += 1
            return name

        sn = _unique_sheet(wb, "AlphaNet_PGBM_Summary")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        img_pi = Image(buf_pi)
        sn = _unique_sheet(wb, "AlphaNet_PGBM_Plot_PI")
        ws = wb.create_sheet(sn)
        ws.add_image(img_pi, "A1")

        img_tc = Image(buf_tc)
        sn = _unique_sheet(wb, "AlphaNet_PGBM_Plot_Train")
        ws = wb.create_sheet(sn)
        ws.add_image(img_tc, "A1")

        sn = _unique_sheet(wb, "AlphaNet_PGBM_Values")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)
        print(f"  [Step 9/9] Saved!")

    print(f"\n  ✅ AlphaNet PGBM complete in {_fmt_time(total_time)}")
    return summary_df

In [66]:
conformal_predictions_AlphaNet_PGBM(
    model_class=PGBMWrapper,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="PGBM",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/PGBM.xlsx",
    alpha=0.05,
)

  [Info] n_calib=24 | alpha_min=0.0500
  [Step 2/9] Training base PGBM model...
Training on CPU
Estimator 0/200, Train metric: 58.9733
Estimator 1/200, Train metric: 55.7220
Estimator 2/200, Train metric: 54.6098
Estimator 3/200, Train metric: 51.5852
Estimator 4/200, Train metric: 48.8077
Estimator 5/200, Train metric: 45.2447
Estimator 6/200, Train metric: 41.7243
Estimator 7/200, Train metric: 39.1308
Estimator 8/200, Train metric: 37.4021
Estimator 9/200, Train metric: 34.9621
Estimator 10/200, Train metric: 33.1476
Estimator 11/200, Train metric: 31.8263
Estimator 12/200, Train metric: 29.8305
Estimator 13/200, Train metric: 28.2801
Estimator 14/200, Train metric: 28.1479
Estimator 15/200, Train metric: 27.5460
Estimator 16/200, Train metric: 26.9014
Estimator 17/200, Train metric: 25.3921
Estimator 18/200, Train metric: 24.0926
Estimator 19/200, Train metric: 23.0661
Estimator 20/200, Train metric: 22.8545
Estimator 21/200, Train metric: 21.7960
Estimator 22/200, Train metric: 20.9641
Estimator 23/200, Train metric: 19.9855
Estimator 24/200, Train metric: 19.4054
Estimator 25/200, Train metric: 18.7411
Estimator 26/200, Train metric: 18.0707
Estimator 27/200, Train metric: 17.6820
Estimator 28/200, Train metric: 17.5805
Estimator 29/200, Train metric: 17.0585
Estimator 30/200, Train metric: 16.4299
Estimator 31/200, Train metric: 15.8244
Estimator 32/200, Train metric: 15.3731
Estimator 33/200, Train metric: 14.9057
Estimator 34/200, Train metric: 14.8690
Estimator 35/200, Train metric: 14.4684
Estimator 36/200, Train metric: 14.0471
Estimator 37/200, Train metric: 13.5441
Estimator 38/200, Train metric: 13.1975
Estimator 39/200, Train metric: 12.9919
Estimator 40/200, Train metric: 13.0263
Estimator 41/200, Train metric: 13.0209
Estimator 42/200, Train metric: 12.6605
Estimator 43/200, Train metric: 12.6666
Estimator 44/200, Train metric: 12.5332
Estimator 45/200, Train metric: 12.3055
Estimator 46/200, Train metric: 11.9550
Estimator 47/200, Train metric: 11.6860
Estimator 48/200, Train metric: 11.3482
Estimator 49/200, Train metric: 11.1050
Estimator 50/200, Train metric: 11.0682
Estimator 51/200, Train metric: 11.0692
Estimator 52/200, Train metric: 11.0418
Estimator 53/200, Train metric: 10.7202
Estimator 54/200, Train metric: 10.4644
Estimator 55/200, Train metric: 10.2972
Estimator 56/200, Train metric: 10.0733
Estimator 57/200, Train metric: 9.8269
Estimator 58/200, Train metric: 9.6774
Estimator 59/200, Train metric: 9.5040
Estimator 60/200, Train metric: 9.4184
Estimator 61/200, Train metric: 9.2104
Estimator 62/200, Train metric: 8.9576
Estimator 63/200, Train metric: 8.6528
Estimator 64/200, Train metric: 8.6618
Estimator 65/200, Train metric: 8.4548
Estimator 66/200, Train metric: 8.4915
Estimator 67/200, Train metric: 8.4364
Estimator 68/200, Train metric: 8.3439
Estimator 69/200, Train metric: 8.0878
Estimator 70/200, Train metric: 7.9016
Estimator 71/200, Train metric: 7.7265
Estimator 72/200, Train metric: 7.6209
Estimator 73/200, Train metric: 7.6266
Estimator 74/200, Train metric: 7.4902
Estimator 75/200, Train metric: 7.3639
Estimator 76/200, Train metric: 7.2117
Estimator 77/200, Train metric: 7.1051
Estimator 78/200, Train metric: 7.0857
Estimator 79/200, Train metric: 7.0750
Estimator 80/200, Train metric: 6.9346
Estimator 81/200, Train metric: 6.9280
Estimator 82/200, Train metric: 6.8446
Estimator 83/200, Train metric: 6.5730
Estimator 84/200, Train metric: 6.5681
Estimator 85/200, Train metric: 6.3484
Estimator 86/200, Train metric: 6.1505
Estimator 87/200, Train metric: 6.0701
Estimator 88/200, Train metric: 6.0651
Estimator 89/200, Train metric: 5.9638
Estimator 90/200, Train metric: 5.7982
Estimator 91/200, Train metric: 5.7970
Estimator 92/200, Train metric: 5.6518
Estimator 93/200, Train metric: 5.5774
Estimator 94/200, Train metric: 5.4128
Estimator 95/200, Train metric: 5.2955
Estimator 96/200, Train metric: 5.1676
Estimator 97/200, Train metric: 5.1546
Estimator 98/200, Train metric: 5.0162
Estimator 99/200, Train metric: 4.8836
Estimator 100/200, Train metric: 4.7981
Estimator 101/200, Train metric: 4.6813
Estimator 102/200, Train metric: 4.6846
Estimator 103/200, Train metric: 4.5441
Estimator 104/200, Train metric: 4.4403
Estimator 105/200, Train metric: 4.3231
Estimator 106/200, Train metric: 4.3139
Estimator 107/200, Train metric: 4.2280
Estimator 108/200, Train metric: 4.1439
Estimator 109/200, Train metric: 4.0752
Estimator 110/200, Train metric: 3.9528
Estimator 111/200, Train metric: 3.8226
Estimator 112/200, Train metric: 3.7815
Estimator 113/200, Train metric: 3.6957
Estimator 114/200, Train metric: 3.5324
Estimator 115/200, Train metric: 3.4005
Estimator 116/200, Train metric: 3.2691
Estimator 117/200, Train metric: 3.2514
Estimator 118/200, Train metric: 3.1898
Estimator 119/200, Train metric: 3.1043
Estimator 120/200, Train metric: 3.0185
Estimator 121/200, Train metric: 2.9684
Estimator 122/200, Train metric: 2.9263
Estimator 123/200, Train metric: 2.8973
Estimator 124/200, Train metric: 2.8804
Estimator 125/200, Train metric: 2.8817
Estimator 126/200, Train metric: 2.8722
Estimator 127/200, Train metric: 2.7865
Estimator 128/200, Train metric: 2.7203
Estimator 129/200, Train metric: 2.6755
Estimator 130/200, Train metric: 2.6750
Estimator 131/200, Train metric: 2.6185
Estimator 132/200, Train metric: 2.5674
Estimator 133/200, Train metric: 2.5255
Estimator 134/200, Train metric: 2.4454
Estimator 135/200, Train metric: 2.4489
Estimator 136/200, Train metric: 2.4166
Estimator 137/200, Train metric: 2.3702
Estimator 138/200, Train metric: 2.3282
Estimator 139/200, Train metric: 2.2949
Estimator 140/200, Train metric: 2.2178
Estimator 141/200, Train metric: 2.2156
Estimator 142/200, Train metric: 2.2147
Estimator 143/200, Train metric: 2.1721
Estimator 144/200, Train metric: 2.1761
Estimator 145/200, Train metric: 2.1746
Estimator 146/200, Train metric: 2.1853
Estimator 147/200, Train metric: 2.1175
Estimator 148/200, Train metric: 2.0797
Estimator 149/200, Train metric: 2.0270
Estimator 150/200, Train metric: 2.0296
Estimator 151/200, Train metric: 2.0404
Estimator 152/200, Train metric: 1.9979
Estimator 153/200, Train metric: 1.9570
Estimator 154/200, Train metric: 1.9272
Estimator 155/200, Train metric: 1.8792
Estimator 156/200, Train metric: 1.8391
Estimator 157/200, Train metric: 1.8421
Estimator 158/200, Train metric: 1.8489
Estimator 159/200, Train metric: 1.8095
Estimator 160/200, Train metric: 1.8173
Estimator 161/200, Train metric: 1.7753
Estimator 162/200, Train metric: 1.7353
Estimator 163/200, Train metric: 1.6936
Estimator 164/200, Train metric: 1.6510
Estimator 165/200, Train metric: 1.6115
Estimator 166/200, Train metric: 1.5808
Estimator 167/200, Train metric: 1.5879
Estimator 168/200, Train metric: 1.5560
Estimator 169/200, Train metric: 1.5624
Estimator 170/200, Train metric: 1.5661
Estimator 171/200, Train metric: 1.5372
Estimator 172/200, Train metric: 1.5412
Estimator 173/200, Train metric: 1.5491
Estimator 174/200, Train metric: 1.5199
Estimator 175/200, Train metric: 1.4933
Estimator 176/200, Train metric: 1.4594
Estimator 177/200, Train metric: 1.4308
Estimator 178/200, Train metric: 1.3932
Estimator 179/200, Train metric: 1.3633
Estimator 180/200, Train metric: 1.3370
Estimator 181/200, Train metric: 1.3206
Estimator 182/200, Train metric: 1.2749
Estimator 183/200, Train metric: 1.2512
Estimator 184/200, Train metric: 1.2233
Estimator 185/200, Train metric: 1.2286
Estimator 186/200, Train metric: 1.2300
Estimator 187/200, Train metric: 1.2093
Estimator 188/200, Train metric: 1.2103
Estimator 189/200, Train metric: 1.1868
Estimator 190/200, Train metric: 1.1896
Estimator 191/200, Train metric: 1.1566
Estimator 192/200, Train metric: 1.1350
Estimator 193/200, Train metric: 1.1047
Estimator 194/200, Train metric: 1.1071
Estimator 195/200, Train metric: 1.0879
Estimator 196/200, Train metric: 1.0599
Estimator 197/200, Train metric: 1.0526
Estimator 198/200, Train metric: 1.0324
Estimator 199/200, Train metric: 1.0117
  [Step 2/9] Done in 1s
  [Step 3/9] Precomputing 24 LOO score vectors...

    LOO precompute:   0%|          | 0/24 [00:00<?, ?it/s]

  [Step 3/9] Done in 0s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 105.1062 | Size: 94.1353 | α̃: 0.5485 | ⏱ 0.01s/epoch | ETA: 5s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 69.3456 | Size: 49.3456 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 69.3456 | Size: 49.3456 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 69.3456 | Size: 49.3456 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 69.3456 | Size: 49.3456 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 69.3456 | Size: 49.3456 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  ✓ Run 1 complete | Final loss: 69.3456

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 69.3463 | Size: 49.3467 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 69.3456 | Size: 49.3456 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 69.3456 | Size: 49.3456 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 69.3456 | Size: 49.3456 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 69.3456 | Size: 49.3456 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 69.3456 | Size: 49.3456 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  ✓ Run 2 complete | Final loss: 69.3456

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 69.3456 | Size: 49.3456 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 69.3456 | Size: 49.3456 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 69.3456 | Size: 49.3456 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 69.3456 | Size: 49.3456 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 69.3456 | Size: 49.3456 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 69.3456 | Size: 49.3456 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  ✓ Run 3 complete | Final loss: 69.3456

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 69.3479 | Size: 49.3494 | α̃: 0.9999 | ⏱ 0.01s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 69.3456 | Size: 49.3456 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 69.3456 | Size: 49.3456 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 69.3456 | Size: 49.3456 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 69.3456 | Size: 49.3456 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 69.3456 | Size: 49.3456 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 69.3456
  [Step 4/9] Training done in 1s
  [Step 5/9] Computing conformal intervals...

=======================================================
  ALPHANET CONFORMAL (PGBM)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 24.6728
  Coverage       : 72.340%
  Avg Width      : 49.3456
  RMSE           : 23.6234
  Total time     : 2s
    ├─ Precompute: 0s
    └─ Training  : 1s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet PGBM complete in 2s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.723404,49.345634,23.623385,0.05,1.0,20.0,1.53

# **Conformal Predictions with TabNet**

In [67]:
best_params = get_best_model_params(best_scores_autosampler, 'TabNet')
print(best_params)

{'n_d': 8, 'n_a': 8, 'n_steps': 10, 'gamma': 1.0, 'lambda_sparse': 0.0001, 'optimizer_params': {'lr': 0.02}, 'mask_type': 'entmax', 'n_shared': 1, 'n_independent': 1, 'scheduler_params': {'step_size': 10, 'gamma': 0.9}, 'scheduler_fn': <class 'torch.optim.lr_scheduler.StepLR'>, 'seed': 42, 'verbose': 0}

In [68]:
class validate:
    @staticmethod
    def coverage(int_pred, y_test):
        y_arr = np.array(y_test)
        return {strat_name: np.mean((y_arr >= int_pred[strat_name][:, 0]) & (y_arr <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred):
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        y_arr = np.array(y_test)
        return {strat_name: np.sqrt(mean_squared_error(y_arr, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = validate.width(int_pred)
        coverages = validate.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}
    @staticmethod
    def cond_coverage(int_pred, y_test, num_bins=10):
        y_arr = np.array(y_test)
        cond_coverages = {}
        for strat_name in int_pred:
            widths = int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]
            bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
            digitized_widths = np.digitize(widths, bin_edges)
            strategy_cond_coverage = []
            for bin_num in range(1, num_bins + 1):
                indices_in_bin = np.where(digitized_widths == bin_num)[0]
                if len(indices_in_bin) > 0:
                    bin_coverage = np.mean((y_arr[indices_in_bin] >= int_pred[strat_name][indices_in_bin, 0]) &
                                           (y_arr[indices_in_bin] <= int_pred[strat_name][indices_in_bin, 1]))
                    strategy_cond_coverage.append(bin_coverage)
                else:
                    strategy_cond_coverage.append(np.nan)
            cond_coverages[strat_name] = strategy_cond_coverage
        return cond_coverages
class visualize:
    @staticmethod
    def goodness(y_true, y_pred, y_pred_low, y_pred_up, coverage, width, rmse, cwc, ax=None, title="Goodness Plot"):
        if ax is None:
            fig, ax = plt.subplots()
        y_true_np = np.array(y_true).ravel()
        inside_interval = (y_true_np >= y_pred_low) & (y_true_np <= y_pred_up)
        outside_interval = ~inside_interval
        ax.scatter(y_true_np[inside_interval], y_pred[inside_interval], color='green', s=10, label='Inside Interval')
        ax.scatter(y_true_np[outside_interval], y_pred[outside_interval], color='orange', s=10, label='Outside Interval')
        ax.scatter(y_true_np, y_true_np, color='blue', marker='x', s=30, linewidths=0.7, label='Ground Truth Values')
        ax.vlines(y_true_np, y_pred_low, y_pred_up, color='gray', alpha=0.5, label='Prediction Intervals')
        ax.plot([min(y_true_np), max(y_true_np)], [min(y_true_np), max(y_true_np)],
                 linestyle='--', color='blue', label='Ideal Prediction Line')
        ax.set_xlabel('Ground Truth')
        ax.set_ylabel('Predictions')
        ax.set_title(f'{title}\nCoverage: {coverage*100:.2f}%, Width: {width:.2f}, RMSE: {rmse:.2f}, CWC: {cwc:.2f}')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def width_size_occurrence(int_pred, train_intervals, num_bins=10, ax=None, x_lim=None, title="Width Size Occurrence"):
        if ax is None:
            fig, ax = plt.subplots()
        widths_test = np.abs(int_pred[:, 1] - int_pred[:, 0])
        widths_train = np.abs(train_intervals[:, 1] - train_intervals[:, 0])
        ax.hist(widths_test, bins=num_bins, alpha=0.6, label='Test Interval Widths', color='red')
        ax.hist(widths_train, bins=num_bins, alpha=0.4, label='Train Interval Widths', color='blue')
        if x_lim is not None:
            ax.set_xlim(x_lim)
        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Occurrence (Frequency)')
        ax.set_title(f'{title} - Interval Width Occurrence')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def coverage_by_width(y_test, int_pred, miscoverage, cond_coverages, num_bins=10, ax=None, title="Coverage vs Width"):
        if ax is None:
            fig, ax = plt.subplots()
        widths = int_pred[:, 1] - int_pred[:, 0]
        bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
        bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
        bin_width = bin_edges[1] - bin_edges[0]
        ax.bar(bin_centers, cond_coverages, width=bin_width, color='blue', alpha=0.7, edgecolor='black', linewidth=0.8, label='Conditional Coverage')
        ax.axhline(1 - miscoverage, color='red', linestyle='--', label=f'Nominal Coverage ({(1 - miscoverage)*100:.0f}%)')
        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Conditional Coverage')
        ax.set_title(f'{title} - Coverage vs Interval Width')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

class TabNetRegressorCP(TabNetRegressor):
    def fit(self, X, y, *args, **kwargs):
        y = np.asarray(y)
        if y.ndim == 1:
            y = y.reshape(-1, 1)
        return super().fit(X, y, *args, **kwargs)

    def predict(self, X, *args, **kwargs):
        return super().predict(X).flatten()

In [69]:
def conformal_predictions_NEXCP_tabnet(
    X_train,
    y_train,
    X_test,
    y_test,
    best_params,
    model_name="TabNet",
    excel_file_path=None,
    alpha=0.1,
    decay=0.99,
    n_folds=5,
    n_bootstrap=50,
):
    warnings.filterwarnings("ignore")

    SEED = 123
    rng = np.random.default_rng(SEED)
    np.random.seed(SEED)

    if "verbose" in best_params:
        best_params = dict(best_params)
        best_params.pop("verbose", None)

    model_class = TabNetRegressorCP

    strategies = {
        "NEXCP-Split": "NexCP Split",
        "NEXCP-Full": "NexCP Full",
        "NEXCP-J+aB": "NexCP Jackknife+ aB",
        "NEXCP-CV+": "NexCP CV+",
    }

    y_pred, int_pred = {}, {}

    y_train_np = np.asarray(y_train).ravel()
    y_test_np = np.asarray(y_test).ravel()

    # =========================
    # NexCP – Split (Weighted)
    # =========================
    model = model_class(**best_params)
    model.fit(X_train, y_train_np)

    yhat_train = model.predict(X_train)
    yhat_test = model.predict(X_test)

    residuals = np.abs(y_train_np - yhat_train)
    weights = decay ** np.arange(len(residuals) - 1, -1, -1)
    q = weighted_quantile(residuals, weights, 1 - alpha)

    y_pred["NEXCP-Split"] = yhat_test
    int_pred["NEXCP-Split"] = np.c_[yhat_test - q, yhat_test + q]

    # =========================
    # NexCP – Full
    # =========================
    model = model_class(**best_params)
    model.fit(X_train, y_train_np)

    yhat_train = model.predict(X_train)
    yhat_test = model.predict(X_test)

    q = np.quantile(np.abs(y_train_np - yhat_train), 1 - alpha)

    y_pred["NEXCP-Full"] = yhat_test
    int_pred["NEXCP-Full"] = np.c_[yhat_test - q, yhat_test + q]

    # =========================
    # NexCP – Jackknife+ aB
    # =========================
    lowers, uppers, preds = [], [], []

    for _ in range(n_bootstrap):
        idx = rng.choice(len(X_train), len(X_train), replace=True)

        model = model_class(**best_params)
        model.fit(X_train[idx], y_train_np[idx])

        yhat_boot_train = model.predict(X_train[idx])
        yhat_test = model.predict(X_test)

        q = np.quantile(
            np.abs(y_train_np[idx] - yhat_boot_train),
            1 - alpha,
        )

        lowers.append(yhat_test - q)
        uppers.append(yhat_test + q)
        preds.append(yhat_test)

    y_pred["NEXCP-J+aB"] = np.mean(preds, axis=0)
    int_pred["NEXCP-J+aB"] = np.c_[np.min(lowers, axis=0), np.max(uppers, axis=0)]

    # =========================
    # NexCP – CV+
    # =========================
    kf = KFold(n_splits=n_folds, shuffle=True, random_state=SEED)

    lowers, uppers, preds = [], [], []

    for tr, cal in kf.split(X_train):
        model = model_class(**best_params)
        model.fit(X_train[tr], y_train_np[tr])

        y_cal = model.predict(X_train[cal])
        q = np.quantile(np.abs(y_train_np[cal] - y_cal), 1 - alpha)

        yhat_test = model.predict(X_test)

        lowers.append(yhat_test - q)
        uppers.append(yhat_test + q)
        preds.append(yhat_test)

    y_pred["NEXCP-CV+"] = np.mean(preds, axis=0)
    int_pred["NEXCP-CV+"] = np.c_[np.mean(lowers, axis=0), np.mean(uppers, axis=0)]

    # =========================
    # Metrics
    # =========================
    def coverage(y, l, u):
        return np.mean((y >= l) & (y <= u))

    def width(l, u):
        return np.mean(u - l)

    def cwc(l, u, y, alpha):
        cov = coverage(y, l, u)
        w = width(l, u)
        penalty = np.exp(-50 * (cov - (1 - alpha)))
        return w * (1 + penalty if cov < (1 - alpha) else 1)

    summary = []

    print("\n===== NEXCP TABNET RESULTS =====")
    for s in strategies:
        cov = coverage(y_test_np, int_pred[s][:, 0], int_pred[s][:, 1])
        wid = width(int_pred[s][:, 0], int_pred[s][:, 1])
        rmse = np.sqrt(mean_squared_error(y_test_np, y_pred[s]))
        cwc_val = cwc(int_pred[s][:, 0], int_pred[s][:, 1], y_test_np, alpha)

        summary.append([strategies[s], cov, wid, rmse, cwc_val])
        print(f"{strategies[s]} | Coverage: {cov*100:.3f}% | Width: {wid:.3f}")

    summary_df = pd.DataFrame(
        summary,
        columns=["Strategy", "Coverage", "Width", "RMSE", "CWC"],
    )

    # =========================
    # Plot + Excel Export
    # =========================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        sheet = "NEXCP_TabNet_Summary"
        base = sheet
        i = 1
        while sheet in wb.sheetnames:
            sheet = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        for s in strategies:
            fig, ax = plt.subplots(figsize=(10, 4))
            idx = np.arange(len(y_test_np))

            ax.scatter(idx, y_test_np, s=10, alpha=0.7, label="True")
            ax.fill_between(idx, int_pred[s][:, 0], int_pred[s][:, 1], alpha=0.4)
            ax.plot(idx, y_pred[s], linewidth=1, label="Pred")

            ax.set_title(f"{strategies[s]} ({model_name})")
            ax.legend()

            buf = io.BytesIO()
            fig.savefig(buf, format="png")
            buf.seek(0)
            plt.close(fig)

            img = Image(buf)
            ps = f"NEXCP_TabNet_{s}"
            base = ps
            i = 1
            while ps in wb.sheetnames:
                ps = f"{base}_{i}"
                i += 1

            ws = wb.create_sheet(ps)
            ws.add_image(img, "A1")

        wb.save(excel_file_path)

    return summary_df


conformal_predictions_NEXCP_tabnet(
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    best_params=best_params,
    model_name="TabNet",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/TabNet.xlsx",
    alpha=0.1,
    decay=0.99,
    n_folds=5,
    n_bootstrap=50
)

Streaming output truncated to the last 5000 lines.
epoch 6  | loss: 21461.76953|  0:00:00s
epoch 7  | loss: 21246.96094|  0:00:00s
epoch 8  | loss: 21092.31641|  0:00:00s
epoch 9  | loss: 20958.42773|  0:00:00s
epoch 10 | loss: 20712.71875|  0:00:00s
epoch 11 | loss: 20465.37695|  0:00:00s
epoch 12 | loss: 20275.26172|  0:00:00s
epoch 13 | loss: 20115.51562|  0:00:00s
epoch 14 | loss: 19912.50586|  0:00:00s
epoch 15 | loss: 19684.13867|  0:00:00s
epoch 16 | loss: 19442.02734|  0:00:00s
epoch 17 | loss: 19431.61133|  0:00:00s
epoch 18 | loss: 19231.36914|  0:00:00s
epoch 19 | loss: 18968.49023|  0:00:00s
epoch 20 | loss: 18700.08789|  0:00:00s
epoch 21 | loss: 18405.16016|  0:00:00s
epoch 22 | loss: 18184.63477|  0:00:00s
epoch 23 | loss: 17931.81641|  0:00:00s
epoch 24 | loss: 17716.0 |  0:00:00s
epoch 25 | loss: 17460.25195|  0:00:00s
epoch 26 | loss: 17191.08789|  0:00:00s
epoch 27 | loss: 16905.89062|  0:00:00s
epoch 28 | loss: 16609.41406|  0:00:00s
epoch 29 | loss: 16350.16797|  0:00:00s
epoch 30 | loss: 16043.33398|  0:00:00s
epoch 31 | loss: 15704.73535|  0:00:00s
epoch 32 | loss: 15374.44727|  0:00:00s
epoch 33 | loss: 15076.14062|  0:00:00s
epoch 34 | loss: 14740.85645|  0:00:00s
epoch 35 | loss: 14400.77148|  0:00:00s
epoch 36 | loss: 14049.66895|  0:00:00s
epoch 37 | loss: 13708.99512|  0:00:00s
epoch 38 | loss: 13354.29102|  0:00:00s
epoch 39 | loss: 12994.25781|  0:00:00s
epoch 40 | loss: 12622.92578|  0:00:00s
epoch 41 | loss: 12236.85645|  0:00:00s
epoch 42 | loss: 11846.18359|  0:00:00s
epoch 43 | loss: 11469.15332|  0:00:00s
epoch 44 | loss: 11095.73242|  0:00:00s
epoch 45 | loss: 10714.86816|  0:00:00s
epoch 46 | loss: 10323.72852|  0:00:01s
epoch 47 | loss: 9923.50293|  0:00:01s
epoch 48 | loss: 9515.07617|  0:00:01s
epoch 49 | loss: 9117.34863|  0:00:01s
epoch 50 | loss: 8769.52734|  0:00:01s
epoch 51 | loss: 8372.39941|  0:00:01s
epoch 52 | loss: 8028.15869|  0:00:01s
epoch 53 | loss: 7641.25684|  0:00:01s
epoch 54 | loss: 7252.62354|  0:00:01s
epoch 55 | loss: 6837.99609|  0:00:01s
epoch 56 | loss: 6456.99805|  0:00:01s
epoch 57 | loss: 6065.36035|  0:00:01s
epoch 58 | loss: 5689.18555|  0:00:01s
epoch 59 | loss: 5310.73828|  0:00:01s
epoch 60 | loss: 4928.45361|  0:00:01s
epoch 61 | loss: 4552.21484|  0:00:01s
epoch 62 | loss: 4187.40137|  0:00:01s
epoch 63 | loss: 3828.46924|  0:00:01s
epoch 64 | loss: 3475.16284|  0:00:01s
epoch 65 | loss: 3128.70239|  0:00:01s
epoch 66 | loss: 2793.60132|  0:00:01s
epoch 67 | loss: 2474.31445|  0:00:01s
epoch 68 | loss: 2166.09839|  0:00:01s
epoch 69 | loss: 1872.62085|  0:00:01s
epoch 70 | loss: 1595.08923|  0:00:01s
epoch 71 | loss: 1338.58521|  0:00:01s
epoch 72 | loss: 1115.14526|  0:00:01s
epoch 73 | loss: 885.33875|  0:00:01s
epoch 74 | loss: 705.7049|  0:00:01s
epoch 75 | loss: 528.90063|  0:00:01s
epoch 76 | loss: 386.71579|  0:00:01s
epoch 77 | loss: 278.37195|  0:00:01s
epoch 78 | loss: 164.94661|  0:00:01s
epoch 79 | loss: 81.11518|  0:00:01s
epoch 80 | loss: 38.01245|  0:00:01s
epoch 81 | loss: 36.93829|  0:00:01s
epoch 82 | loss: 25.65442|  0:00:01s
epoch 83 | loss: 47.93831|  0:00:01s
epoch 84 | loss: 43.06102|  0:00:01s
epoch 85 | loss: 62.53736|  0:00:01s
epoch 86 | loss: 59.87589|  0:00:01s
epoch 87 | loss: 59.95091|  0:00:01s
epoch 88 | loss: 58.57724|  0:00:01s
epoch 89 | loss: 53.285  |  0:00:01s
epoch 90 | loss: 31.41838|  0:00:01s
epoch 91 | loss: 17.29695|  0:00:01s
epoch 92 | loss: 8.76729 |  0:00:01s
epoch 93 | loss: 11.68979|  0:00:02s
epoch 94 | loss: 9.01511 |  0:00:02s
epoch 95 | loss: 7.93881 |  0:00:02s
epoch 96 | loss: 5.84223 |  0:00:02s
epoch 97 | loss: 4.19971 |  0:00:02s
epoch 98 | loss: 6.75574 |  0:00:02s
epoch 99 | loss: 35.53991|  0:00:02s
epoch 0  | loss: 21009.78125|  0:00:00s
epoch 1  | loss: 20697.36914|  0:00:00s
epoch 2  | loss: 20537.16797|  0:00:00s
epoch 3  | loss: 20256.57422|  0:00:00s
epoch 4  | loss: 20172.96875|  0:00:00s
epoch 5  | loss: 19940.57227|  0:00:00s
epoch 6  | loss: 19791.62305|  0:00:00s
epoch 7  | loss: 19623.62109|  0:00:00s
epoch 8  | loss: 19395.27734|  0:00:00s
epoch 9  | loss: 19253.28906|  0:00:00s
epoch 10 | loss: 19051.48828|  0:00:00s
epoch 11 | loss: 18846.33984|  0:00:00s
epoch 12 | loss: 18701.91992|  0:00:00s
epoch 13 | loss: 18501.13867|  0:00:00s
epoch 14 | loss: 18296.64062|  0:00:00s
epoch 15 | loss: 18093.71094|  0:00:00s
epoch 16 | loss: 17884.25781|  0:00:00s
epoch 17 | loss: 17682.67773|  0:00:00s
epoch 18 | loss: 17459.58203|  0:00:00s
epoch 19 | loss: 17243.06055|  0:00:00s
epoch 20 | loss: 17012.45703|  0:00:00s
epoch 21 | loss: 16779.39844|  0:00:00s
epoch 22 | loss: 16560.77148|  0:00:00s
epoch 23 | loss: 16295.18262|  0:00:00s
epoch 24 | loss: 16123.57715|  0:00:00s
epoch 25 | loss: 15966.53711|  0:00:00s
epoch 26 | loss: 15715.71387|  0:00:00s
epoch 27 | loss: 15440.51758|  0:00:00s
epoch 28 | loss: 15252.54297|  0:00:00s
epoch 29 | loss: 14951.27539|  0:00:00s
epoch 30 | loss: 14761.14941|  0:00:00s
epoch 31 | loss: 14490.63281|  0:00:00s
epoch 32 | loss: 14201.81152|  0:00:01s
epoch 33 | loss: 13896.84668|  0:00:01s
epoch 34 | loss: 13585.32324|  0:00:01s
epoch 35 | loss: 13264.08008|  0:00:01s
epoch 36 | loss: 12933.93359|  0:00:01s
epoch 37 | loss: 12597.04883|  0:00:01s
epoch 38 | loss: 12252.05762|  0:00:01s
epoch 39 | loss: 11896.21289|  0:00:01s
epoch 40 | loss: 11526.24316|  0:00:01s
epoch 41 | loss: 11164.95312|  0:00:01s
epoch 42 | loss: 10806.95703|  0:00:01s
epoch 43 | loss: 10444.72168|  0:00:01s
epoch 44 | loss: 10066.23047|  0:00:01s
epoch 45 | loss: 9681.57617|  0:00:01s
epoch 46 | loss: 9298.80859|  0:00:01s
epoch 47 | loss: 8908.01562|  0:00:01s
epoch 48 | loss: 8527.6748|  0:00:01s
epoch 49 | loss: 8138.90479|  0:00:01s
epoch 50 | loss: 7750.69287|  0:00:01s
epoch 51 | loss: 7363.40088|  0:00:01s
epoch 52 | loss: 6993.73926|  0:00:01s
epoch 53 | loss: 6608.22803|  0:00:01s
epoch 54 | loss: 6232.46924|  0:00:01s
epoch 55 | loss: 5851.2998|  0:00:01s
epoch 56 | loss: 5492.25439|  0:00:01s
epoch 57 | loss: 5141.03564|  0:00:01s
epoch 58 | loss: 4772.01514|  0:00:01s
epoch 59 | loss: 4605.17676|  0:00:01s
epoch 60 | loss: 4112.51221|  0:00:01s
epoch 61 | loss: 3805.43652|  0:00:01s
epoch 62 | loss: 3492.27808|  0:00:01s
epoch 63 | loss: 3255.29224|  0:00:01s
epoch 64 | loss: 2898.05786|  0:00:01s
epoch 65 | loss: 2629.99585|  0:00:01s
epoch 66 | loss: 2375.80249|  0:00:02s
epoch 67 | loss: 2080.16772|  0:00:02s
epoch 68 | loss: 1805.26843|  0:00:02s
epoch 69 | loss: 1538.36865|  0:00:02s
epoch 70 | loss: 1286.54163|  0:00:02s
epoch 71 | loss: 1058.25574|  0:00:02s
epoch 72 | loss: 850.02063|  0:00:02s
epoch 73 | loss: 667.5368|  0:00:02s
epoch 74 | loss: 492.02374|  0:00:02s
epoch 75 | loss: 362.43073|  0:00:02s
epoch 76 | loss: 256.24203|  0:00:02s
epoch 77 | loss: 149.60181|  0:00:02s
epoch 78 | loss: 77.45551|  0:00:02s
epoch 79 | loss: 48.38211|  0:00:02s
epoch 80 | loss: 43.13621|  0:00:02s
epoch 81 | loss: 33.35793|  0:00:02s
epoch 82 | loss: 27.10467|  0:00:02s
epoch 83 | loss: 33.33418|  0:00:02s
epoch 84 | loss: 88.48547|  0:00:02s
epoch 85 | loss: 66.65003|  0:00:02s
epoch 86 | loss: 54.48365|  0:00:02s
epoch 87 | loss: 45.07455|  0:00:02s
epoch 88 | loss: 26.89582|  0:00:02s
epoch 89 | loss: 15.43159|  0:00:02s
epoch 90 | loss: 6.38421 |  0:00:02s
epoch 91 | loss: 4.84138 |  0:00:02s
epoch 92 | loss: 5.1393  |  0:00:02s
epoch 93 | loss: 7.84039 |  0:00:02s
epoch 94 | loss: 7.02826 |  0:00:02s
epoch 95 | loss: 4.0647  |  0:00:02s
epoch 96 | loss: 3.32738 |  0:00:02s
epoch 97 | loss: 3.18966 |  0:00:02s
epoch 98 | loss: 2.88705 |  0:00:02s
epoch 99 | loss: 2.64871 |  0:00:02s
epoch 0  | loss: 21123.94922|  0:00:00s
epoch 1  | loss: 20869.30273|  0:00:00s
epoch 2  | loss: 20591.17188|  0:00:00s
epoch 3  | loss: 20379.08594|  0:00:00s
epoch 4  | loss: 20112.5 |  0:00:00s
epoch 5  | loss: 19922.56641|  0:00:00s
epoch 6  | loss: 19704.62305|  0:00:00s
epoch 7  | loss: 19440.06641|  0:00:00s
epoch 8  | loss: 19229.86328|  0:00:00s
epoch 9  | loss: 19023.29883|  0:00:00s
epoch 10 | loss: 18751.66797|  0:00:00s
epoch 11 | loss: 18511.7832|  0:00:00s
epoch 12 | loss: 18294.00195|  0:00:00s
epoch 13 | loss: 18069.88086|  0:00:00s
epoch 14 | loss: 17858.52344|  0:00:00s
epoch 15 | loss: 17708.90625|  0:00:00s
epoch 16 | loss: 17504.01953|  0:00:00s
epoch 17 | loss: 17275.24023|  0:00:00s
epoch 18 | loss: 17067.35352|  0:00:00s
epoch 19 | loss: 16883.64258|  0:00:00s
epoch 20 | loss: 16657.16992|  0:00:00s
epoch 21 | loss: 16424.92383|  0:00:00s
epoch 22 | loss: 16193.31934|  0:00:00s
epoch 23 | loss: 15960.97461|  0:00:00s
epoch 24 | loss: 15721.94531|  0:00:00s
epoch 25 | loss: 15475.77148|  0:00:00s
epoch 26 | loss: 15221.19531|  0:00:00s
epoch 27 | loss: 14958.40527|  0:00:00s
epoch 28 | loss: 14689.55762|  0:00:00s
epoch 29 | loss: 14415.81641|  0:00:00s
epoch 30 | loss: 14136.30469|  0:00:00s
epoch 31 | loss: 13850.54883|  0:00:00s
epoch 32 | loss: 13555.62109|  0:00:00s
epoch 33 | loss: 13256.10254|  0:00:00s
epoch 34 | loss: 12950.39355|  0:00:00s
epoch 35 | loss: 12639.94434|  0:00:00s
epoch 36 | loss: 12323.96289|  0:00:00s
epoch 37 | loss: 12002.06152|  0:00:00s
epoch 38 | loss: 11674.92383|  0:00:00s
epoch 39 | loss: 11341.26074|  0:00:00s
epoch 40 | loss: 11005.98828|  0:00:00s
epoch 41 | loss: 10669.19141|  0:00:00s
epoch 42 | loss: 10322.98242|  0:00:00s
epoch 43 | loss: 9966.62598|  0:00:00s
epoch 44 | loss: 9614.74219|  0:00:00s
epoch 45 | loss: 9252.69434|  0:00:00s
epoch 46 | loss: 8896.58984|  0:00:01s
epoch 47 | loss: 8532.67676|  0:00:01s
epoch 48 | loss: 8164.53711|  0:00:01s
epoch 49 | loss: 7800.87646|  0:00:01s
epoch 50 | loss: 7434.18799|  0:00:01s
epoch 51 | loss: 7063.55908|  0:00:01s
epoch 52 | loss: 6696.12354|  0:00:01s
epoch 53 | loss: 6332.49121|  0:00:01s
epoch 54 | loss: 5972.56787|  0:00:01s
epoch 55 | loss: 5612.97607|  0:00:01s
epoch 56 | loss: 5259.68604|  0:00:01s
epoch 57 | loss: 4960.30518|  0:00:01s
epoch 58 | loss: 4671.19629|  0:00:01s
epoch 59 | loss: 4288.9668|  0:00:01s
epoch 60 | loss: 3946.16504|  0:00:01s
epoch 61 | loss: 3629.8584|  0:00:01s
epoch 62 | loss: 3310.20874|  0:00:01s
epoch 63 | loss: 2992.32959|  0:00:01s
epoch 64 | loss: 2679.14209|  0:00:01s
epoch 65 | loss: 2382.87598|  0:00:01s
epoch 66 | loss: 2099.87305|  0:00:01s
epoch 67 | loss: 1826.43445|  0:00:01s
epoch 68 | loss: 1570.36584|  0:00:01s
epoch 69 | loss: 1332.2478|  0:00:01s
epoch 70 | loss: 1100.88025|  0:00:01s
epoch 71 | loss: 898.63623|  0:00:01s
epoch 72 | loss: 704.53229|  0:00:01s
epoch 73 | loss: 531.29419|  0:00:01s
epoch 74 | loss: 385.89679|  0:00:01s
epoch 75 | loss: 249.77679|  0:00:01s
epoch 76 | loss: 157.82941|  0:00:01s
epoch 77 | loss: 88.95975|  0:00:01s
epoch 78 | loss: 140.39986|  0:00:01s
epoch 79 | loss: 42.33392|  0:00:01s
epoch 80 | loss: 147.46562|  0:00:01s
epoch 81 | loss: 34.08426|  0:00:01s
epoch 82 | loss: 246.6534|  0:00:01s
epoch 83 | loss: 214.41977|  0:00:01s
epoch 84 | loss: 124.49165|  0:00:01s
epoch 85 | loss: 106.01207|  0:00:01s
epoch 86 | loss: 84.21456|  0:00:01s
epoch 87 | loss: 85.68314|  0:00:01s
epoch 88 | loss: 82.18188|  0:00:01s
epoch 89 | loss: 78.55466|  0:00:01s
epoch 90 | loss: 46.81115|  0:00:01s
epoch 91 | loss: 23.45012|  0:00:01s
epoch 92 | loss: 13.52527|  0:00:01s
epoch 93 | loss: 10.3085 |  0:00:02s
epoch 94 | loss: 10.8216 |  0:00:02s
epoch 95 | loss: 16.43463|  0:00:02s
epoch 96 | loss: 9.4164  |  0:00:02s
epoch 97 | loss: 8.97239 |  0:00:02s
epoch 98 | loss: 4.9786  |  0:00:02s
epoch 99 | loss: 2.12079 |  0:00:02s
epoch 0  | loss: 21994.66797|  0:00:00s
epoch 1  | loss: 21741.85742|  0:00:00s
epoch 2  | loss: 21433.3418|  0:00:00s
epoch 3  | loss: 21240.00781|  0:00:00s
epoch 4  | loss: 21001.24219|  0:00:00s
epoch 5  | loss: 20749.40625|  0:00:00s
epoch 6  | loss: 20505.31445|  0:00:00s
epoch 7  | loss: 20289.24805|  0:00:00s
epoch 8  | loss: 20224.41797|  0:00:00s
epoch 9  | loss: 19957.38086|  0:00:00s
epoch 10 | loss: 19727.81445|  0:00:00s
epoch 11 | loss: 19619.99414|  0:00:00s
epoch 12 | loss: 19417.59375|  0:00:00s
epoch 13 | loss: 19247.71094|  0:00:00s
epoch 14 | loss: 19100.08398|  0:00:00s
epoch 15 | loss: 18945.84766|  0:00:00s
epoch 16 | loss: 18814.58594|  0:00:00s
epoch 17 | loss: 18658.07812|  0:00:00s
epoch 18 | loss: 18460.66211|  0:00:00s
epoch 19 | loss: 18287.00977|  0:00:00s
epoch 20 | loss: 18086.69336|  0:00:00s
epoch 21 | loss: 17879.65039|  0:00:00s
epoch 22 | loss: 17699.66992|  0:00:00s
epoch 23 | loss: 17507.42578|  0:00:00s
epoch 24 | loss: 17280.7168|  0:00:00s
epoch 25 | loss: 17044.57617|  0:00:00s
epoch 26 | loss: 16834.63477|  0:00:00s
epoch 27 | loss: 16642.5 |  0:00:00s
epoch 28 | loss: 16353.33398|  0:00:00s
epoch 29 | loss: 16133.04785|  0:00:00s
epoch 30 | loss: 15856.16504|  0:00:00s
epoch 31 | loss: 15538.07324|  0:00:00s
epoch 32 | loss: 15250.68652|  0:00:00s
epoch 33 | loss: 15072.66992|  0:00:00s
epoch 34 | loss: 14833.37891|  0:00:00s
epoch 35 | loss: 14541.71777|  0:00:00s
epoch 36 | loss: 14208.31641|  0:00:00s
epoch 37 | loss: 13849.37012|  0:00:00s
epoch 38 | loss: 13559.66602|  0:00:00s
epoch 39 | loss: 13233.97754|  0:00:00s
epoch 40 | loss: 12892.32812|  0:00:00s
epoch 41 | loss: 12546.90723|  0:00:00s
epoch 42 | loss: 12190.72168|  0:00:00s
epoch 43 | loss: 11828.0957|  0:00:00s
epoch 44 | loss: 11461.35938|  0:00:00s
epoch 45 | loss: 11096.49023|  0:00:00s
epoch 46 | loss: 10715.45801|  0:00:01s
epoch 47 | loss: 10328.52832|  0:00:01s
epoch 48 | loss: 9940.72363|  0:00:01s
epoch 49 | loss: 9552.43066|  0:00:01s
epoch 50 | loss: 9157.08008|  0:00:01s
epoch 51 | loss: 8772.45801|  0:00:01s
epoch 52 | loss: 8371.63867|  0:00:01s
epoch 53 | loss: 7980.87891|  0:00:01s
epoch 54 | loss: 7583.04346|  0:00:01s
epoch 55 | loss: 7189.20068|  0:00:01s
epoch 56 | loss: 6798.69336|  0:00:01s
epoch 57 | loss: 6410.12646|  0:00:01s
epoch 58 | loss: 6024.1377|  0:00:01s
epoch 59 | loss: 5641.79053|  0:00:01s
epoch 60 | loss: 5264.50977|  0:00:01s
epoch 61 | loss: 4895.33398|  0:00:01s
epoch 62 | loss: 4533.21631|  0:00:01s
epoch 63 | loss: 4180.04932|  0:00:01s
epoch 64 | loss: 3837.26294|  0:00:01s
epoch 65 | loss: 3502.85571|  0:00:01s
epoch 66 | loss: 3178.60962|  0:00:01s
epoch 67 | loss: 2867.51343|  0:00:01s
epoch 68 | loss: 2574.32324|  0:00:01s
epoch 69 | loss: 2290.31738|  0:00:01s
epoch 70 | loss: 2012.3811|  0:00:01s
epoch 71 | loss: 1751.4248|  0:00:01s
epoch 72 | loss: 1517.62292|  0:00:01s
epoch 73 | loss: 1380.05542|  0:00:01s
epoch 74 | loss: 1096.40417|  0:00:01s
epoch 75 | loss: 917.00134|  0:00:01s
epoch 76 | loss: 735.74353|  0:00:01s
epoch 77 | loss: 579.32025|  0:00:01s
epoch 78 | loss: 426.54028|  0:00:01s
epoch 79 | loss: 297.59964|  0:00:01s
epoch 80 | loss: 201.60115|  0:00:01s
epoch 81 | loss: 110.40916|  0:00:01s
epoch 82 | loss: 49.13132|  0:00:01s
epoch 83 | loss: 14.48301|  0:00:01s
epoch 84 | loss: 12.97749|  0:00:01s
epoch 85 | loss: 27.91275|  0:00:01s
epoch 86 | loss: 45.39375|  0:00:01s
epoch 87 | loss: 63.63369|  0:00:01s
epoch 88 | loss: 76.49239|  0:00:01s
epoch 89 | loss: 70.0675 |  0:00:01s
epoch 90 | loss: 56.35452|  0:00:02s
epoch 91 | loss: 45.4549 |  0:00:02s
epoch 92 | loss: 33.39029|  0:00:02s
epoch 93 | loss: 16.45004|  0:00:02s
epoch 94 | loss: 10.14744|  0:00:02s
epoch 95 | loss: 9.24708 |  0:00:02s
epoch 96 | loss: 13.29967|  0:00:02s
epoch 97 | loss: 10.82195|  0:00:02s
epoch 98 | loss: 11.61535|  0:00:02s
epoch 99 | loss: 8.99812 |  0:00:02s
epoch 0  | loss: 21279.47656|  0:00:00s
epoch 1  | loss: 21046.22656|  0:00:00s
epoch 2  | loss: 20854.02734|  0:00:00s
epoch 3  | loss: 20574.09766|  0:00:00s
epoch 4  | loss: 20425.37695|  0:00:00s
epoch 5  | loss: 20256.3418|  0:00:00s
epoch 6  | loss: 20004.08008|  0:00:00s
epoch 7  | loss: 19821.43945|  0:00:00s
epoch 8  | loss: 19622.31836|  0:00:00s
epoch 9  | loss: 19448.28125|  0:00:00s
epoch 10 | loss: 19236.79297|  0:00:00s
epoch 11 | loss: 19027.42383|  0:00:00s
epoch 12 | loss: 18865.27539|  0:00:00s
epoch 13 | loss: 18665.49414|  0:00:00s
epoch 14 | loss: 18504.1543|  0:00:00s
epoch 15 | loss: 18272.65039|  0:00:00s
epoch 16 | loss: 18038.26367|  0:00:00s
epoch 17 | loss: 17846.64453|  0:00:00s
epoch 18 | loss: 17640.92578|  0:00:00s
epoch 19 | loss: 17440.45312|  0:00:00s
epoch 20 | loss: 17319.48242|  0:00:00s
epoch 21 | loss: 17084.93945|  0:00:00s
epoch 22 | loss: 16804.62695|  0:00:00s
epoch 23 | loss: 16595.38086|  0:00:00s
epoch 24 | loss: 16384.08984|  0:00:00s
epoch 25 | loss: 16152.04785|  0:00:00s
epoch 26 | loss: 15910.19531|  0:00:00s
epoch 27 | loss: 15664.74707|  0:00:00s
epoch 28 | loss: 15410.76953|  0:00:00s
epoch 29 | loss: 15154.67578|  0:00:00s
epoch 30 | loss: 14876.4707|  0:00:00s
epoch 31 | loss: 14575.76758|  0:00:00s
epoch 32 | loss: 14303.73438|  0:00:00s
epoch 33 | loss: 13999.11719|  0:00:00s
epoch 34 | loss: 13679.53711|  0:00:00s
epoch 35 | loss: 13354.125|  0:00:00s
epoch 36 | loss: 13022.14258|  0:00:00s
epoch 37 | loss: 12682.79688|  0:00:00s
epoch 38 | loss: 12337.66309|  0:00:00s
epoch 39 | loss: 11976.78223|  0:00:00s
epoch 40 | loss: 11616.91309|  0:00:00s
epoch 41 | loss: 11239.78809|  0:00:00s
epoch 42 | loss: 10869.02539|  0:00:00s
epoch 43 | loss: 10525.44922|  0:00:00s
epoch 44 | loss: 10123.08887|  0:00:01s
epoch 45 | loss: 9742.13867|  0:00:01s
epoch 46 | loss: 9340.7002|  0:00:01s
epoch 47 | loss: 8944.25977|  0:00:01s
epoch 48 | loss: 8542.69043|  0:00:01s
epoch 49 | loss: 8144.86426|  0:00:01s
epoch 50 | loss: 7748.375|  0:00:01s
epoch 51 | loss: 7390.77588|  0:00:01s
epoch 52 | loss: 7031.76904|  0:00:01s
epoch 53 | loss: 6622.98145|  0:00:01s
epoch 54 | loss: 6261.66748|  0:00:01s
epoch 55 | loss: 5920.98584|  0:00:01s
epoch 56 | loss: 5569.19922|  0:00:01s
epoch 57 | loss: 5194.68604|  0:00:01s
epoch 58 | loss: 4855.65869|  0:00:01s
epoch 59 | loss: 4498.78125|  0:00:01s
epoch 60 | loss: 4150.86279|  0:00:01s
epoch 61 | loss: 3794.2312|  0:00:01s
epoch 62 | loss: 3439.74536|  0:00:01s
epoch 63 | loss: 3108.2749|  0:00:01s
epoch 64 | loss: 2775.92188|  0:00:01s
epoch 65 | loss: 2450.14966|  0:00:01s
epoch 66 | loss: 2151.05713|  0:00:01s
epoch 67 | loss: 1850.30835|  0:00:01s
epoch 68 | loss: 1568.90808|  0:00:01s
epoch 69 | loss: 1316.04041|  0:00:01s
epoch 70 | loss: 1094.77441|  0:00:01s
epoch 71 | loss: 892.76007|  0:00:01s
epoch 72 | loss: 699.63525|  0:00:01s
epoch 73 | loss: 517.20154|  0:00:01s
epoch 74 | loss: 375.94067|  0:00:01s
epoch 75 | loss: 239.48698|  0:00:01s
epoch 76 | loss: 144.79839|  0:00:01s
epoch 77 | loss: 75.55987|  0:00:01s
epoch 78 | loss: 67.58836|  0:00:01s
epoch 79 | loss: 20.02984|  0:00:01s
epoch 80 | loss: 27.45263|  0:00:01s
epoch 81 | loss: 52.71471|  0:00:01s
epoch 82 | loss: 70.66228|  0:00:01s
epoch 83 | loss: 77.00333|  0:00:01s
epoch 84 | loss: 63.95938|  0:00:01s
epoch 85 | loss: 52.93183|  0:00:01s
epoch 86 | loss: 46.65049|  0:00:01s
epoch 87 | loss: 31.51338|  0:00:01s
epoch 88 | loss: 29.85797|  0:00:01s
epoch 89 | loss: 31.45409|  0:00:01s
epoch 90 | loss: 34.45395|  0:00:01s
epoch 91 | loss: 36.87151|  0:00:02s
epoch 92 | loss: 25.59842|  0:00:02s
epoch 93 | loss: 15.00459|  0:00:02s
epoch 94 | loss: 24.00691|  0:00:02s
epoch 95 | loss: 19.996  |  0:00:02s
epoch 96 | loss: 11.78734|  0:00:02s
epoch 97 | loss: 6.61058 |  0:00:02s
epoch 98 | loss: 3.82747 |  0:00:02s
epoch 99 | loss: 6.23449 |  0:00:02s
epoch 0  | loss: 27960.33789|  0:00:00s
epoch 1  | loss: 27605.32227|  0:00:00s
epoch 2  | loss: 27378.64844|  0:00:00s
epoch 3  | loss: 27013.27148|  0:00:00s
epoch 4  | loss: 26745.31641|  0:00:00s
epoch 5  | loss: 26445.88867|  0:00:00s
epoch 6  | loss: 26156.50586|  0:00:00s
epoch 7  | loss: 25906.11719|  0:00:00s
epoch 8  | loss: 25673.90234|  0:00:00s
epoch 9  | loss: 25425.97852|  0:00:00s
epoch 10 | loss: 25199.88281|  0:00:00s
epoch 11 | loss: 25035.61719|  0:00:00s
epoch 12 | loss: 24751.30078|  0:00:00s
epoch 13 | loss: 24488.20703|  0:00:00s
epoch 14 | loss: 24258.13477|  0:00:00s
epoch 15 | loss: 24085.57227|  0:00:00s
epoch 16 | loss: 23803.79297|  0:00:00s
epoch 17 | loss: 23556.38086|  0:00:00s

              Strategy  Coverage       Width       RMSE           CWC
0          NexCP Split  0.531915   44.795429  53.126616  4.406566e+09
1           NexCP Full  0.574468   46.865139  53.126616  5.491433e+08
2  NexCP Jackknife+ aB  1.000000  199.036026  24.908130  1.990360e+02
3            NexCP CV+  0.978723  123.778809  27.680889  1.237788e+02

In [70]:
y_train = pd.Series(y_train)
y_test = pd.Series(y_test)

conformal_predictions_online_super(
    model_class=TabNetRegressorCP,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="TabNet",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/TabNet.xlsx",
    alpha=0.1,
    strategies="all",
    window_min=50,
    window_max=500,
    window_grid=(25, 50, 100, 200, 400),
    n_bootstrap=30
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage       Width       RMSE         CWC
0          Online Split  0.574468   46.865140  53.126627   66.807753
1            Online CV+  0.808511   75.224363  53.126627   89.629028
2  Online Jackknife+ aB  1.000000  188.639832  26.041387  188.639832
3                 SAOCP  0.851064   85.686640  53.126627   98.448480
4                SF-OGD  0.659574   53.940904  53.126627   72.303765
5                  FACI  0.872340   94.745556  53.126627  106.840733
6            MFCS Split  0.574468   46.865140  53.126627   66.807753
7             MFCS Full  0.617021   56.204645  26.742942   77.729828

               Strategy  Coverage       Width       RMSE         CWC
0          Online Split  0.574468   46.865140  53.126627   66.807753
1            Online CV+  0.808511   75.224363  53.126627   89.629028
2  Online Jackknife+ aB  1.000000  188.639832  26.041387  188.639832
3                 SAOCP  0.851064   85.686640  53.126627   98.448480
4                SF-OGD  0.659574   53.940904  53.126627   72.303765
5                  FACI  0.872340   94.745556  53.126627  106.840733
6            MFCS Split  0.574468   46.865140  53.126627   66.807753
7             MFCS Full  0.617021   56.204645  26.742942   77.729828

In [71]:
conformal_predictions_COP(
    model_class=TabNetRegressorCP,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="TabNet",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/TabNet.xlsx",
    alpha=0.1,
    lr=0.05,
    T_burnin=50,
    scale=0.5
)

===== CONFORMAL OPTIMISTIC PREDICTION (TabNet) =====
Coverage : 57.447%
Avg Width: 47.644
RMSE     : 53.127
Final q  : 24.153

  Strategy  Coverage      Width       RMSE  Alpha    LR  Scale
0      COP  0.574468  47.643651  53.126616    0.1  0.05    0.5

In [72]:
# conformal_predictions_EXTREME(
#     model_class=TabNetRegressorCP,
#     model_params=best_params,
#     X_train=X_train,
#     y_train=y_train,
#     X_test=X_test,
#     y_test=y_test,
#     model_name="TabNet",
#     excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/TabNet.xlsx",
#     alpha=0.05,
#     calib_size=0.3,
#     gpd_threshold_quantile=0.95,
#     n_bootstrap=30
# )

In [73]:
def conformal_predictions_AlphaNet_tabnet(
    X_train,
    y_train,
    X_test,
    y_test,
    best_params,
    model_name="TabNet",
    excel_file_path=None,
    alpha=0.05,
    lambda_reg=20.0,
    num_epochs=50,
    batch_size=32,
    lr_alpha=1e-3,
    calib_fraction=0.5,
    num_runs=4,
    random_state=123,
):
    """
    Learned-α Conformal Prediction via AlphaNet — TabNet-specific variant.

    Handles:
    - TabNetRegressorCP wrapper (y reshape, predict flatten)
    - Removes 'verbose' from best_params if present
    - Precomputed LOO scores for speed
    - Progress tracking with tqdm + ETA
    """

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)
    torch.manual_seed(random_state)
    device = "cuda" if torch.cuda.is_available() else "cpu"

    t_start_total = time.time()

    # =========================================================
    # TabNet-specific: clean params & set model class
    # =========================================================
    tabnet_params = dict(best_params)
    tabnet_params.pop("verbose", None)           # TabNet doesn't use verbose here
    model_class = TabNetRegressorCP

    # =========================================================
    # Data conversion
    # =========================================================
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy()  if hasattr(X_test,  "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # =========================================================
    # 1. Split training data → fit + calibration
    # =========================================================
    n_total = len(Xtr)
    n_fit   = int(n_total * (1 - calib_fraction))
    perm    = np.random.permutation(n_total)

    fit_idx   = perm[:n_fit]
    calib_idx = perm[n_fit:]

    X_fit,   y_fit   = Xtr[fit_idx],   ytr[fit_idx]
    X_calib, y_calib = Xtr[calib_idx],  ytr[calib_idx]
    n_calib = len(X_calib)

    # alpha_min: must satisfy α̃·(n+1) − 1 > 0  →  α̃ > 1/(n+1)
    alpha_min = 1.0 / (n_calib + 1) + 0.01
    print(f"  [Info] n_calib={n_calib} | alpha_min={alpha_min:.4f}")

    # =========================================================
    # 2. Train base TabNet model
    # =========================================================
    print(f"  [Step 2/9] Training base {model_name} model...")
    t0 = time.time()
    base_model = model_class(**tabnet_params)
    base_model.fit(X_fit, y_fit)
    print(f"  [Step 2/9] Done in {_fmt_time(time.time()-t0)}")

    # =========================================================
    # 3. PRECOMPUTE all LOO scores (KEY SPEEDUP)
    # =========================================================
    print(f"  [Step 3/9] Precomputing {n_calib} LOO score vectors...")
    t0 = time.time()

    precomputed_scores = []
    precomputed_sums   = []

    iterator = (
        tqdm(range(n_calib), desc="    LOO precompute", leave=False)
        if HAS_TQDM else range(n_calib)
    )

    for i in iterator:
        loo_X = np.delete(X_calib, i, axis=0)
        loo_y = np.delete(y_calib, i, axis=0)
        preds_loo = base_model.predict(loo_X).ravel()
        scores_loo = np.abs(preds_loo - loo_y)

        scores_tensor = torch.tensor(scores_loo, dtype=torch.float32).to(device)
        precomputed_scores.append(scores_tensor)
        precomputed_sums.append(scores_loo.sum())

    elapsed_precompute = time.time() - t0
    print(f"  [Step 3/9] Done in {_fmt_time(elapsed_precompute)}")

    # Build feature matrix (sum of LOO scores per sample)
    X_alpha = torch.tensor(
        np.array(precomputed_sums).reshape(-1, 1),
        dtype=torch.float32,
    ).to(device)

    # =========================================================
    # 4. Train AlphaNet (multiple runs, keep best)
    # =========================================================
    print(f"  [Step 4/9] Training AlphaNet: {num_runs} runs × {num_epochs} epochs")

    best_net  = None
    best_loss = np.inf
    history   = {"losses": [], "sizes": [], "alphas": []}

    t0_train = time.time()

    for run in range(num_runs):
        np.random.seed(run)
        torch.manual_seed(run)

        alpha_net = AlphaNet(input_dim=1, alpha_min=alpha_min).to(device)
        optimizer = optim.Adam(alpha_net.parameters(), lr=lr_alpha)

        dataset = TensorDataset(X_alpha, torch.arange(n_calib))
        loader  = DataLoader(dataset, batch_size=batch_size, shuffle=True)

        run_losses, run_sizes, run_alphas = [], [], []

        epoch_iter = (
            tqdm(range(num_epochs), desc=f"    Run {run+1}/{num_runs}", leave=False)
            if HAS_TQDM else range(num_epochs)
        )

        for epoch in epoch_iter:
            t_epoch_start = time.time()
            epoch_loss = epoch_size = epoch_alpha = 0.0

            for x_batch, idx_batch in loader:
                x_batch = x_batch.to(device)
                alpha_pred = alpha_net(x_batch)

                batch_sizes = []
                for j, idx in enumerate(idx_batch):
                    # USE PRECOMPUTED scores — no predict() call here
                    scores_t = precomputed_scores[idx.item()]
                    size_j = _interval_size(scores_t, alpha_pred[j])
                    batch_sizes.append(size_j)

                batch_sizes = torch.stack(batch_sizes)
                loss = (batch_sizes + lambda_reg * alpha_pred).mean()

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

                epoch_loss  += loss.item()
                epoch_size  += batch_sizes.mean().item()
                epoch_alpha += alpha_pred.mean().item()

            n_batches = len(loader)
            run_losses.append(epoch_loss  / n_batches)
            run_sizes.append(epoch_size   / n_batches)
            run_alphas.append(epoch_alpha / n_batches)

            epoch_time = time.time() - t_epoch_start

            if epoch % 10 == 0 or epoch == num_epochs - 1:
                epochs_done  = (run * num_epochs) + epoch + 1
                epochs_total = num_runs * num_epochs
                elapsed_train = time.time() - t0_train
                eta = (elapsed_train / epochs_done) * (epochs_total - epochs_done)

                print(
                    f"  λ={lambda_reg} | Run {run+1}/{num_runs} | "
                    f"Epoch {epoch}/{num_epochs} | "
                    f"Loss: {run_losses[-1]:.4f} | "
                    f"Size: {run_sizes[-1]:.4f} | "
                    f"α̃: {run_alphas[-1]:.4f} | "
                    f"⏱ {epoch_time:.2f}s/epoch | "
                    f"ETA: {_fmt_time(eta)}"
                )

        if run_losses[-1] < best_loss:
            best_loss = run_losses[-1]
            best_net  = alpha_net

        history["losses"].append(run_losses)
        history["sizes"].append(run_sizes)
        history["alphas"].append(run_alphas)

        print(f"  ✓ Run {run+1} complete | Final loss: {run_losses[-1]:.4f}")

    train_time = time.time() - t0_train
    print(f"  [Step 4/9] Training done in {_fmt_time(train_time)}")

    alpha_net = best_net
    alpha_net.eval()

    # =========================================================
    # 5. Compute conformal intervals on TEST set
    # =========================================================
    print(f"  [Step 5/9] Computing conformal intervals...")

    calib_preds = base_model.predict(X_calib).ravel()
    scores_calib = np.abs(calib_preds - y_calib)
    sum_scores   = scores_calib.sum()

    with torch.no_grad():
        feat_test = torch.tensor([sum_scores], dtype=torch.float32).to(device)
        alpha_val = alpha_net(feat_test).item()

    denom = alpha_val * (n_calib + 1) - 1
    if denom <= 0:
        q = np.quantile(scores_calib, 1 - alpha)
        half_width = q
        print(f"  [Warning] α̃ too small (denom={denom:.4f}); fallback q={q:.4f}")
    else:
        half_width = sum_scores / denom

    y_pred_test = base_model.predict(Xte).ravel()
    ymin = y_pred_test - half_width
    ymax = y_pred_test + half_width

    # =========================================================
    # 6. Metrics
    # =========================================================
    is_covered = ((yte >= ymin) & (yte <= ymax)).astype(int)
    coverage   = is_covered.mean()
    avg_width  = np.mean(ymax - ymin)
    rmse       = np.sqrt(mean_squared_error(yte, y_pred_test))

    total_time = time.time() - t_start_total

    print(f"\n{'='*55}")
    print(f"  ALPHANET CONFORMAL ({model_name})")
    print(f"{'='*55}")
    print(f"  Learned α̃     : {alpha_val:.4f}")
    print(f"  Half-width (r) : {half_width:.4f}")
    print(f"  Coverage       : {coverage*100:.3f}%")
    print(f"  Avg Width      : {avg_width:.4f}")
    print(f"  RMSE           : {rmse:.4f}")
    print(f"  Total time     : {_fmt_time(total_time)}")
    print(f"    ├─ Precompute: {_fmt_time(elapsed_precompute)}")
    print(f"    └─ Training  : {_fmt_time(train_time)}")
    print(f"{'='*55}")

    # =========================================================
    # 7. Summary & Values
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy":       "AlphaNet Conformal",
        "Coverage":       coverage,
        "Width":          avg_width,
        "RMSE":           rmse,
        "Alpha_nominal":  alpha,
        "Alpha_learned":  alpha_val,
        "Lambda_reg":     lambda_reg,
        "Total_time_sec": round(total_time, 2),
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(yte)),
        "y_true":       yte,
        "y_pred":       y_pred_test,
        "ymin":         ymin,
        "ymax":         ymax,
        "width":        ymax - ymin,
        "is_covered":   is_covered,
    })

    # =========================================================
    # 8. Plotting (SAVE ONLY — NO SHOW)
    # =========================================================
    print(f"  [Step 8/9] Generating plots...")
    idx_arr = np.arange(len(yte))

    # --- Prediction-interval plot ---
    fig_pi, ax_pi = plt.subplots(figsize=(10, 4))
    ax_pi.scatter(idx_arr, yte, color="blue", s=10, alpha=0.7, label="True")
    ax_pi.fill_between(idx_arr, ymin, ymax, color="gray", alpha=0.5,
                       label=f"AlphaNet Interval (α̃={alpha_val:.3f})")
    ax_pi.plot(idx_arr, y_pred_test, color="red", lw=1, label="Predicted mean")
    ax_pi.set_title(f"AlphaNet Conformal ({model_name})")
    ax_pi.set_xlabel("Sample Number")
    ax_pi.set_ylabel("EWQI")
    ax_pi.legend(loc="upper left")
    plt.tight_layout()

    buf_pi = io.BytesIO()
    fig_pi.savefig(buf_pi, format="png")
    buf_pi.seek(0)
    plt.close(fig_pi)

    # --- Training-curves plot ---
    arr_losses = np.array(history["losses"])
    arr_sizes  = np.array(history["sizes"])
    arr_alphas = np.array(history["alphas"])
    epochs_arr = np.arange(1, num_epochs + 1)

    fig_tc, axs = plt.subplots(1, 3, figsize=(14, 4))
    for ax, data, ylabel, title in zip(
        axs,
        [arr_losses, arr_sizes, arr_alphas],
        ["Loss", "Mean Interval Size", r"Mean $\tilde{\alpha}$"],
        ["Training Loss", "Interval Size", r"Learned $\tilde{\alpha}$"],
    ):
        m = data.mean(axis=0)
        s = data.std(axis=0)
        ax.plot(epochs_arr, m, color="#0077bb")
        ax.fill_between(epochs_arr, m - s, m + s, color="#0077bb", alpha=0.25)
        ax.set_xlabel("Epoch")
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.grid(True, linewidth=0.5)
    plt.tight_layout()

    buf_tc = io.BytesIO()
    fig_tc.savefig(buf_tc, format="png")
    buf_tc.seek(0)
    plt.close(fig_tc)

    # =========================================================
    # 9. Excel Export (append-safe)
    # =========================================================
    if excel_file_path:
        print(f"  [Step 9/9] Saving to Excel...")
        try:
            wb = load_workbook(excel_file_path)
        except FileNotFoundError:
            from openpyxl import Workbook
            wb = Workbook()
            wb.remove(wb.active)

        def _unique_sheet(wb, name):
            base, i = name, 1
            while name in wb.sheetnames:
                name = f"{base}_{i}"; i += 1
            return name

        # ---- Summary ----
        sn = _unique_sheet(wb, "AlphaNet_TabNet_Summary")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- PI Plot ----
        img_pi = Image(buf_pi)
        sn = _unique_sheet(wb, "AlphaNet_TabNet_Plot_PI")
        ws = wb.create_sheet(sn)
        ws.add_image(img_pi, "A1")

        # ---- Training Curves Plot ----
        img_tc = Image(buf_tc)
        sn = _unique_sheet(wb, "AlphaNet_TabNet_Plot_Train")
        ws = wb.create_sheet(sn)
        ws.add_image(img_tc, "A1")

        # ---- Values ----
        sn = _unique_sheet(wb, "AlphaNet_TabNet_Values")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)
        print(f"  [Step 9/9] Saved!")

    print(f"\n  ✅ AlphaNet TabNet complete in {_fmt_time(total_time)}")
    return summary_df

In [74]:
conformal_predictions_AlphaNet_tabnet(
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    best_params=best_params,
    model_name="TabNet",
    excel_file_path="./drive/MyDrive/EWQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/TabNet.xlsx",
    alpha=0.05,
)

  [Info] n_calib=24 | alpha_min=0.0500
  [Step 2/9] Training base TabNet model...
epoch 0  | loss: 22759.92969|  0:00:00s
epoch 1  | loss: 22517.81836|  0:00:00s
epoch 2  | loss: 22251.59766|  0:00:00s
epoch 3  | loss: 21912.06445|  0:00:00s
epoch 4  | loss: 21628.18945|  0:00:00s
epoch 5  | loss: 21444.60547|  0:00:00s
epoch 6  | loss: 21143.9668|  0:00:00s
epoch 7  | loss: 20887.95703|  0:00:00s
epoch 8  | loss: 20637.31445|  0:00:00s
epoch 9  | loss: 20411.61914|  0:00:00s
epoch 10 | loss: 20194.05469|  0:00:00s
epoch 11 | loss: 19989.49023|  0:00:00s
epoch 12 | loss: 19786.47266|  0:00:00s
epoch 13 | loss: 19598.81445|  0:00:00s
epoch 14 | loss: 19412.03516|  0:00:00s
epoch 15 | loss: 19208.98242|  0:00:00s
epoch 16 | loss: 19010.42578|  0:00:00s
epoch 17 | loss: 18790.71875|  0:00:00s
epoch 18 | loss: 18569.29297|  0:00:00s
epoch 19 | loss: 18351.60156|  0:00:00s
epoch 20 | loss: 18123.25195|  0:00:00s
epoch 21 | loss: 17920.70703|  0:00:00s
epoch 22 | loss: 17772.57031|  0:00:00s
epoch 23 | loss: 17571.96875|  0:00:00s
epoch 24 | loss: 17341.60352|  0:00:00s
epoch 25 | loss: 17069.51953|  0:00:00s
epoch 26 | loss: 16803.88867|  0:00:00s
epoch 27 | loss: 16540.11914|  0:00:00s
epoch 28 | loss: 16271.51465|  0:00:00s
epoch 29 | loss: 15991.66309|  0:00:00s
epoch 30 | loss: 15703.39648|  0:00:00s
epoch 31 | loss: 15412.46973|  0:00:00s
epoch 32 | loss: 15102.17383|  0:00:00s
epoch 33 | loss: 14786.72949|  0:00:00s
epoch 34 | loss: 14460.54883|  0:00:00s
epoch 35 | loss: 14136.29395|  0:00:00s
epoch 36 | loss: 13802.19434|  0:00:00s
epoch 37 | loss: 13488.61035|  0:00:00s
epoch 38 | loss: 13194.9209|  0:00:00s
epoch 39 | loss: 12840.00684|  0:00:00s
epoch 40 | loss: 12485.33789|  0:00:00s
epoch 41 | loss: 12132.1123|  0:00:00s
epoch 42 | loss: 11772.58105|  0:00:00s
epoch 43 | loss: 11416.02148|  0:00:00s
epoch 44 | loss: 11051.79297|  0:00:00s
epoch 45 | loss: 10690.0791|  0:00:00s
epoch 46 | loss: 10313.90527|  0:00:00s
epoch 47 | loss: 9940.63086|  0:00:00s
epoch 48 | loss: 9569.56348|  0:00:01s
epoch 49 | loss: 9191.54199|  0:00:01s
epoch 50 | loss: 8808.46582|  0:00:01s
epoch 51 | loss: 8438.61133|  0:00:01s
epoch 52 | loss: 8049.67139|  0:00:01s
epoch 53 | loss: 7684.49463|  0:00:01s
epoch 54 | loss: 7306.56055|  0:00:01s
epoch 55 | loss: 6938.10205|  0:00:01s
epoch 56 | loss: 6563.521|  0:00:01s
epoch 57 | loss: 6200.21484|  0:00:01s
epoch 58 | loss: 5826.94238|  0:00:01s
epoch 59 | loss: 5458.2373|  0:00:01s
epoch 60 | loss: 5100.4458|  0:00:01s
epoch 61 | loss: 4744.51074|  0:00:01s
epoch 62 | loss: 4386.37891|  0:00:01s
epoch 63 | loss: 4042.86719|  0:00:01s
epoch 64 | loss: 3709.36426|  0:00:01s
epoch 65 | loss: 3373.82422|  0:00:01s
epoch 66 | loss: 3058.45312|  0:00:01s
epoch 67 | loss: 2742.14526|  0:00:01s
epoch 68 | loss: 2443.6394|  0:00:01s
epoch 69 | loss: 2154.26123|  0:00:01s
epoch 70 | loss: 1927.74609|  0:00:01s
epoch 71 | loss: 1676.91101|  0:00:01s
epoch 72 | loss: 1421.65405|  0:00:01s
epoch 73 | loss: 1210.30603|  0:00:01s
epoch 74 | loss: 1006.80347|  0:00:01s
epoch 75 | loss: 833.71686|  0:00:01s
epoch 76 | loss: 646.99664|  0:00:01s
epoch 77 | loss: 467.06256|  0:00:01s
epoch 78 | loss: 337.89151|  0:00:01s
epoch 79 | loss: 218.63507|  0:00:01s
epoch 80 | loss: 121.16232|  0:00:01s
epoch 81 | loss: 56.68496|  0:00:01s
epoch 82 | loss: 18.7157 |  0:00:01s
epoch 83 | loss: 24.96094|  0:00:01s
epoch 84 | loss: 88.19883|  0:00:01s
epoch 85 | loss: 119.69915|  0:00:01s
epoch 86 | loss: 120.06204|  0:00:01s
epoch 87 | loss: 129.94052|  0:00:01s
epoch 88 | loss: 126.31571|  0:00:01s
epoch 89 | loss: 147.49272|  0:00:01s
epoch 90 | loss: 108.63977|  0:00:01s
epoch 91 | loss: 88.62685|  0:00:01s
epoch 92 | loss: 65.72343|  0:00:01s
epoch 93 | loss: 39.99   |  0:00:01s
epoch 94 | loss: 19.25276|  0:00:01s
epoch 95 | loss: 9.81606 |  0:00:01s
epoch 96 | loss: 8.80384 |  0:00:01s
epoch 97 | loss: 9.78082 |  0:00:01s
epoch 98 | loss: 12.431  |  0:00:02s
epoch 99 | loss: 8.33968 |  0:00:02s
  [Step 2/9] Done in 2s
  [Step 3/9] Precomputing 24 LOO score vectors...

    LOO precompute:   0%|          | 0/24 [00:00<?, ?it/s]

  [Step 3/9] Done in 0s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 68.2363 | Size: 53.0920 | α̃: 0.7572 | ⏱ 0.01s/epoch | ETA: 6s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 59.5293 | Size: 39.5293 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 59.5293 | Size: 39.5293 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 59.5293 | Size: 39.5293 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 59.5293 | Size: 39.5293 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 59.5293 | Size: 39.5293 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  ✓ Run 1 complete | Final loss: 59.5293

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 59.5307 | Size: 39.5321 | α̃: 0.9999 | ⏱ 0.01s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 59.5293 | Size: 39.5293 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 59.5293 | Size: 39.5293 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 59.5293 | Size: 39.5293 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 1s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 59.5293 | Size: 39.5293 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 59.5293 | Size: 39.5293 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  ✓ Run 2 complete | Final loss: 59.5293

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 59.5293 | Size: 39.5293 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 59.5293 | Size: 39.5293 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 59.5293 | Size: 39.5293 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 59.5293 | Size: 39.5293 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 59.5293 | Size: 39.5293 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 59.5293 | Size: 39.5293 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  ✓ Run 3 complete | Final loss: 59.5293

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 59.5331 | Size: 39.5366 | α̃: 0.9998 | ⏱ 0.01s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 59.5293 | Size: 39.5293 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 59.5293 | Size: 39.5293 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 59.5293 | Size: 39.5293 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 59.5293 | Size: 39.5293 | α̃: 1.0000 | ⏱ 0.00s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 59.5293 | Size: 39.5293 | α̃: 1.0000 | ⏱ 0.01s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 59.5293
  [Step 4/9] Training done in 1s
  [Step 5/9] Computing conformal intervals...

=======================================================
  ALPHANET CONFORMAL (TabNet)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 19.7647
  Coverage       : 44.681%
  Avg Width      : 39.5293
  RMSE           : 32.9960
  Total time     : 3s
    ├─ Precompute: 0s
    └─ Training  : 1s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet TabNet complete in 3s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.446809,39.529324,32.996021,0.05,1.0,20.0,3.18