# **Start Section:**

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# Uninstall existing scikit-learn to avoid conflicts
!pip uninstall -y scikit-learn
# Install specific versions of libraries to avoid conflicts
!pip install scikit-learn==1.5.2
!pip install bayesian-optimization==3.2.0
!pip install optuna==4.6.0
!pip install gpboost==1.6.1
!pip install shap==0.50.0
!pip install ngboost==0.5.8
!pip install dask[dataframe]==2025.12.0
!pip install torch==2.9.0+cpu
!pip install seaborn==0.13.2
!pip install lightgbm==4.6.0
!pip install xgboost==3.1.2
!pip install lime==0.2.0.1
!pip install interpret==0.7.4
!pip install optunahub==0.4.0
!pip install cmaes==0.12.0
!pip install plotly==5.24.1
!pip install kaleido==1.2.0
!pip install openpyxl==3.1.5
!pip install properscoring==0.1
!pip install XlsxWriter==3.2.9
!pip install cython==3.0.12
!pip install pgbm==2.2.0
!pip install cp==2020.12.3
!pip install mapie==0.6.0
!pip install skorch==1.3.1
!pip install puncc==0.8.0
# Reinstall scikit-learn to the version required by ngboost
!pip uninstall -y scikit-learn
!pip install scikit-learn==1.6.1
# Reinstall numpy first
!pip install numpy==1.26.4  # Use the version compatible with catboost
# Reinstall catboost
!pip install catboost==1.2.8
!pip install pytorch-tabnet2==4.5.3

Found existing installation: scikit-learn 1.6.1
Uninstalling scikit-learn-1.6.1:
  Successfully uninstalled scikit-learn-1.6.1
Collecting scikit-learn==1.5.2
  Downloading scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (3.6.0)
Downloading scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 69.6 MB/s eta 0:00:00
Installing collected packages: scikit-learn
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
hdbscan 0.8.41 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
umap-learn 0.5.11 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
Successfully installed scikit-learn-1.5.2
Collecting bayesian-optimization==3.2.0
  Downloading bayesian_optimization-3.2.0-py3-none-any.whl.metadata (11 kB)
Collecting colorama>=0.4.6 (from bayesian-optimization==3.2.0)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from bayesian-optimization==3.2.0) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from bayesian-optimization==3.2.0) (26.0)
Requirement already satisfied: scikit-learn>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bayesian-optimization==3.2.0) (1.5.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bayesian-optimization==3.2.0) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.0->bayesian-optimization==3.2.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.0->bayesian-optimization==3.2.0) (3.6.0)
Downloading bayesian_optimization-3.2.0-py3-none-any.whl (37 kB)
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Installing collected packages: colorama, bayesian-optimization
Successfully installed bayesian-optimization-3.2.0 colorama-0.4.6
Collecting optuna==4.6.0
  Downloading optuna-4.6.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna==4.6.0) (1.18.4)
Collecting colorlog (from optuna==4.6.0)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna==4.6.0) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna==4.6.0) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna==4.6.0) (2.0.46)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna==4.6.0) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna==4.6.0) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna==4.6.0) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna==4.6.0) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna==4.6.0) (3.3.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna==4.6.0) (3.0.3)
Downloading optuna-4.6.0-py3-none-any.whl (404 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 404.7/404.7 kB 11.2 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.6.0
Collecting gpboost==1.6.1
  Downloading gpboost-1.6.1-py3-none-manylinux1_x86_64.whl.metadata (7.9 kB)
Requirement already satisfied: wheel in /usr/local/lib/python3.12/dist-packages (from gpboost==1.6.1) (0.46.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from gpboost==1.6.1) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from gpboost==1.6.1) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from gpboost==1.6.1) (1.16.3)
Requirement already satisfied: scikit-learn!=0.22.0 in /usr/local/lib/python3.12/dist-packages (from gpboost==1.6.1) (1.5.2)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (from gpboost==1.6.1) (4.6.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn!=0.22.0->gpboost==1.6.1) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn!=0.22.0->gpboost==1.6.1) (3.6.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna->gpboost==1.6.1) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna->gpboost==1.6.1) (6.10.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna->gpboost==1.6.1) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->gpboost==1.6.1) (2.0.46)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna->gpboost==1.6.1) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna->gpboost==1.6.1) (6.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->gpboost==1.6.1) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->gpboost==1.6.1) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->gpboost==1.6.1) (2025.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->gpboost==1.6.1) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->gpboost==1.6.1) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->gpboost==1.6.1) (1.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna->gpboost==1.6.1) (3.3.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna->gpboost==1.6.1) (3.0.3)
Downloading gpboost-1.6.1-py3-none-manylinux1_x86_64.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 16.1 MB/s eta 0:00:00
Installing collected packages: gpboost
Successfully installed gpboost-1.6.1
Requirement already satisfied: shap==0.50.0 in /usr/local/lib/python3.12/dist-packages (0.50.0)
Requirement already satisfied: numpy>=2 in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (1.16.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (1.5.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (2.2.2)
Requirement already satisfied: tqdm>=4.27.0 in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (4.67.3)
Requirement already satisfied: packaging>20.9 in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (26.0)
Requirement already satisfied: slicer==0.0.8 in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (0.0.8)
Requirement already satisfied: numba>=0.54 in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (0.60.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (3.1.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (4.15.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.54->shap==0.50.0) (0.43.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->shap==0.50.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->shap==0.50.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->shap==0.50.0) (2025.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->shap==0.50.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->shap==0.50.0) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->shap==0.50.0) (1.17.0)
Collecting ngboost==0.5.8
  Downloading ngboost-0.5.8-py3-none-any.whl.metadata (4.2 kB)
Collecting lifelines>=0.25 (from ngboost==0.5.8)
  Downloading lifelines-0.30.1-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: numpy>=1.21.2 in /usr/local/lib/python3.12/dist-packages (from ngboost==0.5.8) (2.0.2)
Collecting scikit-learn<2.0,>=1.6 (from ngboost==0.5.8)
  Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: scipy>=1.7.2 in /usr/local/lib/python3.12/dist-packages (from ngboost==0.5.8) (1.16.3)
Requirement already satisfied: tqdm>=4.3 in /usr/local/lib/python3.12/dist-packages (from ngboost==0.5.8) (4.67.3)
Requirement already satisfied: pandas<3.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from lifelines>=0.25->ngboost==0.5.8) (2.2.2)
Requirement already satisfied: matplotlib>=3.0 in /usr/local/lib/python3.12/dist-packages (from lifelines>=0.25->ngboost==0.5.8) (3.10.0)
Requirement already satisfied: autograd>=1.5 in /usr/local/lib/python3.12/dist-packages (from lifelines>=0.25->ngboost==0.5.8) (1.8.0)
Collecting autograd-gamma>=0.3 (from lifelines>=0.25->ngboost==0.5.8)
  Downloading autograd-gamma-0.5.0.tar.gz (4.0 kB)
  Preparing metadata (setup.py) ... done
Collecting formulaic>=0.2.2 (from lifelines>=0.25->ngboost==0.5.8)
  Downloading formulaic-1.2.1-py3-none-any.whl.metadata (7.0 kB)
Requirement already satisfied: joblib>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0,>=1.6->ngboost==0.5.8) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0,>=1.6->ngboost==0.5.8) (3.6.0)
Collecting interface-meta>=1.2.0 (from formulaic>=0.2.2->lifelines>=0.25->ngboost==0.5.8)
  Downloading interface_meta-1.3.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines>=0.25->ngboost==0.5.8) (2.16.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines>=0.25->ngboost==0.5.8) (4.15.0)
Requirement already satisfied: wrapt>=1.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines>=0.25->ngboost==0.5.8) (2.1.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=2.1->lifelines>=0.25->ngboost==0.5.8) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=2.1->lifelines>=0.25->ngboost==0.5.8) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (1.17.0)
Downloading ngboost-0.5.8-py3-none-any.whl (36 kB)
Downloading lifelines-0.30.1-py3-none-any.whl (350 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 350.0/350.0 kB 15.5 MB/s eta 0:00:00
Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 95.4 MB/s eta 0:00:00
Downloading formulaic-1.2.1-py3-none-any.whl (117 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.3/117.3 kB 8.8 MB/s eta 0:00:00
Downloading interface_meta-1.3.0-py3-none-any.whl (14 kB)
Building wheels for collected packages: autograd-gamma
  Building wheel for autograd-gamma (setup.py) ... done
  Created wheel for autograd-gamma: filename=autograd_gamma-0.5.0-py3-none-any.whl size=4030 sha256=38f4b05bfaf9a03159ad35c0d4a8ce139704041fa3d5790085f4166a6dc1e603
  Stored in directory: /root/.cache/pip/wheels/50/37/21/0a719b9d89c635e89ff24bd93b862882ad675279552013b2fb
Successfully built autograd-gamma
Installing collected packages: interface-meta, scikit-learn, autograd-gamma, formulaic, lifelines, ngboost
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.5.2
    Uninstalling scikit-learn-1.5.2:
      Successfully uninstalled scikit-learn-1.5.2
Successfully installed autograd-gamma-0.5.0 formulaic-1.2.1 interface-meta-1.3.0 lifelines-0.30.1 ngboost-0.5.8 scikit-learn-1.8.0
Requirement already satisfied: dask==2025.12.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]==2025.12.0) (2025.12.0)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (8.3.1)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (3.1.2)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (2025.3.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (26.0)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (6.0.3)
Requirement already satisfied: toolz>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (0.12.1)
Requirement already satisfied: pandas>=2.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]==2025.12.0) (2.2.2)
Requirement already satisfied: pyarrow>=14.0.1 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]==2025.12.0) (18.1.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]==2025.12.0) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]==2025.12.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]==2025.12.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]==2025.12.0) (2025.3)
Requirement already satisfied: locket in /usr/local/lib/python3.12/dist-packages (from partd>=1.4.0->dask==2025.12.0->dask[dataframe]==2025.12.0) (1.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0->dask[dataframe]==2025.12.0) (1.17.0)
ERROR: Could not find a version that satisfies the requirement torch==2.9.0+cpu (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.5.0, 2.5.1, 2.6.0, 2.7.0, 2.7.1, 2.8.0, 2.9.0, 2.9.1, 2.10.0)
ERROR: No matching distribution found for torch==2.9.0+cpu
Requirement already satisfied: seaborn==0.13.2 in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from seaborn==0.13.2) (2.0.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from seaborn==0.13.2) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.12/dist-packages (from seaborn==0.13.2) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn==0.13.2) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn==0.13.2) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (1.17.0)

Collecting catboost==1.2.8
  Downloading catboost-1.2.8-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (1.26.4)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost==1.2.8) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost==1.2.8) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost==1.2.8) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost==1.2.8) (9.1.4)
Downloading catboost-1.2.8-cp312-cp312-manylinux2014_x86_64.whl (99.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 MB 8.5 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.8
Collecting pytorch-tabnet2==4.5.3
  Downloading pytorch_tabnet2-4.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting activations-plus>=0.1.1 (from pytorch-tabnet2==4.5.3)
  Downloading activations_plus-0.1.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pytorch-tabnet2==4.5.3) (1.26.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from pytorch-tabnet2==4.5.3) (1.6.1)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from pytorch-tabnet2==4.5.3) (2.10.0+cpu)
Collecting torcheval (from pytorch-tabnet2==4.5.3)
  Downloading torcheval-0.0.7-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->pytorch-tabnet2==4.5.3) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->pytorch-tabnet2==4.5.3) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->pytorch-tabnet2==4.5.3) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (3.24.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (2025.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->pytorch-tabnet2==4.5.3) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->pytorch-tabnet2==4.5.3) (3.0.3)
Downloading pytorch_tabnet2-4.5.3-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.9/70.9 kB 2.9 MB/s eta 0:00:00
Downloading activations_plus-0.1.1-py3-none-any.whl (15 kB)
Downloading torcheval-0.0.7-py3-none-any.whl (179 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.2/179.2 kB 7.4 MB/s eta 0:00:00
Installing collected packages: torcheval, activations-plus, pytorch-tabnet2
Successfully installed activations-plus-0.1.1 pytorch-tabnet2-4.5.3 torcheval-0.0.7

In [ ]:
# Restart the runtime to apply changes
import os
os._exit(00)

# **Imports**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import randint
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.base import BaseEstimator, RegressorMixin
from sklearn.svm import SVR
import ngboost
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor
from gpboost import GPBoostRegressor
from ngboost import NGBRegressor
import optuna
import optunahub
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import HalvingGridSearchCV
from interpret import show
from interpret.blackbox import LimeTabular, ShapKernel
from optuna.samplers import RandomSampler
import random
import time
from ngboost.distns import Normal
from ngboost.scores import LogScore
from scipy.stats import norm
from optuna.samplers import BaseSampler
from optuna.samplers import GridSampler
from optuna.samplers import TPESampler
from optuna.samplers import PartialFixedSampler
from optuna.samplers import CmaEsSampler
from optuna.samplers import QMCSampler
from optuna.samplers import NSGAIIISampler
from optuna.samplers import NSGAIISampler
from optuna.samplers import BruteForceSampler
from optuna.samplers import GPSampler
from interpret import set_visualize_provider
from interpret.provider import InlineProvider
from interpret.glassbox import ExplainableBoostingRegressor
from interpret import show
import plotly.express as px
from io import BytesIO
from openpyxl import Workbook, load_workbook
import os
import properscoring as ps
import io
from openpyxl.drawing.image import Image as openpyxlImage
import warnings
import xlsxwriter
from openpyxl.drawing.image import Image
from pgbm.sklearn import HistGradientBoostingRegressor
import torch
from pgbm.torch import PGBM
import plotly.graph_objects as go
warnings.filterwarnings('ignore')
import pickle
import json
from mapie.subsample import Subsample
from mapie.regression import MapieRegressor
from deel.puncc.metrics import regression_sharpness, regression_mean_coverage
from deel.puncc.api.prediction import BasePredictor, DualPredictor
from deel.puncc.regression import SplitCP, CVPlus, CQR
from deel.puncc.plotting import plot_prediction_intervals
from sklearn.model_selection import train_test_split
from typing_extensions import TypedDict
from typing import Union
from mapie.metrics import regression_coverage_score
from sklearn.model_selection import KFold
from PIL import Image as PImage
from openpyxl.utils.dataframe import dataframe_to_rows
from scipy.stats import genpareto
from pytorch_tabnet import TabNetRegressor
import torch.nn as nn
import warnings
import io
import time
import numpy as np
import pandas as pd
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
from openpyxl import load_workbook
from openpyxl.drawing.image import Image
from openpyxl.utils.dataframe import dataframe_to_rows

In [2]:
# Go to find & replace button and replace (WQI) with your folder name. Rename your train and test dataset as train.csv and test.csv.
# Modify the names of the feature in the below cell.
# Replace (WQI) with actual data label name.

In [3]:
feature_names = [f'R{i}' for i in range(1, 152)]

In [4]:
train_data_path = "./drive/MyDrive/WQI/Data/train.csv"
test_data_path = "./drive/MyDrive/WQI/Data/test.csv"
train_data = pd.read_csv(train_data_path)
test_data = pd.read_csv(test_data_path)
print("Training data loaded successfully.")
print("Test data loaded successfully.")

Training data loaded successfully.
Test data loaded successfully.

In [5]:
print("\nShape of training data:", train_data.shape)
print("First 5 rows of training data:\n", train_data.head(5))
print("\nShape of test data:", test_data.shape)
print("First 5 rows of test data:\n", test_data.head(5))

Shape of training data: (190, 152)
First 5 rows of training data:
        R1      R2      R3      R4      R5      R6      R7      R8      R9  \
0  3.5960  3.6080  3.0100  3.6130  3.3760  2.2780  1.3410  3.4570  3.3540
1  2.9540  3.0470  3.1160  4.2640  4.4090  3.4810  2.3760  3.4030  3.4320
2  2.4870  2.9430  2.5290  3.7280  2.9870  1.8890  1.9960  2.1020  1.6180
3  1.3640  1.4186  1.3789  1.4776  1.5063  1.4047  1.2648  1.5166  1.5443
4  1.3074  1.3820  1.3476  1.3986  1.3403  1.3004  1.3719  1.3984  1.3865

      R10  ...    R143    R144    R145    R146    R147   R148    R149    R150  \
0  1.9900  ...  2.7930  1.9660  2.3070  1.5280  1.9380  3.371  2.2060  1.5220
1  2.6350  ...  3.0260  2.3530  2.0400  1.7400  2.6250  4.026  2.9010  1.7450
2  1.2720  ...  1.2760  1.5990  1.8610  1.0290  1.8690  3.905  2.3200  1.3310
3  1.3834  ...  1.2223  1.0919  1.0995  1.0856  1.1728  1.315  1.2341  1.0753
4  1.3964  ...  1.1691  1.0689  1.1230  1.1384  1.1810  1.235  1.1589  1.1013

     R151  WQI
0  1.7780  333
1  1.8710  222
2  1.2180  212
3  0.9929  116
4  1.0892  111

[5 rows x 152 columns]

Shape of test data: (82, 152)
First 5 rows of test data:
        R1      R2      R3      R4      R5      R6      R7     R8      R9  \
0  4.5531  4.5227  4.3613  4.3948  4.3138  4.2704  4.4091  4.663  4.5893
1  3.1470  3.2270  1.9290  2.3130  2.5630  1.6990  0.1830  1.843  3.0820
2  6.8500  6.5500  6.1280  8.1530  7.4810  6.2120  6.6030  7.440  7.4990
3  2.8580  3.3860  3.9920  4.3540  4.7960  4.1740  2.6970  5.068  5.2800
4  2.3040  2.0470  1.5690  2.1720  2.9140  2.0430  0.1820  2.306  2.5730

      R10  ...    R143    R144    R145    R146    R147    R148    R149  \
0  4.4647  ...  4.7716  4.6602  4.5285  4.6565  4.9141  5.0277  4.5893
1  2.8590  ...  0.1470  0.6440  0.6740  0.6800  0.7440  1.3620  1.4990
2  7.2750  ...  4.8750  3.8400  3.5400  4.2900  5.0820  5.4270  5.6040
3  4.0420  ...  1.5720  0.5820  0.8030  1.0590  2.0950  3.4330  2.9190
4  1.1490  ...  1.5820  1.4180  0.5000  0.5930  1.3000  1.8410  1.1960

     R150    R151  WQI
0  4.4805  4.5112  315
1  1.3400  0.9700  167
2  5.0390  4.6130  516
3  2.6220  2.5460  144
4  1.2410  1.6430  127

[5 rows x 152 columns]

In [6]:
X_train = train_data.iloc[:, :-1]
y_train = train_data.iloc[:, -1]
X_test = test_data.iloc[:, :-1]
y_test = test_data.iloc[:, -1]
x_test= X_test
print("\nShape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (190, 151)
Shape of y_train: (190,)
Shape of X_test: (82, 151)
Shape of y_test: (82,)

In [7]:
# Apply z-score normalization
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Print the first five rows of the normalized data
print("\nFirst five rows of normalized X_train:")
print(X_train[:5])

print("\nFirst five rows of normalized X_test:")
print(X_test[:5])

First five rows of normalized X_train:
[[ 1.22103295  1.13089815  0.61081314  0.73682842  0.54673262 -0.0261968
  -0.51531151  0.70303503  0.5510272  -0.2441054   0.17648144  0.69219002
   0.9485328   0.82481901  0.34566436 -0.40609522 -0.463771    0.43872889
   0.89421381  1.05057715  1.04529849  1.03900179  0.42575888  0.173456
   0.45642529  0.83037026  0.89010153  0.77972274  0.71866378  0.6206252
   0.82167079  0.97412629  0.67298061  0.39758814  0.52679374  0.94375937
   0.74197071  0.86577935  1.27064247  1.51437415  0.46596778 -0.30888056
  -0.12461695  0.49591603  0.72957494  0.5811918   0.31848773  0.53466849
   0.20246884  0.11900459  0.99635035  0.72105768  0.43065398  0.36777539
   0.10638109 -0.0263905   0.2318847   0.82337505  0.74363607  0.85248236
   0.71669043 -0.11909161 -0.10843386  0.51688952  0.84551287 -0.1576873
  -0.12716017  0.37884167  0.35396679 -0.24556803  0.07962918  0.82628894
   0.54494889  1.02963853  1.17379609  0.60350175 -0.17692428 -0.31350223
   0.22065238  0.76789991  0.64059193  0.86621966  1.13040139  0.67180522
   0.78583621  0.79602328  0.33647099  0.60529386  1.01635137  1.08576158
   0.68198309  0.60488657  0.63845049  0.75030559  1.16412101  0.67839607
   0.21747604  0.63001733  1.09391943  1.12661486  0.75479045  0.61513105
   0.76485633  0.81239976  0.59023363  0.76823564  0.98207943  1.07081204
   0.87033709  0.63322457  0.58565002  0.57672731  0.24192312  0.42561885
   0.64460019  0.37796227  0.38542476  0.56718676  0.77331628  0.74183606
   0.44178732  0.2104186   0.18690739  0.03401537 -0.28065913 -0.29502427
   0.389348    0.73032585  0.43394604 -0.18676862  0.16122091  0.71254249
   0.69937812  0.13844222  0.38765671  0.40025623  0.22640117  0.43834726
   0.63544107  0.70463942  0.64437487  0.88740493  0.56383977  0.09354594
   0.41164416 -0.12762585 -0.0547463   0.54586569 -0.16671531 -0.40103093
  -0.02424279]
 [ 0.65952547  0.64224358  0.70577763  1.26142674  1.38515994  1.01742895
   0.3885051   0.66005629  0.61206304  0.29761137  0.20498732  0.93896615
   1.41567687  1.2167944   0.64986145  0.83692321  1.12783064  0.84781968
   0.33792581  0.52134679  0.93293667  0.66708337  1.10605833  1.60876014
   1.60031126  0.3891826   0.38140623  0.84018031  0.69161494  0.78866472
   0.69528553  0.60250985  0.83996248  0.85645528  0.91153758  1.06079075
   0.91992898  0.64778011  0.66398101  1.04394127  0.52859074  0.71587711
   1.27105658  1.00447058  1.39400348  1.65287179  1.33166848  0.87483986
   0.34574457  0.04040842  0.42467756  1.52021726  1.41580274  0.39163084
   0.63548101  0.57480518  0.86535167  1.61549164  0.71286733  0.18634241
   0.45656799  1.1618933   1.26352895  0.92521038  0.65287883  1.12380799
   0.50797829 -0.07040928  0.52925001  0.83263208  0.56022287  0.2207901
   0.81120948  1.33996448  1.55186253  1.37990409  0.75561709  0.93138637
   1.30044157  1.03963774  0.36512752  0.56799218  1.13635825  0.69881498
   0.49848213  0.48304169  0.45732619  0.38886843  0.4365353   0.58840714
   0.72919121  0.30376237  0.3006032   0.88810776  1.1780129   0.96637806
   0.73843587  0.85255864  0.66238424  0.72574019  0.928377    0.8034145
   1.28360007  1.4218135   0.77610265  0.96655222  0.64822496  0.37656798
   1.04548981  0.95904793  0.80071553  0.87906797  1.04770771  1.07203894
   0.90895524  0.62897664  0.24699574  0.5743465   1.23767461  1.05025099
   0.76653066  0.67900098  0.81706231  0.99129871  0.97143847  0.82515077
   0.78233842  0.86335957  0.56305799 -0.01019177  0.29034318  0.57059805
   0.56328969  0.42620183  0.63397046  0.79530617  0.94818028  1.27711247
   0.64624985  0.12835788  0.58450531  0.82719812  0.74617464  0.41333472
   0.19817803  0.04088639  0.49426871  1.01900218  0.37253163 -0.21513894
   0.05333799]
 [ 0.25107689  0.55165521  0.17988935  0.8294994   0.23100345 -0.36366182
   0.05666905 -0.37541303 -0.80741149 -0.84713274 -0.15972033  0.75528165
   1.03064174  0.58290952  0.09440547 -0.12643588  0.2688588   0.90254308
   0.34128098  0.04648469  0.19595476  0.3250017   0.0094466  -0.03216831
   0.2317833   0.27771232 -0.03563781 -0.18067103  0.21228438  0.64946781
   0.63027004  0.60250985  1.10798433  0.49575374  0.04526277  0.31335836
   0.08116063  0.11943038  0.48192086  0.89499154  0.66676964  0.12005569
  -0.10270887  0.32402846  0.34323406  0.2181602   0.19318269  0.29641082
  -0.5336197  -0.91364013  0.29213687 -0.26162346 -0.24687612  0.8409086
   1.54343371  0.77520373 -0.0658194   0.36351406  0.33496406  0.39106249
   0.45262674  0.32137073  0.27391643  0.25945132  0.34238851  0.70349728
   0.2003331  -0.21167764  0.34078177  0.65638783  0.57431194  0.33512632
   0.53073836  0.7517457   0.89794761  0.7805996  -0.11042594  0.16386107
   0.69504252  0.33970696 -0.19498345  0.37757463  1.25549529  0.97008699
   1.05206132  0.67881105 -0.31986571  0.24605281  0.58792491  0.47794819
   0.32907362  0.31640959  0.24977662  0.20934662  0.55565611  0.50725249
   0.36478563  0.47607111  0.58842135  0.34547882  0.07673554  0.5629438
   0.51062781  0.29563339  0.29273639  0.80393262  0.64628676  0.22429883
   0.29323131  0.37109205  0.39688748  0.51957104  1.00885648  0.56291634
  -0.09707843  0.0244365   0.0855864   0.12163065  0.10536365 -0.03141779
  -0.12534177 -0.45428198 -0.79426405  0.23336436  0.16884663 -0.29907066
   0.23875671  0.49007093  0.40637526 -0.06511134 -0.70096066  0.13360753
   0.67865684  0.06328112  0.2560504   0.45172055  0.28225312 -0.33080883
   0.02636659  0.59115629  0.42835066 -0.4197358  -0.62329321 -0.20971629
   0.05506778 -0.52426553 -0.10988754  0.93159834 -0.07826329 -0.56024784
  -0.49139587]
 [-0.73112389 -0.77616124 -0.85047542 -0.98395074 -0.97079649 -0.78380143
  -0.58185337 -0.84133442 -0.86508254 -0.75357112 -0.8354775  -0.93525463
  -0.90736841 -0.78408413 -0.8164475  -0.78272426 -0.85581654 -0.99489075
  -0.95811118 -0.91631542 -0.8553611  -0.7377413  -0.9272883  -1.05593341
  -1.03900863 -0.9072755  -0.86339025 -0.80445466 -0.66585928 -0.65170987
  -0.77461147 -0.93677653 -1.01321722 -0.97262112 -0.95260645 -1.01585273
  -0.9640642  -0.89486289 -0.85588183 -0.87540008 -0.80793281 -0.87725557
  -0.98611996 -0.97204254 -0.87633262 -0.84340581 -0.9053487  -0.78518263
  -0.68864556 -0.64874769 -0.82754072 -0.79931967 -0.67046701 -0.68886229
  -1.06763123 -0.86151757 -0.58130421 -0.71567457 -0.83235469 -0.97776313
  -1.01162613 -0.96991275 -0.96418213 -0.92237757 -0.86827988 -1.00908382
  -0.68335742 -0.4659607  -0.81942253 -1.00119673 -0.99974983 -0.90783719
  -0.97767273 -0.92843712 -0.92468273 -0.97071628 -0.70398227 -0.72417506
  -0.84927666 -0.78461624 -0.60373026 -0.68449323 -0.9071994  -0.99046978
  -1.05974972 -1.00299736 -0.81128154 -0.84544861 -0.9433779  -0.99051973
  -0.98008812 -0.86622562 -0.79701181 -0.85452036 -0.90999413 -0.889707
  -0.86288389 -0.90164285 -0.92914408 -0.77480044 -0.64390143 -1.05987529
  -1.07009555 -0.94975299 -0.88112257 -1.00387174 -1.04605013 -0.9999967
  -0.89775109 -0.90472482 -0.93842695 -0.94907808 -0.94964912 -0.9555298
  -0.92314513 -0.87179011 -0.97533801 -1.08698851 -1.06311591 -0.71423704
  -0.6865786  -0.79314619 -0.79900941 -0.89700561 -0.84484996 -0.78962774
  -0.9147197  -0.83993532 -0.62947915 -0.53755871 -0.67486293 -0.86545818
  -0.89330458 -0.73101059 -0.84954499 -0.87169677 -0.76480397 -0.74703187
  -0.77213169 -0.86526969 -0.95932712 -0.8589554  -0.66531631 -0.62874701
  -0.5537504  -0.47927594 -0.66625471 -0.93927726 -0.92080754 -0.77339843
  -0.67917473]
 [-0.78062751 -0.80804138 -0.87851682 -1.04761168 -1.10552924 -0.8742837
  -0.488328   -0.93541011 -0.98856274 -0.7426528  -0.71944178 -0.93892832
  -1.00701518 -0.84509453 -0.7479439  -0.74136953 -0.90812523 -1.07116983
  -0.98287237 -0.89608217 -0.84161247 -0.7808311  -0.94239172 -1.05424891
  -1.06102578 -0.96072257 -0.88485756 -0.79771616 -0.6970598  -0.71892568
  -0.85979999 -1.01978032 -1.08208395 -0.98061134 -0.93150566 -1.02870205
  -0.99069572 -0.94895434 -0.90759926 -0.86888353 -0.73298947 -0.79222689
  -0.94107953 -0.95440144 -0.92857939 -0.93195336 -0.97444548 -0.8596898
  -0.72397175 -0.62190048 -0.79666311 -0.852402   -0.82043111 -0.84909144
  -1.07453253 -0.86966125 -0.66883937 -0.82442006 -0.81988941 -0.92874227
  -0.98056908 -0.91168617 -0.92428108 -0.8842733  -0.8156916  -0.99057699
  -0.7265721  -0.54352668 -0.87611812 -1.05806882 -1.02197924 -0.8559833
  -0.87715188 -0.93138559 -1.00092613 -1.03057939 -0.79786227 -0.74882323
  -0.84114031 -0.85815648 -0.63261871 -0.69625431 -0.94508498 -1.01072711
  -1.14909511 -1.1169052  -0.83879934 -0.87218722 -1.00387245 -1.03585995
  -0.91871756 -0.80648257 -0.80645957 -0.91300087 -0.91677337 -0.91181305
  -0.89600167 -0.88635295 -0.96933908 -0.85296829 -0.71024632 -1.10244372
  -1.10585409 -0.99921639 -0.94665743 -1.03039659 -1.06606202 -1.03550896
  -0.93177114 -0.89356577 -0.93326951 -0.9776028  -0.9006562  -0.85269024
  -0.86736222 -0.94864595 -0.97807376 -1.03312524 -1.02863906 -0.73285593
  -0.68892211 -0.78705252 -0.82050306 -0.82563459 -0.77885002 -0.79556244
  -0.9478762  -0.8503927  -0.63680894 -0.57669759 -0.72261768 -0.90760762
  -0.91077767 -0.70754959 -0.79649279 -0.8347895  -0.773683   -0.79156196
  -0.84773907 -0.92183394 -0.946736   -0.88013659 -0.70694814 -0.64775255
  -0.53496219 -0.43730685 -0.65970169 -0.99706492 -0.97915483 -0.75172492
  -0.59884108]]

First five rows of normalized X_test:
[[ 2.05813390e+00  1.92764028e+00  1.82143127e+00  1.36682990e+00
   1.30789152e+00  1.70224871e+00  2.16391529e+00  1.66289360e+00
   1.51766275e+00  1.83432325e+00  2.00580473e+00  1.62754343e+00
   1.61090483e+00  2.01607977e+00  2.01345450e+00  2.11274022e+00
   2.02963553e+00  1.60039992e+00  1.61000684e+00  1.75082670e+00
   1.90399408e+00  1.95651619e+00  1.69470453e+00  1.30404118e+00
   1.10665769e+00  1.33955480e+00  1.64305669e+00  1.83174752e+00
   1.82426929e+00  1.82612067e+00  1.60380109e+00  1.28458204e+00
   1.16924647e+00  1.37456423e+00  1.56295700e+00  1.58972434e+00
   1.62410861e+00  1.68858511e+00  1.69468833e+00  1.69553426e+00
   2.15113781e+00  2.12564299e+00  1.69826413e+00  1.61822550e+00
   1.61952025e+00  1.65481421e+00  1.70858604e+00  1.66350031e+00
   2.03943047e+00  2.25565313e+00  1.94255984e+00  1.73876145e+00
   1.88038382e+00  1.98199460e+00  1.24919377e+00  1.79611863e+00
   2.30947030e+00  1.96267465e+00  1.78701202e+00  1.70303031e+00
   1.66164431e+00  1.71247122e+00  1.81306378e+00  1.90731154e+00
   1.87395108e+00  1.83726693e+00  2.28717797e+00  2.31176142e+00
   1.72683772e+00  1.42408704e+00  1.64695950e+00  1.87141858e+00
   1.45023488e+00  1.55542356e+00  1.42338996e+00  1.11903829e+00
   1.78102144e+00  1.92480122e+00  1.51398608e+00  1.22098633e+00
   1.93499215e+00  1.98912313e+00  1.32250987e+00  1.27981855e+00
   1.30917078e+00  1.44748634e+00  1.64468203e+00  1.78047139e+00
   1.62760989e+00  1.44842550e+00  1.63760207e+00  2.00607772e+00
   2.06422584e+00  1.79794379e+00  1.65211541e+00  1.70043044e+00
   1.72143169e+00  1.57490154e+00  1.49112564e+00  1.75141520e+00
   1.91804504e+00  1.33925485e+00  1.20409855e+00  1.41759290e+00
   1.60530277e+00  1.27795883e+00  1.17415477e+00  1.35542630e+00
   1.63028659e+00  1.52989676e+00  1.51703326e+00  1.63769730e+00
   1.53945326e+00  1.63442442e+00  1.80547855e+00  1.83456600e+00
   1.74481966e+00  1.58910193e+00  1.65979733e+00  2.24103659e+00
   2.29429741e+00  2.26160471e+00  2.31624483e+00  1.90388162e+00
   1.90494378e+00  2.05552243e+00  1.92987044e+00  1.92273155e+00
   2.13755130e+00  2.39445130e+00  2.26871512e+00  1.77861342e+00
   1.60030596e+00  1.97194343e+00  1.79722682e+00  1.67412075e+00
   1.72686156e+00  1.81102923e+00  1.88466528e+00  1.74773855e+00
   1.41317416e+00  1.73088065e+00  2.11219926e+00  2.31983774e+00
   2.18773030e+00  2.35912210e+00  2.32359949e+00  1.74257596e+00
   1.68247495e+00  2.06516393e+00  2.25579795e+00]
 [ 8.28327567e-01  7.99031141e-01 -3.57645528e-01 -3.10756535e-01
  -1.13133223e-01 -5.28490492e-01 -1.52653821e+00 -5.81551806e-01
   3.38184268e-01  4.85742461e-01 -5.59641137e-01 -6.07178145e-01
  -4.12243523e-01 -3.63407621e-01 -3.51223498e-01 -4.67097397e-01
  -4.98438029e-01 -2.91361367e-01  2.05262541e-02 -3.30652166e-01
  -1.01839043e+00 -1.17863115e+00 -7.70251433e-01 -4.64327875e-01
  -4.11966885e-01 -2.77879059e-01 -3.48113279e-01 -5.88759665e-01
  -7.54554307e-01 -1.90729809e-01 -3.47911238e-03 -1.82139835e-01
  -2.48078635e-01 -5.28136378e-01 -6.06397112e-01 -3.38156563e-01
  -1.16709055e-01  6.97994335e-02 -5.12993864e-02 -5.12583371e-01
  -5.59142712e-01 -4.50250222e-01 -4.10066343e-01 -5.78704341e-01
  -5.96689235e-01 -3.91357790e-01 -2.34286508e-01 -9.31373685e-01
  -9.08107592e-01 -5.42448317e-01 -7.91492568e-01 -5.18992328e-01
  -1.36902447e-01  1.48305187e-01  1.95522926e-01 -2.87467510e-01
  -9.33559208e-01 -1.02971228e+00 -6.27545319e-01 -4.40612832e-01
  -1.48019625e-01  5.02784178e-01  4.23404392e-02  3.71800345e-03
   4.05787057e-01 -3.61673712e-01 -5.03371451e-01 -2.91524980e-01
  -3.72760548e-01 -9.39437188e-01 -1.07332606e+00 -7.06782588e-01
  -4.03417459e-01 -3.21495587e-01  8.72051161e-02  5.40204423e-01
  -2.12911614e-01 -3.68882609e-01 -4.59214881e-01 -1.20394129e+00
  -1.38159938e+00 -1.21367199e+00 -8.65144029e-01 -4.96073615e-01
  -3.70824345e-01 -4.50291835e-01 -5.62195879e-01 -3.74282889e-01
  -5.04286747e-01 -6.19701508e-01 -3.15144493e-01 -3.99061524e-01
  -2.43540215e-01 -1.21618364e-02 -7.05727741e-01 -1.22393067e+00
  -1.22712567e+00 -7.90581646e-01 -5.06229386e-01 -5.20822738e-01
  -7.15358419e-01 -7.88808526e-01 -6.09153286e-01 -5.52089944e-01
  -7.46634593e-01 -8.46557117e-01 -5.23415257e-01 -2.74318092e-01
  -7.50948403e-01 -1.04010732e+00 -8.72875810e-01 -5.02831815e-01
  -6.74360408e-01 -4.73492737e-01 -2.00993375e-01 -2.82543556e-01
  -2.00136057e-02 -3.90015377e-01 -1.10278472e+00 -1.00542633e+00
  -2.63943562e-01 -8.44591086e-02 -8.21480046e-01 -7.11672287e-01
  -5.84856377e-01 -8.41961025e-01 -1.46596307e+00 -9.79918562e-01
  -9.76870983e-01 -1.26082863e+00 -9.80384008e-01 -5.70536068e-01
  -6.89507953e-01 -9.55151711e-01 -2.97515420e-01 -3.42790570e-01
  -8.96366350e-01 -9.07429059e-01 -8.95621947e-01 -8.71712223e-01
  -8.14714345e-01 -8.19422009e-01 -1.50679562e+00 -9.98859141e-01
  -8.93937060e-01 -8.01674845e-01 -1.00892958e+00 -9.05327006e-01
  -7.15272985e-01 -5.52745468e-01 -6.98277952e-01]
 [ 4.06705373e+00  3.69350377e+00  3.40420270e+00  4.39531743e+00
   3.87852754e+00  3.38662424e+00  4.07974453e+00  3.87311519e+00
   3.79453432e+00  4.19461260e+00  4.52195217e+00  3.74933897e+00
   3.43810777e+00  3.72199272e+00  3.40738825e+00  3.91951385e+00
   4.28792259e+00  3.63270691e+00  3.54077583e+00  3.51848365e+00
   3.56890321e+00  3.75900214e+00  3.74851177e+00  3.69811222e+00
   3.62711849e+00  2.89198388e+00  3.39421106e+00  3.95689426e+00
   3.36315943e+00  2.88351564e+00  3.30015860e+00  3.73089622e+00
   3.15218279e+00  3.19587870e+00  3.35706563e+00  3.47260246e+00
   3.77846147e+00  3.76573459e+00  3.65100182e+00  3.82930115e+00
   4.24512680e+00  4.01427274e+00  3.40193949e+00  3.37147864e+00
   3.33672769e+00  3.60065017e+00  4.11916861e+00  3.70983077e+00
   3.34013152e+00  2.98971023e+00  3.24080326e+00  4.12753937e+00
   3.87905917e+00  2.94336949e+00  3.42763327e+00  3.21351927e+00
   2.78943360e+00  3.27516448e+00  4.10926313e+00  3.94327575e+00
   3.02705065e+00  2.64964200e+00  3.66425562e+00  3.88489725e+00
   3.17581584e+00  4.14330043e+00  3.79915034e+00  2.65492947e+00
   2.51863701e+00  2.97570290e+00  3.15887283e+00  2.98982003e+00
   3.10583722e+00  2.91444482e+00  2.61114871e+00  2.78860634e+00
   4.45214225e+00  4.72455255e+00  3.79098980e+00  3.12106087e+00
   3.34579373e+00  3.23663808e+00  2.81082935e+00  3.17960335e+00
   3.76864405e+00  3.78742893e+00  3.04548676e+00  3.34206898e+00
   4.02146570e+00  4.01436962e+00  2.95545700e+00  3.13071640e+00
   3.37710638e+00  3.22618934e+00  3.17344436e+00  3.16875461e+00
   3.11528148e+00  2.93345077e+00  2.37475261e+00  2.65254241e+00
   3.37150937e+00  3.18663263e+00  2.81044070e+00  2.40850787e+00
   2.02217279e+00  2.50053096e+00  2.34172477e+00  2.14030921e+00
   2.81217452e+00  2.75976149e+00  2.72805324e+00  2.85443148e+00
   2.62496670e+00  2.80668856e+00  2.94214814e+00  2.70081496e+00
   3.37560110e+00  3.28403265e+00  2.86351213e+00  3.57013394e+00
   3.42875645e+00  3.19771885e+00  3.19950849e+00  2.42620317e+00
   2.37427668e+00  2.63388614e+00  2.41836744e+00  1.95675112e+00
   1.98261696e+00  2.39097538e+00  2.13289761e+00  2.59005213e+00
   2.66117971e+00  1.90741226e+00  1.96744447e+00  2.14024048e+00
   2.14064340e+00  1.97567207e+00  2.27188965e+00  2.78339034e+00
   2.99595267e+00  2.79806459e+00  2.19311524e+00  1.64208385e+00
   1.39742593e+00  2.06780258e+00  2.45777652e+00  2.03100864e+00
   2.46977549e+00  2.53072750e+00  2.34071971e+00]
 [ 5.75561738e-01  9.37526822e-01  1.49057855e+00  1.33395185e+00
   1.69926582e+00  1.61861985e+00  6.68819235e-01  1.98523416e+00
   2.05814293e+00  1.47930980e+00  1.78790238e+00  1.86936807e+00
   1.71142849e+00  1.50708579e+00  1.66911920e+00  1.38831953e+00
   1.10548967e+00  1.04268838e+00  4.30528635e-01  5.35799112e-01
   1.24280406e+00  1.71136922e+00  1.66953216e+00  1.15627049e+00
   7.98417581e-01  1.45167044e+00  1.59009579e+00  1.34651250e+00
   1.18792966e+00  1.17992093e+00  1.39951877e+00  1.36389804e+00
   7.97951114e-01  1.48140494e+00  1.71889849e+00  1.01072062e+00
   1.09539832e+00  1.00776156e+00  9.12076539e-01  1.10476241e+00
   1.47746460e+00  1.42410465e+00  1.08677097e+00  1.09493772e+00
   1.60208305e+00  1.50417619e+00  6.95118877e-01  1.06282930e+00
   1.61627432e+00  1.44580132e+00  4.64002827e-01  6.04802987e-01
   9.70524731e-01  1.24008991e+00  1.35077233e+00  1.01392552e+00
   4.85609789e-01  4.71858270e-01  8.49354318e-01  1.52901825e+00
   1.71303820e+00  9.17896170e-01  9.46986227e-01  1.28408946e+00
   1.47218312e+00  1.53918355e+00  5.70229081e-01  3.92711275e-02
   8.55773180e-01  2.68354279e-01 -4.36969911e-01 -3.87929477e-01
   8.46361860e-01  9.79514622e-01  8.18833702e-01  8.24369026e-01
   6.35137756e-01  9.61026571e-01  1.22390478e+00  9.07252646e-01
   2.06205745e-01  2.36161603e-01  7.16400180e-01  5.44976745e-01
   1.15166935e+00  1.51550684e+00  9.09138699e-01  3.73768978e-01
   5.03955774e-01  8.97229549e-01  9.22053644e-01  7.55448677e-01
   5.58921838e-01  3.97258683e-01  1.16116628e-01  5.23160063e-01
   8.49724499e-01  4.88638151e-01  3.93057309e-01  4.22507517e-01
   5.45812466e-01  7.37924603e-01  7.75632875e-01  6.67766943e-01
   5.07447146e-01  8.66898135e-01  8.63364846e-01  6.38264437e-01
   5.14979152e-01  1.91599702e-01  2.70014304e-01  7.57811204e-01
   1.02903894e+00  1.28840269e+00  1.10422397e+00  3.45269444e-01
   3.20313875e-01  9.55464960e-01  1.52235660e+00  7.92499705e-01
   2.99168082e-01  3.10578956e-01  5.95845138e-01  5.49737316e-01
   4.58105617e-01  4.06349626e-01  5.05593906e-01  1.12744142e+00
   8.66336574e-01 -3.93238411e-01 -7.53566036e-01  3.00934609e-02
   4.92165281e-01  2.89217632e-02  9.73665660e-03  2.72820760e-01
   5.53875024e-01  5.42020415e-01  5.66805350e-01  7.04048360e-01
   8.13490966e-01  4.13729628e-01 -3.91657509e-01 -1.05009145e+00
  -7.90801740e-01 -5.00419459e-01  7.07200136e-02  5.90651128e-01
   3.86497740e-01  5.15925078e-01  6.16424302e-01]
 [ 9.10210161e-02 -2.28798441e-01 -6.80166453e-01 -4.24379211e-01
   1.71753505e-01 -2.30063843e-01 -1.52741146e+00 -2.13048890e-01
  -6.01137126e-02 -9.50436872e-01 -8.37154317e-01 -6.24747967e-01
  -4.95946812e-01 -5.12653478e-01 -7.13889630e-01 -1.06523565e+00
  -9.86857896e-01 -4.13487982e-01 -7.29690868e-01 -8.41300973e-01
  -7.42720111e-01 -8.20590289e-01 -7.14097684e-01 -8.27946002e-01
  -1.03783512e+00 -6.86212319e-01 -5.32646037e-01 -5.03741200e-01
  -4.33742512e-01 -4.84171961e-01 -4.35497948e-01 -4.44824436e-01
  -7.10735413e-01 -8.93974488e-01 -1.03863277e+00 -1.01018214e+00

# **Functions:**

In [8]:
def get_best_model_params(results, model_name):
    # Map model names to dictionary keys, assuming keys are strings like 'XGBoost' and not objects
    model_keys = {
        'LightGBM': 'LightGBM',
        'XGBoost': 'XGBoost',
        'GPBoost': 'GPBoost',
        'NGBoost': 'NGBoost',
        'GradientBoosting': 'Gradient Boosting',
        'HGBR' : 'HistGradientBoosting',
        'CatBoost' : 'CatBoost',
        'TabNet' : 'TabNet',
        'PGBM' : 'PGBM'
    }

    # Ensure the requested model name is valid
    if model_name not in model_keys:
        raise ValueError(f"Model name '{model_name}' is not recognized. Available models are: {list(model_keys.keys())}")

    # Filter out entries for the specified model
    model_entries = {key: value for key, value in results.items() if key[0] == model_keys[model_name]}

    # Find the entry with the best (lowest) 'best_score'
    best_entry_key, best_entry_value = min(model_entries.items(), key=lambda item: item[1]['best_score'])

    # Return the best hyperparameters
    return best_entry_value['best_params']

In [9]:
class validate:
    @staticmethod
    def coverage(int_pred, y_test):
        return {strat_name: np.mean((y_test.to_numpy() >= int_pred[strat_name][:, 0]) & (y_test.to_numpy() <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred): # Corrected: Removed y_test argument as it's not defined and not used
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        return {strat_name: np.sqrt(mean_squared_error(y_test, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = validate.width(int_pred)
        coverages = validate.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}

    @staticmethod
    def cond_coverage(int_pred, y_test, num_bins=10):
        cond_coverages = {}
        for strat_name in int_pred:
            widths = int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]
            bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
            digitized_widths = np.digitize(widths, bin_edges)
            strategy_cond_coverage = []
            for bin_num in range(1, num_bins + 1):
                indices_in_bin = np.where(digitized_widths == bin_num)[0]
                if len(indices_in_bin) > 0:
                    bin_coverage = np.mean((y_test.to_numpy()[indices_in_bin] >= int_pred[strat_name][indices_in_bin, 0]) & (y_test.to_numpy()[indices_in_bin] <= int_pred[strat_name][indices_in_bin, 1]))
                    strategy_cond_coverage.append(bin_coverage)
                else:
                    strategy_cond_coverage.append(np.nan) # or handle empty bins as needed
            cond_coverages[strat_name] = strategy_cond_coverage
        return cond_coverages


class visualize:
    @staticmethod
    def coverage(int_pred, y_test):
        return {strat_name: np.mean((y_test.to_numpy() >= int_pred[strat_name][:, 0]) & (y_test.to_numpy() <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred):
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        return {strat_name: np.sqrt(mean_squared_error(y_test, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = visualize.width(int_pred)
        coverages = visualize.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}
    @staticmethod
    def goodness(y_true, y_pred, y_pred_low, y_pred_up, coverage, width, rmse, cwc, ax=None, title="Goodness Plot"):
        if ax is None:
            fig, ax = plt.subplots()
        n_samples = len(y_true)
        y_true_np = y_true.to_numpy().ravel() # Ensure y_true is numpy array and flattened

        # Determine points inside and outside the interval
        inside_interval = (y_true_np >= y_pred_low) & (y_true_np <= y_pred_up)
        outside_interval = ~inside_interval

        # Plot points inside the interval in green
        ax.scatter(y_true_np[inside_interval], y_pred[inside_interval], color='green', s=10, label='Inside Interval')
        # Plot points outside the interval in orange
        ax.scatter(y_true_np[outside_interval], y_pred[outside_interval], color='orange', s=10, label='Outside Interval')

        # Plot all ground truth values as blue crosses
        ax.scatter(y_true_np, y_true_np, color='blue', marker='x', s=30, linewidths=0.7, label='Ground Truth Values')


        ax.vlines(y_true_np, y_pred_low, y_pred_up, color='gray', alpha=0.5, label='Prediction Intervals')
        ax.plot([min(y_true_np), max(y_true_np)], [min(y_true_np), max(y_true_np)], linestyle='--', color='blue', label='Ideal Prediction Line') # Changed label for clarity
        ax.set_xlabel('Ground Truth')
        ax.set_ylabel('Predictions')
        ax.set_title(f'{title}\nCoverage: {coverage*100:.2f}%, Width: {width:.2f}, RMSE: {rmse:.2f}, CWC: {cwc:.2f}')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def width_size_occurrence(int_pred, train_intervals, num_bins=10, ax=None, x_lim=None, title="Width Size Occurrence"):
        if ax is None:
            fig, ax = plt.subplots()

        # Calculate interval widths for test and train sets
        widths_test = np.abs(int_pred[:, 1] - int_pred[:, 0])
        widths_train = np.abs(train_intervals[:, 1] - train_intervals[:, 0])

        # Plot histograms for both train and test widths
        ax.hist(widths_test, bins=num_bins, alpha=0.6, label='Test Interval Widths', color='red')
        ax.hist(widths_train, bins=num_bins, alpha=0.4, label='Train Interval Widths', color='blue')


        if x_lim is not None:
            ax.set_xlim(x_lim)
        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Occurrence (Frequency)')
        ax.set_title(f'{title} - Interval Width Occurrence')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def coverage_by_width(y_test, int_pred, miscoverage, cond_coverages, num_bins=10, ax=None, title="Coverage vs Width"):
        if ax is None:
            fig, ax = plt.subplots()

        widths = int_pred[:, 1] - int_pred[:, 0]
        bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
        bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
        bin_width = bin_edges[1] - bin_edges[0]

        ax.bar(bin_centers, cond_coverages, width=bin_width, color='blue', alpha=0.7, edgecolor='black', linewidth=0.8, label='Conditional Coverage')
        ax.axhline(1 - miscoverage, color='red', linestyle='--', label=f'Nominal Coverage ({(1 - miscoverage)*100:.0f}%)')

        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Conditional Coverage')
        ax.set_title(f'{title} - Coverage vs Interval Width')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax


def weighted_quantile(values, weights, q):
    sorter = np.argsort(values)
    values = values[sorter]
    weights = weights[sorter]
    cum_weights = np.cumsum(weights)
    cum_weights = cum_weights / cum_weights[-1]
    return np.interp(q, cum_weights, values)

In [10]:
def conformal_predictions_NEXCP(
    model_class,
    best_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    decay=0.99,
    n_folds=5,
    n_bootstrap=50,
):

    warnings.filterwarnings("ignore")

    SEED = 123
    np.random.seed(SEED)

    strategies_names = {
        "NexCP-Split": "NexCP Split",
        "NexCP-Full": "NexCP Full",
        "NexCP-J+aB": "NexCP Jackknife+ aB",
        "NexCP-CV+": "NexCP CV+",
    }

    y_pred, int_pred = {}, {}

    # =========================================================
    # NexCP – Split
    # =========================================================
    model = model_class(**best_params)
    model.fit(X_train, y_train)

    yhat_train = model.predict(X_train)
    yhat_test = model.predict(X_test)

    res = np.abs(y_train.to_numpy() - yhat_train)
    weights = decay ** np.arange(len(res) - 1, -1, -1)
    q = weighted_quantile(res, weights, 1 - alpha)

    y_pred["NexCP-Split"] = yhat_test
    int_pred["NexCP-Split"] = np.c_[yhat_test - q, yhat_test + q]

    # =========================================================
    # NexCP – Full
    # =========================================================
    model = model_class(**best_params)
    model.fit(X_train, y_train)

    yhat_train = model.predict(X_train)
    yhat_test = model.predict(X_test)

    q = np.quantile(np.abs(y_train.to_numpy() - yhat_train), 1 - alpha)

    y_pred["NexCP-Full"] = yhat_test
    int_pred["NexCP-Full"] = np.c_[yhat_test - q, yhat_test + q]

    # =========================================================
    # NexCP – Jackknife+ after Bootstrap
    # =========================================================
    rng = np.random.default_rng(SEED)
    lowers_t, uppers_t, preds_t = [], [], []

    for _ in range(n_bootstrap):
        idx = rng.choice(len(X_train), len(X_train), replace=True)

        model = model_class(**best_params)
        model.fit(X_train[idx], y_train.iloc[idx])

        yte = model.predict(X_test)

        q = np.quantile(
            np.abs(y_train.iloc[idx].to_numpy() - model.predict(X_train[idx])),
            1 - alpha,
        )

        lowers_t.append(yte - q)
        uppers_t.append(yte + q)
        preds_t.append(yte)

    y_pred["NexCP-J+aB"] = np.mean(preds_t, axis=0)
    int_pred["NexCP-J+aB"] = np.c_[np.min(lowers_t, axis=0), np.max(uppers_t, axis=0)]

    # =========================================================
    # NexCP – CV+
    # =========================================================
    kf = KFold(n_splits=n_folds, shuffle=True, random_state=SEED)

    lowers_t, uppers_t, preds_t = [], [], []

    for tr, cal in kf.split(X_train):
        model = model_class(**best_params)
        model.fit(X_train[tr], y_train.iloc[tr])

        y_cal = model.predict(X_train[cal])
        q = np.quantile(np.abs(y_train.iloc[cal].to_numpy() - y_cal), 1 - alpha)

        yte = model.predict(X_test)

        lowers_t.append(yte - q)
        uppers_t.append(yte + q)
        preds_t.append(yte)

    y_pred["NexCP-CV+"] = np.mean(preds_t, axis=0)
    int_pred["NexCP-CV+"] = np.c_[np.mean(lowers_t, axis=0), np.mean(uppers_t, axis=0)]

    # =========================================================
    # Metrics
    # =========================================================
    def coverage(y, l, u):
        return np.mean((y >= l) & (y <= u))

    def width(l, u):
        return np.mean(u - l)

    def cwc(l, u, y, alpha):
        cov = coverage(y, l, u)
        w = width(l, u)
        penalty = np.exp(-50 * (cov - (1 - alpha)))
        return w * (1 + penalty if cov < (1 - alpha) else 1)

    y_true = y_test.to_numpy()

    summary_rows = []

    print("\n===== NEXCP RESULTS =====")

    for s in strategies_names:
        cov = coverage(y_true, int_pred[s][:, 0], int_pred[s][:, 1])
        wid = width(int_pred[s][:, 0], int_pred[s][:, 1])
        rmse = np.sqrt(mean_squared_error(y_true, y_pred[s]))
        cwc_val = cwc(int_pred[s][:, 0], int_pred[s][:, 1], y_true, alpha)

        summary_rows.append([
            strategies_names[s],
            cov,
            wid,
            rmse,
            cwc_val,
        ])

        print(f"{strategies_names[s]} - Coverage: {cov*100:.3f}% | Width: {wid:.3f}")

    summary_df = pd.DataFrame(
        summary_rows,
        columns=["Strategy", "Coverage", "Width", "RMSE", "CWC"],
    )

    # =========================================================
    # Plotting (SAVE ONLY — NO SHOW)
    # =========================================================
    idx = np.arange(len(y_test))
    plot_buffers = {}

    for s in strategies_names:
        fig, ax = plt.subplots(figsize=(10, 4))

        ax.scatter(idx, y_test, color="blue", s=10, alpha=0.7, label="True")
        ax.fill_between(
            idx,
            int_pred[s][:, 0],
            int_pred[s][:, 1],
            color="gray",
            alpha=0.5,
            label="Prediction interval",
        )
        ax.plot(idx, y_pred[s], color="red", linewidth=1, label="Predicted mean")

        ax.set_title(strategies_names[s])
        ax.set_xlabel("Sample Number")
        ax.set_ylabel("WQI")
        ax.legend(loc="upper left")

        plt.tight_layout()

        buf = io.BytesIO()
        fig.savefig(buf, format="png")
        buf.seek(0)
        plot_buffers[s] = buf

        plt.close(fig)

    # =========================================================
    # Excel Export
    # =========================================================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary sheet ----
        sheet_name = "NEXCP_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name, 0)
        for r_idx, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c_idx, val in enumerate(row, 1):
                ws.cell(row=r_idx, column=c_idx, value=val)

        # ---- Plot sheets ----
        for s, buf in plot_buffers.items():
            img = Image(buf)

            sheet_name = f"NEXCP_Plot_{s}"
            base = sheet_name
            i = 1
            while sheet_name in wb.sheetnames:
                sheet_name = f"{base}_{i}"
                i += 1

            ws = wb.create_sheet(sheet_name)
            ws.add_image(img, "A1")

        # ---- Values sheet ----
        results_dict = {}
        for s in strategies_names:
            results_dict[f"{s}_true"] = y_true
            results_dict[f"{s}_pred"] = y_pred[s]
            results_dict[f"{s}_lower"] = int_pred[s][:, 0]
            results_dict[f"{s}_upper"] = int_pred[s][:, 1]

        df_vals = pd.DataFrame(results_dict)

        sheet_name = "NEXCP_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r_idx, row in enumerate(dataframe_to_rows(df_vals, index=False, header=True), 1):
            for c_idx, val in enumerate(row, 1):
                ws.cell(row=r_idx, column=c_idx, value=val)

        wb.save(excel_file_path)

    return summary_df

In [11]:
def conformal_predictions_online_super(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    strategies="all",
    window_min=50,
    window_max=500,
    window_grid=(25, 50, 100, 200, 400),
    n_bootstrap=30,
):

    warnings.filterwarnings("ignore")

    SEED = 123
    np.random.seed(SEED)

    STRATEGY_NAMES = {
        "Online-Split": "Online Split",
        "Online-CV+": "Online CV+",
        "Online-J+aB": "Online Jackknife+ aB",
        "SAOCP": "SAOCP",
        "SF-OGD": "SF-OGD",
        "FACI": "FACI",
        "MFCS-Split": "MFCS Split",
        "MFCS-Full": "MFCS Full",
    }

    ALL_STRATEGIES = list(STRATEGY_NAMES.keys())
    if strategies == "all":
        strategies = ALL_STRATEGIES

    # =========================================================
    # Base model
    # =========================================================
    base_model = model_class(**model_params)
    base_model.fit(X_train, y_train)

    yhat_train = base_model.predict(X_train)

    X_all = np.vstack([X_train, X_test])
    y_all = np.concatenate([y_train.to_numpy(), y_test.to_numpy()])

    n_train = len(X_train)
    T = len(y_all)

    y_hat_all = np.zeros(T)
    y_hat_all[:n_train] = yhat_train
    for t in range(n_train, T):
        y_hat_all[t] = base_model.predict(X_all[t:t + 1])[0]

    residuals = np.abs(y_all - y_hat_all)

    y_pred, int_pred = {}, {}

    # =========================================================
    # Online methods (UNCHANGED LOGIC)
    # =========================================================
    if "Online-Split" in strategies:
        q = np.quantile(residuals[:n_train], 1 - alpha)
        y_pred["Online-Split"] = y_hat_all[n_train:]
        int_pred["Online-Split"] = np.c_[y_hat_all[n_train:] - q,
                                         y_hat_all[n_train:] + q]

    if "Online-CV+" in strategies:
        lower, upper = [], []
        for t in range(n_train, T):
            q = np.quantile(residuals[:t], 1 - alpha)
            lower.append(y_hat_all[t] - q)
            upper.append(y_hat_all[t] + q)
        y_pred["Online-CV+"] = y_hat_all[n_train:]
        int_pred["Online-CV+"] = np.c_[lower, upper]

    if "Online-J+aB" in strategies:
        lowers, uppers, preds = [], [], []
        for _ in range(n_bootstrap):
            idx = np.random.choice(n_train, n_train, replace=True)
            m = model_class(**model_params)
            m.fit(X_train[idx], y_train.iloc[idx])
            res = np.abs(y_train.iloc[idx] - m.predict(X_train[idx]))
            q = np.quantile(res, 1 - alpha)
            p = m.predict(X_test)
            preds.append(p)
            lowers.append(p - q)
            uppers.append(p + q)
        y_pred["Online-J+aB"] = np.mean(preds, axis=0)
        int_pred["Online-J+aB"] = np.c_[np.min(lowers, axis=0),
                                        np.max(uppers, axis=0)]

    if "SAOCP" in strategies:
        lower, upper = [], []
        for t in range(n_train, T):
            w = min(max(window_min, t // 2), window_max)
            start = max(0, t - w)
            q = np.quantile(residuals[start:t], 1 - alpha)
            lower.append(y_hat_all[t] - q)
            upper.append(y_hat_all[t] + q)
        y_pred["SAOCP"] = y_hat_all[n_train:]
        int_pred["SAOCP"] = np.c_[lower, upper]

    if "SF-OGD" in strategies:
        q_t = np.quantile(residuals[:n_train], 1 - alpha)
        lower, upper = [], []
        for t in range(n_train, T):
            r_t = residuals[t]
            grad = alpha - (r_t <= q_t)
            eta = 1.0 / np.sqrt(t - n_train + 1)
            q_t = max(0.0, q_t - eta * grad)
            lower.append(y_hat_all[t] - q_t)
            upper.append(y_hat_all[t] + q_t)
        y_pred["SF-OGD"] = y_hat_all[n_train:]
        int_pred["SF-OGD"] = np.c_[lower, upper]

    if "FACI" in strategies:
        windows = list(window_grid)
        losses = np.zeros(len(windows))
        lower, upper = [], []
        for t in range(n_train, T):
            r_t = residuals[t]
            qs = []
            for i, w in enumerate(windows):
                start = max(0, t - w)
                q = np.quantile(residuals[start:t], 1 - alpha)
                qs.append(q)
                losses[i] += alpha * q + (r_t - q) * (r_t > q)
            q_star = qs[np.argmin(losses)]
            lower.append(y_hat_all[t] - q_star)
            upper.append(y_hat_all[t] + q_star)
        y_pred["FACI"] = y_hat_all[n_train:]
        int_pred["FACI"] = np.c_[lower, upper]

    if "MFCS-Split" in strategies:
        q = np.quantile(residuals[:n_train], 1 - alpha)
        y_pred["MFCS-Split"] = y_hat_all[n_train:]
        int_pred["MFCS-Split"] = np.c_[y_hat_all[n_train:] - q,
                                       y_hat_all[n_train:] + q]

    if "MFCS-Full" in strategies:
        lower, upper, preds = [], [], []
        for t in range(n_train, T):
            m = model_class(**model_params)
            m.fit(X_all[:t], y_all[:t])
            yhat = m.predict(X_all[t:t + 1])[0]
            preds.append(yhat)
            res = np.abs(y_all[:t] - m.predict(X_all[:t]))
            q = np.quantile(res, 1 - alpha)
            lower.append(yhat - q)
            upper.append(yhat + q)
        y_pred["MFCS-Full"] = np.array(preds)
        int_pred["MFCS-Full"] = np.c_[lower, upper]

    # =========================================================
    # METRICS
    # =========================================================
    y_true = y_test.to_numpy().ravel()

    rows = []
    for s in y_pred:
        ymin, ymax = int_pred[s].T
        cov = np.mean((y_true >= ymin) & (y_true <= ymax))
        wid = np.mean(ymax - ymin)
        rmse = np.sqrt(mean_squared_error(y_true, y_pred[s]))
        cwc = wid * (1 + (cov < (1 - alpha)) * (1 - cov))

        rows.append([STRATEGY_NAMES[s], cov, wid, rmse, cwc])

    summary_df = pd.DataFrame(
        rows, columns=["Strategy", "Coverage", "Width", "RMSE", "CWC"]
    )

    print("\n===== ONLINE CP RESULTS =====")
    print(summary_df)

    # =========================================================
    # PLOTTING (SAVE ONLY)
    # =========================================================
    plot_buffers = {}
    idx = np.arange(len(y_test))

    for s in y_pred:
        fig, ax = plt.subplots(figsize=(10, 4))

        ax.scatter(idx, y_true, color="blue", s=10, alpha=0.7, label="True")
        ax.fill_between(idx,
                        int_pred[s][:, 0],
                        int_pred[s][:, 1],
                        color="gray",
                        alpha=0.5,
                        label="Prediction interval")
        ax.plot(idx, y_pred[s], color="red", linewidth=1, label="Predicted mean")

        ax.set_title(f"{STRATEGY_NAMES[s]} ({model_name})")
        ax.set_xlabel("Sample Number")
        ax.set_ylabel("WQI")
        ax.legend(loc="upper left")

        plt.tight_layout()

        buf = io.BytesIO()
        fig.savefig(buf, format="png")
        buf.seek(0)
        plot_buffers[s] = buf

        plt.close(fig)

    # =========================================================
    # EXCEL EXPORT (APPEND SAFE)
    # =========================================================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary ----
        sheet_name = "ONLINECP_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plots ----
        for s, buf in plot_buffers.items():
            img = Image(buf)
            sheet_name = f"ONLINECP_Plot_{s}"
            base = sheet_name
            i = 1
            while sheet_name in wb.sheetnames:
                sheet_name = f"{base}_{i}"
                i += 1
            ws = wb.create_sheet(sheet_name)
            ws.add_image(img, "A1")

        # ---- Values ----
        values = {}
        for s in y_pred:
            values[f"{s}_true"] = y_true
            values[f"{s}_pred"] = y_pred[s]
            values[f"{s}_lower"] = int_pred[s][:, 0]
            values[f"{s}_upper"] = int_pred[s][:, 1]

        df_vals = pd.DataFrame(values)

        sheet_name = "ONLINECP_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(df_vals, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)

    return summary_df

In [12]:
def conformal_predictions_COP(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    lr=0.05,          # Learning rate for COP
    T_burnin=50,      # Window size for distribution estimation
    scale=0.5,        # Scale factor for the integrator
    random_state=123,
):
    """
    Conformal Optimistic Prediction (COP)
    ✔ Implements the Distribution-Informed Gradient logic from the repository.
    ✔ Matches the "Excel-safe" and plotting structure of your previous functions.
    """

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)

    # =========================================================
    # 1. Train Base Model & Generate Test Predictions
    # =========================================================
    # COP is an online calibration method, but we usually start with a pre-trained model
    # or an online model. Here we fit on Train and calibrate on Test stream.
    model = model_class(**model_params)
    model.fit(X_train, y_train)

    # Predict on test set
    y_pred_test = model.predict(X_test).ravel()
    y_true_test = y_test.to_numpy().ravel()

    # Calculate non-conformity scores (Absolute Residuals)
    # This assumes symmetric intervals.
    scores = np.abs(y_true_test - y_pred_test)
    T_test = len(scores)

    # =========================================================
    # 2. COP Initialization
    # =========================================================
    # Initialize quantiles based on training data residuals if possible
    y_pred_train = model.predict(X_train).ravel()
    scores_train = np.abs(y_train.to_numpy().ravel() - y_pred_train)
    init_q = np.quantile(scores_train, 1 - alpha)

    # Arrays to store history
    qs = np.zeros(T_test)          # Final adaptive quantile
    qts = np.zeros(T_test)         # Base quantile term
    integrators = np.zeros(T_test) # Optimistic integrator term
    covereds = np.zeros(T_test)    # Coverage boolean

    # Set initial values
    qs[0] = init_q
    qts[0] = init_q

    # =========================================================
    # 3. Online COP Loop
    # =========================================================
    # Logic adapted from `core/methods.py` function `COP`

    for t in range(T_test - 1):
        # 1. Observe coverage at current step t
        covereds[t] = 1 if qs[t] >= scores[t] else 0

        # 2. Calculate Standard Gradient
        # If covered, we decrease q (grad is positive). If not, increase q.
        grad = alpha if covereds[t] else -(1 - alpha)

        # 3. Calculate Distribution-Informed Gradient (The "Optimistic" part)
        if t < T_burnin:
            grad_i = 0
        else:
            # Look at the window of recent scores
            window_s = scores[t - T_burnin : t]

            # Calculate ECDF at the predicted next quantile step
            # logic: np.mean(window_s <= qts[t] - lr * grad) - (1 - alpha)
            current_target = qts[t] - lr * grad
            grad_i = np.mean(window_s <= current_target) - (1 - alpha)

        # 4. Update Terms
        integrator = -scale * grad_i

        # Update base quantile (Gradient Descent)
        qts[t + 1] = qts[t] - lr * grad

        # Update integrator state
        integrators[t + 1] = lr * integrator

        # Combine for final quantile
        qs[t + 1] = qts[t + 1] + integrators[t + 1]

        # Safety: Ensure quantile implies non-negative width
        qs[t + 1] = max(0, qs[t + 1])

    # Handle the final step coverage for metrics
    covereds[-1] = 1 if qs[-1] >= scores[-1] else 0

    # =========================================================
    # 4. Construct Prediction Intervals
    # =========================================================
    ymin = y_pred_test - qs
    ymax = y_pred_test + qs

    # =========================================================
    # 5. Metrics
    # =========================================================
    rmse = np.sqrt(mean_squared_error(y_true_test, y_pred_test))
    coverage = np.mean(covereds)
    avg_width = np.mean(ymax - ymin)

    print(f"\n===== CONFORMAL OPTIMISTIC PREDICTION ({model_name}) =====")
    print(f"Coverage : {coverage*100:.3f}%")
    print(f"Avg Width: {avg_width:.3f}")
    print(f"RMSE     : {rmse:.3f}")
    print(f"Final q  : {qs[-1]:.3f}")

    # =========================================================
    # 6. Summary Tables
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy": "COP",
        "Coverage": coverage,
        "Width": avg_width,
        "RMSE": rmse,
        "Alpha": alpha,
        "LR": lr,
        "Scale": scale
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(y_true_test)),
        "y_true": y_true_test,
        "y_pred": y_pred_test,
        "ymin": ymin,
        "ymax": ymax,
        "width": ymax - ymin,
        "is_covered": covereds.astype(int),
        "score_residual": scores,
        "adaptive_q": qs
    })

    # =========================================================
    # 7. Plotting
    # =========================================================
    idx = np.arange(len(y_true_test))
    fig, ax = plt.subplots(figsize=(10, 4))

    ax.scatter(idx, y_true_test, color="blue", s=10, alpha=0.7, label="True")
    ax.fill_between(idx, ymin, ymax, color="gray", alpha=0.5, label="COP Interval")
    ax.plot(idx, y_pred_test, color="red", linewidth=1, label="Predicted mean")

    ax.set_title(f"Conformal Optimistic Prediction (COP) - {model_name}")
    ax.set_xlabel("Sample Number")
    ax.set_ylabel("WQI")
    ax.legend(loc="upper left")

    plt.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    buf.seek(0)
    plt.close(fig)

    # =========================================================
    # 8. Excel Export
    # =========================================================
    if excel_file_path:
        try:
            wb = load_workbook(excel_file_path)
        except FileNotFoundError:
            # Create a new workbook if it doesn't exist
            from openpyxl import Workbook
            wb = Workbook()
            wb.remove(wb.active) # Remove default sheet

        # ---- Summary ----
        sheet_name = "COP_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot ----
        img = Image(buf)
        sheet_name = "COP_Plot"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "COP_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)

    return summary_df

In [13]:
def conformal_predictions_EXTREME(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    calib_size=0.2,
    gpd_threshold_quantile=0.95,
    n_bootstrap=30,
    random_state=123,
):
    """
    Extreme Conformal Prediction (upper-tail, single-sided)
    ✔ Same structure as NexCP & OnlineCP
    ✔ No return values
    ✔ Excel-safe
    """

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)

    # =========================================================
    # Train / calibration split
    # =========================================================
    X_fit, X_calib, y_fit, y_calib = train_test_split(
        X_train,
        y_train,
        test_size=calib_size,
        random_state=random_state,
        shuffle=True,
    )

    # =========================================================
    # Train model
    # =========================================================
    model = model_class(**model_params)
    model.fit(X_fit, y_fit)

    y_pred_test = model.predict(X_test).ravel()
    y_pred_calib = model.predict(X_calib).ravel()

    # =========================================================
    # Nonconformity scores (upper tail only)
    # =========================================================
    scores = y_calib.to_numpy().ravel() - y_pred_calib
    scores = scores[scores > 0]

    if len(scores) < 30:
        raise RuntimeError("Too few calibration exceedances for GPD fitting.")

    # =========================================================
    # Peaks-over-threshold
    # =========================================================
    u = np.quantile(scores, gpd_threshold_quantile)
    excesses = scores[scores > u] - u

    # =========================================================
    # Bootstrap GPD extreme quantile
    # =========================================================
    boot_q = []
    n_exc = len(excesses)
    n_scores = len(scores)

    for _ in range(n_bootstrap):
        resampled = np.random.choice(excesses, size=n_exc, replace=True)
        xi_b, _, sigma_b = genpareto.fit(resampled, floc=0)

        q_b = (
            u
            + (sigma_b / xi_b)
            * ((n_scores / (n_scores * alpha)) ** xi_b - 1)
        )
        boot_q.append(q_b)

    q_extreme = np.quantile(boot_q, 0.95)

    # =========================================================
    # Finite prediction intervals (for plotting & width)
    # =========================================================
    ymin = y_pred_test - q_extreme
    ymax = y_pred_test + q_extreme

    # =========================================================
    # Metrics
    # =========================================================
    y_true = y_test.to_numpy().ravel()

    rmse = np.sqrt(mean_squared_error(y_true, y_pred_test))
    coverage = np.mean(y_true <= ymax)
    width = q_extreme  # meaningful one-sided width

    print(f"\n===== EXTREME CONFORMAL PREDICTION ({model_name}) =====")
    print(f"Coverage : {coverage*100:.3f}%")
    print(f"Width    : {width:.3f}")
    print(f"RMSE     : {rmse:.3f}")
    print(f"q_extreme: {q_extreme:.3f}")
    print(f"u        : {u:.3f}")
    print(f"#Exceed. : {len(scores)}")

    # =========================================================
    # Summary table
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy": "EXTREME CP",
        "Coverage": coverage,
        "Width": width,
        "RMSE": rmse,
        "q_extreme": q_extreme,
        "threshold_u": u,
        "n_exceedances": len(scores),
    }])

    # =========================================================
    # Values table
    # =========================================================
    values_df = pd.DataFrame({
        "sample_index": np.arange(len(y_true)),
        "y_true": y_true,
        "y_pred": y_pred_test,
        "ymin": ymin,
        "ymax": ymax,
        "width": ymax - ymin,
        "is_covered": (y_true <= ymax).astype(int),
        "residual": y_true - y_pred_test,
    })

    # =========================================================
    # Plot (SAVE ONLY)
    # =========================================================
    idx = np.arange(len(y_true))

    fig, ax = plt.subplots(figsize=(10, 4))
    ax.scatter(idx, y_true, s=10, alpha=0.7, label="True")
    ax.fill_between(idx, ymin, ymax, alpha=0.4, label="Extreme PI")
    ax.plot(idx, y_pred_test, color="red", lw=1, label="Prediction")

    ax.set_title(f"Extreme Conformal Prediction ({model_name})")
    ax.set_xlabel("Sample Number")
    ax.set_ylabel("WQI")
    ax.legend(loc="upper left")

    plt.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    buf.seek(0)
    plt.close(fig)

    # =========================================================
    # Excel export (append-safe, SAME FILE)
    # =========================================================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary ----
        sheet_name = "EXTREMECP_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot ----
        img = Image(buf)
        sheet_name = "EXTREMECP_Plot"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "EXTREMECP_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)

In [14]:


try:
    from tqdm.auto import tqdm
    HAS_TQDM = True
except ImportError:
    HAS_TQDM = False
    print("[Info] Install tqdm for progress bars: pip install tqdm")


# ═══════════════════════════════════════════════════════════
# AlphaNet Architecture  (FIXED)
# ═══════════════════════════════════════════════════════════
class AlphaNet(nn.Module):
    """
    Maps a feature vector (sum of LOO scores) → learned α̃.
    Output is clamped to (alpha_min, 1) so that the conformal
    denominator α̃·(n+1)−1 is always positive.
    """

    def __init__(self, input_dim, alpha_min=0.05):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, 32)
        self.fc2 = nn.Linear(32, 1)
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()
        self.alpha_min = alpha_min  # lower bound for valid α̃
        self._initialize_near_one()

    def _initialize_near_one(self):
        """Bias output toward α̃ ≈ 1 at init (sigmoid(5) ≈ 0.993)."""
        with torch.no_grad():
            self.fc2.weight.data.normal_(0, 0.01)
            self.fc2.bias.data.fill_(5.0)

    def forward(self, x):
        x = self.relu(self.fc1(x))
        raw = self.sigmoid(self.fc2(x)).squeeze(-1)
        # Remap from (0,1) → (alpha_min, 1) so denominator stays positive
        return self.alpha_min + (1.0 - self.alpha_min) * raw


def _interval_size(scores, alpha, eps=1e-8):
    """
    Conformal interval width = 2 * Σscores / (α̃·(n+1) − 1).
    Denominator is clamped to be strictly positive.
    """
    n = len(scores)
    denom = alpha * (n + 1) - 1
    denom = torch.clamp(denom, min=eps)   # ← KEY FIX: prevent negative/zero
    r = scores.sum() / denom
    return 2 * r


def _fmt_time(seconds):
    """Format seconds into human-readable string."""
    if seconds < 60:
        return f"{seconds:.0f}s"
    elif seconds < 3600:
        return f"{seconds/60:.1f}min"
    else:
        return f"{seconds/3600:.1f}hr"


# ═══════════════════════════════════════════════════════════
# Main function  (CORRECTED + PROGRESS TRACKING)
# ═══════════════════════════════════════════════════════════
def conformal_predictions_AlphaNet(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    lambda_reg=20.0,
    num_epochs=50,
    batch_size=32,
    lr_alpha=1e-3,
    calib_fraction=0.5,
    num_runs=4,
    random_state=123,
):
    """
    Learned-α Conformal Prediction via AlphaNet.
    - FIXED: α̃ clamped to valid range (no negative intervals)
    - FIXED: LOO scores precomputed (massive speedup)
    - ADDED: tqdm progress bars + ETA estimates
    """

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)
    torch.manual_seed(random_state)
    device = "cuda" if torch.cuda.is_available() else "cpu"

    t_start_total = time.time()

    # --- numpy-ify if pandas ---
    y_train_np = y_train.to_numpy().ravel() if hasattr(y_train, "to_numpy") else np.asarray(y_train).ravel()
    y_test_np  = y_test.to_numpy().ravel()  if hasattr(y_test,  "to_numpy") else np.asarray(y_test).ravel()
    X_train_np = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    X_test_np  = X_test.to_numpy()  if hasattr(X_test,  "to_numpy") else np.asarray(X_test)

    # =================================================================
    # 1.  Split training data → fit + calibration
    # =================================================================
    n_total = len(X_train_np)
    n_fit   = int(n_total * (1 - calib_fraction))
    perm    = np.random.permutation(n_total)

    fit_idx   = perm[:n_fit]
    calib_idx = perm[n_fit:]

    X_fit,   y_fit   = X_train_np[fit_idx],   y_train_np[fit_idx]
    X_calib, y_calib = X_train_np[calib_idx],  y_train_np[calib_idx]
    n_calib = len(X_calib)

    # Compute alpha_min: must satisfy α̃·(n+1) − 1 > 0  →  α̃ > 1/(n+1)
    alpha_min = 1.0 / (n_calib + 1) + 0.01   # small margin above threshold
    print(f"  [Info] n_calib={n_calib} | alpha_min={alpha_min:.4f}")

    # =================================================================
    # 2.  Train base regression model
    # =================================================================
    print(f"  [Step 2/9] Training base {model_name} model...")
    t0 = time.time()
    base_model = model_class(**model_params)
    base_model.fit(X_fit, y_fit)
    print(f"  [Step 2/9] Done in {_fmt_time(time.time()-t0)}")

    # =================================================================
    # 3.  PRECOMPUTE all LOO scores  (KEY SPEEDUP)
    # =================================================================
    print(f"  [Step 3/9] Precomputing {n_calib} LOO score vectors...")
    t0 = time.time()

    precomputed_scores = []
    precomputed_sums   = []

    iterator = tqdm(range(n_calib), desc="    LOO precompute", leave=False) if HAS_TQDM else range(n_calib)

    for i in iterator:
        loo_X = np.delete(X_calib, i, axis=0)
        loo_y = np.delete(y_calib, i, axis=0)
        scores_loo = np.abs(base_model.predict(loo_X).ravel() - loo_y)

        scores_tensor = torch.tensor(scores_loo, dtype=torch.float32).to(device)
        precomputed_scores.append(scores_tensor)
        precomputed_sums.append(scores_loo.sum())

    elapsed_precompute = time.time() - t0
    print(f"  [Step 3/9] Done in {_fmt_time(elapsed_precompute)}")

    # Build feature matrix (sum of LOO scores per sample)
    X_alpha = torch.tensor(
        np.array(precomputed_sums).reshape(-1, 1),
        dtype=torch.float32,
    ).to(device)

    # =================================================================
    # 4.  Train AlphaNet (multiple runs, keep best)
    # =================================================================
    print(f"  [Step 4/9] Training AlphaNet: {num_runs} runs × {num_epochs} epochs")

    best_net   = None
    best_loss  = np.inf
    history    = {"losses": [], "sizes": [], "alphas": []}

    t0_train = time.time()

    for run in range(num_runs):
        np.random.seed(run)
        torch.manual_seed(run)

        alpha_net = AlphaNet(input_dim=1, alpha_min=alpha_min).to(device)
        optimizer = optim.Adam(alpha_net.parameters(), lr=lr_alpha)

        dataset = TensorDataset(X_alpha, torch.arange(n_calib))
        loader  = DataLoader(dataset, batch_size=batch_size, shuffle=True)

        run_losses, run_sizes, run_alphas = [], [], []

        epoch_iter = (
            tqdm(range(num_epochs), desc=f"    Run {run+1}/{num_runs}", leave=False)
            if HAS_TQDM else range(num_epochs)
        )

        for epoch in epoch_iter:
            t_epoch_start = time.time()
            epoch_loss = epoch_size = epoch_alpha = 0.0

            for x_batch, idx_batch in loader:
                x_batch = x_batch.to(device)
                alpha_pred = alpha_net(x_batch)

                batch_sizes = []
                for j, idx in enumerate(idx_batch):
                    # USE PRECOMPUTED scores instead of calling predict()
                    scores_t = precomputed_scores[idx.item()]
                    size_j = _interval_size(scores_t, alpha_pred[j])
                    batch_sizes.append(size_j)

                batch_sizes = torch.stack(batch_sizes)
                loss = (batch_sizes + lambda_reg * alpha_pred).mean()

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

                epoch_loss  += loss.item()
                epoch_size  += batch_sizes.mean().item()
                epoch_alpha += alpha_pred.mean().item()

            n_batches = len(loader)
            run_losses.append(epoch_loss  / n_batches)
            run_sizes.append(epoch_size   / n_batches)
            run_alphas.append(epoch_alpha / n_batches)

            epoch_time = time.time() - t_epoch_start

            if epoch % 10 == 0 or epoch == num_epochs - 1:
                epochs_done = (run * num_epochs) + epoch + 1
                epochs_total = num_runs * num_epochs
                elapsed_train = time.time() - t0_train
                eta = (elapsed_train / epochs_done) * (epochs_total - epochs_done)

                print(
                    f"  λ={lambda_reg} | Run {run+1}/{num_runs} | "
                    f"Epoch {epoch}/{num_epochs} | "
                    f"Loss: {run_losses[-1]:.4f} | "
                    f"Size: {run_sizes[-1]:.4f} | "
                    f"α̃: {run_alphas[-1]:.4f} | "
                    f"⏱ {epoch_time:.2f}s/epoch | "
                    f"ETA: {_fmt_time(eta)}"
                )

        if run_losses[-1] < best_loss:
            best_loss = run_losses[-1]
            best_net  = alpha_net

        history["losses"].append(run_losses)
        history["sizes"].append(run_sizes)
        history["alphas"].append(run_alphas)

        print(f"  ✓ Run {run+1} complete | Final loss: {run_losses[-1]:.4f}")

    train_time = time.time() - t0_train
    print(f"  [Step 4/9] Training done in {_fmt_time(train_time)}")

    alpha_net = best_net
    alpha_net.eval()

    # =================================================================
    # 5.  Compute conformal intervals on the TEST set
    # =================================================================
    print(f"  [Step 5/9] Computing conformal intervals on test set...")

    scores_calib = np.abs(base_model.predict(X_calib).ravel() - y_calib)
    sum_scores   = scores_calib.sum()

    with torch.no_grad():
        feat_test = torch.tensor([sum_scores], dtype=torch.float32).to(device)
        alpha_val = alpha_net(feat_test).item()

    denom = alpha_val * (n_calib + 1) - 1
    if denom <= 0:
        q = np.quantile(scores_calib, 1 - alpha)
        half_width = q
        print(f"  [Warning] α̃ too small (denom={denom:.4f}); fallback q={q:.4f}")
    else:
        half_width = sum_scores / denom

    y_pred_test = base_model.predict(X_test_np).ravel()
    ymin = y_pred_test - half_width
    ymax = y_pred_test + half_width

    # =================================================================
    # 6.  Metrics
    # =================================================================
    y_true_test = y_test_np
    is_covered  = ((y_true_test >= ymin) & (y_true_test <= ymax)).astype(int)
    coverage    = is_covered.mean()
    avg_width   = np.mean(ymax - ymin)
    rmse        = np.sqrt(mean_squared_error(y_true_test, y_pred_test))

    total_time = time.time() - t_start_total

    print(f"\n{'='*55}")
    print(f"  ALPHANET CONFORMAL ({model_name})")
    print(f"{'='*55}")
    print(f"  Learned α̃     : {alpha_val:.4f}")
    print(f"  Half-width (r) : {half_width:.4f}")
    print(f"  Coverage       : {coverage*100:.3f}%")
    print(f"  Avg Width      : {avg_width:.4f}")
    print(f"  RMSE           : {rmse:.4f}")
    print(f"  Total time     : {_fmt_time(total_time)}")
    print(f"    ├─ Precompute: {_fmt_time(elapsed_precompute)}")
    print(f"    └─ Training  : {_fmt_time(train_time)}")
    print(f"{'='*55}")

    # =================================================================
    # 7.  Summary & values DataFrames
    # =================================================================
    summary_df = pd.DataFrame([{
        "Strategy":       "AlphaNet Conformal",
        "Coverage":       coverage,
        "Width":          avg_width,
        "RMSE":           rmse,
        "Alpha_nominal":  alpha,
        "Alpha_learned":  alpha_val,
        "Lambda_reg":     lambda_reg,
        "Total_time_sec": round(total_time, 2),
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(y_true_test)),
        "y_true":       y_true_test,
        "y_pred":       y_pred_test,
        "ymin":         ymin,
        "ymax":         ymax,
        "width":        ymax - ymin,
        "is_covered":   is_covered,
    })

    # =================================================================
    # 8.  Plotting (SAVE ONLY — NO SHOW)
    # =================================================================
    print(f"  [Step 8/9] Generating plots...")
    idx = np.arange(len(y_true_test))

    # --- PI plot ---
    fig_pi, ax_pi = plt.subplots(figsize=(10, 4))
    ax_pi.scatter(idx, y_true_test, color="blue", s=10, alpha=0.7, label="True")
    ax_pi.fill_between(idx, ymin, ymax, color="gray", alpha=0.5,
                       label=f"AlphaNet Interval (α̃={alpha_val:.3f})")
    ax_pi.plot(idx, y_pred_test, color="red", linewidth=1, label="Predicted mean")
    ax_pi.set_title(f"AlphaNet Conformal – {model_name}")
    ax_pi.set_xlabel("Sample Number")
    ax_pi.set_ylabel("WQI")
    ax_pi.legend(loc="upper left")
    plt.tight_layout()

    buf_pi = io.BytesIO()
    fig_pi.savefig(buf_pi, format="png")
    buf_pi.seek(0)
    plt.close(fig_pi)

    # --- Training curves ---
    arr_losses = np.array(history["losses"])
    arr_sizes  = np.array(history["sizes"])
    arr_alphas = np.array(history["alphas"])
    epochs_arr = np.arange(1, num_epochs + 1)

    fig_tc, axs = plt.subplots(1, 3, figsize=(14, 4))
    for ax, data, ylabel, title in zip(
        axs,
        [arr_losses, arr_sizes, arr_alphas],
        ["Loss", "Mean Interval Size", r"Mean $\tilde{\alpha}$"],
        ["Training Loss", "Interval Size", r"Learned $\tilde{\alpha}$"],
    ):
        m = data.mean(axis=0)
        s = data.std(axis=0)
        ax.plot(epochs_arr, m, color="#0077bb")
        ax.fill_between(epochs_arr, m - s, m + s, color="#0077bb", alpha=0.25)
        ax.set_xlabel("Epoch")
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.grid(True, linewidth=0.5)
    plt.tight_layout()

    buf_tc = io.BytesIO()
    fig_tc.savefig(buf_tc, format="png")
    buf_tc.seek(0)
    plt.close(fig_tc)

    # =================================================================
    # 9.  Excel Export
    # =================================================================
    if excel_file_path:
        print(f"  [Step 9/9] Saving to Excel...")
        try:
            wb = load_workbook(excel_file_path)
        except FileNotFoundError:
            from openpyxl import Workbook
            wb = Workbook()
            wb.remove(wb.active)

        def _unique_sheet(wb, name):
            base, i = name, 1
            while name in wb.sheetnames:
                name = f"{base}_{i}"; i += 1
            return name

        sn = _unique_sheet(wb, "AlphaNet_Summary")
        ws = wb.create_sheet(sn, 0)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        sn = _unique_sheet(wb, "AlphaNet_Plot_PI")
        ws = wb.create_sheet(sn)
        ws.add_image(Image(buf_pi), "A1")

        sn = _unique_sheet(wb, "AlphaNet_Plot_Train")
        ws = wb.create_sheet(sn)
        ws.add_image(Image(buf_tc), "A1")

        sn = _unique_sheet(wb, "AlphaNet_Values")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)
        print(f"  [Step 9/9] Saved!")

    print(f"\n  ✅ AlphaNet Conformal complete in {_fmt_time(total_time)}")
    return summary_df

# **Tuned Parameters**

In [15]:
best_scores_autosampler = {('Random Forest', 'MedianPruner'): {'best_score': 925.9229836969165,
  'best_params': {'n_estimators': 700,
   'criterion': 'friedman_mse',
   'max_depth': 30,
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.2,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.05},
  'test_mse': 925.9229836969165,
  'test_rmse': 30.428982626714888,
  'test_corr_coef': 0.9384435962694506,
  'pruner': 'MedianPruner'},
 ('Random Forest', 'NopPruner'): {'best_score': 884.5655573170734,
  'best_params': {'n_estimators': 100,
   'criterion': 'friedman_mse',
   'max_depth': 40,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 'sqrt',
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001},
  'test_mse': 884.5655573170734,
  'test_rmse': 29.741646849444525,
  'test_corr_coef': 0.9266370563047189,
  'pruner': 'NopPruner'},
 ('Random Forest', 'PatientPruner'): {'best_score': 952.3059884361339,
  'best_params': {'n_estimators': 500,
   'criterion': 'friedman_mse',
   'max_depth': None,
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.2,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.1},
  'test_mse': 952.3059884361339,
  'test_rmse': 30.859455413797146,
  'test_corr_coef': 0.9431234158200679,
  'pruner': 'PatientPruner'},
 ('Random Forest', 'PercentilePruner'): {'best_score': 945.1750384494538,
  'best_params': {'n_estimators': 300,
   'criterion': 'friedman_mse',
   'max_depth': 30,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.05},
  'test_mse': 945.1750384494538,
  'test_rmse': 30.74369916664964,
  'test_corr_coef': 0.9369852382981433,
  'pruner': 'PercentilePruner'},
 ('Random Forest',
  'SuccessiveHalvingPruner'): {'best_score': 949.8734761204729, 'best_params': {'n_estimators': 700,
   'criterion': 'friedman_mse',
   'max_depth': 10,
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_features': 0.5,
   'max_leaf_nodes': 200,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.1}, 'test_mse': 949.8734761204729, 'test_rmse': 30.82001745814679, 'test_corr_coef': 0.9353194353048929, 'pruner': 'SuccessiveHalvingPruner'},
 ('Random Forest', 'HyperbandPruner'): {'best_score': 950.8061182872815,
  'best_params': {'n_estimators': 500,
   'criterion': 'squared_error',
   'max_depth': 40,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_features': 0.3,
   'max_leaf_nodes': 200,
   'min_impurity_decrease': 0.01,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.01},
  'test_mse': 950.8061182872815,
  'test_rmse': 30.83514420733721,
  'test_corr_coef': 0.9312225050028389,
  'pruner': 'HyperbandPruner'},
 ('Random Forest', 'ThresholdPruner'): {'best_score': 928.6979037649045,
  'best_params': {'n_estimators': 200,
   'criterion': 'squared_error',
   'max_depth': 30,
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.3,
   'max_leaf_nodes': 50,
   'min_impurity_decrease': 0.1,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.01},
  'test_mse': 928.6979037649045,
  'test_rmse': 30.474545177326345,
  'test_corr_coef': 0.9305524100852464,
  'pruner': 'ThresholdPruner'},
 ('Random Forest', 'WilcoxonPruner'): {'best_score': 944.473006562782,
  'best_params': {'n_estimators': 700,
   'criterion': 'friedman_mse',
   'max_depth': 10,
   'min_samples_split': 2,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_features': 0.5,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.2,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001},
  'test_mse': 944.473006562782,
  'test_rmse': 30.732279553635163,
  'test_corr_coef': 0.9366163217464192,
  'pruner': 'WilcoxonPruner'},
 ('Gradient Boosting', 'MedianPruner'): {'best_score': 875.5173308277115,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 100,
   'subsample': 0.9,
   'criterion': 'squared_error',
   'min_samples_split': 10,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 10,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'tol': 0.0001,
   'ccp_alpha': 0.0},
  'test_mse': 875.5173308277115,
  'test_rmse': 29.58914211037068,
  'test_corr_coef': 0.9265557047442682,
  'pruner': 'MedianPruner'},
 ('Gradient Boosting', 'NopPruner'): {'best_score': 664.2972880055108,
  'best_params': {'loss': 'quantile',
   'learning_rate': 0.05,
   'n_estimators': 500,
   'subsample': 0.5,
   'criterion': 'squared_error',
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.001,
   'ccp_alpha': 0.01},
  'test_mse': 664.2972880055108,
  'test_rmse': 25.773965313965775,
  'test_corr_coef': 0.9495779363320385,
  'pruner': 'NopPruner'},
 ('Gradient Boosting', 'PatientPruner'): {'best_score': 773.891298245442,
  'best_params': {'loss': 'absolute_error',
   'learning_rate': 0.05,
   'n_estimators': 500,
   'subsample': 0.9,
   'criterion': 'friedman_mse',
   'min_samples_split': 0.01,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 5,
   'min_impurity_decrease': 0.1,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.001,
   'ccp_alpha': 0.01},
  'test_mse': 773.891298245442,
  'test_rmse': 27.818901815949566,
  'test_corr_coef': 0.9437312892357432,
  'pruner': 'PatientPruner'},
 ('Gradient Boosting', 'PercentilePruner'): {'best_score': 793.2999777602216,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.1,
   'n_estimators': 300,
   'subsample': 0.5,
   'criterion': 'friedman_mse',
   'min_samples_split': 5,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.1,
   'max_depth': 5,
   'min_impurity_decrease': 0.1,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 50,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'tol': 0.0001,
   'ccp_alpha': 0.001},
  'test_mse': 793.2999777602216,
  'test_rmse': 28.165581438348145,
  'test_corr_coef': 0.9332348490667438,
  'pruner': 'PercentilePruner'},
 ('Gradient Boosting',
  'SuccessiveHalvingPruner'): {'best_score': 659.7597327344057, 'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 500,
   'subsample': 0.5,
   'criterion': 'squared_error',
   'min_samples_split': 2,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 7,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 50,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.0}, 'test_mse': 659.7597327344057, 'test_rmse': 25.685788536356164, 'test_corr_coef': 0.9543547128124821, 'pruner': 'SuccessiveHalvingPruner'},
 ('Gradient Boosting', 'HyperbandPruner'): {'best_score': 654.5467763955762,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.2,
   'n_estimators': 200,
   'subsample': 0.5,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 10,
   'min_impurity_decrease': 0.1,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 50,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.001},
  'test_mse': 654.5467763955762,
  'test_rmse': 25.584111796104555,
  'test_corr_coef': 0.9522653568521282,
  'pruner': 'HyperbandPruner'},
 ('Gradient Boosting', 'ThresholdPruner'): {'best_score': 747.4310241048272,
  'best_params': {'loss': 'squared_error',
   'learning_rate': 0.05,
   'n_estimators': 300,
   'subsample': 1.0,
   'criterion': 'squared_error',
   'min_samples_split': 0.01,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 3,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': 30,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.0},
  'test_mse': 747.4310241048272,
  'test_rmse': 27.339184773961847,
  'test_corr_coef': 0.9394670832526059,
  'pruner': 'ThresholdPruner'},
 ('Gradient Boosting', 'WilcoxonPruner'): {'best_score': 764.0838158013141,
  'best_params': {'loss': 'absolute_error',
   'learning_rate': 0.2,
   'n_estimators': 300,
   'subsample': 1.0,
   'criterion': 'friedman_mse',
   'min_samples_split': 2,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.05,
   'max_depth': 7,
   'min_impurity_decrease': 0.1,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.001},
  'test_mse': 764.0838158013141,
  'test_rmse': 27.642066055223044,
  'test_corr_coef': 0.9354276383227715,
  'pruner': 'WilcoxonPruner'},
 ('XGBoost', 'MedianPruner'): {'best_score': 614.4274291992188,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 3,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.6,
   'colsample_bytree': 0.7,
   'colsample_bylevel': 0.5,
   'reg_alpha': 0,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 614.4274291992188,
  'test_rmse': 24.787646705551108,
  'test_corr_coef': 0.9522169703567832,
  'pruner': 'MedianPruner'},
 ('XGBoost', 'NopPruner'): {'best_score': 670.6622924804688,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.1,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 670.6622924804688,
  'test_rmse': 25.89714834649693,
  'test_corr_coef': 0.9513704007098449,
  'pruner': 'NopPruner'},
 ('XGBoost', 'PatientPruner'): {'best_score': 669.5545043945312,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.15,
   'max_depth': 7,
   'min_child_weight': 3,
   'gamma': 0,
   'subsample': 0.7,
   'colsample_bytree': 0.7,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 669.5545043945312,
  'test_rmse': 25.8757512817412,
  'test_corr_coef': 0.9509928934435375,
  'pruner': 'PatientPruner'},
 ('XGBoost', 'PercentilePruner'): {'best_score': 659.177490234375,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0.1,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0.01,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 659.177490234375,
  'test_rmse': 25.674452092194198,
  'test_corr_coef': 0.9456642589505885,
  'pruner': 'PercentilePruner'},
 ('XGBoost', 'SuccessiveHalvingPruner'): {'best_score': 667.6946411132812,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.15,
   'max_depth': 3,
   'min_child_weight': 1,
   'gamma': 1,
   'subsample': 0.7,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 0.01,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 667.6946411132812,
  'test_rmse': 25.839787946368315,
  'test_corr_coef': 0.9466963925325174,
  'pruner': 'SuccessiveHalvingPruner'},
 ('XGBoost', 'HyperbandPruner'): {'best_score': 648.543701171875,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.15,
   'max_depth': 3,
   'min_child_weight': 3,
   'gamma': 0.1,
   'subsample': 0.6,
   'colsample_bytree': 0.5,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 648.543701171875,
  'test_rmse': 25.466521183150927,
  'test_corr_coef': 0.948750104221492,
  'pruner': 'HyperbandPruner'},
 ('XGBoost', 'ThresholdPruner'): {'best_score': 641.7772827148438,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.1,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0.1,
   'subsample': 0.7,
   'colsample_bytree': 0.7,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 0.1,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 641.7772827148438,
  'test_rmse': 25.333323562352486,
  'test_corr_coef': 0.9546356735260031,
  'pruner': 'ThresholdPruner'},
 ('XGBoost', 'WilcoxonPruner'): {'best_score': 555.0560913085938,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 7,
   'min_child_weight': 5,
   'gamma': 0.5,
   'subsample': 0.5,
   'colsample_bytree': 0.7,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 555.0560913085938,
  'test_rmse': 23.559628420427046,
  'test_corr_coef': 0.9561345408003707,
  'pruner': 'WilcoxonPruner'},
 ('LightGBM', 'MedianPruner'): {'best_score': 691.8386654480481,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.05,
   'num_leaves': 31,
   'max_depth': 3,
   'min_child_samples': 1,
   'subsample': 0.5,
   'colsample_bytree': 0.5,
   'reg_alpha': 0,
   'reg_lambda': 0.1,
   'min_child_weight': 0.1,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 691.8386654480481,
  'test_rmse': 26.302826187466017,
  'test_corr_coef': 0.9518587758240807,
  'pruner': 'MedianPruner'},
 ('LightGBM', 'NopPruner'): {'best_score': 749.9714349120778,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.05,
   'num_leaves': 15,
   'max_depth': -1,
   'min_child_samples': 20,
   'subsample': 0.7,
   'colsample_bytree': 0.9,
   'reg_alpha': 1,
   'reg_lambda': 1,
   'min_child_weight': 0.1,
   'bagging_freq': 0,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 749.9714349120778,
  'test_rmse': 27.385606345525343,
  'test_corr_coef': 0.9390178067480383,
  'pruner': 'NopPruner'},
 ('LightGBM', 'PatientPruner'): {'best_score': 713.0824325972014,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': -1,
   'min_child_samples': 10,
   'subsample': 0.5,
   'colsample_bytree': 1.0,
   'reg_alpha': 0,
   'reg_lambda': 0.1,
   'min_child_weight': 0.001,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 713.0824325972014,
  'test_rmse': 26.703603363538814,
  'test_corr_coef': 0.9362955441578421,
  'pruner': 'PatientPruner'},
 ('LightGBM', 'PercentilePruner'): {'best_score': 715.4970836892941,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.15,
   'num_leaves': 63,
   'max_depth': -1,
   'min_child_samples': 20,
   'subsample': 0.9,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 0,
   'min_child_weight': 1e-05,
   'bagging_freq': 0,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 715.4970836892941,
  'test_rmse': 26.748777237273746,
  'test_corr_coef': 0.9390824848906032,
  'pruner': 'PercentilePruner'},
 ('LightGBM', 'SuccessiveHalvingPruner'): {'best_score': 679.1289844325579,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.1,
   'num_leaves': 31,
   'max_depth': 3,
   'min_child_samples': 5,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 0,
   'min_child_weight': 1e-05,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 679.1289844325579,
  'test_rmse': 26.060103308171247,
  'test_corr_coef': 0.946583168228478,
  'pruner': 'SuccessiveHalvingPruner'},
 ('LightGBM', 'HyperbandPruner'): {'best_score': 562.2992986035254,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'num_leaves': 31,
   'max_depth': 7,
   'min_child_samples': 5,
   'subsample': 0.5,
   'colsample_bytree': 0.5,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'min_child_weight': 0.1,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 562.2992986035254,
  'test_rmse': 23.712850916824095,
  'test_corr_coef': 0.9578239395238843,
  'pruner': 'HyperbandPruner'},
 ('LightGBM', 'ThresholdPruner'): {'best_score': 757.8422227270987,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'num_leaves': 15,
   'max_depth': 7,
   'min_child_samples': 20,
   'subsample': 1.0,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.01,
   'reg_lambda': 0.1,
   'min_child_weight': 0.1,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 757.8422227270987,
  'test_rmse': 27.528934282443604,
  'test_corr_coef': 0.9386332240637238,
  'pruner': 'ThresholdPruner'},
 ('LightGBM', 'WilcoxonPruner'): {'best_score': 581.91510158147,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'num_leaves': 63,
   'max_depth': 3,
   'min_child_samples': 1,
   'subsample': 0.5,
   'colsample_bytree': 0.7,
   'reg_alpha': 1,
   'reg_lambda': 0.1,
   'min_child_weight': 0.01,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 581.91510158147,
  'test_rmse': 24.122916523121123,
  'test_corr_coef': 0.9541693709217092,
  'pruner': 'WilcoxonPruner'},
 ('GPBoost', 'MedianPruner'): {'best_score': 708.2076521710694,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': -1,
   'num_leaves': 31,
   'min_child_samples': 20,
   'subsample': 1.0,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 0.5,
   'min_child_weight': 0.01,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 708.2076521710694,
  'test_rmse': 26.612171128471825,
  'test_corr_coef': 0.9403144204818553,
  'pruner': 'MedianPruner'},
 ('GPBoost', 'NopPruner'): {'best_score': 735.8901723459298,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.15,
   'max_depth': 5,
   'num_leaves': 31,
   'min_child_samples': 20,
   'subsample': 0.6,
   'colsample_bytree': 0.7,
   'reg_alpha': 1.0,
   'reg_lambda': 0.5,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 735.8901723459298,
  'test_rmse': 27.12729570646381,
  'test_corr_coef': 0.9390432462360848,
  'pruner': 'NopPruner'},
 ('GPBoost', 'PatientPruner'): {'best_score': 752.3331387371761,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 5,
   'num_leaves': 15,
   'min_child_samples': 20,
   'subsample': 0.5,
   'colsample_bytree': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 1.0,
   'min_child_weight': 0.1,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 752.3331387371761,
  'test_rmse': 27.428691888917637,
  'test_corr_coef': 0.9361301582131424,
  'pruner': 'PatientPruner'},
 ('GPBoost', 'PercentilePruner'): {'best_score': 716.339492253343,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 7,
   'num_leaves': 31,
   'min_child_samples': 20,
   'subsample': 0.6,
   'colsample_bytree': 0.5,
   'reg_alpha': 0.5,
   'reg_lambda': 1.0,
   'min_child_weight': 0.1,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 716.339492253343,
  'test_rmse': 26.764519279324688,
  'test_corr_coef': 0.9398871712481036,
  'pruner': 'PercentilePruner'},
 ('GPBoost', 'SuccessiveHalvingPruner'): {'best_score': 717.4428498127506,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.15,
   'max_depth': 5,
   'num_leaves': 63,
   'min_child_samples': 20,
   'subsample': 1.0,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 0.5,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 717.4428498127506,
  'test_rmse': 26.785123666183633,
  'test_corr_coef': 0.939670858109895,
  'pruner': 'SuccessiveHalvingPruner'},
 ('GPBoost', 'HyperbandPruner'): {'best_score': 781.1510555384973,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.1,
   'max_depth': 3,
   'num_leaves': 15,
   'min_child_samples': 1,
   'subsample': 0.7,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.5,
   'reg_lambda': 0,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 781.1510555384973,
  'test_rmse': 27.949079690367217,
  'test_corr_coef': 0.9493922288466194,
  'pruner': 'HyperbandPruner'},
 ('GPBoost', 'ThresholdPruner'): {'best_score': 756.4041284075729,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.05,
   'max_depth': 5,
   'num_leaves': 63,
   'min_child_samples': 20,
   'subsample': 0.8,
   'colsample_bytree': 0.9,
   'reg_alpha': 0,
   'reg_lambda': 0,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 756.4041284075729,
  'test_rmse': 27.502802191914427,
  'test_corr_coef': 0.9390291047514162,
  'pruner': 'ThresholdPruner'},
 ('GPBoost', 'WilcoxonPruner'): {'best_score': 714.1866718063685,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_depth': 5,
   'num_leaves': 31,
   'min_child_samples': 20,
   'subsample': 0.6,
   'colsample_bytree': 0.5,
   'reg_alpha': 0,
   'reg_lambda': 1.0,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 714.1866718063685,
  'test_rmse': 26.724271211884684,
  'test_corr_coef': 0.9390516133015835,
  'pruner': 'WilcoxonPruner'},
 ('CatBoost', 'MedianPruner'): {'best_score': 630.5890782836616,
  'best_params': {'iterations': 500,
   'learning_rate': 0.1,
   'depth': 6,
   'l2_leaf_reg': 1,
   'border_count': 64,
   'min_data_in_leaf': 5,
   'rsm': 1.0,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 630.5890782836616,
  'test_rmse': 25.111532774477578,
  'test_corr_coef': 0.9489559729651481,
  'pruner': 'MedianPruner'},
 ('CatBoost', 'NopPruner'): {'best_score': 630.5453803317046,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.1,
   'depth': 6,
   'l2_leaf_reg': 1,
   'border_count': 64,
   'min_data_in_leaf': 5,
   'rsm': 1.0,
   'bagging_temperature': 0,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 630.5453803317046,
  'test_rmse': 25.11066268205012,
  'test_corr_coef': 0.9489600108379744,
  'pruner': 'NopPruner'},
 ('CatBoost', 'PatientPruner'): {'best_score': 630.5453803317046,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.1,
   'depth': 6,
   'l2_leaf_reg': 1,
   'border_count': 64,
   'min_data_in_leaf': 20,
   'rsm': 1.0,
   'bagging_temperature': 0,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 630.5453803317046,
  'test_rmse': 25.11066268205012,
  'test_corr_coef': 0.9489600108379744,
  'pruner': 'PatientPruner'},
 ('CatBoost', 'PercentilePruner'): {'best_score': 630.5453803317046,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.1,
   'depth': 6,
   'l2_leaf_reg': 1,
   'border_count': 64,
   'min_data_in_leaf': 10,
   'rsm': 1.0,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 630.5453803317046,
  'test_rmse': 25.11066268205012,
  'test_corr_coef': 0.9489600108379744,
  'pruner': 'PercentilePruner'},
 ('CatBoost', 'SuccessiveHalvingPruner'): {'best_score': 630.5453803317046,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.1,
   'depth': 6,
   'l2_leaf_reg': 1,
   'border_count': 64,
   'min_data_in_leaf': 5,
   'rsm': 1.0,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 630.5453803317046,
  'test_rmse': 25.11066268205012,
  'test_corr_coef': 0.9489600108379744,
  'pruner': 'SuccessiveHalvingPruner'},
 ('CatBoost', 'HyperbandPruner'): {'best_score': 605.3897168900045,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.05,
   'depth': 6,
   'l2_leaf_reg': 1,
   'border_count': 64,
   'min_data_in_leaf': 1,
   'rsm': 0.6,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 605.3897168900045,
  'test_rmse': 24.60466859947527,
  'test_corr_coef': 0.9533736935494838,
  'pruner': 'HyperbandPruner'},
 ('CatBoost', 'ThresholdPruner'): {'best_score': 641.4704516535505,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.05,
   'depth': 4,
   'l2_leaf_reg': 3,
   'border_count': 128,
   'min_data_in_leaf': 1,
   'rsm': 1.0,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 641.4704516535505,
  'test_rmse': 25.32726695981133,
  'test_corr_coef': 0.9507825715295065,
  'pruner': 'ThresholdPruner'},
 ('CatBoost', 'WilcoxonPruner'): {'best_score': 660.4434801495852,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.05,
   'depth': 6,
   'l2_leaf_reg': 3,
   'border_count': 128,
   'min_data_in_leaf': 20,
   'rsm': 1.0,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 660.4434801495852,
  'test_rmse': 25.699094928607607,
  'test_corr_coef': 0.9502904767404701,
  'pruner': 'WilcoxonPruner'},
 ('NGBoost', 'MedianPruner'): {'best_score': 665.9319696968881,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.05,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 665.9319696968881,
  'test_rmse': 25.80565770711702,
  'test_corr_coef': 0.9534495011742371,
  'pruner': 'MedianPruner'},
 ('NGBoost', 'NopPruner'): {'best_score': 643.276870565578,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.05,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 643.276870565578,
  'test_rmse': 25.362903433273917,
  'test_corr_coef': 0.9568377830210449,
  'pruner': 'NopPruner'},
 ('NGBoost', 'PatientPruner'): {'best_score': 592.7841946366195,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.1,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 592.7841946366195,
  'test_rmse': 24.34715988850896,
  'test_corr_coef': 0.9599171799804269,
  'pruner': 'PatientPruner'},
 ('NGBoost', 'PercentilePruner'): {'best_score': 676.5734069200353,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.03,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 676.5734069200353,
  'test_rmse': 26.01102471876176,
  'test_corr_coef': 0.9557560601212998,
  'pruner': 'PercentilePruner'},
 ('NGBoost', 'SuccessiveHalvingPruner'): {'best_score': 650.5747004361921,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.03,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 650.5747004361921,
  'test_rmse': 25.506365880622667,
  'test_corr_coef': 0.9526469096873105,
  'pruner': 'SuccessiveHalvingPruner'},
 ('NGBoost', 'HyperbandPruner'): {'best_score': 598.0119322161584,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.05,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 598.0119322161584,
  'test_rmse': 24.454282492360278,
  'test_corr_coef': 0.9601905451078416,
  'pruner': 'HyperbandPruner'},
 ('NGBoost', 'ThresholdPruner'): {'best_score': 673.5043263899729,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.03,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.5,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 673.5043263899729,
  'test_rmse': 25.951961898669104,
  'test_corr_coef': 0.9524026393725683,
  'pruner': 'ThresholdPruner'},
 ('NGBoost', 'WilcoxonPruner'): {'best_score': 657.7330265288662,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 657.7330265288662,
  'test_rmse': 25.64630629406243,
  'test_corr_coef': 0.9549702826625915,
  'pruner': 'WilcoxonPruner'},
 ('TabNet', 'MedianPruner'): {'best_score': 1291.916259765625,
  'best_params': {'n_d': 32,
   'n_a': 8,
   'n_steps': 3,
   'gamma': 2.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 1291.916259765625,
  'test_rmse': 35.943236634527295,
  'test_corr_coef': 0.8969197643763044,
  'pruner': 'MedianPruner'},
 ('TabNet', 'NopPruner'): {'best_score': 631.5394287109375,
  'best_params': {'n_d': 64,
   'n_a': 16,
   'n_steps': 3,
   'gamma': 1.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 631.5394287109375,
  'test_rmse': 25.13044823935573,
  'test_corr_coef': 0.9518179090396214,
  'pruner': 'NopPruner'},
 ('TabNet', 'PatientPruner'): {'best_score': 1154.278076171875,
  'best_params': {'n_d': 32,
   'n_a': 8,
   'n_steps': 3,
   'gamma': 2.0,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 3,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 1154.278076171875,
  'test_rmse': 33.97466815396252,
  'test_corr_coef': 0.913076416067907,
  'pruner': 'PatientPruner'},
 ('TabNet', 'PercentilePruner'): {'best_score': 937.249267578125,
  'best_params': {'n_d': 64,
   'n_a': 32,
   'n_steps': 3,
   'gamma': 1.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 2,
   'n_independent': 3,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 937.249267578125,
  'test_rmse': 30.614527067686755,
  'test_corr_coef': 0.9203513351964621,
  'pruner': 'PercentilePruner'},
 ('TabNet', 'SuccessiveHalvingPruner'): {'best_score': 712.4828491210938,
  'best_params': {'n_d': 64,
   'n_a': 8,
   'n_steps': 3,
   'gamma': 1.5,
   'lambda_sparse': 0.01,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 2,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 712.4828491210938,
  'test_rmse': 26.692374362748133,
  'test_corr_coef': 0.9347721417914999,
  'pruner': 'SuccessiveHalvingPruner'},
 ('TabNet', 'HyperbandPruner'): {'best_score': 618.77392578125,
  'best_params': {'n_d': 64,
   'n_a': 8,
   'n_steps': 5,
   'gamma': 1.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 618.77392578125,
  'test_rmse': 24.8751668493148,
  'test_corr_coef': 0.9512967370478271,
  'pruner': 'HyperbandPruner'},
 ('TabNet', 'ThresholdPruner'): {'best_score': 631.5394287109375,
  'best_params': {'n_d': 64,
   'n_a': 16,
   'n_steps': 3,
   'gamma': 1.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 1,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 631.5394287109375,
  'test_rmse': 25.13044823935573,
  'test_corr_coef': 0.9518179090396214,
  'pruner': 'ThresholdPruner'},
 ('TabNet', 'WilcoxonPruner'): {'best_score': 805.7788696289062,
  'best_params': {'n_d': 64,
   'n_a': 16,
   'n_steps': 3,
   'gamma': 1.5,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 2,
   'n_independent': 1,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 805.7788696289062,
  'test_rmse': 28.38624437344444,
  'test_corr_coef': 0.9378987661527479,
  'pruner': 'WilcoxonPruner'},
 ('HistGradientBoosting', 'MedianPruner'): {'best_score': 887.852870315111,
  'best_params': {'learning_rate': 0.1,
   'max_iter': 500,
   'max_depth': None,
   'min_samples_leaf': 20,
   'max_leaf_nodes': 31,
   'l2_regularization': 0.1,
   'max_bins': 255,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 887.852870315111,
  'test_rmse': 29.796860074764773,
  'test_corr_coef': 0.9275994694463101,
  'pruner': 'MedianPruner'},
 ('HistGradientBoosting', 'NopPruner'): {'best_score': 895.9881855499773,
  'best_params': {'learning_rate': 0.15,
   'max_iter': 100,
   'max_depth': 7,
   'min_samples_leaf': 20,
   'max_leaf_nodes': 63,
   'l2_regularization': 0.0,
   'max_bins': 128,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 895.9881855499773,
  'test_rmse': 29.933061747004388,
  'test_corr_coef': 0.9247941374428854,
  'pruner': 'NopPruner'},
 ('HistGradientBoosting', 'PatientPruner'): {'best_score': 895.9881855499773,
  'best_params': {'learning_rate': 0.15,
   'max_iter': 100,
   'max_depth': 7,
   'min_samples_leaf': 20,
   'max_leaf_nodes': 15,
   'l2_regularization': 0.0,
   'max_bins': 128,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 895.9881855499773,
  'test_rmse': 29.933061747004388,
  'test_corr_coef': 0.9247941374428854,
  'pruner': 'PatientPruner'},
 ('HistGradientBoosting',
  'PercentilePruner'): {'best_score': 903.8766200943321, 'best_params': {'learning_rate': 0.1,
   'max_iter': 400,
   'max_depth': 7,
   'min_samples_leaf': 20,
   'max_leaf_nodes': None,
   'l2_regularization': 0.0,
   'max_bins': 255,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 15,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 903.8766200943321, 'test_rmse': 30.064540909422384, 'test_corr_coef': 0.9268427349727221, 'pruner': 'PercentilePruner'},
 ('HistGradientBoosting',
  'SuccessiveHalvingPruner'): {'best_score': 971.9581251948764, 'best_params': {'learning_rate': 0.1,
   'max_iter': 500,
   'max_depth': 7,
   'min_samples_leaf': 5,
   'max_leaf_nodes': 31,
   'l2_regularization': 0.0,
   'max_bins': 255,
   'early_stopping': True,
   'validation_fraction': 0.2,
   'n_iter_no_change': 15,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 971.9581251948764, 'test_rmse': 31.176242961506386, 'test_corr_coef': 0.9371355246827604, 'pruner': 'SuccessiveHalvingPruner'},
 ('HistGradientBoosting', 'HyperbandPruner'): {'best_score': 908.2273957235172,
  'best_params': {'learning_rate': 0.1,
   'max_iter': 200,
   'max_depth': None,
   'min_samples_leaf': 20,
   'max_leaf_nodes': None,
   'l2_regularization': 0.0,
   'max_bins': 255,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 908.2273957235172,
  'test_rmse': 30.136811306498856,
  'test_corr_coef': 0.9267495832581238,
  'pruner': 'HyperbandPruner'},
 ('HistGradientBoosting', 'ThresholdPruner'): {'best_score': 913.2351566923057,
  'best_params': {'learning_rate': 0.05,
   'max_iter': 500,
   'max_depth': None,
   'min_samples_leaf': 20,
   'max_leaf_nodes': None,
   'l2_regularization': 0.5,
   'max_bins': 255,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 15,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 913.2351566923057,
  'test_rmse': 30.219780884253705,
  'test_corr_coef': 0.9241795341186559,
  'pruner': 'ThresholdPruner'},
 ('HistGradientBoosting', 'WilcoxonPruner'): {'best_score': 900.3576635232477,
  'best_params': {'learning_rate': 0.15,
   'max_iter': 100,
   'max_depth': None,
   'min_samples_leaf': 20,
   'max_leaf_nodes': 31,
   'l2_regularization': 0.0,
   'max_bins': 255,
   'early_stopping': False,
   'validation_fraction': 0.2,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 900.3576635232477,
  'test_rmse': 30.005960466601426,
  'test_corr_coef': 0.9236942198337691,
  'pruner': 'WilcoxonPruner'},
 ('PGBM', 'MedianPruner'): {'best_score': 658.0406314199307,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.1,
   'max_leaves': 34,
   'min_split_gain': 0.5,
   'reg_lambda': 1.0,
   'feature_fraction': 0.5,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 3,
   'max_bin': 64,
   'distribution': 'normal'},
  'test_mse': 658.0406314199307,
  'test_rmse': 25.652302653366828,
  'test_corr_coef': 0.9467269292188372,
  'pruner': 'MedianPruner'},
 ('PGBM', 'NopPruner'): {'best_score': 625.065209550903,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_leaves': 25,
   'min_split_gain': 0.1,
   'reg_lambda': 5.0,
   'feature_fraction': 0.7,
   'bagging_fraction': 0.5,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 3,
   'max_bin': 64,
   'distribution': 'laplace'},
  'test_mse': 625.065209550903,
  'test_rmse': 25.00130415700155,
  'test_corr_coef': 0.9512883993327096,
  'pruner': 'NopPruner'},
 ('PGBM', 'PatientPruner'): {'best_score': 616.1661948759922,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.15,
   'max_leaves': 22,
   'min_split_gain': 1.0,
   'reg_lambda': 0.1,
   'feature_fraction': 0.7,
   'bagging_fraction': 0.5,
   'tree_correlation': 0.2,
   'min_data_in_leaf': 3,
   'max_bin': 128,
   'distribution': 'laplace'},
  'test_mse': 616.1661948759922,
  'test_rmse': 24.82269515737548,
  'test_corr_coef': 0.9550929646023637,
  'pruner': 'PatientPruner'},
 ('PGBM', 'PercentilePruner'): {'best_score': 723.1873057916002,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_leaves': 51,
   'min_split_gain': 0.0,
   'reg_lambda': 10.0,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.5,
   'tree_correlation': 0.1,
   'min_data_in_leaf': 10,
   'max_bin': 64,
   'distribution': 'studentt'},
  'test_mse': 723.1873057916002,
  'test_rmse': 26.892142082615884,
  'test_corr_coef': 0.9397508710145436,
  'pruner': 'PercentilePruner'},
 ('PGBM', 'SuccessiveHalvingPruner'): {'best_score': 683.1532241547042,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_leaves': 22,
   'min_split_gain': 1.0,
   'reg_lambda': 5.0,
   'feature_fraction': 0.5,
   'bagging_fraction': 0.9,
   'tree_correlation': 0.0,
   'min_data_in_leaf': 3,
   'max_bin': 64,
   'distribution': 'laplace'},
  'test_mse': 683.1532241547042,
  'test_rmse': 26.137200006020233,
  'test_corr_coef': 0.949825413179436,
  'pruner': 'SuccessiveHalvingPruner'},
 ('PGBM', 'HyperbandPruner'): {'best_score': 731.1511210436257,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_leaves': 49,
   'min_split_gain': 1.0,
   'reg_lambda': 1.0,
   'feature_fraction': 0.5,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.0,
   'min_data_in_leaf': 10,
   'max_bin': 128,
   'distribution': 'laplace'},
  'test_mse': 731.1511210436257,
  'test_rmse': 27.03980623162129,
  'test_corr_coef': 0.9367593670160128,
  'pruner': 'HyperbandPruner'},
 ('PGBM', 'ThresholdPruner'): {'best_score': 648.0499398123818,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.15,
   'max_leaves': 40,
   'min_split_gain': 0.0,
   'reg_lambda': 5.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.5,
   'tree_correlation': 0.2,
   'min_data_in_leaf': 3,
   'max_bin': 64,
   'distribution': 'studentt'},
  'test_mse': 648.0499398123818,
  'test_rmse': 25.45682501437251,
  'test_corr_coef': 0.9493501374001289,
  'pruner': 'ThresholdPruner'},
 ('PGBM', 'WilcoxonPruner'): {'best_score': 803.2895911453227,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.1,
   'max_leaves': 33,
   'min_split_gain': 0.5,
   'reg_lambda': 0.1,
   'feature_fraction': 0.7,
   'bagging_fraction': 1.0,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 20,
   'max_bin': 64,
   'distribution': 'laplace'},
  'test_mse': 803.2895911453227,
  'test_rmse': 28.34236389480106,
  'test_corr_coef': 0.9314364334776043,
  'pruner': 'WilcoxonPruner'}}

# **Conformal Predictions with Lightgbm**

In [18]:
best_params = get_best_model_params(best_scores_autosampler, 'LightGBM')

In [19]:
conformal_predictions_NEXCP(
    model_class=LGBMRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="LightGBM",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/LightGBM.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 3.659% | Width: 1.251
NexCP Full - Coverage: 2.439% | Width: 1.069
NexCP Jackknife+ aB - Coverage: 69.512% | Width: 53.606
NexCP CV+ - Coverage: 91.463% | Width: 106.624

              Strategy  Coverage       Width       RMSE           CWC
0          NexCP Split  0.036585    1.250603  23.712851  8.544100e+19
1           NexCP Full  0.024390    1.069338  23.712851  1.344236e+20
2  NexCP Jackknife+ aB  0.695122   53.606184  28.900723  1.835789e+07
3            NexCP CV+  0.914634  106.623610  27.370701  7.315274e+02

In [20]:
conformal_predictions_online_super(
    model_class=LGBMRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="LightGBM",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/LightGBM.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.024390   1.069338  23.712851   2.112595
1            Online CV+  0.597561  35.833082  23.712851  50.253713
2  Online Jackknife+ aB  0.621951  48.470122  28.747582  66.794193
3                 SAOCP  0.707317  53.229946  23.712851  68.809442
4                SF-OGD  0.000000   0.169168  23.712851   0.338336
5                  FACI  0.878049  80.130197  23.712851  89.902173
6            MFCS Split  0.024390   1.069338  23.712851   2.112595
7             MFCS Full  0.012195   0.711184  25.052162   1.413694

               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.024390   1.069338  23.712851   2.112595
1            Online CV+  0.597561  35.833082  23.712851  50.253713
2  Online Jackknife+ aB  0.621951  48.470122  28.747582  66.794193
3                 SAOCP  0.707317  53.229946  23.712851  68.809442
4                SF-OGD  0.000000   0.169168  23.712851   0.338336
5                  FACI  0.878049  80.130197  23.712851  89.902173
6            MFCS Split  0.024390   1.069338  23.712851   2.112595
7             MFCS Full  0.012195   0.711184  25.052162   1.413694

In [21]:
conformal_predictions_COP(
    model_class=LGBMRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="LightGBM",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/LightGBM.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (LightGBM) =====
Coverage : 13.415%
Avg Width: 4.539
RMSE     : 23.713
Final q  : 3.899

  Strategy  Coverage     Width       RMSE  Alpha    LR  Scale
0      COP  0.134146  4.538759  23.712851   0.05  0.05    0.5

In [22]:
conformal_predictions_EXTREME(
    model_class=LGBMRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="LightGBM",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/LightGBM.xlsx",
    alpha=0.05,
    calib_size=0.5,
)

===== EXTREME CONFORMAL PREDICTION (LightGBM) =====
Coverage : 98.780%
Width    : 101.005
RMSE     : 33.136
q_extreme: 101.005
u        : 65.357
#Exceed. : 42

In [23]:
conformal_predictions_AlphaNet(
    model_class=LGBMRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="LightGBM",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/LightGBM.xlsx",
    alpha=0.05,
)

  [Info] n_calib=95 | alpha_min=0.0204
  [Step 2/9] Training base LightGBM model...
  [Step 2/9] Done in 0s
  [Step 3/9] Precomputing 95 LOO score vectors...

    LOO precompute:   0%|          | 0/95 [00:00<?, ?it/s]

  [Step 3/9] Done in 0s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 1507.5096 | Size: 1495.5297 | α̃: 0.5990 | ⏱ 0.17s/epoch | ETA: 44s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 63.7974 | Size: 43.7974 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 7s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 63.7986 | Size: 43.7986 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 5s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 63.7964 | Size: 43.7964 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 4s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 63.7976 | Size: 43.7976 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 4s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 63.7960 | Size: 43.7960 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 3s
  ✓ Run 1 complete | Final loss: 63.7960

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 63.7966 | Size: 43.7966 | α̃: 1.0000 | ⏱ 0.04s/epoch | ETA: 3s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 63.7980 | Size: 43.7980 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 3s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 63.7979 | Size: 43.7979 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 3s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 63.7970 | Size: 43.7970 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 3s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 63.7969 | Size: 43.7969 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 2s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 63.7957 | Size: 43.7957 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 2s
  ✓ Run 2 complete | Final loss: 63.7957

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 63.7978 | Size: 43.7978 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 2s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 63.7981 | Size: 43.7981 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 2s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 63.7978 | Size: 43.7978 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 2s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 63.7995 | Size: 43.7995 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 1s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 63.7974 | Size: 43.7974 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 1s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 63.7963 | Size: 43.7963 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 1s
  ✓ Run 3 complete | Final loss: 63.7963

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 63.7990 | Size: 43.7990 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 63.7973 | Size: 43.7973 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 63.7984 | Size: 43.7984 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 63.7953 | Size: 43.7953 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 63.7984 | Size: 43.7984 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 63.7978 | Size: 43.7978 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 63.7978
  [Step 4/9] Training done in 4s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (LightGBM)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 21.8988
  Coverage       : 65.854%
  Avg Width      : 43.7977
  RMSE           : 27.1361
  Total time     : 5s
    ├─ Precompute: 0s
    └─ Training  : 4s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 5s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.658537,43.797669,27.136139,0.05,1.0,20.0,4.83

# **Conformal Predictions with XGBoost**

In [24]:
best_params = get_best_model_params(best_scores_autosampler, 'XGBoost')

In [25]:
conformal_predictions_NEXCP(
    model_class=XGBRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="XGBoost",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/XGBoost.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 2.439% | Width: 1.316
NexCP Full - Coverage: 2.439% | Width: 1.455
NexCP Jackknife+ aB - Coverage: 64.634% | Width: 55.642
NexCP CV+ - Coverage: 95.122% | Width: 108.688

              Strategy  Coverage       Width       RMSE           CWC
0          NexCP Split  0.024390    1.316162  23.559628  1.654512e+20
1           NexCP Full  0.024390    1.455166  23.559628  1.829250e+20
2  NexCP Jackknife+ aB  0.646341   55.642025  28.254919  2.184059e+08
3            NexCP CV+  0.951220  108.688141  27.226486  1.086881e+02

In [26]:
conformal_predictions_online_super(
    model_class=XGBRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="XGBoost",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/XGBoost.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.024390   1.455167  23.559628   2.874841
1            Online CV+  0.597561  37.241177  23.559628  52.228480
2  Online Jackknife+ aB  0.658537  49.617046  27.686548  66.559452
3                 SAOCP  0.792683  53.752234  23.559628  64.895990
4                SF-OGD  0.000000   0.399212  23.559628   0.798423
5                  FACI  0.890244  86.347704  23.559628  95.824891
6            MFCS Split  0.024390   1.455167  23.559628   2.874841
7             MFCS Full  0.036585   1.222574  25.101087   2.400420

               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.024390   1.455167  23.559628   2.874841
1            Online CV+  0.597561  37.241177  23.559628  52.228480
2  Online Jackknife+ aB  0.658537  49.617046  27.686548  66.559452
3                 SAOCP  0.792683  53.752234  23.559628  64.895990
4                SF-OGD  0.000000   0.399212  23.559628   0.798423
5                  FACI  0.890244  86.347704  23.559628  95.824891
6            MFCS Split  0.024390   1.455167  23.559628   2.874841
7             MFCS Full  0.036585   1.222574  25.101087   2.400420

In [27]:
conformal_predictions_COP(
    model_class=XGBRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="XGBoost",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/XGBoost.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (XGBoost) =====
Coverage : 17.073%
Avg Width: 4.786
RMSE     : 23.560
Final q  : 3.892

  Strategy  Coverage     Width       RMSE  Alpha    LR  Scale
0      COP  0.170732  4.785782  23.559628   0.05  0.05    0.5

In [28]:
conformal_predictions_EXTREME(
    model_class=XGBRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="XGBoost",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/XGBoost.xlsx",
    alpha=0.05,
    calib_size=0.5,
)

===== EXTREME CONFORMAL PREDICTION (XGBoost) =====
Coverage : 98.780%
Width    : 80.923
RMSE     : 31.098
q_extreme: 80.923
u        : 65.387
#Exceed. : 47

In [29]:
conformal_predictions_AlphaNet(
    model_class=XGBRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="XGBoost",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/XGBoost.xlsx",
    alpha=0.05,
)

  [Info] n_calib=95 | alpha_min=0.0204
  [Step 2/9] Training base XGBoost model...
  [Step 2/9] Done in 1s
  [Step 3/9] Precomputing 95 LOO score vectors...

    LOO precompute:   0%|          | 0/95 [00:00<?, ?it/s]

  [Step 3/9] Done in 0s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 1444.5347 | Size: 1432.3900 | α̃: 0.6072 | ⏱ 0.03s/epoch | ETA: 10s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 62.0695 | Size: 42.0695 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 4s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 62.0708 | Size: 42.0708 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 4s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 62.0687 | Size: 42.0687 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 3s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 62.0699 | Size: 42.0699 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 3s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 62.0689 | Size: 42.0689 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 3s
  ✓ Run 1 complete | Final loss: 62.0689

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 62.0691 | Size: 42.0691 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 3s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 62.0707 | Size: 42.0707 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 3s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 62.0704 | Size: 42.0704 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 3s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 62.0691 | Size: 42.0691 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 2s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 62.0684 | Size: 42.0684 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 2s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 62.0681 | Size: 42.0681 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 2s
  ✓ Run 2 complete | Final loss: 62.0681

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 62.0690 | Size: 42.0690 | α̃: 1.0000 | ⏱ 0.04s/epoch | ETA: 2s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 62.0696 | Size: 42.0696 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 2s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 62.0696 | Size: 42.0696 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 2s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 62.0710 | Size: 42.0710 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 1s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 62.0690 | Size: 42.0690 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 1s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 62.0688 | Size: 42.0688 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 1s
  ✓ Run 3 complete | Final loss: 62.0688

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 62.0711 | Size: 42.0711 | α̃: 1.0000 | ⏱ 0.04s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 62.0698 | Size: 42.0698 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 62.0707 | Size: 42.0707 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 62.0673 | Size: 42.0673 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 62.0710 | Size: 42.0710 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 62.0696 | Size: 42.0696 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 62.0696
  [Step 4/9] Training done in 4s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (XGBoost)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 21.0349
  Coverage       : 54.878%
  Avg Width      : 42.0698
  RMSE           : 30.5201
  Total time     : 5s
    ├─ Precompute: 0s
    └─ Training  : 4s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 5s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.54878,42.069763,30.520113,0.05,1.0,20.0,4.6

# **Conformal Predictions with GPBoost**

In [30]:
best_params = get_best_model_params(best_scores_autosampler, 'GPBoost')

In [31]:
conformal_predictions_NEXCP(
    model_class=GPBoostRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GPBoost",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/GPBoost.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 8.537% | Width: 5.550
NexCP Full - Coverage: 2.439% | Width: 1.320
NexCP Jackknife+ aB - Coverage: 80.488% | Width: 71.220
NexCP CV+ - Coverage: 96.341% | Width: 118.018

              Strategy  Coverage       Width       RMSE           CWC
0          NexCP Split  0.085366    5.549612  26.612171  3.307917e+19
1           NexCP Full  0.024390    1.320074  26.612171  1.659429e+20
2  NexCP Jackknife+ aB  0.804878   71.220448  29.834263  1.009704e+05
3            NexCP CV+  0.963415  118.017607  31.512373  1.180176e+02

In [32]:
conformal_predictions_online_super(
    model_class=GPBoostRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GPBoost",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/GPBoost.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.024390   1.320074  26.612171   2.607951
1            Online CV+  0.621951  41.232572  26.612171  56.820495
2  Online Jackknife+ aB  0.792683  63.206350  29.677494  76.310106
3                 SAOCP  0.804878  56.994214  26.612171  68.115036
4                SF-OGD  0.012195   0.436168  26.612171   0.867017
5                  FACI  0.890244  86.102552  26.612171  95.552832
6            MFCS Split  0.024390   1.320074  26.612171   2.607951
7             MFCS Full  0.097561   2.950188  28.004024   5.612552

               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.024390   1.320074  26.612171   2.607951
1            Online CV+  0.621951  41.232572  26.612171  56.820495
2  Online Jackknife+ aB  0.792683  63.206350  29.677494  76.310106
3                 SAOCP  0.804878  56.994214  26.612171  68.115036
4                SF-OGD  0.012195   0.436168  26.612171   0.867017
5                  FACI  0.890244  86.102552  26.612171  95.552832
6            MFCS Split  0.024390   1.320074  26.612171   2.607951
7             MFCS Full  0.097561   2.950188  28.004024   5.612552

In [33]:
conformal_predictions_COP(
    model_class=GPBoostRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GPBoost",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/GPBoost.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (GPBoost) =====
Coverage : 8.537%
Avg Width: 4.947
RMSE     : 26.612
Final q  : 4.178

  Strategy  Coverage     Width       RMSE  Alpha    LR  Scale
0      COP  0.085366  4.946836  26.612171   0.05  0.05    0.5

In [34]:
conformal_predictions_EXTREME(
    model_class=GPBoostRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GPBoost",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/GPBoost.xlsx",
    alpha=0.05,
    calib_size=0.5,
)

===== EXTREME CONFORMAL PREDICTION (GPBoost) =====
Coverage : 98.780%
Width    : 150.567
RMSE     : 48.407
q_extreme: 150.567
u        : 81.118
#Exceed. : 42

In [35]:
conformal_predictions_AlphaNet(
    model_class=GPBoostRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GPBoost",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/GPBoost.xlsx",
    alpha=0.05,
)

  [Info] n_calib=95 | alpha_min=0.0204
  [Step 2/9] Training base GPBoost model...
  [Step 2/9] Done in 0s
  [Step 3/9] Precomputing 95 LOO score vectors...

    LOO precompute:   0%|          | 0/95 [00:00<?, ?it/s]

  [Step 3/9] Done in 0s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 1922.4689 | Size: 1911.9709 | α̃: 0.5249 | ⏱ 0.03s/epoch | ETA: 10s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 75.8100 | Size: 55.8100 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 4s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 75.8123 | Size: 55.8123 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 4s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 75.8096 | Size: 55.8096 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 3s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 75.8113 | Size: 55.8113 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 3s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 75.8085 | Size: 55.8085 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 3s
  ✓ Run 1 complete | Final loss: 75.8085

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 75.8094 | Size: 55.8094 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 3s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 75.8115 | Size: 55.8115 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 3s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 75.8112 | Size: 55.8112 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 3s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 75.8102 | Size: 55.8102 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 2s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 75.8099 | Size: 55.8099 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 2s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 75.8080 | Size: 55.8080 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 2s
  ✓ Run 2 complete | Final loss: 75.8080

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 75.8114 | Size: 55.8114 | α̃: 1.0000 | ⏱ 0.04s/epoch | ETA: 2s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 75.8107 | Size: 55.8107 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 2s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 75.8120 | Size: 55.8120 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 2s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 75.8133 | Size: 55.8133 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 1s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 75.8096 | Size: 55.8096 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 1s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 75.8091 | Size: 55.8091 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 1s
  ✓ Run 3 complete | Final loss: 75.8091

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 75.8126 | Size: 55.8126 | α̃: 1.0000 | ⏱ 0.04s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 75.8107 | Size: 55.8107 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 75.8128 | Size: 55.8128 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 75.8080 | Size: 55.8080 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 75.8125 | Size: 55.8125 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 75.8107 | Size: 55.8107 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 75.8107
  [Step 4/9] Training done in 5s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (GPBoost)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 27.9055
  Coverage       : 64.634%
  Avg Width      : 55.8110
  RMSE           : 40.0328
  Total time     : 5s
    ├─ Precompute: 0s
    └─ Training  : 5s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 5s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.646341,55.81103,40.032802,0.05,1.0,20.0,5.09

# **Conformal Predictions with NGBoost**

In [36]:
best_params = get_best_model_params(best_scores_autosampler, 'NGBoost')

In [37]:
conformal_predictions_NEXCP(
    model_class=NGBRegressor,
    best_params={**best_params, "Dist": Normal},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="NGBoost",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/NGBoost.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 0.000% | Width: 0.002
NexCP Full - Coverage: 0.000% | Width: 0.001
NexCP Jackknife+ aB - Coverage: 65.854% | Width: 62.486
NexCP CV+ - Coverage: 95.122% | Width: 126.547

              Strategy  Coverage       Width       RMSE           CWC
0          NexCP Split  0.000000    0.001850  28.924087  7.874689e+17
1           NexCP Full  0.000000    0.001310  29.981841  5.576257e+17
2  NexCP Jackknife+ aB  0.658537   62.485673  28.647956  1.332994e+08
3            NexCP CV+  0.951220  126.547414  28.341197  1.265474e+02

In [38]:
conformal_predictions_online_super(
    model_class=NGBRegressor,
    model_params={**best_params, "Dist": Normal},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="NGBoost",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/NGBoost.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage       Width       RMSE         CWC
0          Online Split  0.000000    0.001822  28.924087    0.003644
1            Online CV+  0.560976   44.363571  28.924087   63.840261
2  Online Jackknife+ aB  0.646341   57.514725  28.436292   77.855299
3                 SAOCP  0.756098   70.334365  28.924087   87.489089
4                SF-OGD  0.000000    0.000000  28.924087    0.000000
5                  FACI  0.914634  105.401917  28.924087  114.399642
6            MFCS Split  0.000000    0.001822  28.924087    0.003644
7             MFCS Full  0.000000    0.007709  24.179123    0.015419

               Strategy  Coverage       Width       RMSE         CWC
0          Online Split  0.000000    0.001822  28.924087    0.003644
1            Online CV+  0.560976   44.363571  28.924087   63.840261
2  Online Jackknife+ aB  0.646341   57.514725  28.436292   77.855299
3                 SAOCP  0.756098   70.334365  28.924087   87.489089
4                SF-OGD  0.000000    0.000000  28.924087    0.000000
5                  FACI  0.914634  105.401917  28.924087  114.399642
6            MFCS Split  0.000000    0.001822  28.924087    0.003644
7             MFCS Full  0.000000    0.007709  24.179123    0.015419

In [39]:
conformal_predictions_COP(
    model_class=NGBRegressor,
    model_params={**best_params, "Dist": Normal},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="NGBoost",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/NGBoost.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (NGBoost) =====
Coverage : 6.098%
Avg Width: 3.717
RMSE     : 28.924
Final q  : 3.670

  Strategy  Coverage     Width       RMSE  Alpha    LR  Scale
0      COP  0.060976  3.717279  28.924087   0.05  0.05    0.5

In [40]:
conformal_predictions_EXTREME(
    model_class=NGBRegressor,
    model_params={**best_params, "Dist": Normal},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="NGBoost",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/NGBoost.xlsx",
    alpha=0.05,
    calib_size=0.5,
)

===== EXTREME CONFORMAL PREDICTION (NGBoost) =====
Coverage : 100.000%
Width    : 104.639
RMSE     : 34.371
q_extreme: 104.639
u        : 80.729
#Exceed. : 35

In [41]:
conformal_predictions_AlphaNet(
    model_class=NGBRegressor,
    model_params={**best_params, "Dist": Normal},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="NGBoost",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/NGBoost.xlsx",
    alpha=0.05,
)

  [Info] n_calib=95 | alpha_min=0.0204
  [Step 2/9] Training base NGBoost model...
  [Step 2/9] Done in 13s
  [Step 3/9] Precomputing 95 LOO score vectors...

    LOO precompute:   0%|          | 0/95 [00:00<?, ?it/s]

  [Step 3/9] Done in 48s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 1659.1259 | Size: 1647.6362 | α̃: 0.5745 | ⏱ 0.04s/epoch | ETA: 12s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 68.2328 | Size: 48.2328 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 5s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 68.2341 | Size: 48.2341 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 4s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 68.2322 | Size: 48.2322 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 4s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 68.2326 | Size: 48.2326 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 3s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 68.2321 | Size: 48.2321 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 3s
  ✓ Run 1 complete | Final loss: 68.2321

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 68.2314 | Size: 48.2314 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 3s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 68.2338 | Size: 48.2338 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 3s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 68.2334 | Size: 48.2334 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 3s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 68.2322 | Size: 48.2322 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 2s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 68.2324 | Size: 48.2324 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 2s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 68.2313 | Size: 48.2313 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 2s
  ✓ Run 2 complete | Final loss: 68.2313

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 68.2329 | Size: 48.2329 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 2s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 68.2325 | Size: 48.2325 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 2s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 68.2332 | Size: 48.2332 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 2s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 68.2356 | Size: 48.2356 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 1s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 68.2330 | Size: 48.2330 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 1s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 68.2315 | Size: 48.2315 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 1s
  ✓ Run 3 complete | Final loss: 68.2315

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 68.2354 | Size: 48.2354 | α̃: 1.0000 | ⏱ 0.05s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 68.2329 | Size: 48.2329 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 68.2332 | Size: 48.2332 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 68.2302 | Size: 48.2302 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 68.2345 | Size: 48.2345 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 68.2331 | Size: 48.2331 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 68.2331
  [Step 4/9] Training done in 4s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (NGBoost)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 24.1166
  Coverage       : 57.317%
  Avg Width      : 48.2331
  RMSE           : 29.7422
  Total time     : 1.1min
    ├─ Precompute: 48s
    └─ Training  : 4s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 1.1min

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.573171,48.233129,29.742173,0.05,1.0,20.0,66.46

# **Conformal Predictions with Gradient Boosting**

In [42]:
best_params = get_best_model_params(best_scores_autosampler, 'GradientBoosting')

In [43]:
conformal_predictions_NEXCP(
    model_class=GradientBoostingRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GradientBoosting",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/Gradient Boosting.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 30.488% | Width: 18.936
NexCP Full - Coverage: 31.707% | Width: 20.434
NexCP Jackknife+ aB - Coverage: 80.488% | Width: 77.139
NexCP CV+ - Coverage: 96.341% | Width: 148.325

              Strategy  Coverage       Width       RMSE           CWC
0          NexCP Split  0.304878   18.935532  25.584112  1.931624e+15
1           NexCP Full  0.317073   20.433523  25.584112  1.132856e+15
2  NexCP Jackknife+ aB  0.804878   77.138624  29.244600  1.093607e+05
3            NexCP CV+  0.963415  148.324992  29.977982  1.483250e+02

In [44]:
conformal_predictions_online_super(
    model_class=GradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GradientBoosting",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/Gradient Boosting.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.317073  20.433523  25.584112  34.388124
1            Online CV+  0.756098  57.000383  25.584112  70.902915
2  Online Jackknife+ aB  0.756098  73.875823  28.804406  91.894316
3                 SAOCP  0.829268  72.931358  25.584112  85.383053
4                SF-OGD  0.378049  26.173152  25.584112  42.451576
5                  FACI  0.865854  83.387414  25.584112  94.573530
6            MFCS Split  0.317073  20.433523  25.584112  34.388124
7             MFCS Full  0.463415  23.323814  26.537435  35.839031

               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.317073  20.433523  25.584112  34.388124
1            Online CV+  0.756098  57.000383  25.584112  70.902915
2  Online Jackknife+ aB  0.756098  73.875823  28.804406  91.894316
3                 SAOCP  0.829268  72.931358  25.584112  85.383053
4                SF-OGD  0.378049  26.173152  25.584112  42.451576
5                  FACI  0.865854  83.387414  25.584112  94.573530
6            MFCS Split  0.317073  20.433523  25.584112  34.388124
7             MFCS Full  0.463415  23.323814  26.537435  35.839031

In [45]:
conformal_predictions_COP(
    model_class=GradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GradientBoosting",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/Gradient Boosting.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (GradientBoosting) =====
Coverage : 35.366%
Avg Width: 22.843
RMSE     : 25.584
Final q  : 12.628

  Strategy  Coverage      Width       RMSE  Alpha    LR  Scale
0      COP  0.353659  22.842712  25.584112   0.05  0.05    0.5

In [46]:
conformal_predictions_EXTREME(
    model_class=GradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GradientBoosting",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/Gradient Boosting.xlsx",
    alpha=0.05,
    calib_size=0.5,
)

===== EXTREME CONFORMAL PREDICTION (GradientBoosting) =====
Coverage : 100.000%
Width    : 131.025
RMSE     : 39.547
q_extreme: 131.025
u        : 86.352
#Exceed. : 39

In [47]:
conformal_predictions_AlphaNet(
    model_class=GradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GradientBoosting",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/Gradient Boosting.xlsx",
    alpha=0.05,
)

  [Info] n_calib=95 | alpha_min=0.0204
  [Step 2/9] Training base GradientBoosting model...
  [Step 2/9] Done in 0s
  [Step 3/9] Precomputing 95 LOO score vectors...

    LOO precompute:   0%|          | 0/95 [00:00<?, ?it/s]

  [Step 3/9] Done in 0s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 1639.2658 | Size: 1627.6940 | α̃: 0.5786 | ⏱ 0.03s/epoch | ETA: 10s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 67.5956 | Size: 47.5956 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 4s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 67.5965 | Size: 47.5965 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 4s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 67.5950 | Size: 47.5950 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 4s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 67.5960 | Size: 47.5960 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 3s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 67.5951 | Size: 47.5951 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 3s
  ✓ Run 1 complete | Final loss: 67.5951

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 67.5951 | Size: 47.5951 | α̃: 1.0000 | ⏱ 0.06s/epoch | ETA: 3s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 67.5962 | Size: 47.5962 | α̃: 1.0000 | ⏱ 0.04s/epoch | ETA: 3s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 67.5962 | Size: 47.5962 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 3s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 67.5962 | Size: 47.5962 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 3s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 67.5947 | Size: 47.5947 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 3s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 67.5936 | Size: 47.5936 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 3s
  ✓ Run 2 complete | Final loss: 67.5936

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 67.5959 | Size: 47.5959 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 3s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 67.5961 | Size: 47.5961 | α̃: 1.0000 | ⏱ 0.04s/epoch | ETA: 2s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 67.5957 | Size: 47.5957 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 2s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 67.5981 | Size: 47.5981 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 2s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 67.5952 | Size: 47.5952 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 2s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 67.5953 | Size: 47.5953 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 1s
  ✓ Run 3 complete | Final loss: 67.5953

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 67.5971 | Size: 47.5971 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 67.5962 | Size: 47.5962 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 67.5968 | Size: 47.5968 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 67.5940 | Size: 47.5940 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 67.5973 | Size: 47.5973 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 67.5956 | Size: 47.5956 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 67.5956
  [Step 4/9] Training done in 6s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (GradientBoosting)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 23.7980
  Coverage       : 67.073%
  Avg Width      : 47.5961
  RMSE           : 31.8415
  Total time     : 6s
    ├─ Precompute: 0s
    └─ Training  : 6s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 6s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.670732,47.596056,31.841536,0.05,1.0,20.0,5.76

# **Conformal Predictions with CatBoost**

In [48]:
best_params = get_best_model_params(best_scores_autosampler, 'CatBoost')

In [49]:
conformal_predictions_NEXCP(
    model_class=CatBoostRegressor,
    best_params={**best_params, "verbose": False},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="CatBoost",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/CatBoost.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 1.220% | Width: 0.070
NexCP Full - Coverage: 2.439% | Width: 0.074
NexCP Jackknife+ aB - Coverage: 50.000% | Width: 37.679
NexCP CV+ - Coverage: 96.341% | Width: 129.099

              Strategy  Coverage       Width       RMSE           CWC
0          NexCP Split  0.012195    0.070375  24.604669  1.627765e+19
1           NexCP Full  0.024390    0.074148  24.604669  9.320957e+18
2  NexCP Jackknife+ aB  0.500000   37.678980  28.476713  2.227024e+11
3            NexCP CV+  0.963415  129.098959  27.306920  1.290990e+02

In [50]:
conformal_predictions_online_super(
    model_class=CatBoostRegressor,
    model_params={**best_params, "verbose": False},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="CatBoost",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/CatBoost.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.024390   0.074148  24.604669   0.146488
1            Online CV+  0.536585  36.548121  24.604669  53.485056
2  Online Jackknife+ aB  0.439024  32.864772  27.875370  51.301108
3                 SAOCP  0.731707  56.482589  24.604669  71.636454
4                SF-OGD  0.000000   0.000000  24.604669   0.000000
5                  FACI  0.890244  89.597220  24.604669  99.431061
6            MFCS Split  0.024390   0.074148  24.604669   0.146488
7             MFCS Full  0.000000   0.167796  21.446824   0.335591

               Strategy  Coverage      Width       RMSE        CWC
0          Online Split  0.024390   0.074148  24.604669   0.146488
1            Online CV+  0.536585  36.548121  24.604669  53.485056
2  Online Jackknife+ aB  0.439024  32.864772  27.875370  51.301108
3                 SAOCP  0.731707  56.482589  24.604669  71.636454
4                SF-OGD  0.000000   0.000000  24.604669   0.000000
5                  FACI  0.890244  89.597220  24.604669  99.431061
6            MFCS Split  0.024390   0.074148  24.604669   0.146488
7             MFCS Full  0.000000   0.167796  21.446824   0.335591

In [51]:
conformal_predictions_COP(
    model_class=CatBoostRegressor,
    model_params={**best_params, "verbose": False},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="CatBoost",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/CatBoost.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (CatBoost) =====
Coverage : 9.756%
Avg Width: 3.696
RMSE     : 24.605
Final q  : 3.554

  Strategy  Coverage     Width       RMSE  Alpha    LR  Scale
0      COP  0.097561  3.696093  24.604669   0.05  0.05    0.5

In [52]:
conformal_predictions_EXTREME(
    model_class=CatBoostRegressor,
    model_params={**best_params, "verbose": False},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="CatBoost",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/CatBoost.xlsx",
    alpha=0.05,
    calib_size=0.5,
)

===== EXTREME CONFORMAL PREDICTION (CatBoost) =====
Coverage : 100.000%
Width    : 153428.724
RMSE     : 28.817
q_extreme: 153428.724
u        : 84.110
#Exceed. : 42

In [ ]:
conformal_predictions_AlphaNet(
    model_class=CatBoostRegressor,
    model_params={**best_params, "verbose": False},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="CatBoost",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/CatBoost.xlsx",
    alpha=0.05,
)

# **Conformal Predictions with HistGradientBoosting**

In [54]:
best_params = get_best_model_params(best_scores_autosampler, 'HGBR')

In [ ]:
conformal_predictions_NEXCP(
    model_class=HistGradientBoostingRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="HGBR",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/HGBM.xlsx",
    alpha=0.05,
)

In [ ]:
conformal_predictions_online_super(
    model_class=HistGradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="HGBR",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/HGBM.xlsx",
    alpha=0.05,
)

In [57]:
conformal_predictions_COP(
    model_class=HistGradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="HGBR",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/HGBM.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (HGBR) =====
Coverage : 15.854%
Avg Width: 6.693
RMSE     : 29.797
Final q  : 4.936

  Strategy  Coverage     Width      RMSE  Alpha    LR  Scale
0      COP  0.158537  6.692614  29.79686   0.05  0.05    0.5

In [ ]:
conformal_predictions_EXTREME(
    model_class=HistGradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="HGBR",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/HGBM.xlsx",
    alpha=0.05,
    calib_size=0.5,
)

In [ ]:
conformal_predictions_AlphaNet(
    model_class=HistGradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="HGBR",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/HGBM.xlsx",
    alpha=0.05,
)

# **Conformal Predictions with PGBM**

In [ ]:
class PGBMWrapper(BaseEstimator, RegressorMixin):
    def __init__(self, **params):
        self.params = params
        self.model = None

    def fit(self, X, y):
        X_ = X.to_numpy() if hasattr(X, "to_numpy") else np.array(X)
        y_ = y.to_numpy() if hasattr(y, "to_numpy") else np.array(y)
        self.model = PGBM()
        self.model.train(
            train_set=(X_, y_),
            objective=mseloss_objective,
            metric=rmseloss_metric,
            params=self.params
        )
        return self

    def predict(self, X):
        X_ = X.to_numpy() if hasattr(X, "to_numpy") else np.array(X)
        return self.model.predict(X_).numpy()

In [61]:
# Assuming best_params is obtained correctly
best_params = get_best_model_params(best_scores_autosampler, 'PGBM')

# Remove any conflicting parameters from best_params
incompatible_keys = ['Dist', 'Score']
for key in incompatible_keys:
    best_params.pop(key, None)

# Initialize PGBM model
pgbm_model = PGBM()
def mseloss_objective(yhat, y, sample_weight=None):
    # Ensure that yhat and y are PyTorch tensors
    if not torch.is_tensor(yhat):
        yhat = torch.from_numpy(np.array(yhat)).float()
    if not torch.is_tensor(y):
        y = torch.from_numpy(np.array(y)).float()
    gradient = yhat - y
    hessian = torch.ones_like(yhat)
    return gradient, hessian

def rmseloss_metric(yhat, y, sample_weight=None):
    # Ensure that yhat and y are PyTorch tensors
    if not torch.is_tensor(yhat):
        yhat = torch.from_numpy(np.array(yhat)).float()
    if not torch.is_tensor(y):
        y = torch.from_numpy(np.array(y)).float()
    loss = torch.sqrt(torch.mean((yhat - y) ** 2))
    return loss

X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)

# Fit the model
pgbm_model.train((X_train, y_train), objective=mseloss_objective, metric=rmseloss_metric, params=best_params)

# Predict the distribution
pred_dist = pgbm_model.predict_dist(X_test)

# Define the quantiles you want to predict
quantiles = [0.05, 0.1, 0.15, 0.2, 0.3,
             0.4, 0.5, 0.6, 0.7, 0.8,
             0.85, 0.9, 0.95]

# DataFrame to store predictions
predictions_PGBM_df = pd.DataFrame()

# Calculate and store quantiles
for q in quantiles:
    predictions_PGBM_df[q] = np.quantile(pred_dist, q, axis=0)

# Add actual WQI to the DataFrame
predictions_PGBM_df['Actual'] = y_test.ravel()

# Print the DataFrame with predictions for each quantile
print(predictions_PGBM_df.head())

Training on CPU
Estimator 0/200, Train metric: 72.1814
Estimator 1/200, Train metric: 62.5421
Estimator 2/200, Train metric: 55.4674
Estimator 3/200, Train metric: 47.3446
Estimator 4/200, Train metric: 42.5748
Estimator 5/200, Train metric: 37.6706
Estimator 6/200, Train metric: 33.2748
Estimator 7/200, Train metric: 30.5895
Estimator 8/200, Train metric: 28.0573
Estimator 9/200, Train metric: 25.5309
Estimator 10/200, Train metric: 22.7531
Estimator 11/200, Train metric: 20.1323
Estimator 12/200, Train metric: 17.7140
Estimator 13/200, Train metric: 16.3604
Estimator 14/200, Train metric: 14.9130
Estimator 15/200, Train metric: 13.3459
Estimator 16/200, Train metric: 12.3739
Estimator 17/200, Train metric: 11.3981
Estimator 18/200, Train metric: 10.9000
Estimator 19/200, Train metric: 10.2134
Estimator 20/200, Train metric: 9.4343
Estimator 21/200, Train metric: 8.7925
Estimator 22/200, Train metric: 8.2140
Estimator 23/200, Train metric: 7.7307
Estimator 24/200, Train metric: 7.2653
Estimator 25/200, Train metric: 6.4584
Estimator 26/200, Train metric: 6.3367
Estimator 27/200, Train metric: 5.8325
Estimator 28/200, Train metric: 5.4816
Estimator 29/200, Train metric: 5.1819
Estimator 30/200, Train metric: 4.7984
Estimator 31/200, Train metric: 4.6051
Estimator 32/200, Train metric: 4.4565
Estimator 33/200, Train metric: 4.3297
Estimator 34/200, Train metric: 4.2813
Estimator 35/200, Train metric: 4.0322
Estimator 36/200, Train metric: 3.8137
Estimator 37/200, Train metric: 3.6706
Estimator 38/200, Train metric: 3.4390
Estimator 39/200, Train metric: 3.3613
Estimator 40/200, Train metric: 3.3147
Estimator 41/200, Train metric: 3.2562
Estimator 42/200, Train metric: 3.0793
Estimator 43/200, Train metric: 3.0413
Estimator 44/200, Train metric: 2.8216
Estimator 45/200, Train metric: 2.7918
Estimator 46/200, Train metric: 2.7250
Estimator 47/200, Train metric: 2.7181
Estimator 48/200, Train metric: 2.7397
Estimator 49/200, Train metric: 2.7379
Estimator 50/200, Train metric: 2.7370
Estimator 51/200, Train metric: 2.6035
Estimator 52/200, Train metric: 2.6144
Estimator 53/200, Train metric: 2.6042
Estimator 54/200, Train metric: 2.4797
Estimator 55/200, Train metric: 2.4665
Estimator 56/200, Train metric: 2.4822
Estimator 57/200, Train metric: 2.3194
Estimator 58/200, Train metric: 2.2166
Estimator 59/200, Train metric: 2.2188
Estimator 60/200, Train metric: 2.1456
Estimator 61/200, Train metric: 2.0580
Estimator 62/200, Train metric: 2.0378
Estimator 63/200, Train metric: 1.9625
Estimator 64/200, Train metric: 1.8710
Estimator 65/200, Train metric: 1.8339
Estimator 66/200, Train metric: 1.7827
Estimator 67/200, Train metric: 1.7513
Estimator 68/200, Train metric: 1.7300
Estimator 69/200, Train metric: 1.7311
Estimator 70/200, Train metric: 1.7274
Estimator 71/200, Train metric: 1.7318
Estimator 72/200, Train metric: 1.6913
Estimator 73/200, Train metric: 1.6775
Estimator 74/200, Train metric: 1.6755
Estimator 75/200, Train metric: 1.5755
Estimator 76/200, Train metric: 1.5033
Estimator 77/200, Train metric: 1.4561
Estimator 78/200, Train metric: 1.4156
Estimator 79/200, Train metric: 1.3931
Estimator 80/200, Train metric: 1.3896
Estimator 81/200, Train metric: 1.3603
Estimator 82/200, Train metric: 1.3363
Estimator 83/200, Train metric: 1.3220
Estimator 84/200, Train metric: 1.2956
Estimator 85/200, Train metric: 1.2909
Estimator 86/200, Train metric: 1.2780
Estimator 87/200, Train metric: 1.2788
Estimator 88/200, Train metric: 1.2754
Estimator 89/200, Train metric: 1.2726
Estimator 90/200, Train metric: 1.2752
Estimator 91/200, Train metric: 1.2793
Estimator 92/200, Train metric: 1.2748
Estimator 93/200, Train metric: 1.2706
Estimator 94/200, Train metric: 1.2633
Estimator 95/200, Train metric: 1.2184
Estimator 96/200, Train metric: 1.2222
Estimator 97/200, Train metric: 1.2044
Estimator 98/200, Train metric: 1.2029
Estimator 99/200, Train metric: 1.1487
Estimator 100/200, Train metric: 1.1533
Estimator 101/200, Train metric: 1.1182
Estimator 102/200, Train metric: 1.1154
Estimator 103/200, Train metric: 1.0943
Estimator 104/200, Train metric: 1.0931
Estimator 105/200, Train metric: 1.0521
Estimator 106/200, Train metric: 1.0577
Estimator 107/200, Train metric: 1.0354
Estimator 108/200, Train metric: 1.0348
Estimator 109/200, Train metric: 1.0347
Estimator 110/200, Train metric: 0.9878
Estimator 111/200, Train metric: 0.9513
Estimator 112/200, Train metric: 0.9384
Estimator 113/200, Train metric: 0.9242
Estimator 114/200, Train metric: 0.8811
Estimator 115/200, Train metric: 0.8549
Estimator 116/200, Train metric: 0.8103
Estimator 117/200, Train metric: 0.8075
Estimator 118/200, Train metric: 0.7961
Estimator 119/200, Train metric: 0.7705
Estimator 120/200, Train metric: 0.7666
Estimator 121/200, Train metric: 0.7652
Estimator 122/200, Train metric: 0.7242
Estimator 123/200, Train metric: 0.7121
Estimator 124/200, Train metric: 0.7096
Estimator 125/200, Train metric: 0.7082
Estimator 126/200, Train metric: 0.6979
Estimator 127/200, Train metric: 0.7025
Estimator 128/200, Train metric: 0.6709
Estimator 129/200, Train metric: 0.6689
Estimator 130/200, Train metric: 0.6664
Estimator 131/200, Train metric: 0.6694
Estimator 132/200, Train metric: 0.6444
Estimator 133/200, Train metric: 0.6378
Estimator 134/200, Train metric: 0.6326
Estimator 135/200, Train metric: 0.6252
Estimator 136/200, Train metric: 0.6273
Estimator 137/200, Train metric: 0.6028
Estimator 138/200, Train metric: 0.6005
Estimator 139/200, Train metric: 0.6006
Estimator 140/200, Train metric: 0.6036
Estimator 141/200, Train metric: 0.5980
Estimator 142/200, Train metric: 0.5997
Estimator 143/200, Train metric: 0.5974
Estimator 144/200, Train metric: 0.5983
Estimator 145/200, Train metric: 0.5955
Estimator 146/200, Train metric: 0.5820
Estimator 147/200, Train metric: 0.5678
Estimator 148/200, Train metric: 0.5649
Estimator 149/200, Train metric: 0.5419
Estimator 150/200, Train metric: 0.5435
Estimator 151/200, Train metric: 0.5434
Estimator 152/200, Train metric: 0.5467
Estimator 153/200, Train metric: 0.5227
Estimator 154/200, Train metric: 0.5192
Estimator 155/200, Train metric: 0.5083
Estimator 156/200, Train metric: 0.4911
Estimator 157/200, Train metric: 0.4897
Estimator 158/200, Train metric: 0.4718
Estimator 159/200, Train metric: 0.4704
Estimator 160/200, Train metric: 0.4541
Estimator 161/200, Train metric: 0.4547
Estimator 162/200, Train metric: 0.4547
Estimator 163/200, Train metric: 0.4411
Estimator 164/200, Train metric: 0.4356
Estimator 165/200, Train metric: 0.4358
Estimator 166/200, Train metric: 0.4358
Estimator 167/200, Train metric: 0.4205
Estimator 168/200, Train metric: 0.4108
Estimator 169/200, Train metric: 0.4108
Estimator 170/200, Train metric: 0.4109
Estimator 171/200, Train metric: 0.4089
Estimator 172/200, Train metric: 0.4084
Estimator 173/200, Train metric: 0.3993
Estimator 174/200, Train metric: 0.3993
Estimator 175/200, Train metric: 0.3997
Estimator 176/200, Train metric: 0.3991
Estimator 177/200, Train metric: 0.3992
Estimator 178/200, Train metric: 0.3986
Estimator 179/200, Train metric: 0.3992
Estimator 180/200, Train metric: 0.4013
Estimator 181/200, Train metric: 0.4012
Estimator 182/200, Train metric: 0.4013
Estimator 183/200, Train metric: 0.4023
Estimator 184/200, Train metric: 0.3928
Estimator 185/200, Train metric: 0.3924
Estimator 186/200, Train metric: 0.3933
Estimator 187/200, Train metric: 0.3950
Estimator 188/200, Train metric: 0.3930
Estimator 189/200, Train metric: 0.3930
Estimator 190/200, Train metric: 0.3929
Estimator 191/200, Train metric: 0.3942
Estimator 192/200, Train metric: 0.3942
Estimator 193/200, Train metric: 0.3942
Estimator 194/200, Train metric: 0.3942
Estimator 195/200, Train metric: 0.3900
Estimator 196/200, Train metric: 0.3915
Estimator 197/200, Train metric: 0.3848
Estimator 198/200, Train metric: 0.3823
Estimator 199/200, Train metric: 0.3729
         0.05         0.1        0.15         0.2         0.3         0.4  \
0  291.719006  292.018503  292.157997  292.476160  292.691379  292.788538
1  191.745421  192.366002  192.709194  192.788046  192.983632  193.194998
2  455.278616  455.469418  455.664276  455.872620  456.082162  456.206281
3  230.487223  230.789241  231.805695  231.994296  232.418887  232.613635
4  128.699831  128.768069  128.786921  128.826135  128.867984  128.899506

          0.5         0.6         0.7         0.8        0.85         0.9  \
0  292.958191  293.184357  293.412067  293.582672  293.664258  293.791068
1  193.414345  193.684717  193.828679  194.074762  194.247289  194.526291
2  456.356140  456.466394  456.567264  456.782916  457.010556  457.314505
3  232.828011  232.957986  233.144127  233.378952  233.568391  234.272911
4  128.921204  128.949399  128.986795  129.016129  129.058627  129.078798

         0.95  Actual
0  293.936066     315
1  194.816419     167
2  457.689816     516
3  235.153036     144
4  129.105811     127

In [ ]:
class validate:
    @staticmethod
    def coverage(int_pred, y_test):
        return {strat_name: np.mean((y_test >= int_pred[strat_name][:, 0]) & (y_test <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred): # Corrected: Removed y_test argument as it's not defined and not used
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        return {strat_name: np.sqrt(mean_squared_error(y_test, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = validate.width(int_pred)
        coverages = validate.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}

    @staticmethod
    def cond_coverage(int_pred, y_test, num_bins=10):
        cond_coverages = {}
        for strat_name in int_pred:
            widths = int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]
            bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
            digitized_widths = np.digitize(widths, bin_edges)
            strategy_cond_coverage = []
            for bin_num in range(1, num_bins + 1):
                indices_in_bin = np.where(digitized_widths == bin_num)[0]
                if len(indices_in_bin) > 0:
                    bin_coverage = np.mean((y_test[indices_in_bin] >= int_pred[strat_name][indices_in_bin, 0]) & (y_test[indices_in_bin] <= int_pred[strat_name][indices_in_bin, 1]))
                    strategy_cond_coverage.append(bin_coverage)
                else:
                    strategy_cond_coverage.append(np.nan) # or handle empty bins as needed
            cond_coverages[strat_name] = strategy_cond_coverage
        return cond_coverages


class visualize:
    @staticmethod
    def coverage(int_pred, y_test):
        return {strat_name: np.mean((y_test >= int_pred[strat_name][:, 0]) & (y_test.to_numpy() <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred):
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        return {strat_name: np.sqrt(mean_squared_error(y_test, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = visualize.width(int_pred)
        coverages = visualize.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}
    @staticmethod
    def goodness(y_true, y_pred, y_pred_low, y_pred_up, coverage, width, rmse, cwc, ax=None, title="Goodness Plot"):
        if ax is None:
            fig, ax = plt.subplots()
        n_samples = len(y_true)
        y_true_np = y_true.ravel() # Ensure y_true is numpy array and flattened

        # Determine points inside and outside the interval
        inside_interval = (y_true_np >= y_pred_low) & (y_true_np <= y_pred_up)
        outside_interval = ~inside_interval

        # Plot points inside the interval in green
        ax.scatter(y_true_np[inside_interval], y_pred[inside_interval], color='green', s=10, label='Inside Interval')
        # Plot points outside the interval in orange
        ax.scatter(y_true_np[outside_interval], y_pred[outside_interval], color='orange', s=10, label='Outside Interval')

        # Plot all ground truth values as blue crosses
        ax.scatter(y_true_np, y_true_np, color='blue', marker='x', s=30, linewidths=0.7, label='Ground Truth Values')


        ax.vlines(y_true_np, y_pred_low, y_pred_up, color='gray', alpha=0.5, label='Prediction Intervals')
        ax.plot([min(y_true_np), max(y_true_np)], [min(y_true_np), max(y_true_np)], linestyle='--', color='blue', label='Ideal Prediction Line') # Changed label for clarity
        ax.set_xlabel('Ground Truth')
        ax.set_ylabel('Predictions')
        ax.set_title(f'{title}\nCoverage: {coverage*100:.2f}%, Width: {width:.2f}, RMSE: {rmse:.2f}, CWC: {cwc:.2f}')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def width_size_occurrence(int_pred, train_intervals, num_bins=10, ax=None, x_lim=None, title="Width Size Occurrence"):
        if ax is None:
            fig, ax = plt.subplots()

        # Calculate interval widths for test and train sets
        widths_test = np.abs(int_pred[:, 1] - int_pred[:, 0])
        widths_train = np.abs(train_intervals[:, 1] - train_intervals[:, 0])

        # Plot histograms for both train and test widths
        ax.hist(widths_test, bins=num_bins, alpha=0.6, label='Test Interval Widths', color='red')
        ax.hist(widths_train, bins=num_bins, alpha=0.4, label='Train Interval Widths', color='blue')


        if x_lim is not None:
            ax.set_xlim(x_lim)
        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Occurrence (Frequency)')
        ax.set_title(f'{title} - Interval Width Occurrence')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def coverage_by_width(y_test, int_pred, miscoverage, cond_coverages, num_bins=10, ax=None, title="Coverage vs Width"):
        if ax is None:
            fig, ax = plt.subplots()

        widths = int_pred[:, 1] - int_pred[:, 0]
        bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
        bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
        bin_width = bin_edges[1] - bin_edges[0]

        ax.bar(bin_centers, cond_coverages, width=bin_width, color='blue', alpha=0.7, edgecolor='black', linewidth=0.8, label='Conditional Coverage')
        ax.axhline(1 - miscoverage, color='red', linestyle='--', label=f'Nominal Coverage ({(1 - miscoverage)*100:.0f}%)')

        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Conditional Coverage')
        ax.set_title(f'{title} - Coverage vs Interval Width')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

In [ ]:

def to_numpy_1d(y):
    return y.to_numpy().ravel() if hasattr(y, "to_numpy") else np.asarray(y).ravel()


def weighted_quantile(values, weights, q):
    sorter = np.argsort(values)
    values, weights = values[sorter], weights[sorter]
    cdf = np.cumsum(weights) / np.sum(weights)
    return np.interp(q, cdf, values)



# ============================================================
# NexCP for PGBM (Excel-safe, NexCP-style, NO RETURNS)
# ============================================================

def conformal_predictions_NEXCP_PGBM(
    model_class,
    best_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    decay=0.99,
    n_folds=5,
    n_bootstrap=50,
    seed=123,
):

    warnings.filterwarnings("ignore")
    np.random.seed(seed)

    # ========================================================
    # Data conversion (PGBM-specific)
    # ========================================================
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy() if hasattr(X_test, "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    STRATEGIES = {
        "NexCP-Split": "NexCP Split",
        "NexCP-Full": "NexCP Full",
        "NexCP-J+aB": "NexCP Jackknife+ aB",
        "NexCP-CV+": "NexCP CV+",
    }

    y_pred, int_pred = {}, {}

    # ========================================================
    # Fit base model
    # ========================================================
    base_model = model_class(**best_params)
    base_model.fit(Xtr, ytr)

    yhat_tr = base_model.predict(Xtr)
    yhat_te = base_model.predict(Xte)
    residuals = np.abs(ytr - yhat_tr)

    # ========================================================
    # NexCP – Split (Exponentially Weighted)
    # ========================================================
    weights = decay ** np.arange(len(residuals) - 1, -1, -1)
    q = weighted_quantile(residuals, weights, 1 - alpha)

    y_pred["NexCP-Split"] = yhat_te
    int_pred["NexCP-Split"] = np.c_[yhat_te - q, yhat_te + q]

    # ========================================================
    # NexCP – Full
    # ========================================================
    q = np.quantile(residuals, 1 - alpha)
    y_pred["NexCP-Full"] = yhat_te
    int_pred["NexCP-Full"] = np.c_[yhat_te - q, yhat_te + q]

    # ========================================================
    # NexCP – Jackknife+ aB
    # ========================================================
    rng = np.random.default_rng(seed)
    lowers, uppers, preds = [], [], []

    for _ in range(n_bootstrap):
        idx = rng.choice(len(Xtr), len(Xtr), replace=True)
        m = model_class(**best_params)
        m.fit(Xtr[idx], ytr[idx])

        q = np.quantile(np.abs(ytr[idx] - m.predict(Xtr[idx])), 1 - alpha)
        p = m.predict(Xte)

        preds.append(p)
        lowers.append(p - q)
        uppers.append(p + q)

    y_pred["NexCP-J+aB"] = np.mean(preds, axis=0)
    int_pred["NexCP-J+aB"] = np.c_[np.min(lowers, axis=0), np.max(uppers, axis=0)]

    # ========================================================
    # NexCP – CV+
    # ========================================================
    kf = KFold(n_splits=n_folds, shuffle=True, random_state=seed)
    lowers, uppers, preds = [], [], []

    for tr_idx, cal_idx in kf.split(Xtr):
        m = model_class(**best_params)
        m.fit(Xtr[tr_idx], ytr[tr_idx])

        q = np.quantile(np.abs(ytr[cal_idx] - m.predict(Xtr[cal_idx])), 1 - alpha)
        p = m.predict(Xte)

        preds.append(p)
        lowers.append(p - q)
        uppers.append(p + q)

    y_pred["NexCP-CV+"] = np.mean(preds, axis=0)
    int_pred["NexCP-CV+"] = np.c_[np.mean(lowers, axis=0), np.mean(uppers, axis=0)]

    # ========================================================
    # Metrics + Summary
    # ========================================================
    summary_rows = []
    values_dict = {}

    print("\n===== NEXCP (PGBM) RESULTS =====")

    for s in STRATEGIES:
        ymin, ymax = int_pred[s].T
        yhat = y_pred[s]

        coverage = np.mean((yte >= ymin) & (yte <= ymax))
        width = np.mean(ymax - ymin)
        rmse = np.sqrt(mean_squared_error(yte, yhat))

        print(f"{STRATEGIES[s]} - Coverage: {coverage*100:.3f}% | Width: {width:.3f}")

        summary_rows.append({
            "Strategy": STRATEGIES[s],
            "Coverage": coverage,
            "Width": width,
            "RMSE": rmse,
        })

        values_dict[f"{s}_true"] = yte
        values_dict[f"{s}_pred"] = yhat
        values_dict[f"{s}_lower"] = ymin
        values_dict[f"{s}_upper"] = ymax

    summary_df = pd.DataFrame(summary_rows)
    values_df = pd.DataFrame(values_dict)

    # ========================================================
    # Plotting (SAVE ONLY — NO SHOW)
    # ========================================================
    idx = np.arange(len(yte))
    plot_buffers = {}

    for s in STRATEGIES:
        fig, ax = plt.subplots(figsize=(10, 4))

        ax.scatter(idx, yte, s=10, color="blue", alpha=0.7, label="True")
        ax.fill_between(idx, int_pred[s][:, 0], int_pred[s][:, 1],
                        color="gray", alpha=0.5, label="Prediction interval")
        ax.plot(idx, y_pred[s], color="red", lw=1, label="Predicted mean")

        ax.set_title(f"{STRATEGIES[s]} ({model_name})")
        ax.set_xlabel("Sample Number")
        ax.set_ylabel("WQI")
        ax.legend(loc="upper left")

        plt.tight_layout()

        buf = io.BytesIO()
        fig.savefig(buf, format="png")
        buf.seek(0)
        plot_buffers[s] = buf

        plt.close(fig)

    # ========================================================
    # Excel Export (append-safe)
    # ========================================================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary sheet ----
        sheet_name = "NEXCP_PGBM_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot sheets ----
        for s, buf in plot_buffers.items():
            img = Image(buf)
            sheet_name = f"NEXCP_PGBM_Plot_{s}"
            base = sheet_name
            i = 1
            while sheet_name in wb.sheetnames:
                sheet_name = f"{base}_{i}"
                i += 1
            ws = wb.create_sheet(sheet_name)
            ws.add_image(img, "A1")

        # ---- Values sheet ----
        sheet_name = "NEXCP_PGBM_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)


conformal_predictions_NEXCP_PGBM(
    model_class=PGBMWrapper,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="PGBM",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/PGBM.xlsx",
    alpha=0.05,
)

In [ ]:
def conformal_predictions_online_super_PGBM(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    strategies="all",
    window_min=50,
    window_max=500,
    window_grid=(25, 50, 100, 200, 400),
    n_bootstrap=30,
    seed=123,
):

    warnings.filterwarnings("ignore")
    np.random.seed(seed)

    STRATEGIES = {
        "Online-Split": "Online Split",
        "Online-CV+": "Online CV+",
        "Online-J+aB": "Online Jackknife+ aB",
        "SAOCP": "SAOCP",
        "SF-OGD": "SF-OGD",
        "FACI": "FACI",
        "MFCS-Split": "MFCS Split",
        "MFCS-Full": "MFCS Full",
    }

    if strategies == "all":
        strategies = list(STRATEGIES.keys())

    # --------------------------------------------------------
    # Safe NumPy conversion (PGBM-specific)
    # --------------------------------------------------------
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy() if hasattr(X_test, "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # --------------------------------------------------------
    # Base model (trained once)
    # --------------------------------------------------------
    base_model = model_class(**model_params)
    base_model.fit(Xtr, ytr)

    yhat_train = base_model.predict(Xtr)

    # --------------------------------------------------------
    # Streaming predictions
    # --------------------------------------------------------
    X_all = np.vstack([Xtr, Xte])
    y_all = np.concatenate([ytr, yte])

    n_train = len(Xtr)
    T = len(y_all)

    y_hat_all = np.zeros(T)
    y_hat_all[:n_train] = yhat_train

    for t in range(n_train, T):
        y_hat_all[t] = base_model.predict(X_all[t:t + 1])[0]

    residuals = np.abs(y_all - y_hat_all)

    y_pred, int_pred = {}, {}

    # ========================================================
    # Online Split
    # ========================================================
    if "Online-Split" in strategies:
        q = np.quantile(residuals[:n_train], 1 - alpha)
        y_pred["Online-Split"] = y_hat_all[n_train:]
        int_pred["Online-Split"] = np.c_[y_pred["Online-Split"] - q,
                                          y_pred["Online-Split"] + q]

    # ========================================================
    # Online CV+
    # ========================================================
    if "Online-CV+" in strategies:
        lower, upper = [], []
        for t in range(n_train, T):
            q = np.quantile(residuals[:t], 1 - alpha)
            lower.append(y_hat_all[t] - q)
            upper.append(y_hat_all[t] + q)
        y_pred["Online-CV+"] = y_hat_all[n_train:]
        int_pred["Online-CV+"] = np.c_[lower, upper]

    # ========================================================
    # Online Jackknife+ aB
    # ========================================================
    if "Online-J+aB" in strategies:
        lowers, uppers, preds = [], [], []
        for _ in range(n_bootstrap):
            idx = np.random.choice(n_train, n_train, replace=True)
            m = model_class(**model_params)
            m.fit(Xtr[idx], ytr[idx])

            q = np.quantile(np.abs(ytr[idx] - m.predict(Xtr[idx])), 1 - alpha)
            p = m.predict(Xte)

            preds.append(p)
            lowers.append(p - q)
            uppers.append(p + q)

        y_pred["Online-J+aB"] = np.mean(preds, axis=0)
        int_pred["Online-J+aB"] = np.c_[np.min(lowers, axis=0),
                                        np.max(uppers, axis=0)]

    # ========================================================
    # SAOCP
    # ========================================================
    if "SAOCP" in strategies:
        lower, upper = [], []
        for t in range(n_train, T):
            w = min(max(window_min, t // 2), window_max)
            start = max(0, t - w)
            q = np.quantile(residuals[start:t], 1 - alpha)
            lower.append(y_hat_all[t] - q)
            upper.append(y_hat_all[t] + q)
        y_pred["SAOCP"] = y_hat_all[n_train:]
        int_pred["SAOCP"] = np.c_[lower, upper]

    # ========================================================
    # SF-OGD
    # ========================================================
    if "SF-OGD" in strategies:
        q_t = np.quantile(residuals[:n_train], 1 - alpha)
        lower, upper = [], []
        for t in range(n_train, T):
            grad = alpha - (residuals[t] <= q_t)
            eta = 1.0 / np.sqrt(t - n_train + 1)
            q_t = max(0.0, q_t - eta * grad)
            lower.append(y_hat_all[t] - q_t)
            upper.append(y_hat_all[t] + q_t)
        y_pred["SF-OGD"] = y_hat_all[n_train:]
        int_pred["SF-OGD"] = np.c_[lower, upper]

    # ========================================================
    # FACI
    # ========================================================
    if "FACI" in strategies:
        windows = list(window_grid)
        losses = np.zeros(len(windows))
        lower, upper = [], []
        for t in range(n_train, T):
            r_t = residuals[t]
            qs = []
            for i, w in enumerate(windows):
                start = max(0, t - w)
                q = np.quantile(residuals[start:t], 1 - alpha)
                qs.append(q)
                losses[i] += alpha * q + (r_t - q) * (r_t > q)
            q_star = qs[np.argmin(losses)]
            lower.append(y_hat_all[t] - q_star)
            upper.append(y_hat_all[t] + q_star)
        y_pred["FACI"] = y_hat_all[n_train:]
        int_pred["FACI"] = np.c_[lower, upper]

    # ========================================================
    # MFCS-Split ✅ (ADDED)
    # ========================================================
    if "MFCS-Split" in strategies:
        q = np.quantile(residuals[:n_train], 1 - alpha)
        y_pred["MFCS-Split"] = y_hat_all[n_train:]
        int_pred["MFCS-Split"] = np.c_[y_pred["MFCS-Split"] - q,
                                       y_pred["MFCS-Split"] + q]

    # ========================================================
    # MFCS-Full
    # ========================================================
    if "MFCS-Full" in strategies:
        lower, upper, preds = [], [], []
        for t in range(n_train, T):
            m = model_class(**model_params)
            m.fit(X_all[:t], y_all[:t])
            yhat = m.predict(X_all[t:t + 1])[0]
            q = np.quantile(np.abs(y_all[:t] - m.predict(X_all[:t])), 1 - alpha)
            preds.append(yhat)
            lower.append(yhat - q)
            upper.append(yhat + q)
        y_pred["MFCS-Full"] = np.array(preds)
        int_pred["MFCS-Full"] = np.c_[lower, upper]

    # ========================================================
    # Metrics + Summary
    # ========================================================
    summary_rows = []
    values_dict = {}

    print("\n===== ONLINE CP (PGBM) RESULTS =====")

    for s in y_pred:
        ymin, ymax = int_pred[s].T
        yhat = y_pred[s]

        coverage = np.mean((yte >= ymin) & (yte <= ymax))
        width = np.mean(ymax - ymin)
        rmse = np.sqrt(mean_squared_error(yte, yhat))

        print(f"{STRATEGIES[s]} - Coverage: {coverage*100:.3f}% | Width: {width:.3f}")

        summary_rows.append({
            "Strategy": STRATEGIES[s],
            "Coverage": coverage,
            "Width": width,
            "RMSE": rmse,
        })

        values_dict[f"{s}_true"] = yte
        values_dict[f"{s}_pred"] = yhat
        values_dict[f"{s}_lower"] = ymin
        values_dict[f"{s}_upper"] = ymax

    summary_df = pd.DataFrame(summary_rows)
    values_df = pd.DataFrame(values_dict)

    # ========================================================
    # Plotting (SAVE ONLY — NO SHOW)
    # ========================================================
    idx = np.arange(len(yte))
    plot_buffers = {}

    for s in y_pred:
        fig, ax = plt.subplots(figsize=(10, 4))

        ax.scatter(idx, yte, s=10, color="blue", alpha=0.7, label="True")
        ax.fill_between(idx, int_pred[s][:, 0], int_pred[s][:, 1],
                        color="gray", alpha=0.5, label="Prediction interval")
        ax.plot(idx, y_pred[s], color="red", lw=1, label="Predicted mean")

        ax.set_title(f"{STRATEGIES[s]} ({model_name})")
        ax.set_xlabel("Sample Number")
        ax.set_ylabel("WQI")
        ax.legend(loc="upper left")

        plt.tight_layout()

        buf = io.BytesIO()
        fig.savefig(buf, format="png")
        buf.seek(0)
        plot_buffers[s] = buf

        plt.close(fig)

    # ========================================================
    # Excel Export (append-safe)
    # ========================================================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary ----
        sheet_name = "ONLINECP_PGBM_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plots ----
        for s, buf in plot_buffers.items():
            img = Image(buf)
            sheet_name = f"ONLINECP_PGBM_Plot_{s}"
            base = sheet_name
            i = 1
            while sheet_name in wb.sheetnames:
                sheet_name = f"{base}_{i}"
                i += 1
            ws = wb.create_sheet(sheet_name)
            ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "ONLINECP_PGBM_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)


conformal_predictions_online_super_PGBM(
    model_class=PGBMWrapper,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="PGBM",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/PGBM.xlsx",
    alpha=0.05,
    strategies="all",
)

In [65]:
def conformal_predictions_COP_PGBM(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    lr=0.05,
    T_burnin=50,
    scale=0.5,
    random_state=123,
):

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)

    # =========================================================
    # Safe NumPy conversion (PGBM-specific)
    # =========================================================
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy() if hasattr(X_test, "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # =========================================================
    # Train base PGBM model
    # =========================================================
    model = model_class(**model_params)
    model.fit(Xtr, ytr)

    y_pred_test = model.predict(Xte).ravel()
    y_pred_train = model.predict(Xtr).ravel()

    # Absolute residuals (symmetric COP)
    scores_test = np.abs(yte - y_pred_test)
    scores_train = np.abs(ytr - y_pred_train)

    T_test = len(scores_test)

    # =========================================================
    # COP initialization
    # =========================================================
    init_q = np.quantile(scores_train, 1 - alpha)

    qs = np.zeros(T_test)
    qts = np.zeros(T_test)
    integrators = np.zeros(T_test)
    covereds = np.zeros(T_test)

    qs[0] = init_q
    qts[0] = init_q

    # =========================================================
    # Online COP loop
    # =========================================================
    for t in range(T_test - 1):

        covereds[t] = 1 if qs[t] >= scores_test[t] else 0

        # Standard COP gradient
        grad = alpha if covereds[t] else -(1 - alpha)

        # Distribution-informed (optimistic) gradient
        if t < T_burnin:
            grad_i = 0.0
        else:
            window_s = scores_test[t - T_burnin : t]
            target = qts[t] - lr * grad
            grad_i = np.mean(window_s <= target) - (1 - alpha)

        # Updates
        integrator = -scale * grad_i
        qts[t + 1] = qts[t] - lr * grad
        integrators[t + 1] = lr * integrator
        qs[t + 1] = max(0.0, qts[t + 1] + integrators[t + 1])

    covereds[-1] = 1 if qs[-1] >= scores_test[-1] else 0

    # =========================================================
    # Prediction intervals
    # =========================================================
    ymin = y_pred_test - qs
    ymax = y_pred_test + qs

    # =========================================================
    # Metrics
    # =========================================================
    rmse = np.sqrt(mean_squared_error(yte, y_pred_test))
    coverage = np.mean(covereds)
    avg_width = np.mean(ymax - ymin)

    print(f"\n===== COP (PGBM) =====")
    print(f"Coverage : {coverage*100:.3f}%")
    print(f"Width    : {avg_width:.3f}")
    print(f"RMSE     : {rmse:.3f}")
    print(f"Final q  : {qs[-1]:.3f}")

    # =========================================================
    # Tables
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy": "COP",
        "Coverage": coverage,
        "Width": avg_width,
        "RMSE": rmse,
        "Alpha": alpha,
        "LR": lr,
        "Scale": scale,
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(yte)),
        "y_true": yte,
        "y_pred": y_pred_test,
        "ymin": ymin,
        "ymax": ymax,
        "width": ymax - ymin,
        "is_covered": covereds.astype(int),
        "score": scores_test,
        "adaptive_q": qs,
    })

    # =========================================================
    # Plot (SAVE ONLY)
    # =========================================================
    idx = np.arange(len(yte))
    fig, ax = plt.subplots(figsize=(10, 4))

    ax.scatter(idx, yte, s=10, color="blue", alpha=0.7, label="True")
    ax.fill_between(idx, ymin, ymax, color="gray", alpha=0.5, label="COP Interval")
    ax.plot(idx, y_pred_test, color="red", lw=1, label="Predicted mean")


    ax.set_title(f"COP ({model_name})")
    ax.set_xlabel("Sample Number")
    ax.set_ylabel("WQI")
    ax.legend(loc="upper left")

    plt.tight_layout()
    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    buf.seek(0)
    plt.close(fig)

    # =========================================================
    # Excel export (append-safe)
    # =========================================================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary ----
        sheet_name = "COP_PGBM_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot ----
        img = Image(buf)
        sheet_name = "COP_PGBM_Plot"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1
        ws = wb.create_sheet(sheet_name)
        ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "COP_PGBM_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)

    return summary_df

conformal_predictions_COP_PGBM(
    model_class=PGBMWrapper,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="PGBM",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/PGBM.xlsx",
    alpha=0.05,
)

Training on CPU
Estimator 0/200, Train metric: 72.1814
Estimator 1/200, Train metric: 62.5421
Estimator 2/200, Train metric: 55.4674
Estimator 3/200, Train metric: 47.3446
Estimator 4/200, Train metric: 42.5748
Estimator 5/200, Train metric: 37.6706
Estimator 6/200, Train metric: 33.2748
Estimator 7/200, Train metric: 30.5895
Estimator 8/200, Train metric: 28.0573
Estimator 9/200, Train metric: 25.5309
Estimator 10/200, Train metric: 22.7531
Estimator 11/200, Train metric: 20.1323
Estimator 12/200, Train metric: 17.7140
Estimator 13/200, Train metric: 16.3604
Estimator 14/200, Train metric: 14.9130
Estimator 15/200, Train metric: 13.3459
Estimator 16/200, Train metric: 12.3739
Estimator 17/200, Train metric: 11.3981
Estimator 18/200, Train metric: 10.9000
Estimator 19/200, Train metric: 10.2134
Estimator 20/200, Train metric: 9.4343
Estimator 21/200, Train metric: 8.7925
Estimator 22/200, Train metric: 8.2140
Estimator 23/200, Train metric: 7.7307
Estimator 24/200, Train metric: 7.2653
Estimator 25/200, Train metric: 6.4584
Estimator 26/200, Train metric: 6.3367
Estimator 27/200, Train metric: 5.8325
Estimator 28/200, Train metric: 5.4816
Estimator 29/200, Train metric: 5.1819
Estimator 30/200, Train metric: 4.7984
Estimator 31/200, Train metric: 4.6051
Estimator 32/200, Train metric: 4.4565
Estimator 33/200, Train metric: 4.3297
Estimator 34/200, Train metric: 4.2813
Estimator 35/200, Train metric: 4.0322
Estimator 36/200, Train metric: 3.8137
Estimator 37/200, Train metric: 3.6706
Estimator 38/200, Train metric: 3.4390
Estimator 39/200, Train metric: 3.3613
Estimator 40/200, Train metric: 3.3147
Estimator 41/200, Train metric: 3.2562
Estimator 42/200, Train metric: 3.0793
Estimator 43/200, Train metric: 3.0413
Estimator 44/200, Train metric: 2.8216
Estimator 45/200, Train metric: 2.7918
Estimator 46/200, Train metric: 2.7250
Estimator 47/200, Train metric: 2.7181
Estimator 48/200, Train metric: 2.7397
Estimator 49/200, Train metric: 2.7379
Estimator 50/200, Train metric: 2.7370
Estimator 51/200, Train metric: 2.6035
Estimator 52/200, Train metric: 2.6144
Estimator 53/200, Train metric: 2.6042
Estimator 54/200, Train metric: 2.4797
Estimator 55/200, Train metric: 2.4665
Estimator 56/200, Train metric: 2.4822
Estimator 57/200, Train metric: 2.3194
Estimator 58/200, Train metric: 2.2166
Estimator 59/200, Train metric: 2.2188
Estimator 60/200, Train metric: 2.1456
Estimator 61/200, Train metric: 2.0580
Estimator 62/200, Train metric: 2.0378
Estimator 63/200, Train metric: 1.9625
Estimator 64/200, Train metric: 1.8710
Estimator 65/200, Train metric: 1.8339
Estimator 66/200, Train metric: 1.7827
Estimator 67/200, Train metric: 1.7513
Estimator 68/200, Train metric: 1.7300
Estimator 69/200, Train metric: 1.7311
Estimator 70/200, Train metric: 1.7274
Estimator 71/200, Train metric: 1.7318
Estimator 72/200, Train metric: 1.6913
Estimator 73/200, Train metric: 1.6775
Estimator 74/200, Train metric: 1.6755
Estimator 75/200, Train metric: 1.5755
Estimator 76/200, Train metric: 1.5033
Estimator 77/200, Train metric: 1.4561
Estimator 78/200, Train metric: 1.4156
Estimator 79/200, Train metric: 1.3931
Estimator 80/200, Train metric: 1.3896
Estimator 81/200, Train metric: 1.3603
Estimator 82/200, Train metric: 1.3363
Estimator 83/200, Train metric: 1.3220
Estimator 84/200, Train metric: 1.2956
Estimator 85/200, Train metric: 1.2909
Estimator 86/200, Train metric: 1.2780
Estimator 87/200, Train metric: 1.2788
Estimator 88/200, Train metric: 1.2754
Estimator 89/200, Train metric: 1.2726
Estimator 90/200, Train metric: 1.2752
Estimator 91/200, Train metric: 1.2793
Estimator 92/200, Train metric: 1.2748
Estimator 93/200, Train metric: 1.2706
Estimator 94/200, Train metric: 1.2633
Estimator 95/200, Train metric: 1.2184
Estimator 96/200, Train metric: 1.2222
Estimator 97/200, Train metric: 1.2044
Estimator 98/200, Train metric: 1.2029
Estimator 99/200, Train metric: 1.1487
Estimator 100/200, Train metric: 1.1533
Estimator 101/200, Train metric: 1.1182
Estimator 102/200, Train metric: 1.1154
Estimator 103/200, Train metric: 1.0943
Estimator 104/200, Train metric: 1.0931
Estimator 105/200, Train metric: 1.0521
Estimator 106/200, Train metric: 1.0577
Estimator 107/200, Train metric: 1.0354
Estimator 108/200, Train metric: 1.0348
Estimator 109/200, Train metric: 1.0347
Estimator 110/200, Train metric: 0.9878
Estimator 111/200, Train metric: 0.9513
Estimator 112/200, Train metric: 0.9384
Estimator 113/200, Train metric: 0.9242
Estimator 114/200, Train metric: 0.8811
Estimator 115/200, Train metric: 0.8549
Estimator 116/200, Train metric: 0.8103
Estimator 117/200, Train metric: 0.8075
Estimator 118/200, Train metric: 0.7961
Estimator 119/200, Train metric: 0.7705
Estimator 120/200, Train metric: 0.7666
Estimator 121/200, Train metric: 0.7652
Estimator 122/200, Train metric: 0.7242
Estimator 123/200, Train metric: 0.7121
Estimator 124/200, Train metric: 0.7096
Estimator 125/200, Train metric: 0.7082
Estimator 126/200, Train metric: 0.6979
Estimator 127/200, Train metric: 0.7025
Estimator 128/200, Train metric: 0.6709
Estimator 129/200, Train metric: 0.6689
Estimator 130/200, Train metric: 0.6664
Estimator 131/200, Train metric: 0.6694
Estimator 132/200, Train metric: 0.6444
Estimator 133/200, Train metric: 0.6378
Estimator 134/200, Train metric: 0.6326
Estimator 135/200, Train metric: 0.6252
Estimator 136/200, Train metric: 0.6273
Estimator 137/200, Train metric: 0.6028
Estimator 138/200, Train metric: 0.6005
Estimator 139/200, Train metric: 0.6006
Estimator 140/200, Train metric: 0.6036
Estimator 141/200, Train metric: 0.5980
Estimator 142/200, Train metric: 0.5997
Estimator 143/200, Train metric: 0.5974
Estimator 144/200, Train metric: 0.5983
Estimator 145/200, Train metric: 0.5955
Estimator 146/200, Train metric: 0.5820
Estimator 147/200, Train metric: 0.5678
Estimator 148/200, Train metric: 0.5649
Estimator 149/200, Train metric: 0.5419
Estimator 150/200, Train metric: 0.5435
Estimator 151/200, Train metric: 0.5434
Estimator 152/200, Train metric: 0.5467
Estimator 153/200, Train metric: 0.5227
Estimator 154/200, Train metric: 0.5192
Estimator 155/200, Train metric: 0.5083
Estimator 156/200, Train metric: 0.4911
Estimator 157/200, Train metric: 0.4897
Estimator 158/200, Train metric: 0.4718
Estimator 159/200, Train metric: 0.4704
Estimator 160/200, Train metric: 0.4541
Estimator 161/200, Train metric: 0.4547
Estimator 162/200, Train metric: 0.4547
Estimator 163/200, Train metric: 0.4411
Estimator 164/200, Train metric: 0.4356
Estimator 165/200, Train metric: 0.4358
Estimator 166/200, Train metric: 0.4358
Estimator 167/200, Train metric: 0.4205
Estimator 168/200, Train metric: 0.4108
Estimator 169/200, Train metric: 0.4108
Estimator 170/200, Train metric: 0.4109
Estimator 171/200, Train metric: 0.4089
Estimator 172/200, Train metric: 0.4084
Estimator 173/200, Train metric: 0.3993
Estimator 174/200, Train metric: 0.3993
Estimator 175/200, Train metric: 0.3997
Estimator 176/200, Train metric: 0.3991
Estimator 177/200, Train metric: 0.3992
Estimator 178/200, Train metric: 0.3986
Estimator 179/200, Train metric: 0.3992
Estimator 180/200, Train metric: 0.4013
Estimator 181/200, Train metric: 0.4012
Estimator 182/200, Train metric: 0.4013
Estimator 183/200, Train metric: 0.4023
Estimator 184/200, Train metric: 0.3928
Estimator 185/200, Train metric: 0.3924
Estimator 186/200, Train metric: 0.3933
Estimator 187/200, Train metric: 0.3950
Estimator 188/200, Train metric: 0.3930
Estimator 189/200, Train metric: 0.3930
Estimator 190/200, Train metric: 0.3929
Estimator 191/200, Train metric: 0.3942
Estimator 192/200, Train metric: 0.3942
Estimator 193/200, Train metric: 0.3942
Estimator 194/200, Train metric: 0.3942
Estimator 195/200, Train metric: 0.3900
Estimator 196/200, Train metric: 0.3915
Estimator 197/200, Train metric: 0.3848
Estimator 198/200, Train metric: 0.3823
Estimator 199/200, Train metric: 0.3729

===== COP (PGBM) =====
Coverage : 14.634%
Width    : 4.669
RMSE     : 24.823
Final q  : 3.950

  Strategy  Coverage     Width       RMSE  Alpha    LR  Scale
0      COP  0.146341  4.668868  24.822695   0.05  0.05    0.5

In [ ]:
def conformal_predictions_EXTREME_PGBM(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    calib_size=0.2,
    gpd_threshold_quantile=0.95,
    n_bootstrap=30,
    random_state=123,
):

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)

    # --------------------------------------------------------
    # Safe NumPy conversion (PGBM-specific)
    # --------------------------------------------------------
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy() if hasattr(X_test, "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # --------------------------------------------------------
    # Train / calibration split
    # --------------------------------------------------------
    X_fit, X_cal, y_fit, y_cal = train_test_split(
        Xtr, ytr, test_size=calib_size, random_state=random_state, shuffle=True
    )

    # --------------------------------------------------------
    # Train model
    # --------------------------------------------------------
    model = model_class(**model_params)
    model.fit(X_fit, y_fit)

    y_pred_test = model.predict(Xte)
    y_pred_cal = model.predict(X_cal)

    # --------------------------------------------------------
    # Upper-tail nonconformity scores
    # --------------------------------------------------------
    scores = y_cal - y_pred_cal
    scores = scores[scores > 0]

    if len(scores) < 30:
        raise RuntimeError("Too few exceedances for EVT fitting.")

    # --------------------------------------------------------
    # Peaks-over-threshold
    # --------------------------------------------------------
    u = np.quantile(scores, gpd_threshold_quantile)
    excesses = scores[scores > u] - u

    # --------------------------------------------------------
    # Bootstrap EVT quantile
    # --------------------------------------------------------
    boot_q = []
    n_exc = len(excesses)
    n_scores = len(scores)

    for _ in range(n_bootstrap):
        res = np.random.choice(excesses, size=n_exc, replace=True)
        xi, _, sigma = genpareto.fit(res, floc=0)
        q = u + (sigma / xi) * ((n_scores / (n_scores * alpha)) ** xi - 1)
        boot_q.append(q)

    q_extreme = np.quantile(boot_q, 0.95)

    # --------------------------------------------------------
    # FINITE prediction intervals (for plotting & width)
    # --------------------------------------------------------
    ymin = y_pred_test - q_extreme
    ymax = y_pred_test + q_extreme

    # --------------------------------------------------------
    # Metrics (one-sided coverage)
    # --------------------------------------------------------
    rmse = np.sqrt(mean_squared_error(yte, y_pred_test))
    coverage = np.mean(yte <= ymax)
    width = q_extreme

    print(f"\n===== EXTREME CP (PGBM) =====")
    print(f"Coverage     : {coverage*100:.3f}%")
    print(f"Width        : {width:.3f}")
    print(f"RMSE         : {rmse:.3f}")
    print(f"q_extreme    : {q_extreme:.3f}")
    print(f"threshold_u  : {u:.3f}")
    print(f"#Exceedances : {len(scores)}")

    # --------------------------------------------------------
    # Summary table
    # --------------------------------------------------------
    summary_df = pd.DataFrame([{
        "Strategy": "EXTREME CP",
        "Coverage": coverage,
        "Width": width,
        "RMSE": rmse,
        "q_extreme": q_extreme,
        "threshold_u": u,
        "n_exceedances": len(scores),
    }])

    # --------------------------------------------------------
    # Values table
    # --------------------------------------------------------
    values_df = pd.DataFrame({
        "sample_index": np.arange(len(yte)),
        "y_true": yte,
        "y_pred": y_pred_test,
        "ymin": ymin,
        "ymax": ymax,
        "width": ymax - ymin,
        "is_covered": (yte <= ymax).astype(int),
        "residual": yte - y_pred_test,
    })

    # --------------------------------------------------------
    # Plot (SAVE ONLY — NO SHOW)
    # --------------------------------------------------------
    idx = np.arange(len(yte))
    fig, ax = plt.subplots(figsize=(10, 4))

    ax.scatter(idx, yte, s=10, color="blue", alpha=0.7, label="True")
    ax.fill_between(idx, ymin, ymax, alpha=0.4, label="Extreme PI")
    ax.plot(idx, y_pred_test, color="red", lw=1, label="Prediction")

    ax.set_title(f"Extreme CP ({model_name})")
    ax.set_xlabel("Sample Number")
    ax.set_ylabel("WQI")
    ax.legend(loc="upper left")

    plt.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    buf.seek(0)
    plt.close(fig)

    # --------------------------------------------------------
    # Excel export (append-safe)
    # --------------------------------------------------------
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary ----
        sheet_name = "EXTREMECP_PGBM_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot ----
        img = Image(buf)
        sheet_name = "EXTREMECP_PGBM_Plot"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "EXTREMECP_PGBM_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)


conformal_predictions_EXTREME_PGBM(
    model_class=PGBMWrapper,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="PGBM",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/PGBM.xlsx",
    alpha=0.05,
    calib_size=0.5,
)

In [ ]:
def conformal_predictions_AlphaNet_PGBM(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    lambda_reg=20.0,
    num_epochs=50,
    batch_size=32,
    lr_alpha=1e-3,
    calib_fraction=0.5,
    num_runs=4,
    random_state=123,
):
    warnings.filterwarnings("ignore")
    np.random.seed(random_state)
    torch.manual_seed(random_state)
    device = "cuda" if torch.cuda.is_available() else "cpu"

    t_start_total = time.time()

    # =========================================================
    # Data conversion (PGBM-specific)
    # =========================================================
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy()  if hasattr(X_test,  "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # =========================================================
    # 1. Split training data → fit + calibration
    # =========================================================
    n_total = len(Xtr)
    n_fit   = int(n_total * (1 - calib_fraction))
    perm    = np.random.permutation(n_total)

    fit_idx   = perm[:n_fit]
    calib_idx = perm[n_fit:]

    X_fit,   y_fit   = Xtr[fit_idx],   ytr[fit_idx]
    X_calib, y_calib = Xtr[calib_idx],  ytr[calib_idx]
    n_calib = len(X_calib)

    alpha_min = 1.0 / (n_calib + 1) + 0.01
    print(f"  [Info] n_calib={n_calib} | alpha_min={alpha_min:.4f}")

    # =========================================================
    # 2. Train base PGBM model
    # =========================================================
    print(f"  [Step 2/9] Training base {model_name} model...")
    t0 = time.time()
    base_model = model_class(**model_params)
    base_model.fit(X_fit, y_fit)
    print(f"  [Step 2/9] Done in {_fmt_time(time.time()-t0)}")

    def _safe_predict(m, X):
        p = m.predict(X)
        return p.ravel() if hasattr(p, "ravel") else np.asarray(p).ravel()

    # =========================================================
    # 3. PRECOMPUTE all LOO scores
    # =========================================================
    print(f"  [Step 3/9] Precomputing {n_calib} LOO score vectors...")
    t0 = time.time()

    precomputed_scores = []
    precomputed_sums   = []

    iterator = tqdm(range(n_calib), desc="    LOO precompute", leave=False) if HAS_TQDM else range(n_calib)

    for i in iterator:
        loo_X = np.delete(X_calib, i, axis=0)
        loo_y = np.delete(y_calib, i, axis=0)
        scores_loo = np.abs(_safe_predict(base_model, loo_X) - loo_y)

        scores_tensor = torch.tensor(scores_loo, dtype=torch.float32).to(device)
        precomputed_scores.append(scores_tensor)
        precomputed_sums.append(scores_loo.sum())

    elapsed_precompute = time.time() - t0
    print(f"  [Step 3/9] Done in {_fmt_time(elapsed_precompute)}")

    X_alpha = torch.tensor(
        np.array(precomputed_sums).reshape(-1, 1),
        dtype=torch.float32,
    ).to(device)

    # =========================================================
    # 4. Train AlphaNet
    # =========================================================
    print(f"  [Step 4/9] Training AlphaNet: {num_runs} runs × {num_epochs} epochs")

    best_net  = None
    best_loss = np.inf
    history   = {"losses": [], "sizes": [], "alphas": []}

    t0_train = time.time()

    for run in range(num_runs):
        np.random.seed(run)
        torch.manual_seed(run)

        alpha_net = AlphaNet(input_dim=1, alpha_min=alpha_min).to(device)
        optimizer = optim.Adam(alpha_net.parameters(), lr=lr_alpha)

        dataset = TensorDataset(X_alpha, torch.arange(n_calib))
        loader  = DataLoader(dataset, batch_size=batch_size, shuffle=True)

        run_losses, run_sizes, run_alphas = [], [], []

        epoch_iter = (
            tqdm(range(num_epochs), desc=f"    Run {run+1}/{num_runs}", leave=False)
            if HAS_TQDM else range(num_epochs)
        )

        for epoch in epoch_iter:
            t_epoch_start = time.time()
            epoch_loss = epoch_size = epoch_alpha = 0.0

            for x_batch, idx_batch in loader:
                x_batch = x_batch.to(device)
                alpha_pred = alpha_net(x_batch)

                batch_sizes = []
                for j, idx in enumerate(idx_batch):
                    scores_t = precomputed_scores[idx.item()]
                    size_j = _interval_size(scores_t, alpha_pred[j])
                    batch_sizes.append(size_j)

                batch_sizes = torch.stack(batch_sizes)
                loss = (batch_sizes + lambda_reg * alpha_pred).mean()

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

                epoch_loss  += loss.item()
                epoch_size  += batch_sizes.mean().item()
                epoch_alpha += alpha_pred.mean().item()

            n_batches = len(loader)
            run_losses.append(epoch_loss  / n_batches)
            run_sizes.append(epoch_size   / n_batches)
            run_alphas.append(epoch_alpha / n_batches)

            epoch_time = time.time() - t_epoch_start

            if epoch % 10 == 0 or epoch == num_epochs - 1:
                epochs_done  = (run * num_epochs) + epoch + 1
                epochs_total = num_runs * num_epochs
                elapsed_train = time.time() - t0_train
                eta = (elapsed_train / epochs_done) * (epochs_total - epochs_done)

                print(
                    f"  λ={lambda_reg} | Run {run+1}/{num_runs} | "
                    f"Epoch {epoch}/{num_epochs} | "
                    f"Loss: {run_losses[-1]:.4f} | "
                    f"Size: {run_sizes[-1]:.4f} | "
                    f"α̃: {run_alphas[-1]:.4f} | "
                    f"⏱ {epoch_time:.2f}s/epoch | "
                    f"ETA: {_fmt_time(eta)}"
                )

        if run_losses[-1] < best_loss:
            best_loss = run_losses[-1]
            best_net  = alpha_net

        history["losses"].append(run_losses)
        history["sizes"].append(run_sizes)
        history["alphas"].append(run_alphas)

        print(f"  ✓ Run {run+1} complete | Final loss: {run_losses[-1]:.4f}")

    train_time = time.time() - t0_train
    print(f"  [Step 4/9] Training done in {_fmt_time(train_time)}")

    alpha_net = best_net
    alpha_net.eval()

    # =========================================================
    # 5. Compute conformal intervals on TEST set
    # =========================================================
    print(f"  [Step 5/9] Computing conformal intervals...")
    scores_calib = np.abs(_safe_predict(base_model, X_calib) - y_calib)
    sum_scores   = scores_calib.sum()

    with torch.no_grad():
        feat_test = torch.tensor([sum_scores], dtype=torch.float32).to(device)
        alpha_val = alpha_net(feat_test).item()

    denom = alpha_val * (n_calib + 1) - 1
    if denom <= 0:
        q = np.quantile(scores_calib, 1 - alpha)
        half_width = q
        print(f"  [Warning] α̃ too small; fallback q={q:.4f}")
    else:
        half_width = sum_scores / denom

    y_pred_test = _safe_predict(base_model, Xte)
    ymin = y_pred_test - half_width
    ymax = y_pred_test + half_width

    # =========================================================
    # 6. Metrics
    # =========================================================
    is_covered = ((yte >= ymin) & (yte <= ymax)).astype(int)
    coverage   = is_covered.mean()
    avg_width  = np.mean(ymax - ymin)
    rmse       = np.sqrt(mean_squared_error(yte, y_pred_test))

    total_time = time.time() - t_start_total

    print(f"\n{'='*55}")
    print(f"  ALPHANET CONFORMAL ({model_name})")
    print(f"{'='*55}")
    print(f"  Learned α̃     : {alpha_val:.4f}")
    print(f"  Half-width (r) : {half_width:.4f}")
    print(f"  Coverage       : {coverage*100:.3f}%")
    print(f"  Avg Width      : {avg_width:.4f}")
    print(f"  RMSE           : {rmse:.4f}")
    print(f"  Total time     : {_fmt_time(total_time)}")
    print(f"    ├─ Precompute: {_fmt_time(elapsed_precompute)}")
    print(f"    └─ Training  : {_fmt_time(train_time)}")
    print(f"{'='*55}")

    # =========================================================
    # 7. Summary & Values
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy":       "AlphaNet Conformal",
        "Coverage":       coverage,
        "Width":          avg_width,
        "RMSE":           rmse,
        "Alpha_nominal":  alpha,
        "Alpha_learned":  alpha_val,
        "Lambda_reg":     lambda_reg,
        "Total_time_sec": round(total_time, 2),
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(yte)),
        "y_true":       yte,
        "y_pred":       y_pred_test,
        "ymin":         ymin,
        "ymax":         ymax,
        "width":        ymax - ymin,
        "is_covered":   is_covered,
    })

    # =========================================================
    # 8. Plotting (SAVE ONLY)
    # =========================================================
    print(f"  [Step 8/9] Generating plots...")
    idx_arr = np.arange(len(yte))

    fig_pi, ax_pi = plt.subplots(figsize=(10, 4))
    ax_pi.scatter(idx_arr, yte, color="blue", s=10, alpha=0.7, label="True")
    ax_pi.fill_between(idx_arr, ymin, ymax, color="gray", alpha=0.5,
                       label=f"AlphaNet Interval (α̃={alpha_val:.3f})")
    ax_pi.plot(idx_arr, y_pred_test, color="red", lw=1, label="Predicted mean")
    ax_pi.set_title(f"AlphaNet Conformal ({model_name})")
    ax_pi.set_xlabel("Sample Number")
    ax_pi.set_ylabel("WQI")
    ax_pi.legend(loc="upper left")
    plt.tight_layout()

    buf_pi = io.BytesIO()
    fig_pi.savefig(buf_pi, format="png")
    buf_pi.seek(0)
    plt.close(fig_pi)

    arr_losses = np.array(history["losses"])
    arr_sizes  = np.array(history["sizes"])
    arr_alphas = np.array(history["alphas"])
    epochs_arr = np.arange(1, num_epochs + 1)

    fig_tc, axs = plt.subplots(1, 3, figsize=(14, 4))
    for ax, data, ylabel, title in zip(
        axs,
        [arr_losses, arr_sizes, arr_alphas],
        ["Loss", "Mean Interval Size", r"Mean $\tilde{\alpha}$"],
        ["Training Loss", "Interval Size", r"Learned $\tilde{\alpha}$"],
    ):
        m = data.mean(axis=0)
        s = data.std(axis=0)
        ax.plot(epochs_arr, m, color="#0077bb")
        ax.fill_between(epochs_arr, m - s, m + s, color="#0077bb", alpha=0.25)
        ax.set_xlabel("Epoch")
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.grid(True, linewidth=0.5)
    plt.tight_layout()

    buf_tc = io.BytesIO()
    fig_tc.savefig(buf_tc, format="png")
    buf_tc.seek(0)
    plt.close(fig_tc)

    # =========================================================
    # 9. Excel Export
    # =========================================================
    if excel_file_path:
        print(f"  [Step 9/9] Saving to Excel...")
        try:
            wb = load_workbook(excel_file_path)
        except FileNotFoundError:
            from openpyxl import Workbook
            wb = Workbook()
            wb.remove(wb.active)

        def _unique_sheet(wb, name):
            base, i = name, 1
            while name in wb.sheetnames:
                name = f"{base}_{i}"; i += 1
            return name

        sn = _unique_sheet(wb, "AlphaNet_PGBM_Summary")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        img_pi = Image(buf_pi)
        sn = _unique_sheet(wb, "AlphaNet_PGBM_Plot_PI")
        ws = wb.create_sheet(sn)
        ws.add_image(img_pi, "A1")

        img_tc = Image(buf_tc)
        sn = _unique_sheet(wb, "AlphaNet_PGBM_Plot_Train")
        ws = wb.create_sheet(sn)
        ws.add_image(img_tc, "A1")

        sn = _unique_sheet(wb, "AlphaNet_PGBM_Values")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)
        print(f"  [Step 9/9] Saved!")

    print(f"\n  ✅ AlphaNet PGBM complete in {_fmt_time(total_time)}")
    return summary_df

In [ ]:
conformal_predictions_AlphaNet_PGBM(
    model_class=PGBMWrapper,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="PGBM",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/PGBM.xlsx",
    alpha=0.05,
)

# **Conformal Predictions with TabNet**

In [ ]:
best_params = get_best_model_params(best_scores_autosampler, 'TabNet')
print(best_params)

In [ ]:
class validate:
    @staticmethod
    def coverage(int_pred, y_test):
        y_arr = np.array(y_test)
        return {strat_name: np.mean((y_arr >= int_pred[strat_name][:, 0]) & (y_arr <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred):
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        y_arr = np.array(y_test)
        return {strat_name: np.sqrt(mean_squared_error(y_arr, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = validate.width(int_pred)
        coverages = validate.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}
    @staticmethod
    def cond_coverage(int_pred, y_test, num_bins=10):
        y_arr = np.array(y_test)
        cond_coverages = {}
        for strat_name in int_pred:
            widths = int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]
            bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
            digitized_widths = np.digitize(widths, bin_edges)
            strategy_cond_coverage = []
            for bin_num in range(1, num_bins + 1):
                indices_in_bin = np.where(digitized_widths == bin_num)[0]
                if len(indices_in_bin) > 0:
                    bin_coverage = np.mean((y_arr[indices_in_bin] >= int_pred[strat_name][indices_in_bin, 0]) &
                                           (y_arr[indices_in_bin] <= int_pred[strat_name][indices_in_bin, 1]))
                    strategy_cond_coverage.append(bin_coverage)
                else:
                    strategy_cond_coverage.append(np.nan)
            cond_coverages[strat_name] = strategy_cond_coverage
        return cond_coverages
class visualize:
    @staticmethod
    def goodness(y_true, y_pred, y_pred_low, y_pred_up, coverage, width, rmse, cwc, ax=None, title="Goodness Plot"):
        if ax is None:
            fig, ax = plt.subplots()
        y_true_np = np.array(y_true).ravel()
        inside_interval = (y_true_np >= y_pred_low) & (y_true_np <= y_pred_up)
        outside_interval = ~inside_interval
        ax.scatter(y_true_np[inside_interval], y_pred[inside_interval], color='green', s=10, label='Inside Interval')
        ax.scatter(y_true_np[outside_interval], y_pred[outside_interval], color='orange', s=10, label='Outside Interval')
        ax.scatter(y_true_np, y_true_np, color='blue', marker='x', s=30, linewidths=0.7, label='Ground Truth Values')
        ax.vlines(y_true_np, y_pred_low, y_pred_up, color='gray', alpha=0.5, label='Prediction Intervals')
        ax.plot([min(y_true_np), max(y_true_np)], [min(y_true_np), max(y_true_np)],
                 linestyle='--', color='blue', label='Ideal Prediction Line')
        ax.set_xlabel('Ground Truth')
        ax.set_ylabel('Predictions')
        ax.set_title(f'{title}\nCoverage: {coverage*100:.2f}%, Width: {width:.2f}, RMSE: {rmse:.2f}, CWC: {cwc:.2f}')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def width_size_occurrence(int_pred, train_intervals, num_bins=10, ax=None, x_lim=None, title="Width Size Occurrence"):
        if ax is None:
            fig, ax = plt.subplots()
        widths_test = np.abs(int_pred[:, 1] - int_pred[:, 0])
        widths_train = np.abs(train_intervals[:, 1] - train_intervals[:, 0])
        ax.hist(widths_test, bins=num_bins, alpha=0.6, label='Test Interval Widths', color='red')
        ax.hist(widths_train, bins=num_bins, alpha=0.4, label='Train Interval Widths', color='blue')
        if x_lim is not None:
            ax.set_xlim(x_lim)
        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Occurrence (Frequency)')
        ax.set_title(f'{title} - Interval Width Occurrence')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def coverage_by_width(y_test, int_pred, miscoverage, cond_coverages, num_bins=10, ax=None, title="Coverage vs Width"):
        if ax is None:
            fig, ax = plt.subplots()
        widths = int_pred[:, 1] - int_pred[:, 0]
        bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
        bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
        bin_width = bin_edges[1] - bin_edges[0]
        ax.bar(bin_centers, cond_coverages, width=bin_width, color='blue', alpha=0.7, edgecolor='black', linewidth=0.8, label='Conditional Coverage')
        ax.axhline(1 - miscoverage, color='red', linestyle='--', label=f'Nominal Coverage ({(1 - miscoverage)*100:.0f}%)')
        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Conditional Coverage')
        ax.set_title(f'{title} - Coverage vs Interval Width')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

class TabNetRegressorCP(TabNetRegressor):
    def fit(self, X, y, *args, **kwargs):
        y = np.asarray(y)
        if y.ndim == 1:
            y = y.reshape(-1, 1)
        return super().fit(X, y, *args, **kwargs)

    def predict(self, X, *args, **kwargs):
        return super().predict(X).flatten()

In [71]:
def conformal_predictions_NEXCP_tabnet(
    X_train,
    y_train,
    X_test,
    y_test,
    best_params,
    model_name="TabNet",
    excel_file_path=None,
    alpha=0.1,
    decay=0.99,
    n_folds=5,
    n_bootstrap=50,
):
    warnings.filterwarnings("ignore")

    SEED = 123
    rng = np.random.default_rng(SEED)
    np.random.seed(SEED)

    if "verbose" in best_params:
        best_params = dict(best_params)
        best_params.pop("verbose", None)

    model_class = TabNetRegressorCP

    strategies = {
        "NEXCP-Split": "NexCP Split",
        "NEXCP-Full": "NexCP Full",
        "NEXCP-J+aB": "NexCP Jackknife+ aB",
        "NEXCP-CV+": "NexCP CV+",
    }

    y_pred, int_pred = {}, {}

    y_train_np = np.asarray(y_train).ravel()
    y_test_np = np.asarray(y_test).ravel()

    # =========================
    # NexCP – Split (Weighted)
    # =========================
    model = model_class(**best_params)
    model.fit(X_train, y_train_np)

    yhat_train = model.predict(X_train)
    yhat_test = model.predict(X_test)

    residuals = np.abs(y_train_np - yhat_train)
    weights = decay ** np.arange(len(residuals) - 1, -1, -1)
    q = weighted_quantile(residuals, weights, 1 - alpha)

    y_pred["NEXCP-Split"] = yhat_test
    int_pred["NEXCP-Split"] = np.c_[yhat_test - q, yhat_test + q]

    # =========================
    # NexCP – Full
    # =========================
    model = model_class(**best_params)
    model.fit(X_train, y_train_np)

    yhat_train = model.predict(X_train)
    yhat_test = model.predict(X_test)

    q = np.quantile(np.abs(y_train_np - yhat_train), 1 - alpha)

    y_pred["NEXCP-Full"] = yhat_test
    int_pred["NEXCP-Full"] = np.c_[yhat_test - q, yhat_test + q]

    # =========================
    # NexCP – Jackknife+ aB
    # =========================
    lowers, uppers, preds = [], [], []

    for _ in range(n_bootstrap):
        idx = rng.choice(len(X_train), len(X_train), replace=True)

        model = model_class(**best_params)
        model.fit(X_train[idx], y_train_np[idx])

        yhat_boot_train = model.predict(X_train[idx])
        yhat_test = model.predict(X_test)

        q = np.quantile(
            np.abs(y_train_np[idx] - yhat_boot_train),
            1 - alpha,
        )

        lowers.append(yhat_test - q)
        uppers.append(yhat_test + q)
        preds.append(yhat_test)

    y_pred["NEXCP-J+aB"] = np.mean(preds, axis=0)
    int_pred["NEXCP-J+aB"] = np.c_[np.min(lowers, axis=0), np.max(uppers, axis=0)]

    # =========================
    # NexCP – CV+
    # =========================
    kf = KFold(n_splits=n_folds, shuffle=True, random_state=SEED)

    lowers, uppers, preds = [], [], []

    for tr, cal in kf.split(X_train):
        model = model_class(**best_params)
        model.fit(X_train[tr], y_train_np[tr])

        y_cal = model.predict(X_train[cal])
        q = np.quantile(np.abs(y_train_np[cal] - y_cal), 1 - alpha)

        yhat_test = model.predict(X_test)

        lowers.append(yhat_test - q)
        uppers.append(yhat_test + q)
        preds.append(yhat_test)

    y_pred["NEXCP-CV+"] = np.mean(preds, axis=0)
    int_pred["NEXCP-CV+"] = np.c_[np.mean(lowers, axis=0), np.mean(uppers, axis=0)]

    # =========================
    # Metrics
    # =========================
    def coverage(y, l, u):
        return np.mean((y >= l) & (y <= u))

    def width(l, u):
        return np.mean(u - l)

    def cwc(l, u, y, alpha):
        cov = coverage(y, l, u)
        w = width(l, u)
        penalty = np.exp(-50 * (cov - (1 - alpha)))
        return w * (1 + penalty if cov < (1 - alpha) else 1)

    summary = []

    print("\n===== NEXCP TABNET RESULTS =====")
    for s in strategies:
        cov = coverage(y_test_np, int_pred[s][:, 0], int_pred[s][:, 1])
        wid = width(int_pred[s][:, 0], int_pred[s][:, 1])
        rmse = np.sqrt(mean_squared_error(y_test_np, y_pred[s]))
        cwc_val = cwc(int_pred[s][:, 0], int_pred[s][:, 1], y_test_np, alpha)

        summary.append([strategies[s], cov, wid, rmse, cwc_val])
        print(f"{strategies[s]} | Coverage: {cov*100:.3f}% | Width: {wid:.3f}")

    summary_df = pd.DataFrame(
        summary,
        columns=["Strategy", "Coverage", "Width", "RMSE", "CWC"],
    )

    # =========================
    # Plot + Excel Export
    # =========================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        sheet = "NEXCP_TabNet_Summary"
        base = sheet
        i = 1
        while sheet in wb.sheetnames:
            sheet = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        for s in strategies:
            fig, ax = plt.subplots(figsize=(10, 4))
            idx = np.arange(len(y_test_np))

            ax.scatter(idx, y_test_np, s=10, alpha=0.7, label="True")
            ax.fill_between(idx, int_pred[s][:, 0], int_pred[s][:, 1], alpha=0.4)
            ax.plot(idx, y_pred[s], linewidth=1, label="Pred")

            ax.set_title(f"{strategies[s]} ({model_name})")
            ax.legend()

            buf = io.BytesIO()
            fig.savefig(buf, format="png")
            buf.seek(0)
            plt.close(fig)

            img = Image(buf)
            ps = f"NEXCP_TabNet_{s}"
            base = ps
            i = 1
            while ps in wb.sheetnames:
                ps = f"{base}_{i}"
                i += 1

            ws = wb.create_sheet(ps)
            ws.add_image(img, "A1")

        wb.save(excel_file_path)

    return summary_df


conformal_predictions_NEXCP_tabnet(
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    best_params=best_params,
    model_name="TabNet",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/TabNet.xlsx",
    alpha=0.1,
    decay=0.99,
    n_folds=5,
    n_bootstrap=50
)

Streaming output truncated to the last 5000 lines.
epoch 6  | loss: 35682.50781|  0:00:00s
epoch 7  | loss: 34998.63281|  0:00:00s
epoch 8  | loss: 34208.48438|  0:00:00s
epoch 9  | loss: 33364.10156|  0:00:00s
epoch 10 | loss: 32381.77344|  0:00:01s
epoch 11 | loss: 31292.82812|  0:00:01s
epoch 12 | loss: 30363.90234|  0:00:01s
epoch 13 | loss: 29251.63281|  0:00:01s
epoch 14 | loss: 28275.96289|  0:00:01s
epoch 15 | loss: 27434.82227|  0:00:01s
epoch 16 | loss: 26130.625|  0:00:01s
epoch 17 | loss: 25050.64062|  0:00:01s
epoch 18 | loss: 23535.68359|  0:00:01s
epoch 19 | loss: 22123.86719|  0:00:01s
epoch 20 | loss: 20933.21484|  0:00:02s
epoch 21 | loss: 19371.79102|  0:00:02s
epoch 22 | loss: 17673.9375|  0:00:02s
epoch 23 | loss: 16543.54688|  0:00:02s
epoch 24 | loss: 14976.77539|  0:00:02s
epoch 25 | loss: 13763.11426|  0:00:02s
epoch 26 | loss: 12348.45312|  0:00:02s
epoch 27 | loss: 10631.77148|  0:00:02s
epoch 28 | loss: 9362.57129|  0:00:02s
epoch 29 | loss: 7824.05518|  0:00:02s
epoch 30 | loss: 6328.86719|  0:00:03s
epoch 31 | loss: 5053.71826|  0:00:03s
epoch 32 | loss: 4049.92236|  0:00:03s
epoch 33 | loss: 2978.84473|  0:00:03s
epoch 34 | loss: 2157.58179|  0:00:03s
epoch 35 | loss: 1585.9259|  0:00:03s
epoch 36 | loss: 1131.39124|  0:00:03s
epoch 37 | loss: 960.31757|  0:00:03s
epoch 38 | loss: 745.61615|  0:00:03s
epoch 39 | loss: 637.76532|  0:00:03s
epoch 40 | loss: 547.1969|  0:00:03s
epoch 41 | loss: 489.52405|  0:00:03s
epoch 42 | loss: 373.84186|  0:00:03s
epoch 43 | loss: 242.25459|  0:00:03s
epoch 44 | loss: 182.62222|  0:00:04s
epoch 45 | loss: 130.11636|  0:00:04s
epoch 46 | loss: 167.37523|  0:00:04s
epoch 47 | loss: 198.92926|  0:00:04s
epoch 48 | loss: 188.66393|  0:00:04s
epoch 49 | loss: 138.91109|  0:00:04s
epoch 50 | loss: 80.81947|  0:00:04s
epoch 51 | loss: 112.37303|  0:00:04s
epoch 52 | loss: 153.81932|  0:00:04s
epoch 53 | loss: 106.48225|  0:00:04s
epoch 54 | loss: 75.0413 |  0:00:04s
epoch 55 | loss: 89.81609|  0:00:04s
epoch 56 | loss: 56.78022|  0:00:04s
epoch 57 | loss: 56.50772|  0:00:04s
epoch 58 | loss: 36.30804|  0:00:04s
epoch 59 | loss: 35.12819|  0:00:05s
epoch 60 | loss: 33.27766|  0:00:05s
epoch 61 | loss: 28.44224|  0:00:05s
epoch 62 | loss: 42.07167|  0:00:05s
epoch 63 | loss: 29.82765|  0:00:05s
epoch 64 | loss: 25.05031|  0:00:05s
epoch 65 | loss: 34.76841|  0:00:05s
epoch 66 | loss: 24.42224|  0:00:05s
epoch 67 | loss: 22.32927|  0:00:05s
epoch 68 | loss: 23.17437|  0:00:05s
epoch 69 | loss: 19.92222|  0:00:05s
epoch 70 | loss: 15.86674|  0:00:05s
epoch 71 | loss: 16.02032|  0:00:05s
epoch 72 | loss: 12.2976 |  0:00:05s
epoch 73 | loss: 12.49335|  0:00:06s
epoch 74 | loss: 12.07179|  0:00:06s
epoch 75 | loss: 10.51554|  0:00:06s
epoch 76 | loss: 11.96705|  0:00:06s
epoch 77 | loss: 10.09334|  0:00:06s
epoch 78 | loss: 8.49174 |  0:00:06s
epoch 79 | loss: 9.25382 |  0:00:06s
epoch 80 | loss: 10.43505|  0:00:06s
epoch 81 | loss: 6.01309 |  0:00:06s
epoch 82 | loss: 10.5925 |  0:00:06s
epoch 83 | loss: 10.74887|  0:00:06s
epoch 84 | loss: 7.57427 |  0:00:06s
epoch 85 | loss: 9.50403 |  0:00:06s
epoch 86 | loss: 7.50543 |  0:00:06s
epoch 87 | loss: 4.14135 |  0:00:06s
epoch 88 | loss: 7.00619 |  0:00:07s
epoch 89 | loss: 4.51527 |  0:00:07s
epoch 90 | loss: 6.23295 |  0:00:07s
epoch 91 | loss: 5.20356 |  0:00:07s
epoch 92 | loss: 6.76392 |  0:00:07s
epoch 93 | loss: 5.8237  |  0:00:07s
epoch 94 | loss: 3.41754 |  0:00:07s
epoch 95 | loss: 5.78065 |  0:00:07s
epoch 96 | loss: 6.48587 |  0:00:07s
epoch 97 | loss: 4.66845 |  0:00:07s
epoch 98 | loss: 3.8968  |  0:00:07s
epoch 99 | loss: 4.13786 |  0:00:07s
epoch 0  | loss: 42114.78906|  0:00:00s
epoch 1  | loss: 41052.33203|  0:00:00s
epoch 2  | loss: 40187.5 |  0:00:00s
epoch 3  | loss: 39080.17578|  0:00:00s
epoch 4  | loss: 38224.64453|  0:00:00s
epoch 5  | loss: 37267.35547|  0:00:00s
epoch 6  | loss: 36410.75781|  0:00:00s
epoch 7  | loss: 35529.47656|  0:00:00s
epoch 8  | loss: 34647.5 |  0:00:00s
epoch 9  | loss: 33537.94922|  0:00:00s
epoch 10 | loss: 32416.60938|  0:00:00s
epoch 11 | loss: 31477.91016|  0:00:00s
epoch 12 | loss: 30542.32617|  0:00:00s
epoch 13 | loss: 29333.42383|  0:00:00s
epoch 14 | loss: 28157.31836|  0:00:01s
epoch 15 | loss: 26546.30273|  0:00:01s
epoch 16 | loss: 25430.40625|  0:00:01s
epoch 17 | loss: 24350.50195|  0:00:01s
epoch 18 | loss: 22768.91211|  0:00:01s
epoch 19 | loss: 21328.57812|  0:00:01s
epoch 20 | loss: 19741.28125|  0:00:01s
epoch 21 | loss: 18281.4668|  0:00:01s
epoch 22 | loss: 16510.96875|  0:00:01s
epoch 23 | loss: 14872.16895|  0:00:01s
epoch 24 | loss: 13195.05176|  0:00:01s
epoch 25 | loss: 11590.56738|  0:00:01s
epoch 26 | loss: 10030.66797|  0:00:01s
epoch 27 | loss: 8580.98438|  0:00:01s
epoch 28 | loss: 7105.19141|  0:00:01s
epoch 29 | loss: 5784.71387|  0:00:02s
epoch 30 | loss: 4554.45166|  0:00:02s
epoch 31 | loss: 3454.55688|  0:00:02s
epoch 32 | loss: 2476.09082|  0:00:02s
epoch 33 | loss: 1631.01501|  0:00:02s
epoch 34 | loss: 1061.9209|  0:00:02s
epoch 35 | loss: 648.87183|  0:00:02s
epoch 36 | loss: 459.45886|  0:00:02s
epoch 37 | loss: 454.76932|  0:00:02s
epoch 38 | loss: 542.67664|  0:00:02s
epoch 39 | loss: 694.72247|  0:00:02s
epoch 40 | loss: 761.76166|  0:00:02s
epoch 41 | loss: 779.46185|  0:00:02s
epoch 42 | loss: 745.4776|  0:00:02s
epoch 43 | loss: 553.55585|  0:00:02s
epoch 44 | loss: 439.69406|  0:00:03s
epoch 45 | loss: 329.64557|  0:00:03s
epoch 46 | loss: 227.97055|  0:00:03s
epoch 47 | loss: 237.44852|  0:00:03s
epoch 48 | loss: 229.85979|  0:00:03s
epoch 49 | loss: 250.06761|  0:00:03s
epoch 50 | loss: 263.84985|  0:00:03s
epoch 51 | loss: 258.3963|  0:00:03s
epoch 52 | loss: 184.92566|  0:00:03s
epoch 53 | loss: 160.67012|  0:00:03s
epoch 54 | loss: 114.47063|  0:00:03s
epoch 55 | loss: 99.78564|  0:00:03s
epoch 56 | loss: 85.8596 |  0:00:03s
epoch 57 | loss: 88.23495|  0:00:03s
epoch 58 | loss: 77.48322|  0:00:03s
epoch 59 | loss: 49.22202|  0:00:04s
epoch 60 | loss: 59.28785|  0:00:04s
epoch 61 | loss: 111.80929|  0:00:04s
epoch 62 | loss: 150.45085|  0:00:04s
epoch 63 | loss: 87.31129|  0:00:04s
epoch 64 | loss: 45.11099|  0:00:04s
epoch 65 | loss: 49.11759|  0:00:04s
epoch 66 | loss: 57.6524 |  0:00:04s
epoch 67 | loss: 53.56729|  0:00:04s
epoch 68 | loss: 33.99353|  0:00:04s
epoch 69 | loss: 33.57215|  0:00:04s
epoch 70 | loss: 29.99078|  0:00:04s
epoch 71 | loss: 29.83467|  0:00:04s
epoch 72 | loss: 23.99724|  0:00:04s
epoch 73 | loss: 18.03942|  0:00:04s
epoch 74 | loss: 20.3406 |  0:00:05s
epoch 75 | loss: 20.68952|  0:00:05s
epoch 76 | loss: 14.16345|  0:00:05s
epoch 77 | loss: 23.12515|  0:00:05s
epoch 78 | loss: 21.53023|  0:00:05s
epoch 79 | loss: 21.37951|  0:00:05s
epoch 80 | loss: 13.35589|  0:00:05s
epoch 81 | loss: 21.46357|  0:00:05s
epoch 82 | loss: 20.09426|  0:00:05s
epoch 83 | loss: 19.31335|  0:00:05s
epoch 84 | loss: 17.63613|  0:00:05s
epoch 85 | loss: 10.6193 |  0:00:06s
epoch 86 | loss: 15.49277|  0:00:06s
epoch 87 | loss: 11.29113|  0:00:06s
epoch 88 | loss: 16.17626|  0:00:06s
epoch 89 | loss: 11.78647|  0:00:06s
epoch 90 | loss: 12.97337|  0:00:06s
epoch 91 | loss: 13.45171|  0:00:06s
epoch 92 | loss: 8.12454 |  0:00:06s
epoch 93 | loss: 15.74455|  0:00:06s
epoch 94 | loss: 13.08222|  0:00:06s
epoch 95 | loss: 13.62193|  0:00:07s
epoch 96 | loss: 14.38066|  0:00:07s
epoch 97 | loss: 9.23332 |  0:00:07s
epoch 98 | loss: 15.63325|  0:00:07s
epoch 99 | loss: 10.30111|  0:00:07s
epoch 0  | loss: 35833.68359|  0:00:00s
epoch 1  | loss: 35001.18359|  0:00:00s
epoch 2  | loss: 34061.67578|  0:00:00s
epoch 3  | loss: 33262.85547|  0:00:00s
epoch 4  | loss: 32544.09961|  0:00:00s
epoch 5  | loss: 31623.20703|  0:00:00s
epoch 6  | loss: 30844.84961|  0:00:00s
epoch 7  | loss: 30172.77344|  0:00:00s
epoch 8  | loss: 29230.92773|  0:00:00s
epoch 9  | loss: 28342.58789|  0:00:00s
epoch 10 | loss: 27384.33789|  0:00:01s
epoch 11 | loss: 26386.49219|  0:00:01s
epoch 12 | loss: 25347.87109|  0:00:01s
epoch 13 | loss: 24177.68555|  0:00:01s
epoch 14 | loss: 23050.19336|  0:00:01s
epoch 15 | loss: 21884.50586|  0:00:01s
epoch 16 | loss: 20601.71484|  0:00:01s
epoch 17 | loss: 19523.875|  0:00:01s
epoch 18 | loss: 18326.14648|  0:00:01s
epoch 19 | loss: 16975.51953|  0:00:01s
epoch 20 | loss: 15694.40625|  0:00:02s
epoch 21 | loss: 14305.01953|  0:00:02s
epoch 22 | loss: 13001.67969|  0:00:02s
epoch 23 | loss: 11606.61621|  0:00:02s
epoch 24 | loss: 10254.05469|  0:00:02s
epoch 25 | loss: 8869.4541|  0:00:02s
epoch 26 | loss: 7630.48145|  0:00:02s
epoch 27 | loss: 6417.52148|  0:00:02s
epoch 28 | loss: 5188.75537|  0:00:02s
epoch 29 | loss: 4129.02002|  0:00:02s
epoch 30 | loss: 3279.73975|  0:00:02s
epoch 31 | loss: 2605.60474|  0:00:02s
epoch 32 | loss: 2101.74634|  0:00:02s
epoch 33 | loss: 1686.73535|  0:00:02s
epoch 34 | loss: 1176.56421|  0:00:03s
epoch 35 | loss: 863.13922|  0:00:03s
epoch 36 | loss: 794.11493|  0:00:03s
epoch 37 | loss: 637.3692|  0:00:03s
epoch 38 | loss: 545.29004|  0:00:03s
epoch 39 | loss: 462.93933|  0:00:03s
epoch 40 | loss: 426.92252|  0:00:03s
epoch 41 | loss: 369.88309|  0:00:03s
epoch 42 | loss: 278.86819|  0:00:03s
epoch 43 | loss: 224.22342|  0:00:03s
epoch 44 | loss: 200.47218|  0:00:03s
epoch 45 | loss: 169.48364|  0:00:03s
epoch 46 | loss: 155.44083|  0:00:03s
epoch 47 | loss: 169.6479|  0:00:03s
epoch 48 | loss: 112.64426|  0:00:04s
epoch 49 | loss: 68.73276|  0:00:04s
epoch 50 | loss: 55.73302|  0:00:04s
epoch 51 | loss: 67.43163|  0:00:04s
epoch 52 | loss: 61.83074|  0:00:04s
epoch 53 | loss: 52.67083|  0:00:04s
epoch 54 | loss: 37.23195|  0:00:04s
epoch 55 | loss: 38.87005|  0:00:04s
epoch 56 | loss: 26.8137 |  0:00:04s
epoch 57 | loss: 58.56218|  0:00:04s
epoch 58 | loss: 50.04332|  0:00:04s
epoch 59 | loss: 29.95408|  0:00:04s
epoch 60 | loss: 24.88611|  0:00:04s
epoch 61 | loss: 24.13139|  0:00:04s
epoch 62 | loss: 31.16686|  0:00:04s
epoch 63 | loss: 37.34609|  0:00:05s
epoch 64 | loss: 28.82909|  0:00:05s
epoch 65 | loss: 28.04626|  0:00:05s
epoch 66 | loss: 20.07989|  0:00:05s
epoch 67 | loss: 19.22174|  0:00:05s
epoch 68 | loss: 18.67045|  0:00:05s
epoch 69 | loss: 27.58648|  0:00:05s
epoch 70 | loss: 19.91134|  0:00:05s
epoch 71 | loss: 20.01982|  0:00:05s
epoch 72 | loss: 21.53913|  0:00:05s
epoch 73 | loss: 19.39581|  0:00:05s
epoch 74 | loss: 13.87271|  0:00:05s
epoch 75 | loss: 12.01345|  0:00:05s
epoch 76 | loss: 12.90957|  0:00:05s
epoch 77 | loss: 12.71229|  0:00:06s
epoch 78 | loss: 8.913   |  0:00:06s
epoch 79 | loss: 9.4278  |  0:00:06s
epoch 80 | loss: 9.09579 |  0:00:06s
epoch 81 | loss: 8.59662 |  0:00:06s
epoch 82 | loss: 8.82115 |  0:00:06s
epoch 83 | loss: 9.24369 |  0:00:06s
epoch 84 | loss: 5.5624  |  0:00:06s
epoch 85 | loss: 7.08665 |  0:00:06s
epoch 86 | loss: 6.60122 |  0:00:06s
epoch 87 | loss: 5.98167 |  0:00:06s
epoch 88 | loss: 7.37225 |  0:00:06s
epoch 89 | loss: 9.52434 |  0:00:06s
epoch 90 | loss: 5.73378 |  0:00:06s
epoch 91 | loss: 5.48952 |  0:00:06s
epoch 92 | loss: 5.24542 |  0:00:07s
epoch 93 | loss: 3.42898 |  0:00:07s
epoch 94 | loss: 5.64794 |  0:00:07s
epoch 95 | loss: 6.70898 |  0:00:07s
epoch 96 | loss: 4.94581 |  0:00:07s
epoch 97 | loss: 3.37112 |  0:00:07s
epoch 98 | loss: 6.48241 |  0:00:07s
epoch 99 | loss: 4.4137  |  0:00:07s
epoch 0  | loss: 37240.59766|  0:00:00s
epoch 1  | loss: 36310.5 |  0:00:00s
epoch 2  | loss: 35390.30859|  0:00:00s
epoch 3  | loss: 34599.46875|  0:00:00s
epoch 4  | loss: 33724.60547|  0:00:00s
epoch 5  | loss: 32787.44531|  0:00:00s
epoch 6  | loss: 32011.81055|  0:00:00s
epoch 7  | loss: 30889.00781|  0:00:00s
epoch 8  | loss: 30103.82227|  0:00:00s
epoch 9  | loss: 28964.07617|  0:00:00s
epoch 10 | loss: 28025.5625|  0:00:00s
epoch 11 | loss: 27358.16797|  0:00:00s
epoch 12 | loss: 26133.7207|  0:00:00s
epoch 13 | loss: 25051.46289|  0:00:00s
epoch 14 | loss: 23942.63867|  0:00:01s
epoch 15 | loss: 22523.90625|  0:00:01s
epoch 16 | loss: 21291.39648|  0:00:01s
epoch 17 | loss: 19929.08789|  0:00:01s
epoch 18 | loss: 19021.51758|  0:00:01s
epoch 19 | loss: 17657.91016|  0:00:01s
epoch 20 | loss: 16028.75488|  0:00:01s
epoch 21 | loss: 14805.54492|  0:00:01s
epoch 22 | loss: 13194.2627|  0:00:01s
epoch 23 | loss: 11778.3418|  0:00:01s
epoch 24 | loss: 10265.08887|  0:00:01s
epoch 25 | loss: 8865.08984|  0:00:01s
epoch 26 | loss: 7596.05322|  0:00:01s
epoch 27 | loss: 6414.81982|  0:00:01s
epoch 28 | loss: 5209.88965|  0:00:02s
epoch 29 | loss: 4088.15186|  0:00:02s
epoch 30 | loss: 3207.63843|  0:00:02s
epoch 31 | loss: 2360.16138|  0:00:02s
epoch 32 | loss: 1687.46179|  0:00:02s
epoch 33 | loss: 1180.22241|  0:00:02s
epoch 34 | loss: 814.72723|  0:00:02s
epoch 35 | loss: 591.23016|  0:00:02s
epoch 36 | loss: 476.02676|  0:00:02s
epoch 37 | loss: 464.28171|  0:00:02s
epoch 38 | loss: 482.93234|  0:00:02s
epoch 39 | loss: 452.5838|  0:00:02s
epoch 40 | loss: 392.24564|  0:00:02s
epoch 41 | loss: 309.45297|  0:00:02s
epoch 42 | loss: 248.25774|  0:00:02s
epoch 43 | loss: 199.05548|  0:00:03s
epoch 44 | loss: 199.46573|  0:00:03s
epoch 45 | loss: 190.72281|  0:00:03s
epoch 46 | loss: 311.10825|  0:00:03s
epoch 47 | loss: 224.1338|  0:00:03s
epoch 48 | loss: 227.64003|  0:00:03s
epoch 49 | loss: 225.49187|  0:00:03s
epoch 50 | loss: 164.06201|  0:00:03s
epoch 51 | loss: 114.80592|  0:00:03s
epoch 52 | loss: 81.93616|  0:00:03s
epoch 53 | loss: 107.23246|  0:00:03s
epoch 54 | loss: 71.59216|  0:00:03s
epoch 55 | loss: 72.63158|  0:00:03s
epoch 56 | loss: 60.44513|  0:00:03s
epoch 57 | loss: 44.62074|  0:00:04s
epoch 58 | loss: 48.18411|  0:00:04s
epoch 59 | loss: 39.97523|  0:00:04s
epoch 60 | loss: 32.83397|  0:00:04s
epoch 61 | loss: 59.24071|  0:00:04s
epoch 62 | loss: 111.99747|  0:00:04s
epoch 63 | loss: 128.46402|  0:00:04s
epoch 64 | loss: 97.82837|  0:00:04s
epoch 65 | loss: 62.91617|  0:00:04s
epoch 66 | loss: 53.53138|  0:00:04s
epoch 67 | loss: 35.39099|  0:00:04s
epoch 68 | loss: 22.43782|  0:00:05s
epoch 69 | loss: 30.57164|  0:00:05s
epoch 70 | loss: 25.16483|  0:00:05s
epoch 71 | loss: 30.90231|  0:00:05s
epoch 72 | loss: 23.24281|  0:00:05s
epoch 73 | loss: 22.14088|  0:00:05s
epoch 74 | loss: 19.37356|  0:00:05s
epoch 75 | loss: 23.34692|  0:00:05s
epoch 76 | loss: 24.59032|  0:00:05s
epoch 77 | loss: 27.0688 |  0:00:05s
epoch 78 | loss: 40.74441|  0:00:06s
epoch 79 | loss: 21.2579 |  0:00:06s
epoch 80 | loss: 26.09641|  0:00:06s
epoch 81 | loss: 36.89062|  0:00:06s
epoch 82 | loss: 18.71582|  0:00:06s
epoch 83 | loss: 21.09401|  0:00:06s
epoch 84 | loss: 27.69821|  0:00:06s
epoch 85 | loss: 13.29742|  0:00:06s
epoch 86 | loss: 17.47722|  0:00:06s
epoch 87 | loss: 19.707  |  0:00:06s
epoch 88 | loss: 10.85757|  0:00:07s
epoch 89 | loss: 13.15721|  0:00:07s
epoch 90 | loss: 11.42947|  0:00:07s
epoch 91 | loss: 7.3114  |  0:00:07s
epoch 92 | loss: 9.73291 |  0:00:07s
epoch 93 | loss: 7.02328 |  0:00:07s
epoch 94 | loss: 8.26916 |  0:00:07s
epoch 95 | loss: 6.02608 |  0:00:07s
epoch 96 | loss: 8.52905 |  0:00:07s
epoch 97 | loss: 7.06845 |  0:00:07s
epoch 98 | loss: 8.48418 |  0:00:07s
epoch 99 | loss: 9.46395 |  0:00:08s
epoch 0  | loss: 37227.25781|  0:00:00s
epoch 1  | loss: 36203.29297|  0:00:00s
epoch 2  | loss: 35422.59766|  0:00:00s
epoch 3  | loss: 34628.96484|  0:00:00s
epoch 4  | loss: 33799.14453|  0:00:00s
epoch 5  | loss: 32960.3125|  0:00:00s
epoch 6  | loss: 32386.91211|  0:00:00s
epoch 7  | loss: 31383.70117|  0:00:00s
epoch 8  | loss: 30500.86523|  0:00:00s
epoch 9  | loss: 29719.71484|  0:00:01s
epoch 10 | loss: 28891.37305|  0:00:01s
epoch 11 | loss: 28040.39648|  0:00:01s
epoch 12 | loss: 26910.49609|  0:00:01s
epoch 13 | loss: 25851.75391|  0:00:01s
epoch 14 | loss: 24547.23828|  0:00:01s
epoch 15 | loss: 23285.71484|  0:00:01s
epoch 16 | loss: 22190.60156|  0:00:01s
epoch 17 | loss: 20768.42773|  0:00:01s
epoch 18 | loss: 19496.26758|  0:00:01s
epoch 19 | loss: 17992.89258|  0:00:01s
epoch 20 | loss: 16628.23828|  0:00:01s
epoch 21 | loss: 15076.31152|  0:00:01s
epoch 22 | loss: 13546.1416|  0:00:01s
epoch 23 | loss: 12005.08105|  0:00:02s
epoch 24 | loss: 10494.55176|  0:00:02s
epoch 25 | loss: 9300.03906|  0:00:02s
epoch 26 | loss: 7873.56201|  0:00:02s
epoch 27 | loss: 6526.04736|  0:00:02s
epoch 28 | loss: 5251.87061|  0:00:02s
epoch 29 | loss: 4067.93555|  0:00:02s
epoch 30 | loss: 3043.63623|  0:00:02s
epoch 31 | loss: 2124.59595|  0:00:02s
epoch 32 | loss: 1354.51404|  0:00:02s
epoch 33 | loss: 785.83527|  0:00:02s
epoch 34 | loss: 414.80316|  0:00:02s
epoch 35 | loss: 246.82469|  0:00:02s
epoch 36 | loss: 455.27557|  0:00:03s
epoch 37 | loss: 554.09052|  0:00:03s
epoch 38 | loss: 790.11444|  0:00:03s
epoch 39 | loss: 879.44666|  0:00:03s
epoch 40 | loss: 877.87006|  0:00:03s
epoch 41 | loss: 710.06659|  0:00:03s
epoch 42 | loss: 527.01123|  0:00:03s
epoch 43 | loss: 369.60114|  0:00:03s
epoch 44 | loss: 261.86536|  0:00:03s
epoch 45 | loss: 133.5367|  0:00:03s
epoch 46 | loss: 108.34557|  0:00:03s
epoch 47 | loss: 108.18661|  0:00:03s
epoch 48 | loss: 107.71175|  0:00:03s
epoch 49 | loss: 97.27859|  0:00:03s
epoch 50 | loss: 85.33105|  0:00:04s
epoch 51 | loss: 71.44222|  0:00:04s
epoch 52 | loss: 60.63908|  0:00:04s
epoch 53 | loss: 44.79979|  0:00:04s
epoch 54 | loss: 65.47575|  0:00:04s
epoch 55 | loss: 58.08727|  0:00:04s
epoch 56 | loss: 48.08708|  0:00:04s
epoch 57 | loss: 35.51998|  0:00:04s
epoch 58 | loss: 40.96143|  0:00:04s
epoch 59 | loss: 30.67442|  0:00:04s
epoch 60 | loss: 35.2512 |  0:00:04s
epoch 61 | loss: 28.96512|  0:00:04s
epoch 62 | loss: 28.72396|  0:00:04s
epoch 63 | loss: 24.35656|  0:00:04s
epoch 64 | loss: 26.09037|  0:00:05s
epoch 65 | loss: 16.77497|  0:00:05s
epoch 66 | loss: 21.34521|  0:00:05s
epoch 67 | loss: 16.95273|  0:00:05s
epoch 68 | loss: 20.0185 |  0:00:05s
epoch 69 | loss: 15.49916|  0:00:05s
epoch 70 | loss: 11.73792|  0:00:05s
epoch 71 | loss: 19.61732|  0:00:05s
epoch 72 | loss: 12.78707|  0:00:05s
epoch 73 | loss: 21.04681|  0:00:05s
epoch 74 | loss: 14.76182|  0:00:05s
epoch 75 | loss: 17.89268|  0:00:05s
epoch 76 | loss: 16.67434|  0:00:05s
epoch 77 | loss: 21.53148|  0:00:05s
epoch 78 | loss: 35.92721|  0:00:05s
epoch 79 | loss: 42.15877|  0:00:06s
epoch 80 | loss: 17.50819|  0:00:06s
epoch 81 | loss: 19.20927|  0:00:06s
epoch 82 | loss: 17.93481|  0:00:06s
epoch 83 | loss: 10.50607|  0:00:06s
epoch 84 | loss: 16.35543|  0:00:06s
epoch 85 | loss: 12.56514|  0:00:06s
epoch 86 | loss: 17.05186|  0:00:06s
epoch 87 | loss: 23.22866|  0:00:06s
epoch 88 | loss: 15.22132|  0:00:06s
epoch 89 | loss: 16.38608|  0:00:06s
epoch 90 | loss: 18.8453 |  0:00:06s
epoch 91 | loss: 11.53056|  0:00:06s
epoch 92 | loss: 13.55651|  0:00:06s
epoch 93 | loss: 13.12085|  0:00:07s
epoch 94 | loss: 9.58413 |  0:00:07s
epoch 95 | loss: 7.62608 |  0:00:07s
epoch 96 | loss: 10.39351|  0:00:07s
epoch 97 | loss: 8.77248 |  0:00:07s
epoch 98 | loss: 4.2776  |  0:00:07s
epoch 99 | loss: 9.58466 |  0:00:07s
epoch 0  | loss: 42088.18359|  0:00:00s
epoch 1  | loss: 41080.28125|  0:00:00s
epoch 2  | loss: 40008.41016|  0:00:00s
epoch 3  | loss: 39311.29688|  0:00:00s
epoch 4  | loss: 38484.01562|  0:00:00s
epoch 5  | loss: 37473.28125|  0:00:00s
epoch 6  | loss: 36654.87109|  0:00:00s
epoch 7  | loss: 36010.39453|  0:00:00s
epoch 8  | loss: 34933.55469|  0:00:00s
epoch 9  | loss: 34135.02344|  0:00:00s
epoch 10 | loss: 33053.44531|  0:00:00s
epoch 11 | loss: 32155.73438|  0:00:00s
epoch 12 | loss: 31048.45703|  0:00:00s
epoch 13 | loss: 29923.35742|  0:00:00s
epoch 14 | loss: 28788.04883|  0:00:01s
epoch 15 | loss: 27475.90625|  0:00:01s
epoch 16 | loss: 26222.73438|  0:00:01s
epoch 17 | loss: 25019.89062|  0:00:01s
epoch 18 | loss: 23839.75391|  0:00:01s
epoch 19 | loss: 22651.95703|  0:00:01s
epoch 20 | loss: 21106.60938|  0:00:01s
epoch 21 | loss: 20261.23438|  0:00:01s
epoch 22 | loss: 18925.14648|  0:00:01s
epoch 23 | loss: 17554.19141|  0:00:01s
epoch 24 | loss: 16088.63184|  0:00:01s
epoch 25 | loss: 14720.08887|  0:00:01s
epoch 26 | loss: 13470.0166|  0:00:01s
epoch 27 | loss: 12073.00488|  0:00:01s

              Strategy  Coverage       Width       RMSE          CWC
0          NexCP Split  0.804878   66.676125  24.875167  7820.523986
1           NexCP Full  0.841463   70.344856  24.875167  1383.566849
2  NexCP Jackknife+ aB  1.000000  227.563553  24.537029   227.563553
3            NexCP CV+  1.000000  152.744186  24.698067   152.744186

In [ ]:
y_train = pd.Series(y_train)
y_test = pd.Series(y_test)

conformal_predictions_online_super(
    model_class=TabNetRegressorCP,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="TabNet",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/TabNet.xlsx",
    alpha=0.1,
    strategies="all",
    window_min=50,
    window_max=500,
    window_grid=(25, 50, 100, 200, 400),
    n_bootstrap=30
)

In [ ]:
conformal_predictions_COP(
    model_class=TabNetRegressorCP,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="TabNet",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/TabNet.xlsx",
    alpha=0.1,
    lr=0.05,
    T_burnin=50,
    scale=0.5
)

In [ ]:
conformal_predictions_EXTREME(
    model_class=TabNetRegressorCP,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="TabNet",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/TabNet.xlsx",
    alpha=0.05,
    calib_size=0.5,
    gpd_threshold_quantile=0.95,
    n_bootstrap=30
)

In [ ]:
def conformal_predictions_AlphaNet_tabnet(
    X_train,
    y_train,
    X_test,
    y_test,
    best_params,
    model_name="TabNet",
    excel_file_path=None,
    alpha=0.05,
    lambda_reg=20.0,
    num_epochs=50,
    batch_size=32,
    lr_alpha=1e-3,
    calib_fraction=0.5,
    num_runs=4,
    random_state=123,
):
    """
    Learned-α Conformal Prediction via AlphaNet — TabNet-specific variant.

    Handles:
    - TabNetRegressorCP wrapper (y reshape, predict flatten)
    - Removes 'verbose' from best_params if present
    - Precomputed LOO scores for speed
    - Progress tracking with tqdm + ETA
    """

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)
    torch.manual_seed(random_state)
    device = "cuda" if torch.cuda.is_available() else "cpu"

    t_start_total = time.time()

    # =========================================================
    # TabNet-specific: clean params & set model class
    # =========================================================
    tabnet_params = dict(best_params)
    tabnet_params.pop("verbose", None)           # TabNet doesn't use verbose here
    model_class = TabNetRegressorCP

    # =========================================================
    # Data conversion
    # =========================================================
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy()  if hasattr(X_test,  "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # =========================================================
    # 1. Split training data → fit + calibration
    # =========================================================
    n_total = len(Xtr)
    n_fit   = int(n_total * (1 - calib_fraction))
    perm    = np.random.permutation(n_total)

    fit_idx   = perm[:n_fit]
    calib_idx = perm[n_fit:]

    X_fit,   y_fit   = Xtr[fit_idx],   ytr[fit_idx]
    X_calib, y_calib = Xtr[calib_idx],  ytr[calib_idx]
    n_calib = len(X_calib)

    # alpha_min: must satisfy α̃·(n+1) − 1 > 0  →  α̃ > 1/(n+1)
    alpha_min = 1.0 / (n_calib + 1) + 0.01
    print(f"  [Info] n_calib={n_calib} | alpha_min={alpha_min:.4f}")

    # =========================================================
    # 2. Train base TabNet model
    # =========================================================
    print(f"  [Step 2/9] Training base {model_name} model...")
    t0 = time.time()
    base_model = model_class(**tabnet_params)
    base_model.fit(X_fit, y_fit)
    print(f"  [Step 2/9] Done in {_fmt_time(time.time()-t0)}")

    # =========================================================
    # 3. PRECOMPUTE all LOO scores (KEY SPEEDUP)
    # =========================================================
    print(f"  [Step 3/9] Precomputing {n_calib} LOO score vectors...")
    t0 = time.time()

    precomputed_scores = []
    precomputed_sums   = []

    iterator = (
        tqdm(range(n_calib), desc="    LOO precompute", leave=False)
        if HAS_TQDM else range(n_calib)
    )

    for i in iterator:
        loo_X = np.delete(X_calib, i, axis=0)
        loo_y = np.delete(y_calib, i, axis=0)
        preds_loo = base_model.predict(loo_X).ravel()
        scores_loo = np.abs(preds_loo - loo_y)

        scores_tensor = torch.tensor(scores_loo, dtype=torch.float32).to(device)
        precomputed_scores.append(scores_tensor)
        precomputed_sums.append(scores_loo.sum())

    elapsed_precompute = time.time() - t0
    print(f"  [Step 3/9] Done in {_fmt_time(elapsed_precompute)}")

    # Build feature matrix (sum of LOO scores per sample)
    X_alpha = torch.tensor(
        np.array(precomputed_sums).reshape(-1, 1),
        dtype=torch.float32,
    ).to(device)

    # =========================================================
    # 4. Train AlphaNet (multiple runs, keep best)
    # =========================================================
    print(f"  [Step 4/9] Training AlphaNet: {num_runs} runs × {num_epochs} epochs")

    best_net  = None
    best_loss = np.inf
    history   = {"losses": [], "sizes": [], "alphas": []}

    t0_train = time.time()

    for run in range(num_runs):
        np.random.seed(run)
        torch.manual_seed(run)

        alpha_net = AlphaNet(input_dim=1, alpha_min=alpha_min).to(device)
        optimizer = optim.Adam(alpha_net.parameters(), lr=lr_alpha)

        dataset = TensorDataset(X_alpha, torch.arange(n_calib))
        loader  = DataLoader(dataset, batch_size=batch_size, shuffle=True)

        run_losses, run_sizes, run_alphas = [], [], []

        epoch_iter = (
            tqdm(range(num_epochs), desc=f"    Run {run+1}/{num_runs}", leave=False)
            if HAS_TQDM else range(num_epochs)
        )

        for epoch in epoch_iter:
            t_epoch_start = time.time()
            epoch_loss = epoch_size = epoch_alpha = 0.0

            for x_batch, idx_batch in loader:
                x_batch = x_batch.to(device)
                alpha_pred = alpha_net(x_batch)

                batch_sizes = []
                for j, idx in enumerate(idx_batch):
                    # USE PRECOMPUTED scores — no predict() call here
                    scores_t = precomputed_scores[idx.item()]
                    size_j = _interval_size(scores_t, alpha_pred[j])
                    batch_sizes.append(size_j)

                batch_sizes = torch.stack(batch_sizes)
                loss = (batch_sizes + lambda_reg * alpha_pred).mean()

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

                epoch_loss  += loss.item()
                epoch_size  += batch_sizes.mean().item()
                epoch_alpha += alpha_pred.mean().item()

            n_batches = len(loader)
            run_losses.append(epoch_loss  / n_batches)
            run_sizes.append(epoch_size   / n_batches)
            run_alphas.append(epoch_alpha / n_batches)

            epoch_time = time.time() - t_epoch_start

            if epoch % 10 == 0 or epoch == num_epochs - 1:
                epochs_done  = (run * num_epochs) + epoch + 1
                epochs_total = num_runs * num_epochs
                elapsed_train = time.time() - t0_train
                eta = (elapsed_train / epochs_done) * (epochs_total - epochs_done)

                print(
                    f"  λ={lambda_reg} | Run {run+1}/{num_runs} | "
                    f"Epoch {epoch}/{num_epochs} | "
                    f"Loss: {run_losses[-1]:.4f} | "
                    f"Size: {run_sizes[-1]:.4f} | "
                    f"α̃: {run_alphas[-1]:.4f} | "
                    f"⏱ {epoch_time:.2f}s/epoch | "
                    f"ETA: {_fmt_time(eta)}"
                )

        if run_losses[-1] < best_loss:
            best_loss = run_losses[-1]
            best_net  = alpha_net

        history["losses"].append(run_losses)
        history["sizes"].append(run_sizes)
        history["alphas"].append(run_alphas)

        print(f"  ✓ Run {run+1} complete | Final loss: {run_losses[-1]:.4f}")

    train_time = time.time() - t0_train
    print(f"  [Step 4/9] Training done in {_fmt_time(train_time)}")

    alpha_net = best_net
    alpha_net.eval()

    # =========================================================
    # 5. Compute conformal intervals on TEST set
    # =========================================================
    print(f"  [Step 5/9] Computing conformal intervals...")

    calib_preds = base_model.predict(X_calib).ravel()
    scores_calib = np.abs(calib_preds - y_calib)
    sum_scores   = scores_calib.sum()

    with torch.no_grad():
        feat_test = torch.tensor([sum_scores], dtype=torch.float32).to(device)
        alpha_val = alpha_net(feat_test).item()

    denom = alpha_val * (n_calib + 1) - 1
    if denom <= 0:
        q = np.quantile(scores_calib, 1 - alpha)
        half_width = q
        print(f"  [Warning] α̃ too small (denom={denom:.4f}); fallback q={q:.4f}")
    else:
        half_width = sum_scores / denom

    y_pred_test = base_model.predict(Xte).ravel()
    ymin = y_pred_test - half_width
    ymax = y_pred_test + half_width

    # =========================================================
    # 6. Metrics
    # =========================================================
    is_covered = ((yte >= ymin) & (yte <= ymax)).astype(int)
    coverage   = is_covered.mean()
    avg_width  = np.mean(ymax - ymin)
    rmse       = np.sqrt(mean_squared_error(yte, y_pred_test))

    total_time = time.time() - t_start_total

    print(f"\n{'='*55}")
    print(f"  ALPHANET CONFORMAL ({model_name})")
    print(f"{'='*55}")
    print(f"  Learned α̃     : {alpha_val:.4f}")
    print(f"  Half-width (r) : {half_width:.4f}")
    print(f"  Coverage       : {coverage*100:.3f}%")
    print(f"  Avg Width      : {avg_width:.4f}")
    print(f"  RMSE           : {rmse:.4f}")
    print(f"  Total time     : {_fmt_time(total_time)}")
    print(f"    ├─ Precompute: {_fmt_time(elapsed_precompute)}")
    print(f"    └─ Training  : {_fmt_time(train_time)}")
    print(f"{'='*55}")

    # =========================================================
    # 7. Summary & Values
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy":       "AlphaNet Conformal",
        "Coverage":       coverage,
        "Width":          avg_width,
        "RMSE":           rmse,
        "Alpha_nominal":  alpha,
        "Alpha_learned":  alpha_val,
        "Lambda_reg":     lambda_reg,
        "Total_time_sec": round(total_time, 2),
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(yte)),
        "y_true":       yte,
        "y_pred":       y_pred_test,
        "ymin":         ymin,
        "ymax":         ymax,
        "width":        ymax - ymin,
        "is_covered":   is_covered,
    })

    # =========================================================
    # 8. Plotting (SAVE ONLY — NO SHOW)
    # =========================================================
    print(f"  [Step 8/9] Generating plots...")
    idx_arr = np.arange(len(yte))

    # --- Prediction-interval plot ---
    fig_pi, ax_pi = plt.subplots(figsize=(10, 4))
    ax_pi.scatter(idx_arr, yte, color="blue", s=10, alpha=0.7, label="True")
    ax_pi.fill_between(idx_arr, ymin, ymax, color="gray", alpha=0.5,
                       label=f"AlphaNet Interval (α̃={alpha_val:.3f})")
    ax_pi.plot(idx_arr, y_pred_test, color="red", lw=1, label="Predicted mean")
    ax_pi.set_title(f"AlphaNet Conformal ({model_name})")
    ax_pi.set_xlabel("Sample Number")
    ax_pi.set_ylabel("WQI")
    ax_pi.legend(loc="upper left")
    plt.tight_layout()

    buf_pi = io.BytesIO()
    fig_pi.savefig(buf_pi, format="png")
    buf_pi.seek(0)
    plt.close(fig_pi)

    # --- Training-curves plot ---
    arr_losses = np.array(history["losses"])
    arr_sizes  = np.array(history["sizes"])
    arr_alphas = np.array(history["alphas"])
    epochs_arr = np.arange(1, num_epochs + 1)

    fig_tc, axs = plt.subplots(1, 3, figsize=(14, 4))
    for ax, data, ylabel, title in zip(
        axs,
        [arr_losses, arr_sizes, arr_alphas],
        ["Loss", "Mean Interval Size", r"Mean $\tilde{\alpha}$"],
        ["Training Loss", "Interval Size", r"Learned $\tilde{\alpha}$"],
    ):
        m = data.mean(axis=0)
        s = data.std(axis=0)
        ax.plot(epochs_arr, m, color="#0077bb")
        ax.fill_between(epochs_arr, m - s, m + s, color="#0077bb", alpha=0.25)
        ax.set_xlabel("Epoch")
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.grid(True, linewidth=0.5)
    plt.tight_layout()

    buf_tc = io.BytesIO()
    fig_tc.savefig(buf_tc, format="png")
    buf_tc.seek(0)
    plt.close(fig_tc)

    # =========================================================
    # 9. Excel Export (append-safe)
    # =========================================================
    if excel_file_path:
        print(f"  [Step 9/9] Saving to Excel...")
        try:
            wb = load_workbook(excel_file_path)
        except FileNotFoundError:
            from openpyxl import Workbook
            wb = Workbook()
            wb.remove(wb.active)

        def _unique_sheet(wb, name):
            base, i = name, 1
            while name in wb.sheetnames:
                name = f"{base}_{i}"; i += 1
            return name

        # ---- Summary ----
        sn = _unique_sheet(wb, "AlphaNet_TabNet_Summary")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- PI Plot ----
        img_pi = Image(buf_pi)
        sn = _unique_sheet(wb, "AlphaNet_TabNet_Plot_PI")
        ws = wb.create_sheet(sn)
        ws.add_image(img_pi, "A1")

        # ---- Training Curves Plot ----
        img_tc = Image(buf_tc)
        sn = _unique_sheet(wb, "AlphaNet_TabNet_Plot_Train")
        ws = wb.create_sheet(sn)
        ws.add_image(img_tc, "A1")

        # ---- Values ----
        sn = _unique_sheet(wb, "AlphaNet_TabNet_Values")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)
        print(f"  [Step 9/9] Saved!")

    print(f"\n  ✅ AlphaNet TabNet complete in {_fmt_time(total_time)}")
    return summary_df

In [76]:
conformal_predictions_AlphaNet_tabnet(
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    best_params=best_params,
    model_name="TabNet",
    excel_file_path="./drive/MyDrive/WQI/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/TabNet.xlsx",
    alpha=0.05,
)

  [Info] n_calib=95 | alpha_min=0.0204
  [Step 2/9] Training base TabNet model...
epoch 0  | loss: 42263.68359|  0:00:00s
epoch 1  | loss: 41300.64062|  0:00:00s
epoch 2  | loss: 40389.14844|  0:00:00s
epoch 3  | loss: 39301.97656|  0:00:00s
epoch 4  | loss: 38324.65234|  0:00:00s
epoch 5  | loss: 37479.35547|  0:00:00s
epoch 6  | loss: 36466.93359|  0:00:00s
epoch 7  | loss: 35576.08984|  0:00:00s
epoch 8  | loss: 34637.66016|  0:00:00s
epoch 9  | loss: 33812.70312|  0:00:00s
epoch 10 | loss: 32804.10547|  0:00:00s
epoch 11 | loss: 31581.70898|  0:00:00s
epoch 12 | loss: 30469.13281|  0:00:00s
epoch 13 | loss: 29049.52734|  0:00:00s
epoch 14 | loss: 27697.66211|  0:00:00s
epoch 15 | loss: 26213.76172|  0:00:01s
epoch 16 | loss: 24620.24609|  0:00:01s
epoch 17 | loss: 22888.18945|  0:00:01s
epoch 18 | loss: 21275.04883|  0:00:01s
epoch 19 | loss: 19499.02539|  0:00:01s
epoch 20 | loss: 17755.69531|  0:00:01s
epoch 21 | loss: 16042.99902|  0:00:01s
epoch 22 | loss: 14309.20605|  0:00:01s
epoch 23 | loss: 12603.4834|  0:00:01s
epoch 24 | loss: 10977.72754|  0:00:01s
epoch 25 | loss: 9402.14551|  0:00:01s
epoch 26 | loss: 7826.66846|  0:00:01s
epoch 27 | loss: 6514.92676|  0:00:01s
epoch 28 | loss: 5214.47217|  0:00:01s
epoch 29 | loss: 3991.90381|  0:00:01s
epoch 30 | loss: 2957.50488|  0:00:01s
epoch 31 | loss: 2118.17676|  0:00:02s
epoch 32 | loss: 1364.72729|  0:00:02s
epoch 33 | loss: 805.65143|  0:00:02s
epoch 34 | loss: 452.84503|  0:00:02s
epoch 35 | loss: 316.05838|  0:00:02s
epoch 36 | loss: 342.40775|  0:00:02s
epoch 37 | loss: 412.55878|  0:00:02s
epoch 38 | loss: 519.55444|  0:00:02s
epoch 39 | loss: 590.89056|  0:00:02s
epoch 40 | loss: 590.49506|  0:00:02s
epoch 41 | loss: 478.61301|  0:00:02s
epoch 42 | loss: 470.52615|  0:00:02s
epoch 43 | loss: 516.50562|  0:00:02s
epoch 44 | loss: 232.82605|  0:00:02s
epoch 45 | loss: 203.98157|  0:00:02s
epoch 46 | loss: 170.52432|  0:00:02s
epoch 47 | loss: 129.96439|  0:00:02s
epoch 48 | loss: 130.99219|  0:00:02s
epoch 49 | loss: 186.50627|  0:00:02s
epoch 50 | loss: 95.7096 |  0:00:02s
epoch 51 | loss: 65.81013|  0:00:02s
epoch 52 | loss: 65.14381|  0:00:03s
epoch 53 | loss: 46.87577|  0:00:03s
epoch 54 | loss: 55.70259|  0:00:03s
epoch 55 | loss: 40.84926|  0:00:03s
epoch 56 | loss: 32.26995|  0:00:03s
epoch 57 | loss: 38.26599|  0:00:03s
epoch 58 | loss: 24.62063|  0:00:03s
epoch 59 | loss: 41.62499|  0:00:03s
epoch 60 | loss: 62.333  |  0:00:03s
epoch 61 | loss: 41.0359 |  0:00:03s
epoch 62 | loss: 28.81178|  0:00:03s
epoch 63 | loss: 30.81227|  0:00:03s
epoch 64 | loss: 23.52114|  0:00:03s
epoch 65 | loss: 29.82802|  0:00:03s
epoch 66 | loss: 19.69145|  0:00:03s
epoch 67 | loss: 24.38126|  0:00:03s
epoch 68 | loss: 23.2438 |  0:00:03s
epoch 69 | loss: 17.13188|  0:00:03s
epoch 70 | loss: 15.0757 |  0:00:03s
epoch 71 | loss: 15.82724|  0:00:03s
epoch 72 | loss: 22.12321|  0:00:03s
epoch 73 | loss: 20.02257|  0:00:03s
epoch 74 | loss: 16.44191|  0:00:03s
epoch 75 | loss: 13.74346|  0:00:03s
epoch 76 | loss: 14.03165|  0:00:04s
epoch 77 | loss: 11.49532|  0:00:04s
epoch 78 | loss: 9.786   |  0:00:04s
epoch 79 | loss: 14.80205|  0:00:04s
epoch 80 | loss: 14.13055|  0:00:04s
epoch 81 | loss: 7.62019 |  0:00:04s
epoch 82 | loss: 9.60141 |  0:00:04s
epoch 83 | loss: 13.02656|  0:00:04s
epoch 84 | loss: 8.59859 |  0:00:04s
epoch 85 | loss: 10.68756|  0:00:04s
epoch 86 | loss: 8.50922 |  0:00:04s
epoch 87 | loss: 10.06789|  0:00:04s
epoch 88 | loss: 6.46509 |  0:00:04s
epoch 89 | loss: 9.45363 |  0:00:04s
epoch 90 | loss: 6.43847 |  0:00:04s
epoch 91 | loss: 9.1471  |  0:00:04s
epoch 92 | loss: 6.31304 |  0:00:04s
epoch 93 | loss: 6.35924 |  0:00:04s
epoch 94 | loss: 9.33433 |  0:00:04s
epoch 95 | loss: 4.25971 |  0:00:04s
epoch 96 | loss: 7.1939  |  0:00:04s
epoch 97 | loss: 6.83257 |  0:00:04s
epoch 98 | loss: 4.67117 |  0:00:04s
epoch 99 | loss: 7.10251 |  0:00:05s
  [Step 2/9] Done in 5s
  [Step 3/9] Precomputing 95 LOO score vectors...

    LOO precompute:   0%|          | 0/95 [00:00<?, ?it/s]

  [Step 3/9] Done in 2s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 3217.6468 | Size: 3210.1721 | α̃: 0.3738 | ⏱ 0.04s/epoch | ETA: 11s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 105.8676 | Size: 85.8676 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 5s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 105.8684 | Size: 85.8684 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 4s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 105.8679 | Size: 85.8679 | α̃: 1.0000 | ⏱ 0.03s/epoch | ETA: 4s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 105.8681 | Size: 85.8681 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 3s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 105.8686 | Size: 85.8686 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 3s
  ✓ Run 1 complete | Final loss: 105.8686

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 105.8687 | Size: 85.8687 | α̃: 1.0000 | ⏱ 0.05s/epoch | ETA: 3s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 105.8700 | Size: 85.8700 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 3s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 105.8688 | Size: 85.8688 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 3s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 105.8682 | Size: 85.8682 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 3s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 105.8679 | Size: 85.8679 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 2s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 105.8676 | Size: 85.8676 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 2s
  ✓ Run 2 complete | Final loss: 105.8676

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 105.8694 | Size: 85.8694 | α̃: 1.0000 | ⏱ 0.04s/epoch | ETA: 2s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 105.8708 | Size: 85.8708 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 2s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 105.8694 | Size: 85.8694 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 2s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 105.8700 | Size: 85.8700 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 1s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 105.8689 | Size: 85.8689 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 1s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 105.8677 | Size: 85.8677 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 1s
  ✓ Run 3 complete | Final loss: 105.8677

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 105.8699 | Size: 85.8699 | α̃: 1.0000 | ⏱ 0.04s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 105.8686 | Size: 85.8686 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 105.8701 | Size: 85.8701 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 1s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 105.8654 | Size: 85.8654 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 105.8687 | Size: 85.8687 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 0s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 105.8693 | Size: 85.8693 | α̃: 1.0000 | ⏱ 0.02s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 105.8693
  [Step 4/9] Training done in 4s
  [Step 5/9] Computing conformal intervals...

=======================================================
  ALPHANET CONFORMAL (TabNet)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 42.9345
  Coverage       : 74.390%
  Avg Width      : 85.8690
  RMSE           : 37.1785
  Total time     : 11s
    ├─ Precompute: 2s
    └─ Training  : 4s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet TabNet complete in 11s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.743902,85.869011,37.178503,0.05,1.0,20.0,10.77